### ISSUE TITLE
Page translation

### ISSUE THREAD

**Issue by kocmozzz** [rainlab/translate-plugin#10]
Is it possible to translate page.htm files? Like page.fr.htm or put pages in subdirectory like /fr/page.htm?

I've tried to put translated pages in subdirectory but current route rules

Route::group(['prefix' => $locale], function() use ($locale) {
    Route::any('{slug}', 'Cms\Classes\Controller@run')->where('slug', '(.*)?');
});
Route::any($locale, 'Cms\Classes\Controller@run');

prevents this way of routing. I get 404 on all site.com/fr/page requests.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
