### ISSUE TITLE
Another Page title localisation related issue

### ISSUE THREAD

**Issue by CptMeatball** [rainlab/translate-plugin#100]
Why isn't there an option to translate the page title from within the CMS section of OctoberCMS?

The way content is currently translated isn't really client friendly, but can be circumvented by implementing `editable` on all content sections. This will leave a client in (somewhat) full control of the website and its languages. Simple strings in forms and other infrequently changed content can still be translated in `Settings -> Manage translations`, as a client won't change that any time soon. 
But for something that's so important to SEO, it's mindblowingly client-unfriendly.  Why can't it just be a simple dropdown like in other parts (plugins) of October?

I'm aware of the fact that because of the flatfile way October is built, not everything can be changed as simple as in a plugin that already uses the database, but surely there must be a way to take the currently active page into account, just like with localised `content` files.

I'm currently using the standard way, but it just doesn't feel right. :(

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
