### ISSUE TITLE
Internet explorer / Edge

### ISSUE THREAD

**Issue by goeroe** [rainlab/translate-plugin#101]
The plugin grid doens't load as it should in internet explorer / edge. (Someone just brought this to my attention)

**Comment by goeroe** [comment]
![schermafdruk 2015-11-13 13 27 07](https://cloud.githubusercontent.com/assets/4172138/11146051/201e3f6a-8a0b-11e5-97a8-fe4f76d0a978.png)

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
