### ISSUE TITLE
Error with save russian text

### ISSUE THREAD

**Issue by valiknet18** [rainlab/translate-plugin#103]
Hello, i get error, when try save russian text. In result i get cropped text =C
Before: 
![image](https://cloud.githubusercontent.com/assets/5772019/11180021/2e32644e-8c60-11e5-9a70-1630a8ab856a.png)

Result: 
![image](https://cloud.githubusercontent.com/assets/5772019/11180002/15ee821e-8c60-11e5-8511-cb9f15958263.png)

i don't know, it's plugin bug or editor, help plz resolve him

**Comment by sayawan** [comment]
In my case when cyrillic data is saved to db, it encodes to unicode something like `u041f\u0435\u0440\u0432\u0430\u044f`. And when text is too large, it exceeds the `MEDIUMTEXT` limit which translate plugin uses for storing translations. Maybe you can try to increase the data limit for something like `LONGTEXT`, or store plain cyrillic

**Comment by LukeTowers** [comment]
Hmm... @daftspunk perhaps we need to store the translation content as longtext

**Comment by sayawan** [comment]
@LukeTowers is there a way to store plain cyrillic data. Because searching with plugins like SiteSearch returns any results.

**Comment by sayawan** [comment]
Adding JSON_UNESCAPED_UNICODE [in this line](https://github.com/rainlab/translate-plugin/blob/master/behaviors/TranslatableModel.php#L98) solves problem .
```php
// this line
json_encode($this->translatableAttributes[$locale]);

// to this
json_encode($this->translatableAttributes[$locale], JSON_UNESCAPED_UNICODE);
```

**Comment by LukeTowers** [comment]
@sayawan is that going to cause a problem when running `json_decode()` on the information? Does that flag need to be passed there as well?

**Comment by sayawan** [comment]
@LukeTowers no it decodes correctly without any flags.

**Comment by LukeTowers** [comment]
Fixed in https://github.com/rainlab/translate-plugin/commit/ff99192509a5d56cbca93580428d007bbbe3da84

Thanks @sayawan!
