### ISSUE TITLE
Hiding translated positions causing NOT saving data

### ISSUE THREAD

**Issue by KievDevel** [rainlab/translate-plugin#108]
How to meet a bug:
1. go to translations
2. click checkbox hide translated
3. enter any data for translation
4. reload page (f5)
5. data not saved

**Comment by eddyloewen** [comment]
I was having the same problem and it was driving me nuts until I found this issue description. Especially for my clients it would be nice for this one to be fixed

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
