### ISSUE TITLE
Default root (/) language

### ISSUE THREAD

**Issue by vizo** [rainlab/translate-plugin#11]
In documentation is written:
- http://website/ru/ will display the site in Russian
- http://website/fr/ will display the site in French
- http://website/ will display the site in the default language or the user's chosen language.

I think, if you have multilingual site, it is better that you always redirected to /language when you come to root. Joomla have the same option. Why?
- people often don't look at url, they just make bookmark, share, etc., so if you change default language later, content could be gone on same url, which is very bad.
- for search engines content is duplicated on two urls: / and /language, which is also bad

Is it possible to make this as an option, that you are always redirected?

So when user come to root, it checks:
1. if user have language in session, redirect to user's language
2. if browser sends language in request header, redirect to browser's language
3. redirect to default language

Thanks in advance,
vizo

**Comment by daftspunk** [comment]
Fixed by #72 and should be available soon.
