### ISSUE TITLE
Can't Translate Blog Content

### ISSUE THREAD

**Issue by marcoelho97** [rainlab/translate-plugin#110]
I was trying to use the translate on blog, and it worked fine. I was able to translate everything, EXCEPT FOR the content. The language slugs don't show up. When I removed the markdown (Which comes by default with blog), the slugs showed up, which makes me believe it has some problem with, at least, this text editor.

Is there a fix to this, or..?

**Comment by marcoelho97** [comment]
Any help?

**Comment by rsobon** [comment]
I made pull request with this feature
https://github.com/rainlab/translate-plugin/pull/122

**Comment by daftspunk** [comment]
Fixed by #122
