### ISSUE TITLE
How can I translate settings information?

### ISSUE THREAD

**Issue by Hambern** [rainlab/translate-plugin#111]
This works perfect. But how can i translate a settings model? I have the basic information in a 'System.Behaviors.SettingsModel' . But translate doesn't seem to work on it.

**Comment by ametad** [comment]
Hi Hambern,
Thank you for asking them this question!

**Comment by Keyj1n** [comment]
Hello,

need that information too!

**Comment by Keyj1n** [comment]
Hello again,

i could find it out by myself. You need to get the instance of the the class like:
`Settings::instance()->getTranslateAttribute('confirmation_text')`

hope i could help anyone with this :)

Keyjin

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
