### ISSUE TITLE
onCacheClear not doing its job

### ISSUE THREAD

**Issue by schniper** [rainlab/translate-plugin#114]
Hey,
Message.onClearCache() seems to clear the cms cache and it's not touching the standard cache, where the translations are actually stored (framework/cache in case of file storage, dynamic in other cases). Shouldn't there be a `Cache::flush()` or something a bit less aggressive in that method?

**Comment by schniper** [comment]
Of course, for file caching, a simple fix is to set the caching path in config/cache.php to storage_path('cms/cache'), which currently gets cleared by the cache helper used. This will only work with file storage, though.

**Comment by Himapan** [comment]
That really helped me, thx for posting this!

**Comment by daftspunk** [comment]
This should probably be calling `\Cache::flush()` instead of `CacheHelper::clear()`
