### ISSUE TITLE
Dosen't work

### ISSUE THREAD

**Issue by FelixINX** [rainlab/translate-plugin#116]
Hi,

When I click my button to change locale, nothing happen.

Here is the code of my button:

``` html
 <li><a href="#" data-request="onSwitchLocale" data-request-data="locale: 'en'">{{ 'English'|_ }}</a></li>
```

Is this an incompatibility with something?

**Comment by CptMeatball** [comment]
Have you included: ````{{ framework extras }} ```` in your layout?

**Comment by FelixINX** [comment]
@CptMeatball Yes, both `{{ framework extras }}` and `{% framework extras %}`. It didn't add nothing to the page.

**Comment by CptMeatball** [comment]
It **should** add a few scripts and styles to your page. Have you added ````{% scripts %}```` too?

My scripts section looks like this and for me this works.

    [...]
    {% framework extras %}
    {% scripts %}
    [...]

**Comment by eisenhorn13** [comment]
Just add LocalePicker component on your page or layout.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
