### ISSUE TITLE
Another editor for StaticPages + Translate

### ISSUE THREAD

**Issue by wilsonglasser** [rainlab/translate-plugin#118]
@daftspunk 
Is possible to replace the static page editor with this new update? I was using CKEditor instead of Redactor, but with this new update the StaticPage changed the way to replace the editor.

I was using this:

```
foreach ($form->getFields() as $field)
 {
      if (empty($field->config['type']) || $field->config['type'] != ''richeditor' )
            continue;
     $field->config['type'] = $field->config['widget'] = 'Castwork\Ckeditor\FormWidgets\Wysiwyg';
}
```

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
