### ISSUE TITLE
The parameter translation not working

### ISSUE THREAD

**Issue by gergo85** [rainlab/translate-plugin#121]
In my own plugin (https://github.com/gergo85/oc-news) I wanted to used the ``{{ post.title|_ }}`` format. But nothing happened. The front-end components based on Rainlab Blog plugin. Is it a bug?

**Comment by marcoelho97** [comment]
I speak of personal experience when I say: You can't translate a variable like that. You can either change your plugin's model and implement translate ( Check the documentation, under "Model Translation" ) Or, you can translate text with a variable's placeholder, like so: 
{{ 'Hello :name!'|_({ name: 'Friend' }) }}

Hope this helps you out ^^

**Comment by gergo85** [comment]
Thanks for your answer. Finally I solved this problem.
