### ISSUE TITLE
Language selector disappears when using richeditor type field

### ISSUE THREAD

**Issue by bombozama** [rainlab/translate-plugin#123]
When enabling translate on a field of type richeditor, the language selector disappears if richeditor buttons are displayed on two lines.

Buttons appear in single line. Expected behavior
<img width="655" alt="screen shot 2016-04-14 at 11 23 58" src="https://cloud.githubusercontent.com/assets/1273093/14531413/9d164f44-0233-11e6-9eb9-f9e2efec6af1.png">

Buttons appear in two or more lines. Language selector disappears.
<img width="646" alt="screen shot 2016-04-14 at 11 24 20" src="https://cloud.githubusercontent.com/assets/1273093/14531420/a26ac8d0-0233-11e6-81df-2a5912544d1d.png">

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred. Also, October switched to using Froala so this is probably not present anymore.
