### ISSUE TITLE
language selector  options in ckeditor are not visible

### ISSUE THREAD

**Issue by nikita-yugtia** [rainlab/translate-plugin#127]
Hi , I have used rain lab to translate my site into norway everything seems working fine but the language selector options in ckeditor are not visible, richeditor and textarea does shows the options but ckeditor does not.
![image](https://cloud.githubusercontent.com/assets/18721036/14935529/d15266b4-0e89-11e6-963d-31dc741e0903.png)

![image](https://cloud.githubusercontent.com/assets/18721036/14935535/f1fdb0da-0e89-11e6-8e34-0b7a3b291bfb.png)

Any suggestions?

**Comment by LukeTowers** [comment]
Ckeditor is not supported by October, talk to the plugin author. 
Closing as it has been over a month since any activity on this occurred.
