### ISSUE TITLE
Cache is cleared not all

### ISSUE THREAD

**Issue by reg2005** [rainlab/translate-plugin#128]
I found a bug. The cache is cleared not all. Because should be cleaned: storage/framework/cache. If this is not done, it will show the old version of the translation. 

Temporary solution: paste in modules/system/helpersCache this code:

```
    public static function clear()
    {
        $instance = self::instance();
        $instance->clearCombiner();
        $instance->clearCache();
        $instance->clearFramework();
        if (!Config::get('cms.twigNoCache')) {
            $instance->clearTwig();
        }

        $instance->clearMeta();
    }
    /*
     * My function
     */
    public function clearFramework()
    {
        foreach (File::directories(storage_path().'/framework/cache') as $directory) {
            File::deleteDirectory($directory);
        }
    }
```

**Comment by fresswolf** [comment]
I'm having the same problem. Only after "php artisan cache:clear" my translations show up.

**Comment by loic294** [comment]
Same here! @reg2005 Your solution works great for now!

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
