### ISSUE TITLE
Bug?: Caching Models which implement TranslatableModel with Cache::remember

### ISSUE THREAD

**Issue by ekrokowski** [rainlab/translate-plugin#129]
I'm currently trying to Cache a model via Cache::remember. That model implements the TranslatableModel:

```
Cache::remember('test', 60, function(){
    return Country::find(1);
});
```

This will throw an error: 

> Serialization of 'Closure' is not allowed

This seems to come from model bindings from the constructor of the `TranslatableBehavior`: 

```
$this->model->bindEvent('model.beforeGetAttribute', function($key) {
    if ($this->isTranslatable($key)) {
        return $this->getTranslateAttribute($key);
    }
});

$this->model->bindEvent('model.beforeSetAttribute', function($key, $value) {
    if ($this->isTranslatable($key)) {
        return $this->setTranslateAttribute($key, $value);
    }
});

$this->model->bindEvent('model.saveInternal', function() {
    $this->syncTranslatableAttributes();
});
```

https://github.com/rainlab/translate-plugin/blob/master/classes/TranslatableBehavior.php#L61

I can use `toArray()` to make the caching work but I would rather have the Model object cached. 
Any way we can get this working?

**Comment by ekrokowski** [comment]
@rounce That's not how you Cache models on Laravel 5. The remember method was once in Laravel but not nowadays. There is no error thrown, but that call doesn't hit Cache.

**Comment by rounce** [comment]
Odd, I used it today and debugbar have shown that it works.
And https://octobercms.com/docs/database/query#caching-queries

**Comment by ekrokowski** [comment]
@rounce Indeed, the method is available and looks implemented. I checked the caching with clockwork, maybe there is some error with it. Going to check that again later. Thanks

**Comment by ekrokowski** [comment]
@rounce This works: `Country::remember(60)->find(1);`

**Comment by AugmentBLU** [comment]
I know this is an old post - however is there a decent method to cache translated objects, without destroying the model?

I want to cache Blog posts that are translated but I'm not getting very far with it.
