### ISSUE TITLE
Bug with 'model' attribute

### ISSUE THREAD

**Issue by Nks** [rainlab/translate-plugin#131]
If we creating attribute with name `model` in any model class it's will happen error like this:
`PHP message: PHP Fatal error:  Cannot access protected property RainLab\Translate\Behaviors\TranslatableModel::$model in /vagrant/vendor/october/rain/src/Extension/ExtendableTrait.php on line 322`

I'm not sure that this error refers only to this plugin but I'm not found any mention about it when google it. 
Solution: just not use `model` as attribute anywhere in the model.

**Comment by cx-emerge** [comment]
I think it is your expansion of the model with the same `model` name field
Modify the name of `model`
