### ISSUE TITLE
Test makeMessageCode is failing

### ISSUE THREAD

**Issue by gabsource** [rainlab/translate-plugin#132]
#### OctoberCMS version 341 - Translate Plugin version 1.1.4
# 

At this line https://github.com/rainlab/translate-plugin/blob/master/tests/models/MessageTest.php#L76
The actual code replaces `_` with `.` but the test is expected nothing as a separator.

```
Failed asserting that two strings are equal.
Expected :'helloworld'
Actual   :'hello.world'
```

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
