### ISSUE TITLE
[BOUNTY] Allow translation of CMS Page properties

### ISSUE THREAD

**Issue by pavlo-tk** [rainlab/translate-plugin#138]
Bounty link: https://www.bountysource.com/issues/35021479-bounty-allow-translation-of-cms-page-properties

Bounty specification:
- Translate the page Description property
- Translate the page Title property
- Translate the page Meta Description property
- Translate the page Meta Title property

Discovery is needed for the best way to achieve this. There is a solution in place with no supporting UI. 

Possible options:
1. A generic key seeder can be used, similar to Builder plugin.
2. Implement a Translatable behavior that proxies the values to the page settings.

Original notes:

Hello.
In StaticPages plugin we have ability to translate pages title, meta_description, etc.
Do you have plans to add such ability to standard CMS pages to translate the same form fields (title, meta_description)?

**Comment by norgen** [comment]
Maybe:
`<meta name="description" content="{{ this.page.meta_description|_ }}">
 <meta name="keywords" content="{{ this.page.meta_keywords|_ }}">
`

**Comment by side-by-side** [comment]
I know about that method, but I wonder if there any plans to make this available like in Static Pages, via pages forms directly.

**Comment by amdad** [comment]
Right, translations of this via Settings = terrible UX.

**Comment by ilyaskorik** [comment]
+100500 to this

**Comment by daftspunk** [comment]
Here's how I would do it

```
<title>{{ this.page.meta_title|_ }}</title>
<meta name="description" content="{{ this.page.meta_description|_ }}">
<meta name="keywords" content="{{ this.page.meta_keywords|_ }}">
```

Set each value to something like

- `mypage.title`
- `mypage.description`
- `mypage.keywords`

Then open `theme.yaml` and include:

```
en:
    mypage.title: "Title in English"
    mypage.description: "Description in English"
    mypage.keywrods: "keywords, in, english"

ru:
   mypage.title: ...
   ...
```

Right now there is no UI for this approach, we could make it by borrowing the on-the-fly language key creation process from the RainLab.Builder plugin.

**Comment by thomasilmer** [comment]
Bounty added on BOUNTYSOURCE to implement the input locale switcher in CMS pages

**Comment by mortezaataiy** [comment]
i do all this works but
not translatable in the backend edit field :(

**Comment by mjauvin** [comment]
Fixed by https://github.com/rainlab/translate-plugin/pull/367
