### ISSUE TITLE
Does this plugin work with pages and blog?

### ISSUE THREAD

**Issue by GasimGasimzada** [rainlab/translate-plugin#139]
I can't seem to find anything regarding this. I need to build a multilingual website, so I need all the static and blog page form fields (title, excerpt, and content) to be translatable. 

If it doesn't work out of the box, is there a way to customize variables to make this work?

Thank you!

**Comment by DennaGherlyn** [comment]
Yes, it works with RainLab.Pages and RainLab.Blog. You'll have a little EN in the corner of the textbox. When you've configured two or more languages you can change the language with this EN in the corner.

**Comment by daftspunk** [comment]
It sure does! Must be using the latest version of all plugins.
