### ISSUE TITLE
No new lines when translating long texts 

### ISSUE THREAD

**Issue by ariponce** [rainlab/translate-plugin#140]
When translating messages, if we have a long text, the text continues to the right of the input, instead of adding new lines, making it really hard to detect errors, or see the complete result. I think this is because a  text input is used for messaged, instead of a textarea.

How it looks like: 
![2016-06-20-111432_1920x1045_scrot](https://cloud.githubusercontent.com/assets/1083390/16189037/b4149fc8-36d8-11e6-9d85-571b4aa197d2.png)

How i think it should look:
![2016-06-20-112020_1920x1045_scrot](https://cloud.githubusercontent.com/assets/1083390/16189122/1c3070d2-36d9-11e6-8c09-533617c946f6.png)

Is there a reason for this behaviour, or is it a bug?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.

**Comment by Samuell1** [comment]
Having same issue.

**Comment by mjauvin** [comment]
For very long text, you should use content blocks. See here:

https://github.com/rainlab/translate-plugin/blob/master/README.md#content-translation

**Comment by Samuell1** [comment]
@mjauvin But that cant be edited trough backend.

**Comment by mjauvin** [comment]
yes, under CMS pages / Content

**Comment by Samuell1** [comment]
But still it should work there too for just simple text strings, there isnt limit for column size limit.

**Comment by bennothommo** [comment]
@Samuell1 That message editor was not designed for long form text, it's meant for small messages. @mjauvin is right, there's better places for large textual translations.
