### ISSUE TITLE
No translate pluralized messages

### ISSUE THREAD

**Issue by norgen** [rainlab/translate-plugin#144]
Choice in template:
`{{ ':n год|:n года|:n лет'|__(girl.age, {n: girl.age}) }}`

Key "n год|:n года|:n лет" don't collect in message translate page.

Sorry for bad english.

**Comment by jan-vince** [comment]
I have tried this and it worked:

**Two choices:**
` {{ 'There are no apples|There are :number applies!'|__(2, { number: 'two' }) }}`

**Several choices:**
`{{ '{0} There are no apples|{1} There is one apple|]1,19] There are :number apples|[20,Inf[ There are many apples'|__( 3, {number: 'three'} ) }}`

Sources:
[http://symfony.com/doc/current/components/translation/usage.html](url)
[https://octobercms.com/plugin/rainlab-translate](url)

**Comment by norgen** [comment]
Yes, the English keys work. If symbols are used in the key Russian language, the key is not going to the table rainlab_translate_messages and does not appear in the admin area (Translate Messages page).

**Comment by jan-vince** [comment]
Now I can see, what you mean. I have just tested only choice, but not a translation itself.

This is probably a **missing feature in Translate plugin**.

ThemeScanner.php class (in Rainlab.Translate) has processStandardTags() method that parse only " |_ ", but not " |__ " (choice).

It looks like Translate plugin has never been able to handle choice translations :(

*I will try to add a missing method and send a pull request.*

**Comment by norgen** [comment]
Ok. Thanks.

**Comment by norgen** [comment]
Another issue like this https://github.com/rainlab/translate-plugin/issues/143

**Comment by rounce** [comment]
https://github.com/rainlab/translate-plugin/pull/151

**Comment by LukeTowers** [comment]
Fixed by #151
