### ISSUE TITLE
Add composer.json?

### ISSUE THREAD

**Issue by acasar** [rainlab/translate-plugin#146]
Is it possible to add composer.json files to all free Rainlab plugins, so we can install them using composer? It would really help when managing more complex projects.

For example, in case of a translate plugin, a minimal setup would be:
```json
{
    "name": "rainlab/translate-plugin",
    "type": "october-plugin",
    "description": "Enables multi-lingual websites for October CMS.",
}
```

I can also submit PRs if that's something you would consider. Thanks!

**Comment by daftspunk** [comment]
Sounds good

**Comment by acasar** [comment]
@daftspunk Created the PRs, all referenced above.

**Comment by vojtasvoboda** [comment]
Hi @daftspunk. How about requiring `composer/installers` in `composer.json` when using `october-plugin` type? It's necessary, or not?

And how about requiring plugin dependencies? For example RainLab.UserPlus depends on RainLab.User and RainLab.Location. Should it be noted in `composer.json` at require section?

**Comment by acasar** [comment]
@daftspunk @vojtasvoboda I now added both, but let me know if I need to change anything.

**Comment by ametad** [comment]
I think the plugin requiring other plugins would not work, because there are also plugins not exposed as public package.

But OC has it's own dependency management for the plugins that works rather well; in Plugin.php you declare a public $require attribute with names of the required plugins. 

If for example you have set a dependency that is NOT met, the plugin is just not working and not giving fatal errors, so your application can be inspected easily.

**Comment by vojtasvoboda** [comment]
@ametad There is great construct for private repositories, see https://getcomposer.org/doc/05-repositories.md#using-private-repositories

When you will use only October dependency management, you will have to install missing dependencies manually. I think that typing `composer install` is just better :-)

**Comment by ametad** [comment]
@vojtasvoboda Yeah I like Composer also very much and use it for my private OC plugins too! So in practice the needed plugins come from two sources: 1. our private packagist (satis); 2. OC Market.

There are overlapping requirements from both sources. Thing is that when composer first has dragged the private plugins in, they perhaps need other 3rd party plugins! This is not possible with Composer alone there days... that is a pity. But the nice thing is that OC wont break and just disables the plugins with extra requirements. Then I can just install those latter plugins from the Marketplace and all works well!

**Comment by acasar** [comment]
@ametad Composer dependencies were defined only for free RainLab plugins since they're most commonly used. To install 3rd party plugins you should still use the normal installation process.

I'm closing this issue since there is really nothing else to do here.
