### ISSUE TITLE
Translations in Plugins

### ISSUE THREAD

**Issue by dionduodeka** [rainlab/translate-plugin#147]
Hi there,

I am wondering if I can just enter the {{ ' & '|_ }} inside other plugins/themes etc in order to translate the messages. What happens when the plugin/theme gets updated? I suppose that my code will be overwritten...

In Wordpress you would make a child theme or fork the plugin. How does this work in OctoberCMS in combination with the Rainlan Translate plugin?

Thanks in advance

**Comment by CptMeatball** [comment]
You can overwrite the plugin's component view as per: [Components: Customizing default markup](https://octobercms.com/docs/cms/components#customizing-default-markup)

This prevents edits to be overwritten in future updates.
