### ISSUE TITLE
Add import and export strings feature

### ISSUE THREAD

**Issue by daftspunk** [rainlab/translate-plugin#15]
Add import and export strings feature to the Messages page.

**Comment by vojtasvoboda** [comment]
+1

**Comment by viezel** [comment]
+1

**Comment by LukeTowers** [comment]
@daftspunk are you still planning on implementing this?

**Comment by alvaro-canepa** [comment]
More than 3 years and we wait for this feature...
@daftspunk any news on it?

Thanks

**Comment by munxar** [comment]
I started to work on it, but hadn't the time to finish. But will do in the next weeks.

**Comment by LukeTowers** [comment]
Awesome, thanks @munxar! The core team is quite swamped with everything else that needs doing so I appreciate the community's work on this plugin.

**Comment by munxar** [comment]
@alvaro-canepa @LukeTowers here you go:
https://github.com/rainlab/translate-plugin/pull/344
It needs some testing, polishing and documentation, I'd be very happy if some native could do the docs ;-)
