### ISSUE TITLE
Dosen't make difference btw lower and upper case messages keys

### ISSUE THREAD

**Issue by EMFLUX** [rainlab/translate-plugin#150]
The Plugin is really useful even if it doesn't translate urls.

There is an other little problem, when you scan messages and you have two times the same word  (for example 'Login' and 'login') the plugin scan only one word in lowercase ('login'). any idea ?

**Comment by boogiestrat** [comment]
+1

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
