### ISSUE TITLE
Error with "Choose link" in Richeditor when Translate plugin installed

### ISSUE THREAD

**Issue by tombien** [rainlab/translate-plugin#152]
Hello,
there is an error when I have Translate plugin installed. Richeditor (no matter what plugin it is) shows error in Insert link > Choose Link.  "... _pages_links_form.htm not found..."
Without Translate plugin is all OK.

Can you please make some upgrade of Translate plugin? Thank you.

**Comment by boogiestrat** [comment]
+1

**Comment by abnmt** [comment]
Same problem. But the error only appears in the Pages Richeditor.
October fresh install.
![chose_link_error](https://cloud.githubusercontent.com/assets/894120/17632887/68a9fab8-60d3-11e6-98e0-89cb17a9c3d5.PNG)

**Comment by daftspunk** [comment]
Thanks @tombien and @abnmt!
