### ISSUE TITLE
HTML placeholder translation from static page not loaded

### ISSUE THREAD

**Issue by Eoler** [rainlab/translate-plugin#153]
Tried with HTML type of placeholder in layout with StaticPage component:
`{% placeholder services title="Services" %}`

Already saved content isn't loaded back after switching language with dropdown in richtext editor.

**Comment by amdad** [comment]
Tru.

**Comment by daftspunk** [comment]
As per the contribution guidelines, please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by Eoler** [comment]
OctoberCMS build 364, Translate 1.2.4 and Pages 1.2.10 plugins:

1. create layout with a placeholder to define additional tab in static page [per instructions](https://octobercms.com/blog/post/static-pages-content-blocks-and-placeholders)
`{% placeholder services title="Services" %}`

2. add two languages in Settings/Translate/Manage languages

3. create a new static page, enter value for both languages in tab/richtext field Services, save

4. reopening page from 3. and switching entry field language to non-default doesn't load previously saved value (that exists in `content\static-pages-<nondefault_lang_code>\<page_name>.htm` inside `{% put services %}{% endput %}`)

**Comment by daftspunk** [comment]
This bug has been replicated successfully.

**Comment by daftspunk** [comment]
Fixed in v1.2.7+ using October Build 381+

**Comment by Eoler** [comment]
Looks Fixed To Me.
