### ISSUE TITLE
Save model with translation

### ISSUE THREAD

**Issue by ametad** [rainlab/translate-plugin#155]
Hello,

I've got a question about how this plugin works. In the documentation I found this:

```
$user = User::first();

// Outputs the name in the default language
echo $user->name;

$user->translateContext('fr');

// Sets the name in French
$user->name = 'Giselle';

// Outputs the name in French
echo $user->name;
```

Do I understand correctly that with the text above in mind, saving this French name of the $user model would be as simple as:

```
$user->save();
```

Correct?

**Comment by ametad** [comment]
And then retrieving this would echo the name in the language that is currently set (e.g. choosen with the locale picker)?

Or do you always have to set the translateContext() first?

**Comment by daftspunk** [comment]
Correct. Test it and you should see these assertions to be true. 

> Or do you always have to set the translateContext() first?

You shouldn't need to use `translateContext` as it will detect it from the session (locale picker) or URL prefix.

**Comment by ametad** [comment]
For my project developing ElasticSearch functionality, I need to get model attributes with all their translations. So that upon save the translations can also be indexed in their own place. 

Is there a way to get all translations of a model attribute?

**Comment by daftspunk** [comment]
May I suggest casting your model to an array to have all the attributes mutated (and thereby translated)...

```
$model->lang('en')->toArray();
```

**Comment by ametad** [comment]
Thank you!
