### ISSUE TITLE
[QUESTION] Translating the Static Page URL property

### ISSUE THREAD

**Issue by Verbat** [rainlab/translate-plugin#156]
Just found out that it is now possible to translate the CMS URL. Tried it and it works great.
I was just wondering if this will be available for the Static pages as well or does it already work and I just missed it?

Thanks

**Comment by daftspunk** [comment]
Relates to Issue #25. Yes, it should be covered off as part of this issue.

**Comment by Verbat** [comment]
Thanks for letting me know.

**Comment by daftspunk** [comment]
This is implemented as part of #25
