### ISSUE TITLE
Plugin components ignored

### ISSUE THREAD

**Issue by trsh** [rainlab/translate-plugin#158]
I see not way using this plugin with Plugin component, what when added to front-end template, is obviously a part of it.

**Comment by daftspunk** [comment]
![what-meme](https://cloud.githubusercontent.com/assets/1392869/17477141/d6026c38-5da6-11e6-9675-74f5fbbcefbb.jpg)

**Comment by daftspunk** [comment]
Try reading the documentation, or even install the theme called RainLab.Bonjour, it provides a working example that uses this plugin.

**Comment by trsh** [comment]
I'm taking about using translate plugin fro MY custom XXX.XX plugin component. In components/yy/default.html the translations are not gathered.

**Comment by trsh** [comment]
When I put   {{ 'translatable text'|_ }} in
plugins\manage\photoalbum\components\albums\default.htm
it's not found by scan.

**Comment by daftspunk** [comment]
The scan won't scan components, it's only basic enough to scan the theme files. However, this string will be imported the first time it renders on the page.

**Comment by trsh** [comment]
> However, this string will be imported the first time it renders on the page.

How to u recommend to import it? I do not want to spam Theme with plugin/component related stuff.

**Comment by daftspunk** [comment]
Read the documentation:

> Themes can provide default values for these messages by defining a translate key in the theme.yaml file, located in the theme directory.

**Comment by trsh** [comment]
> Themes can provide default values for these messages by defining a translate key in the theme.yaml file, **located in the theme directory**.

Dude! I need translations for MY.PLUGIN component, what will be used in theme. Not theme it self. My plugin can be reused in lot's of themes, so how does your answer and documentation help?
