### ISSUE TITLE
Translatable fields don't show language tag to translate + causes internal server errors

### ISSUE THREAD

**Issue by CptMeatball** [rainlab/translate-plugin#160]
On a fresh install, both local (valet) and on production server, the tags in the input fields that contain the different language option won't show. 

On the current stable build (351) nothing shows at all, with edge updates enabled (357) and the translate plugins updated to 1.2.2 the CMS section does show the translation options for the URL of `cms pages` (which is an edge feature of the translate plugin at the time of writing). 

Translation of custom plugins by implementing the Translate behaviour in a model also does not trigger language options. Tested on inputs and rich editors. 

Build 351:
![screen shot 2016-08-11 at 12 58 42](https://cloud.githubusercontent.com/assets/1681727/17586690/93b66482-5fc3-11e6-98d5-bca652e8e17e.png)

Build 357:
![screen shot 2016-08-11 at 13 00 15](https://cloud.githubusercontent.com/assets/1681727/17586689/93909f40-5fc3-11e6-8fb3-422fbe5feb1e.png)

**UPDATE**
When saving a CMS page a internal server error occurs:
![screen shot 2016-08-11 at 15 43 17](https://cloud.githubusercontent.com/assets/1681727/17590703/fb364458-5fda-11e6-9a63-3de4d75dcfee.png)

**Comment by daftspunk** [comment]
Unable to replicate this, take a screenshot of your languages UI. Is it possible you are missing a default language?

**Comment by CptMeatball** [comment]
<img width="976" alt="screen shot 2016-08-26 at 17 06 55" src="https://cloud.githubusercontent.com/assets/1681727/18010140/8a47fd64-6baf-11e6-9295-e6a6a43ca6ef.png">

**Comment by daftspunk** [comment]
Ok, sorry I'm a bit lost here. Will need end-to-end replication instructions, from a fresh October installation.  As per the contribution guidelines, please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by CptMeatball** [comment]
Will make a screencap soon with step by step instructions.

**Comment by CptMeatball** [comment]
Hmm, never came around to provide further replication of the issue. I've haven't experienced any problems regarding this but the question remains: is translatable suppose to provide `title` and meta tags translation support?

**Comment by daftspunk** [comment]
Not as part of the UI. You can translate them easily by using the `|_` twig filter, eg: `{{ this.page.meta_title|_ }}`.

**Comment by CptMeatball** [comment]
I think this isn't relevant anymore. Hasn't happened anymore and it seems nobody else experiences this problem.
