### ISSUE TITLE
localePicker problem

### ISSUE THREAD

**Issue by feachure** [rainlab/translate-plugin#162]
Going directly to "/ru" and "/en" of the page everything works and is translating just right...

But I have problems with making localePicker work. I tried both default Language Picker Component and simpler example, but neither of them work. For example when I am using 

`<p>
    Switch language to:
    <a href="#" data-request="onSwitchLocale" data-request-data="locale: 'en'">English</a>,
    <a href="#" data-request="onSwitchLocale" data-request-data="locale: 'ru'">Russian</a>
</p>`

links just uses href and just adds "#" to the end of url.

I have included the [localePicker] component in my layouts... Maybe someone can help me figure out what could be wrong?

**Comment by daftspunk** [comment]
You might be missing the `{% framework %}` tag from your layout. Make sure it also has a reference to a copy of jQuery.

**Comment by feachure** [comment]
Huge thanks! Now works like a charm! :+1:
