### ISSUE TITLE
Provide an API for translating slugs via onSwitchLocale

### ISSUE THREAD

**Issue by thomasilmer** [rainlab/translate-plugin#167]
**I was told to create a new issue for this, this is a copy of my post in Translate page's URL issue #25.**

Hello @daftspunk , I have been testing the new feature and so far it's great! 

I just have one small issue with implementing the translatable slugs. Let's say I have a page with this signature:

```
url = "/projects/:slug"

[viewBag]
localeUrl[nl] = "/projecten/:slug"
localeUrl[de] = "/projekte/:slug"
```

In which ":slug" is different for every language, e.g.:
en => house
nl => huis
de => haus

Currently we have a custom plugin which has a backend menu for adding projects (Basically adds a Project model with some properties), which has a translatable index attribute "slug". In the onRun() function of "/projects/:slug" we check the database for a Project model which has the current slug as attribute. The page is then populated with properties of the Project model.

This works fine, untill you use the localePicker, because only the "projects/projecten/projekte" part of the url is switched. The ":slug" part stays the same as before the locale switch. This can result in people being redirected to "projects/huis" for example. This URL (rightfully) gives a 404. 

I tried looking at how RainLab.Pages plugin tries to solve this, but I haven't found the same functionality there.

What is a nice solution to translate the slug when the onSwitchLocale is called?

I also have a second issue which is somewhat similar. Let's say I don't use the language prefixes /en/, /nl/ or /de/, but instead use domains to determine the locale:

example.com => english
example.nl => dutch
example.de => german

Currently we set the session locale based on the domain and it works. Except again, when we switch language with the localePicker, the domain won't change with it. Currently we have a temporary fix by redirecting to the domain homepage (not using the localePicker), but it would be a lot nicer to redirect to the current page in a different language.

Is there an event for onSwitchLocale? Because then we could probably set the domain after onSwitchLocale ourselves, but currently I don't know how to fix this.

Sorry if this is in the wrong topic, but I felt like this is partly in the scope of the new translatableIndexes.

**Comment by jcardell** [comment]
+1

**Comment by Borgoroth** [comment]
+1

**Comment by Fl0Cri** [comment]
+1 currently it's confusing to see that urls for static pages are translatable, but not slugs in blog posts (as mentioned by @thomasilmer, trying to translate a slug would result in a buggy situation where changing the language may lead to a 404)

**Comment by roulendz** [comment]
Is there fix for this, I also have the same problem. 
Switching language the slug does not get translated. 

Maybelline there is some other way to overcome this issue?

**Comment by LukeTowers** [comment]
Potential solution in #244

**Comment by didiervassout** [comment]
@thomasilmer 

>  In the onRun() function of "/projects/:slug" we check the database for a Project model which has the current slug as attribute. The page is then populated with properties of the Project model.

How did you achieve this? I'm also have a custom model and I get, via builderList, a list of records but the detail page with a translated slug give me a "record not found".

**Comment by mjauvin** [comment]
Would you all agree #341 resolves this?

Anyone who thinks not is welcome to re-open this issue.
