### ISSUE TITLE
 Individual values  // RLTranslate[en][title]

### ISSUE THREAD

**Issue by pitylee** [rainlab/translate-plugin#168]
Hi. Lately my backend pages end like this:

        
    <input
        type="hidden"
       name="RLTranslate[en][title]"
        value="int(2)
I have no clue what is wrong. It happens with Rainlab Blog /Update/id and Testimonials plugins.

**Comment by daftspunk** [comment]
As per the contribution guidelines, please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by pitylee** [comment]
Well I simply opened some files, and it just worked. I have no idea why it didn't, than why it did work...

**Comment by daftspunk** [comment]
Interesting, leave another comment if you are able to reliably replicate it.
