### ISSUE TITLE
localeUrl filter for generating prefixed URLs

### ISSUE THREAD

**Issue by daftspunk** [rainlab/translate-plugin#169]
We may need another filter called |localeUrl or something
So you can use {{ 'home'|page|localeUrl('en') }} or {{ 'about'|staticPage|localeUrl('ru') }}

**Comment by alxy** [comment]
Wouldn't it also be an option to force the language via a parameter to the filter? But that would require the translate plugin to override the other filters, however, in my eyes it looks better than these chained filters.

**Comment by daftspunk** [comment]
@alxy it is so you could generate a string of links to different locales. `localeUrl` will look at the first segment of the url and check if it is a locale and replace it with the specified one, if none is found, it will append it. The locale is specified at the Laravel route level, a bit like middleware, so not available as a standard parameter.

```
{{ 'home'|page|localeUrl('en') }} | {{ 'home'|page|localeUrl('ru') }}
```

A simple filter

- `{{ 'http://google.com'|localeUrl('en') }}` --> http://google.com/en
- `{{ 'http://google.com/en'|localeUrl('fr') }}` --> http://google.com/fr

**Comment by mahony0** [comment]
how about this feature? generating localized without JS support is a good feature i think..

**Comment by amdad** [comment]
I was searching for way to get translated links plain from twig/php. This issue is still opened, so currently there is no way to generate static links for page? As @mahony0  said,  without JS switching? 
JS isn't very SEO friendly right?

**Comment by LukeTowers** [comment]
@daftspunk is still something you plan on implementing?

**Comment by mjauvin** [comment]
What do you guys think of the proposed fix above?
