### ISSUE TITLE
How to translate image upload field with type is fileupload?

### ISSUE THREAD

**Issue by andreconghau** [rainlab/translate-plugin#171]
Hi all,

I have quick question about translate field image upload

in file fields.yml:

fields:
    cover:
        label: Banner image
        type: fileupload
        mode: image-single

in file Model:

    public $implement = ['@RainLab.Translate.Behaviors.TranslatableModel'];

    public $translatable = ['cover', 'description'];

Textarea is ok but Image upload field not working.

Thanks

**Comment by daftspunk** [comment]
`fileupload` is not translatable at this stage. What is the expectation here, a different upload per locale?

**Comment by daftspunk** [comment]
Duplicate #171

**Comment by andreconghau** [comment]
Thanks @daftspunk .

Hope it come soon ^^

**Comment by Alex360hd** [comment]
Same here, first multilanguage website with october and I'm surprised to see that it's not fully translatable yet.
