### ISSUE TITLE
How to handle Translation in component ???

### ISSUE THREAD

**Issue by MK4Tech** [rainlab/translate-plugin#172]
Hey guys,  I have a component how to handle it in translation.

**Comment by MK4Tech** [comment]
I found another issue, scene I put my Navigation in content to handle translation it each link throws me to 
404 **Sorry! Page Not Found**.

**Comment by daftspunk** [comment]
As per the contribution guidelines, please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
