### ISSUE TITLE
Question: About back-end locale switcher

### ISSUE THREAD

**Issue by daviskregers** [rainlab/translate-plugin#178]
Hello,

I'm new to octobercms. I was setting up translatable fields for Models and stumbled upon a problem with the locale switcher on backend forms. Is it possible to have separate tabs for backend forms for each locale instead of the switcher on each input field?

For example, I have one tab for English language and one for Russian etc while creating an entry instead of having to switch the language for each input field.

Thanks in advance

Best Regards

**Comment by Kunilt** [comment]
No, it's not possible without custom implementation.
Try switching locale with Ctrl/Cmd pressed. It will switch locale on all translatable fields.

**Comment by dragontree** [comment]
I created a workaround in a form of a plugin.
The plugin adds a backend localepicker widget which creates a tab for each locale. Actually they are not actually tabs but just look like ones. And clicking on a locale will switch the locale for all input fields at once.
