### ISSUE TITLE
How can customize the back-end localePicker

### ISSUE THREAD

**Issue by Obazure** [rainlab/translate-plugin#179]
Hi everybody,

I didn't found the information how to customize the localePicker

I found that i can use 

> < a href="" data-request="onSwitchLocale" data-request-data="locale: 'en'" >EN< /a >

But is it possible to get only current language key or name? I just one of them.

I mean this localePicker
![asd](https://cloud.githubusercontent.com/assets/18247533/19782313/1c7ecf48-9caf-11e6-9bf3-d55501d68a09.png)

**Comment by daftspunk** [comment]
See the documentation on [customizing default component markup](http://octobercms.com/docs/cms/components#customizing-default-markup) for more information.

**Comment by Obazure** [comment]
Thanks,

I sivled it with
```
<li><a href="">{{ localePicker.activeLocale | upper  }}</a>
    <ul class="dropdown">
        <li><a href="" data-request="onSwitchLocale" data-request-data="locale: 'kz'">KZ</a></li>
        <li><a href="" data-request="onSwitchLocale" data-request-data="locale: 'ru'">RU</a></li>
        <li><a href="" data-request="onSwitchLocale" data-request-data="locale: 'en'">EN</a></li>
    </ul>
</li>
```
