### ISSUE TITLE
Translations when creating Models

### ISSUE THREAD

**Issue by alxy** [rainlab/translate-plugin#18]
Currently, translations do not work in Popups/Modals. Screenshot: https://www.dropbox.com/s/13lo069zldzkmqx/Screenshot%202014-08-23%2015.36.34.png?dl=0

The POST-data looks correct, it includes the translation strings. Also, the TranslatableModel::setTranslateAttribute() function is called accordingly. However, in the syncTranslatableAttributes()-method the $translateableAttributes array is empty (empty array).
My guess is, the model / model behaviour is re -instanciated somewhere in the application. It may be related to the way october saves related models, but I couldnt investigate this any further.
I could somehow verify my guess by specifying a default value on the array:
```
protected $translatableAttributes = ['test'];
```
In this case, it really contained this value in the syncTranslatableAttributes()-method.

Hope this helps a bit. to identify the error.

**Comment by daftspunk** [comment]
Noted this only occurs during creation. Subsequent updates are fine.
