### ISSUE TITLE
Translate don't updates anymore

### ISSUE THREAD

**Issue by Michael-Reich** [rainlab/translate-plugin#180]
I installed following plugins:
- Renatio.FormBuilder
  -Indikator.Tracking 
- AlekseyP.GoogleTagManager
- Filipac.FacebookMessengerPopup

Since then the Plugin don't show any new messages. 

And I set {{ this.page.meta_description }} to {{ this.page.meta_description|_ }}.

That I can translate them, and they won't show in the Settings > Translate Messages Tab.

How I can flush the cache or find out why Translate doesn't scan anymore. Also, the Form Builder is buggy when I set a Label and I switch Languages it totally randomizes the outcome.

You can see the bugs here if you switch language:
https://adventure-studio.net/testpage

**Comment by daftspunk** [comment]
The scan for messages feature cannot always find every value, since some are dynamic. Try viewing the page so the translator can pick up the `this.page.meta_description` value for the first time.
