### ISSUE TITLE
Repeater translation throws errors

### ISSUE THREAD

**Issue by daviskregers** [rainlab/translate-plugin#186]
Hello,

I updated both rainlab-translate and rainlab-pages plugins as well as ran the "composer update" and updated all the dependencies. It seems to be throwing an error once I try to switch languages for the repeater:

`"Call to undefined method October\Rain\Halcyon\Builder::forceFill()" on line 776 of /Users/daviskregers/Repositories/ins/vendor/october/rain/src/Halcyon/Builder.php`

In the layout the repeater code is as follows:

```
{repeater name="header_slider" tab="Slider" prompt="Add more items"}
	{text tab="Content" name="title"    label="Slider title"  }{/text}
	{richeditor tab="Content" name="content"  label="Slider content"}{/richeditor}
	{text tab="Content" name="link"    label="Slider url"}{/text}
	{mediafinder tab="Content" 	mode="image" 	name="image" label="Slider image"}{/mediafinder}
{/repeater}
```

---

After inspecting the /content/static-pages it seems that the first language file has settings like this:

```
header_slider[1][title] = "x"
header_slider[1][content] = "<p>x</p>"
header_slider[1][link] = "x"
header_slider[1][image] = "/homepage-slider/slideshow-demo01.jpg"
```

and the second language:

```
header_slider[2][title] = "y"
header_slider[2][content] = "<p>y</p>"
header_slider[2][link] = "y"
header_slider[2][image] = "/homepage-slider/slideshow-demo01.jpg"
```

Also, I'm not quite sure if the first element index should be 2 for the second language array, but changing it to 1 or both to 0 didn't seem to be solving the issue.

**Comment by daftspunk** [comment]
This should be fixed in Build 380+

Ref: https://github.com/octobercms/october/commit/50d3ffb0353e122667ecd8b0af6073eba475c1c4
