### ISSUE TITLE
Translation is not working for the field in repeater.

### ISSUE THREAD

**Issue by jacksun101** [rainlab/translate-plugin#187]
I am using the awesome Translate plugin in one of my models like this.

    public $translatable = ['label', 'dlabel'];

The label is working while the dlabel is not. The dlabel is a field in repeater.

**Comment by mateop** [comment]
Use 
`public $translatable = ['label', 'REPEATER_NAME.dlabel'];
`

**Comment by jacksun101** [comment]
Thanks for your feedback, but it's not working. My repeater field is like this.


        details:
          label: Details
          type: repeater
          form:
            fields:
                dname:
                    label: Name
                    span: auto
                    required: 1
                    type: text
                dcode:
                    label: Code
                    span: auto
                    disabled: 0
                    required: 1
                    preset:
                        field: dname
                        type: slug
                    type: text
                dlabel:
                    label: Label
                    span: full
                    type: text

When I use the following code, the "dlabel" is translatable, UI shows the translatable dropdown language string to the right. It looks correctly, but it's just not saving. However, if I use your suggestion which is "details.dlabel", the field is not even translatable.

`public $translatable = ['label', 'dlabel'];`

**Comment by MaxNozhkin** [comment]
+1

**Comment by daftspunk** [comment]
Update to the latest version of everything, then make your repeater itself translatable, i.e

```
public $translatable = ['label', 'details'];
```

The repeater has recently adopted translation support. Not for individual fields unfortunately.

**Comment by jacksun101** [comment]
Thanks, good enough for now.

**Comment by raskrial** [comment]
> The repeater has recently adopted translation support. Not for individual fields unfortunately.
si basically there's no way to translate individual field in a repeater right now ?
