### ISSUE TITLE
Translation in json api

### ISSUE THREAD

**Issue by mateop** [rainlab/translate-plugin#188]
Hi,  I am building an api for a mobile app, i can echo a translated model attribute but when i want to transform the model to json or an array the translations are lost. Am I doing something wrong? 
```
$tours = Tour::all();

foreach ($tours as $key => $t){
    $tours[$key] = $t->lang('en');
}

echo $tours[0]->name; //works

return response()->json($tours); //prints non translated
```

**Comment by daftspunk** [comment]
This will be fixed in October Build 381+

Thanks!
