### ISSUE TITLE
Translatable mediafinder field

### ISSUE THREAD

**Issue by MaxNozhkin** [rainlab/translate-plugin#192]
How to use translatable mediafinder field? Is it possible?

**Comment by daftspunk** [comment]
This is a planned feature.

**Comment by LukeTowers** [comment]
@daftspunk is this still a planned feature? What needs to happen for this?

**Comment by munxar** [comment]
@LukeTowers @daftspunk here you go: [](https://github.com/rainlab/translate-plugin/pull/325)
Only thing I can't figure out is how it automagically renders as MLMediaFinder if used in a static page syntax field (like text and all others do). Any Idea?

**Comment by LukeTowers** [comment]
Does it not register in https://github.com/rainlab/translate-plugin/pull/325/files#diff-252810a1b0bce82b1a1ef724cee3c8deR140?

**Comment by munxar** [comment]
@LukeTowers thats what I thought, but it doesn't work. `$model->getTranslatableAttributes()` does not return them...

**Comment by LukeTowers** [comment]
@munxar did you mark the attribute it was getting stored in as translatable?

**Comment by munxar** [comment]
@LukeTowers it's a dynamic syntax field, usually I don't have to register anything. If I use it in a normal backend form with a model and the translatable attribute registered, it works.
Do I miss something?

**Comment by LukeTowers** [comment]
Check how the pages plugin determines what fields to render and where it registers them as translatable.

**Comment by munxar** [comment]
Ahhhh, found it. So then this PR is complete. I'll have to add one to the Pages plugin too, to make it  work for syntax fields.

**Comment by mjauvin** [comment]
@LukeTowers @munxar shouldn't that be closed? As far as I know, this is already implemented.

**Comment by mjauvin** [comment]
Closing this as it has been resolved by #325
