### ISSUE TITLE
Translating /builder-built/ plugins

### ISSUE THREAD

**Issue by tbergeron** [rainlab/translate-plugin#195]
I'm trying to implement this plugin to localize my plugin I built with builder.

I can't get my form fields to show the language picker, I did everything the github docs said but no luck. I guess there's some more backend work to do but nothing is stated in the docs. (Is there any more tables to create to contain the localizations?)

For the sake of documenting the process we really should get a tl;dr summary for newcomers. I have good Laravel 4/5 experience and I'm having trouble getting the translate plugin to work with my builder-built plugin. Once this process is documented, I can see a lot of people starting to use OctoberCMS for more serious projects.

I'd really love to learn how to do it the right way if anyone can help. Once I got it done, I guarantee I'll make a blog post about it so people can find it off Google and get to work. Thanks!

**Comment by Eoler** [comment]
> I can't get my form fields to show the language picker

This part usually works great - do you have at least two languages enabled in Settings / Translate / Manage Languages? October and Translate plugin version?

BTW, GitHub is not the greatest channel for support questions.

**Comment by tbergeron** [comment]
@Eoler I do have 2 languages in translate settings. I'm running the latest edge updates:
October build 387, Translate 1.2.7

I know GitHub isn't the best channel for support but both Slack and OctoberCMS forums are even quieter so I'm trying hard to get it to work so I can document it properly so nobody else has to go through what I'm doing right now hehe

Thanks for the help!
