### ISSUE TITLE
Translate functionality is absent in Edge Update 389

### ISSUE THREAD

**Issue by CptMeatball** [rainlab/translate-plugin#197]
After upgrading to latest edge build 389 backend localizations (multilingual form fields replacement, placeholders and variables in all plugins) stopped working. 

**Expected behavior**

Language indicators with dropdown switching behavior shown on translatable model fields.

**Actual behavior**

They are completely missing.

**Reproduce steps**

* Enable Edge Updates.
* Have two active languages defined in Settings/Translate/Manage Languages.
* Add TranslatableBehavior to`implements` array to model.
* Update `translatable` array with translatable fields to model.

**October build**

389 edge, Translate plugin 1.2.7

**Note:**
Existing translated content **does** work. It's only the backend implementation that fails.

Cross reference : https://github.com/octobercms/october/issues/2554

**Comment by tbergeron** [comment]
I'd really like to help with this but I don't know where to begin. I hesitate between trying to downgrade to the last build or try myself to fork and fix this issue. I have time to dedicate to this, I'd really love OctoberCMS to be our (our small startup) next go-to CMS. I'll try to dive into the docs to see what I could do.

**Comment by codee** [comment]
Same here. Both the Pages plugin and my own custom plugins don't show the language switch on form fields anymore.
