### ISSUE TITLE
Flash message translation 

### ISSUE THREAD

**Issue by artras** [rainlab/translate-plugin#200]
Hi, 
how can I translate text in flash messages? 

For example , I wand translate text "Course saved!" to different language

```
public function onCourseSave()
    {
        $course = new Model();

        $course->title = Input::get("title");

        $course->description = Input::get("description");

        Flash::success("Course saved!");

    }
```

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.

**Comment by LukeTowers** [comment]
@artras look into using the backend translator, Lang::get()
