### ISSUE TITLE
Question: Access translations programmatically / in console

### ISSUE THREAD

**Issue by nielsbuus** [rainlab/translate-plugin#203]
I have just joined a program that uses OctoberCMS. Given the following row in the `rainlab_translate_messages` table:

    2, login, {"x":"Login","sv":"Logga in","no":"Logg inn","fi":"Kirjaudu"}

I would expect the following code:

    php artisan tinker
    Psy Shell v0.7.2 (PHP 7.0.14 — cli) by Justin Hileman
    >>> Lang::setLocale("sv")
    => null
    >>> Lang::get("login")
    => "login"

To return `Logga in`, however it just returns the key. I am probably missing something obvious, but what?

**Comment by LukeTowers** [comment]
`Lang::get()` is for backend translations, it doesn't look at this plugin at all, only registered language files for backend use.
