### ISSUE TITLE
Translations in partial do not work in pages (anymore?)

### ISSUE THREAD

**Issue by Verbat** [rainlab/translate-plugin#204]
Edge Updates are enabled.
I'm running October with
Core: 389
Pages: 1.2.13
Translate: 1.2.8 (forceURL = 0)

I'm switching languages with 

```
<a class="item" data-request-data="locale: 'de'" data-request="onSwitchLocale" href="#"> Deutsch </a> 
```

and 

```
<a class="item" data-request-data="locale: 'en'" data-request="onSwitchLocale" href="#"> English   </a>
```

Steps to reproduce this issue.
1. Create new partial named "translate"
2. Add {{ 'Language Primary'|_ }} to this partial
3. Go to Translate messages and add "Language Secondary" as text at the appropriate language field
4. Add partial to a Layout wich is used in **static pages** ->  {% partial 'translate' %}
5. Check Website in primary language and it shows "Language Primary"
4. Switch to secondary language 
5. Website in secondary language still shows "Language Primary" but it should show "Language Secondary" as defined at the translate message section in the backend

Note: Using the partial in a layout which is used for a CMS page works without problems.
I cannot be 100% sure but i think it already worked in a previos version of Pages or at least i didn't notice it at the time.

**Comment by Eoler** [comment]
> Note: Using the partial in a layout which is used for a CMS page works without problems.
I cannot be 100% sure but i think it already worked in a previos version of Pages or at least i didn't notice it at the time.

Ouch, upgraded to edge build 391 with Translate plugin 1.2.8 and Twig translations are not working in partials on a static page with multilingual content. They definitely worked in previous versions before cms.page.renderPartial event was added to the core.

**Comment by tombien** [comment]
Hi,
I have problem with partials and translations. I have a partial with` {{ 'Language Primary'|_ }}`
If I put this partil -for example- to layout this way `{% partial 'my-partial' %}` translations are correct in correct current locale.
But when I use for example something like this - get some partial with ajax:
`function myFunction() { return ['#myDiv'] => $this->renderPartial('my-partial')]; } `
transaltions are always in default language. This php functions does not accept current local. I checked my ajax url and all are correct with correct language (domain.cz/en/....).

Thank you,
Tomas
