### ISSUE TITLE
Bug On CMS

### ISSUE THREAD

**Issue by iboldurev** [rainlab/translate-plugin#205]
Hello!

CMS Pages

There is no way to translate the names of pages, only the translation of links to the page

How to fix? Please help

BUILD Version OctoberCMS 390
Plugin version 1.2.7 - 1.2.8

![2016-12-25 12 59 40](https://cloud.githubusercontent.com/assets/17103170/21470874/a702193c-caa3-11e6-9d77-bf7e2fdf5dfe.png)

P.S

Static pages plugin it works fine
![2016-12-25 14 12 18](https://cloud.githubusercontent.com/assets/17103170/21471079/86004e26-caac-11e6-96f8-f84e9ee8778b.png)

**Comment by tbergeron** [comment]
I don't think this plugin should help translate anything on the CMS tab, only in the static pages tab. I wonder why there's a language picker un the URL field though. I have the same here right now.

**Comment by Eoler** [comment]
> I wonder why there's a language picker un the URL field though.

Because the plugin actually advertises URL translations here:
https://github.com/rainlab/translate-plugin#url-translation

**Comment by ctf0** [comment]
i believe this is intentional because for the pages plugin the page is saved in the db, so u have more than locale because its treated as a normal json column that gets fetched according to the current local,
however for the pages under cms, the page gets saved on the disk, so to have different names for the same file it means it have to be duplicated
as doc says
> Pages will not be duplicated for a given language

**Comment by LukeTowers** [comment]
@ctf0 The pages in the static pages plugin (this) are saved to disk, not to DB

**Comment by ctf0** [comment]
@LukeTowers okey, so why cant we have the same option with cms ? i mean what are the limitations ?

**Comment by LukeTowers** [comment]
I'm not sure, I didn't implement the integration with the Pages plugin. @daftspunk could probably provide more insight. It may be that it simply hasn't been implemented yet, feel free to dig into the existing integration with the Pages plugin to see what you can do as far as implementing it for the CMS pages via a PR

**Comment by ctf0** [comment]
i would gladly implement it if someone could give me some guide lines, am still new into this but surely would love to contribute :100:

**Comment by LukeTowers** [comment]
First step would be to look for any code within this plugin that references the RainLab.Pages plugin or look in the RainLab.Pages plugin for any code that references this plugin. Then take it from there. Apologies I can't provide more guidance than that to start, I'm not hugely familiar with how it was implemented and don't have time to look into it myself right now.

**Comment by ctf0** [comment]
@LukeTowers i found the one responsible for showing trans in pages is
```php
public $implement = [
        '@RainLab.Translate.Behaviors.TranslatablePageUrl',
        '@RainLab.Translate.Behaviors.TranslatableCmsObject'
    ];

public $translatable = [
        'code',
        'markup',
        'viewBag[title]',
        'viewBag[meta_title]',
        'viewBag[meta_description]',
    ];
```

i tried to look for a place to add this under cms but without luck.

strangely, even if u commented those lines out, u still get to translate the url 😲

**Comment by LukeTowers** [comment]
@ctf0 You would add them by extending the Cms\Classes\Page model class to implement them.

So, from the plugin boot method of this plugin where the following code is right now:
```
        /*
         * Handle translated page URLs
         */
        Page::extend(function($page) {
            $page->extendClassWith('RainLab\Translate\Behaviors\TranslatablePageUrl');
        });
```
extend the CMS Page class to add the $translatable property covering what needs to be translatable (I'm assuming `'url', 'title', 'description', 'meta_title', 'meta_description'`) and to implement the `RainLab\Translate\Behaviors\TranslatableCmsObject` behavior. Do this from this plugin and not from the main October project because we don't want to have a dependency on a plugin from October core.

Any questions?

**Comment by ctf0** [comment]
```php
Page::extend(function($page) {
    $page->extendClassWith('RainLab\Translate\Behaviors\TranslatablePageUrl');
    $page->extendClassWith('RainLab\Translate\Behaviors\TranslatableCmsObject');
    $page->addDynamicProperty('translatable',[
            'title',
            'url',
            'meta_title',
            'meta_description',
            'markup',
        ]
    );
});
```
?

**Comment by LukeTowers** [comment]
That should work, at least in theory. Have you tested it @ctf0?

**Comment by ctf0** [comment]
yeap and nothing changed, cms > page still same as b4 😢

**Comment by LukeTowers** [comment]
@ctf0 Try adding the property before extending the class

**Comment by LukeTowers** [comment]
@ctf0 did you try my suggestion at all?

**Comment by ctf0** [comment]
@LukeTowers hi again, i honestly can't remember after so long 😢

**Comment by LukeTowers** [comment]
Do you still use this plugin? Would you be willing to go through this thread again and figure out the original issue and if there was a solution to that?

**Comment by ctf0** [comment]
sadly i cant as i've already built my own https://github.com/ctf0/SimpleMenu which has some ideas of october
