### ISSUE TITLE
 fabriciorabelo slider , title not updating in multi language

### ISSUE THREAD

**Issue by dhanishapa** [rainlab/translate-plugin#208]
I have been working with fabriciorabelo slider and translate plugin in octobercms. The translate action in each slider title is working fine and also translations while creating a slider item. But slider item updation not working in sub languages. Its working only for default language. Anyone know how to make it work for slider item and caption updation for all languages? Please help.

Thanks in advance

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
