### ISSUE TITLE
Repeater richeditor translation

### ISSUE THREAD

**Issue by daviskregers** [rainlab/translate-plugin#218]
Hello,

Thank you for the fix of the https://github.com/rainlab/translate-plugin/issues/216
There is a minor problem though, I use the same setup of the previous issue - whenever I switch the language, the richeditor does not load it's content. If I switch the variable type to textarea, it does show the content:

https://www.dropbox.com/s/vjb2w8s5enl1t9k/Screenshot%202017-02-03%2009.16.51.png?dl=0
https://www.dropbox.com/s/fp8pj8l9s7dassv/Screenshot%202017-02-03%2009.17.26.png?dl=0

**Comment by artras** [comment]
same problem...

**Comment by canthis** [comment]
Got this issue as well.

Proposed fix is modifying [line 24 of /modules/backend/formwidgets/richeditor/partials/_richeditor.htm](https://github.com/octobercms/october/blob/develop/modules/backend/formwidgets/richeditor/partials/_richeditor.htm#L24)
```
 <textarea name="<?= $name ?>" id="<?= $this->getId('textarea') ?>"><?= e($value) ?></textarea>
```
To output _$field->value_ instead of _$value_ fixes this issue.
```
<textarea name="<?= $name ?>" id="<?= $this->getId('textarea') ?>"><?= e($field->value) ?></textarea>
```
I'll be glad to hear @daftspunk thoughts on this.

**Comment by artras** [comment]
@daftspunk ?

**Comment by canthis** [comment]
I've created new issue with all instructions and test plugin on October's main repo here octobercms/october#2662, because problem is with Richeditor formwidget itself, and there's nothing to do with Translate plugin.

**Comment by amdad** [comment]
I can confirm this bug, I was fighting with repeater translation half day. The same problem here. Translations are not loaded correctly after save. Used on Settings Model Behaviour form.

**Comment by daftspunk** [comment]
Fixed in https://github.com/octobercms/october/pull/2663
