### ISSUE TITLE
How to query for language attributes using Eloquent?

### ISSUE THREAD

**Issue by iSaadSalman** [rainlab/translate-plugin#222]
I have some language attributes the I want to search on while the language is switched. For Example:
 
`$items = Recipe::
                                                 where('recipe_name', 'like', "%${query}%")
                                                 ->orWhere('recipe_tag', 'like', "%${query}%")
                                                 ->orWhere('directions', 'like', "%${query}%")
                                                 ->orWhere( 'ingrediants', 'like', "%${query}%")
                                                 ->where('by_user','=', 0)
                                                 ->get();
                                 // do other stuff with found records`

How would I do that?
Thanks

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
