### ISSUE TITLE
How can I access localeUrl in page?

### ISSUE THREAD

**Issue by anonimo9** [rainlab/translate-plugin#223]
Hi, is it possible to access and return localeUrl in page ?
I trying to access:
`{{  this.page.viewBag.localeUrl.en }}` but its returning nothing.
`{{  this.page.settings.viewBag.localeUrl.en }}` this not working too.

`{{ this.page }} `I so it :

`{"fileName":"home.htm","content":"title = \"Pagrindinis\"\nurl = \"\/\"\nlayout = \"default\"\nmeta_title = \"ddd\"\nmeta_description = \"ddd\"\nis_hidden = 0\nseo_keywords = \"ddd\"\ncanonical_url = \"dd\"\nrobot_index = \"index\"\nrobot_follow = \"follow\"\n\n[viewBag]\nlocaleUrl[eng] = \"\/main\"\nlocaleUrl[en] = \"\/main\"\n==\n{% content \"puslapiai\/mainPage.htm\" %}","mtime":1486377348,"markup":"{% content \"puslapiai\/mainPage.htm\" %}","code":null,"title":"Pagrindinis","url":"\/main","layout":"default","meta_title":"dd","meta_description":"dd","is_hidden":"0","seo_keywords":"dd","canonical_url":"dd","robot_index":"index","robot_follow":"follow","viewBag":{"localeUrl":{"eng":"\/main","en":"\/main"}},"settings":{"title":"Pagrindinis","url":"\/main","layout":"default","meta_title":"ddd","meta_description":"dd","is_hidden":"0","seo_keywords":"ddd","canonical_url":"Sddd","robot_index":"index","robot_follow":"follow","viewBag":{"localeUrl":{"eng":"\/main","en":"\/main"}}}} `

**Comment by anonimo9** [comment]
best support ever ! Thanks.

**Comment by LukeTowers** [comment]
@anonimo9 You get what you pay for I suppose :)

Try setting `{% assign pageVar = this.page %}` and then accessing the property of that variable `{{ pageVar.viewBag.localeUrl.en }}`

**Comment by Glitchbone** [comment]
{{ viewBag.localeUrl.en }} does the trick

**Comment by daftspunk** [comment]
It can feel like you are being ignored but the reality is there are so many mouths to feed. Protip: Jump on IRC if you want to chime the service bell. Bonus points for being polite to the volunteers who are there to help.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
