### ISSUE TITLE
"Record finder" form field does not work with translated attribute

### ISSUE THREAD

**Issue by Minius-dev** [rainlab/translate-plugin#224]
Hi,  

This related problem with backend widget Backend\Widgets\Search and **Record finder** form field. Search does not work with **translated attribute**. 
  
**In more details:**  
1. Let use "Record finder" form field (filter works based on Backend\Widgets\Search widget); 
2. Install translations with origin rainLab translation plugin. Setup some languages; 
3. Try search with some key from original language - all good. And now, try again with keyword from translated attribute - search does not work; 
Checked with oc-test-plugin to, the situation is the same. does not work; 
  
How ca we solve this problem?  
Thanks

**Comment by Minius-dev** [comment]
Well, anyone is able to solve this problem? and how much it would cost

**Comment by LukeTowers** [comment]
Am I correct in assuming that you want to be able to search records by their translated attributes?

**Comment by Minius-dev** [comment]
Yes, correctly.
In default language works well, but in translated attributes it is bug

**Comment by Minius-dev** [comment]
It`s so difficult? Even for october team? :)
May you can give me right direction, i try my self

**Comment by LukeTowers** [comment]
More so we don't have time at the moment to look into the issue more ourselves :)
I'd love for you to take a look yourself, first thing you need to do is figure out where and how those translated attributes are stored, and then you can go from there to figure out how to extend the search functionality in such a way that it searches those data sources when they are available.

**Comment by Minius-dev** [comment]
oh, okey, i will try now,
thanks:)
but in the future I hope your team will update that

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
