### ISSUE TITLE
Unable to to create a multilingual page

### ISSUE THREAD

**Issue by 69rand** [rainlab/translate-plugin#228]
What I'm doing wrong, or this functionality does not work in the current version?

Content blocks works (help.ru.htm / help.en.htm / etc), post-processing replacement text works, but pages - doesn't.

Video:
https://yadi.sk/i/be1INfcw3EVaJv

**Comment by LukeTowers** [comment]
I don't think CMS pages are supported to be translated, but I could be wrong. 
Closing as it has been over a month since any activity on this occurred.
