### ISSUE TITLE
Add undocumented features to the README.md

### ISSUE THREAD

**Issue by CptMeatball** [rainlab/translate-plugin#229]
While searching for a way to switch all locales for a model, I've stumbled on an non-documented feature hidden in the `multilingual.js`. This is something some of our clients have requested, but till this day I didn't know of a way to do this. 

I propose to add a simple user manual to the README.md to make this feature accessible for everyone. 

Something like this?

# User Interface

#### Switching locales

Users can switch between locales by clicking on the locale indicator on the right hand side of the Multilanguage input. By holding the CMD / CTRL key all Multilanguage Input fields will switch to the selected locale.

**Comment by daftspunk** [comment]
Sounds great! Can you submit a PR for this?
