### ISSUE TITLE
Pushed partial by ajax request has not the translations.

### ISSUE THREAD

**Issue by intro1987** [rainlab/translate-plugin#234]
```
return [
        '#myDiv' => $this->renderPartial('mypartial')
    ];
```
**mypartial** includes messages, like this {{'message'|_}}, and this message responses without any translation.

**Comment by Hambern** [comment]
I am too geting this error. I want to make things in a partial translatable. Like:

```
return [
            $this->property("idElementWrapperBasketComponent") => $this->renderPartial('::basket-0', $data)
        ];
```

But it doesn't seem to work. I get the error:

```
Unexpected character "'".
```

# | CALLED CODE | DOCUMENT | LINE
-- | -- | -- | --
50 | Twig_Lexer->lexExpression() | ~/vendor/twig/twig/lib/Twig/Lexer.php | 202
49 | Twig_Lexer->lexVar() | ~/vendor/twig/twig/lib/Twig/Lexer.php | 105
48 | Twig_Lexer->tokenize(…) | ~/vendor/twig/twig/lib/Twig/Environment.php | 491
47 | Twig_Environment->tokenize(…) | ~/vendor/twig/twig/lib/Twig/Environment.php | 544
46 | Twig_Environment->compileSource(…) | ~/vendor/twig/twig/lib/Twig/Environment.php | 363
45 | Twig_Environment->loadTemplate(…) | ~/modules/cms/Classes/Controller.php | 917
44 | Cms\Classes\Controller->renderPartial(…) |   |  
43 | call_user_func_array(…) | ~/modules/cms/Classes/ComponentBase.php | 145
42 | Cms\Classes\ComponentBase->renderPartial(…) | ~/plugins/jiri/jkshop/components/Basket.php | 64
41 | Jiri\JKShop\Components\Basket->onRunBasket() | ~/plugins/jiri/jkshop/components/Basket.php | 52
40 | Jiri\JKShop\Components\Basket->onRun() | ~/modules/cms/Classes/CmsCompoundObject.php | 172
39 | Cms\Classes\CmsCompoundObject->runComponents() | ~/modules/cms/Classes/Controller.php | 412
38 | Cms\Classes\Controller->execPageCycle() | ~/modules/cms/Classes/Controller.php | 349
37 | Cms\Classes\Controller->runPage(…) | ~/modules/cms/Classes/Controller.php | 213
36 | Cms\Classes\Controller->run(…) | ~/modules/cms/Classes/CmsController.php | 50
35 | Cms\Classes\CmsController->run(…)

**Comment by Hambern** [comment]
My problem suddenly went away after changing ```{{'Continue'|_}}``` to ```{{"Continue"|_}}```seems like single quotes are not OK in partials.
