### ISSUE TITLE
How can I check if the record is translated?

### ISSUE THREAD

**Issue by PopcornPHP** [rainlab/translate-plugin#236]
Hi every one!

How I can check, in component, if current record is translated? Google provide to use "canonical urls", and I want set link to page with default translation, when current record is not translated

Canonical URLs
[https://support.google.com/webmasters/answer/139066?hl=en](https://support.google.com/webmasters/answer/139066?hl=en)

Thank you!

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
