### ISSUE TITLE
Message::trans('my.message.code') stopped working around 1.2.8

### ISSUE THREAD

**Issue by mrbohnke** [rainlab/translate-plugin#237]
I use `Message::trans('my.message.code')` on my theme pages, inside `onStart()`.
It used to work like a charm on **1.2.7**, just like its twig equivalent `{{'my.message.code'|_}}`. It stopped working on **1.2.8** and now just prints the message code instead of the translated value.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.

**Comment by maartenmachiels** [comment]
Hi guys, I'm seeing the same issue... This used to work and was very useful. Now it just prints the message code...
What is the correct way to use the translate plugin from within PHP? Any workaround?

**Comment by maartenmachiels** [comment]
Figured it out... You need to set the context like so, and then it works:
```
Message::$locale = $labelrequest->user->language_preference;
Message::setContext($labelrequest->user->language_preference, 'mail');
```
