### ISSUE TITLE
GET http://www.example.dev/plugins/rainlab/translate/assets/js/locales.js 404 (Not Found)

### ISSUE THREAD

**Issue by getrightnl** [rainlab/translate-plugin#240]
The plugin is installed by marketplace, but when I open the manage languages in backend settings page. I get the following error in chrome.

GET http://www.example.dev/plugins/rainlab/translate/assets/js/locales.js 404 (Not Found)

I checked the /plugins/rainlab/translate/assets/js folder of the plugin and the file is present.

**Comment by getrightnl** [comment]
My bad. I am using the october:mirror /public command. Just re-run the command and it is working ;)

**Comment by daftspunk** [comment]
That one gets me all the time!
