### ISSUE TITLE
Repeater Field / Media finder / not storing in DB

### ISSUE THREAD

**Issue by alexaxhauck** [rainlab/translate-plugin#241]
Hi,
the Plugin works fine translating Texts and Textaereas in my Repeater field.

I have field 'Media finder' field in my repeater form with 'Mode Image'.

First the User changes the lng from EN to DE all fields are emptied out (which is not very helpfull for a translator) and translate the text. now he hast to select the image again otherwise the field will be empty in the DB.

Second
if a translator needs to change later in the translation sth small,  the image/media will be overwritten and stays empty in the db. So the Translater needs to find the image every time he works on the text. While working on the translation the editor has no thumbnail preview which makes it mor complicates

Cheers Alex

**Comment by LukeTowers** [comment]
I've labelled this as an enhancement as it's not necessarily a bug (kinda debatable though), more so a very annoying UX issue for users of the system.

**Comment by Fl0Cri** [comment]
I have also encountered this problem, especialy the second (as well as other people here #218). As said by @alexaxhauck, the mediafinder value is not loaded correctly by the repeater when switching language, so it is cleared when we save the page. And it doesn't only apply to mediafinder, but also to richeditor and probably all form widgets. An issue is open here on October repo https://github.com/octobercms/october/issues/2662

In my case, I have a page that is made of multiple blocks (repeater) containing an image (mediafinder), a title (text) and a longer content (richeditor). Each time I want to edit the content in an other language that my default language, I have to:
- Find again all images in the media gallery for each block
- Copy and paste the content of each richeditor from the actually online page (or from google cache when I sometimes forget it)

This would make the process of editing this page from the backend quite annoying, but hopefully there is a workaround as suggested here https://github.com/canthis/october/commit/1be31b0dc087a00b7f86a45068855fb495ac0021. It is also applicable to all other form widgets such as mediafinder and I can confirm it is working for a moment now on my website on prod, but a hack is a hack and it have to be reapplied after each core update.

**Comment by LukeTowers** [comment]
In theory fixed by https://github.com/octobercms/october/pull/2663
