### ISSUE TITLE
Translate menu links

### ISSUE THREAD

**Issue by virtualLast** [rainlab/translate-plugin#246]
Hi sorry, I've had to pick up this project and im not familiar with the system. There is some content on the site being translated but the main menu items are not.

I have attached the menu-items.htm where the menu links are generated but dont know what to do with the Translate plugin in order to get the links to translate. I need the links in spanish and french
[menu-items.htm.zip](https://github.com/rainlab/translate-plugin/files/904953/menu-items.htm.zip)

any guidance would be appreciated

**Comment by jan-vince** [comment]
Hi, this is still work in progress. There is an open [bounty](https://www.bountysource.com/issues/37969749-question-are-the-menu-items-be-translatable) to make this more user friendly (and in bounty comments you can find some workarounds).

Basicaly you can use this:

```php
<ul>
{% for item in items %}
 <li>{{ ('nav.' ~ item.code)|_ }}</li>
{% endfor %}
</ul>

```

Once you open frontend page with generated menu, you will see all strings ready for translation in backend list in Settings > Translate messages.
*If you use my code, it will be in form eg.: nav.home, nav.contact, ...*


*I personally find it a better way to have separate menus for each language - easier for clients and same for me as sometimes I have different menu structure for every language.*

**Comment by LukeTowers** [comment]
Duplicate of #213, https://github.com/rainlab/pages-plugin/issues/240, https://github.com/rainlab/pages-plugin/issues/222, and https://github.com/rainlab/pages-plugin/issues/190. Discussion continues in https://github.com/rainlab/pages-plugin/issues/190
