### ISSUE TITLE
Cannot translate inside a partial loaded by an Ajax request

### ISSUE THREAD

**Issue by Fl0Cri** [rainlab/translate-plugin#247]
# Summary
When a partial is rendered from an Ajax call, the lang strings are not loaded. This is a different behaviour that when the partial is rendered from a page load.

I tested it on October build 412 with translate plugin 1.2.10

# Steps to reproduce
Create a page containing this:
```HTML
<!-- AJAX enabled form -->
<form data-request="onTest" data-request-update="testpartial: '#myDiv'">
    <!-- Action button -->
    <button type="submit">Calculate</button>
</form>

<!-- Result container -->
<div id="myDiv">{% partial 'testpartial' %}</div>
```

And an empty onTest handler:
```PHP
function onTest()
{

}
```

Create a partial containing the following code and add a lang string for `translate.test` that translates to `Translated!`:
```
Content to translate is {{ 'translate.test' | _ }}
```

# Expected behavior
When the page loads, the partial should contains `Content to translate is Translated!`

After clicking the Calculate button, the partial sould contains `Content to translate is Translated!`

# Actual behaviour
When the page loads, the partial contains `Content to translate is Translated!`

After clicking the Calculate button, the partial contains `Content to translate is translate.test`

# Workaround
Actually this happens because the lang strings are loaded at this point: https://github.com/rainlab/translate-plugin/blob/master/classes/EventRegistry.php#L175 by this listener https://github.com/rainlab/translate-plugin/blob/master/Plugin.php#L55.

I suppose that the `cms.page.beforeRenderPage` event is (obviously) triggered by a page render, but not by an ajax request.

So what I did as a workaround is to manually set the message context from my Ajax handler:
```PHP
use RainLab\Translate\Classes\Translator;
use RainLab\Translate\Models\Message;

function onTest()
{
    $translator = Translator::instance();
    Message::setContext($translator->getLocale(), $this->page->url);
}
```

I am not sure if it is the intended way to achieve this behaviour. Imo it would be easier to have the lang strings loaded on Ajax requests like it's done for page render, but I can understand that it may be as it is because translator is probably not necessary for most Ajax requests.

**Comment by Eoler** [comment]
I've just encountered this, let me test your workaround this weekend...

**Comment by LukeTowers** [comment]
This should have been fixed in https://github.com/rainlab/translate-plugin/pull/225, however I don't think that fix has been deployed in a new version yet, just here on the repository. I'll ping @daftspunk to bump the version to include the fix.

**Comment by LukeTowers** [comment]
Alright, I bumped the version. The fix should be available on the marketplace shortly.
