### ISSUE TITLE
how to query only a translated content

### ISSUE THREAD

**Issue by aurukas** [rainlab/translate-plugin#250]
Is there a way to fire an Eloquent query, which would return results only if they are present in a given language? # #

**Comment by jan-vince** [comment]
Have you tried [transWhere](https://github.com/rainlab/translate-plugin#indexed-attributes)?

**Comment by aurukas** [comment]
it querries only by index (slug - table: rainlab_translate_indexes) and you have to supply the value.

**Comment by adsa95** [comment]
I would also be interested if there is a nice solution to this. 

I'm thinking of a workaround where I'll use a separate field with a language code to be able to do these searches, and pair it with the proposed solution in #276 in a default scope when in frontend to only get content in that specific language. This means that I won't use the TranslateableModel but instead have multiple content items, and every item is in just one language. This would probably make it harder to get and overview in the backend with multiple items that is the same but in different languages however.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
