### ISSUE TITLE
Translation fields bug

### ISSUE THREAD

**Issue by dunets** [rainlab/translate-plugin#251]
Hard to explain....

[https://www.youtube.com/watch?v=m1oMHuRFA8c](https://www.youtube.com/watch?v=m1oMHuRFA8c)

Now imagine that I will have 20 languages on a website...

**Comment by jan-vince** [comment]
I have never noticed this, but I can confirm, that when you change layout before first save, it will empty other languages URLs, so it is impossible to create a new page (unless you fill all URLs).

But it never happen when you first save (create) and THEN you change layout.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
