### ISSUE TITLE
Non-grouping multilanguage repeater errors on language switch

### ISSUE THREAD

**Issue by Eoler** [rainlab/translate-plugin#252]
Versions: Translate 1.2.12 with October 415 with edgeUpdates turned on.

This is just FYI for people installing newest Translate on fully updated October core: multilingual repeaters display AJAX error when language is switched. 
`exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Undefined class constant 'GROUP_PREFIX'' in /{site_path}/plugins/rainlab/translate/formwidgets/MLRepeater.php:165`

Probably related to: https://github.com/octobercms/october/issues/2772

**Comment by daftspunk** [comment]
Fixed in Build 416+

**Comment by Eoler** [comment]
Error's gone after upgrading core to 416, but now existing MLrepeater data in static pages (checked content/static-pages/*.htm and its still there and showing in frontend) isn't available for editing, even on first static page editor load.

**Comment by daftspunk** [comment]
Can you share the static page layout code?

**Comment by Eoler** [comment]
Yes, here are relevant field definitions from a home layout with [staticPage] component on it:
```
{repeater tab="Highlights" name="highlights" prompt="Add Highlight"}
    {variable type="text" name="title" label="Title" span="left"}{/variable}
    {variable type="text" name="pretitle" label="Pretitle" span="right"}{/variable}
    {variable type="text" name="subtitle" label="Subtitle" span="left"}{/variable}
    {variable type="text" name="link" label="Link" span="right"}{/variable}
    {variable type="mediafinder" name="image" label="Image" span="right" mode="image"}{/variable}
    {variable type="richeditor" name="descr" label="Description" span="left" size="large"}{/variable}
{/repeater}
```

There are two langauges defined, **en** is default.

Static page data:
```
[viewBag]
title = "Home"
url = "/"
layout = "home"
is_hidden = 0
navigation_hidden = 0
meta_description = "About us"
highlights[1][title] = "Novine"
highlights[1][pretitle] = "Filmed Here"
highlights[1][subtitle] = "TV Series, Dalibor Matanić, 2016."
highlights[1][link] = "https://..."
highlights[1][image] = "/artworks/novine-cover.jpg"
highlights[1][descr] = "<p>...</p>"
highlights[2][title] = "Moj Kastav"
highlights[2][pretitle] = "Location"
highlights[2][subtitle] = "Architecture"
highlights[2][link] = "https://..."
highlights[2][image] = "/locations/5878/5878b8fbb1854555135692.jpg"
highlights[2][descr] = "<p><em>...</em></p>"
(...)

**Comment by daftspunk** [comment]
Ah, got it! This will be fixed by https://github.com/octobercms/october/commit/cb56c61e36d3c13505a7be21ebaf5fe8a0370195 in Build 417+ when it lands. Thanks!

**Comment by daftspunk** [comment]
Note for future research, this regression was necessary to prevent templates from looking like this:

```
[viewBag]
title = "Home"
url = "/"
layout = "home"
is_hidden = 0
navigation_hidden = 0
meta_description = "About us"
highlights[0][title] = "Novine"
highlights[0][pretitle] = "Filmed Here"
highlights[0][subtitle] = "TV Series, Dalibor Matanić, 2016."
highlights[0][link] = "https://..."
highlights[0][image] = "/artworks/novine-cover.jpg"
highlights[0][descr] = "<p>...</p>"
highlights[0][_index] = "1"
highlights[1][title] = "Moj Kastav"
highlights[1][pretitle] = "Location"
highlights[1][subtitle] = "Architecture"
highlights[1][link] = "https://..."
highlights[1][image] = "/locations/5878/5878b8fbb1854555135692.jpg"
highlights[1][descr] = "<p><em>...</em></p>"
highlights[1][_index] = "2"
```

**Comment by Eoler** [comment]
Don't sweat it, some of us love to live on the bleeding edge - it makes mondays interesting.
Will test it with new build when available...
