### ISSUE TITLE
Translate "Purge all messages first" not works

### ISSUE THREAD

**Issue by dunets** [rainlab/translate-plugin#253]
Hey ... I lost some time to understand why my messages stop appearing on the list ...
So I discovered that "Purge all messages" not works ... And after any use of that button I need to clear the cache ...

There is a message

>  If checked this will delete all messages before performing the scan.

But... It's not only to refresh the messages?

See here: [https://youtu.be/Y_P4OFtBWj8](https://youtu.be/Y_P4OFtBWj8)

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
