### ISSUE TITLE
Translate extend to model. Relation model popup not working

### ISSUE THREAD

**Issue by adovbos** [rainlab/translate-plugin#254]
When save popup form, data from another language goes to default language. And not creating field in rainlab_translate_attributes table. Debugging showed that 
`   
 /**
     * Returns an array of translated values for this field
     * @return array
     */
    public function getSaveValue($value)
    {
        dump('save', $value);
        return $this->getLocaleSaveValue($value);
    }
`  
in MLText.php not fired.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
