### ISSUE TITLE
Message::makeMessageCode() collisions

### ISSUE THREAD

**Issue by matteotrubini** [rainlab/translate-plugin#256]
In italian (and maybe in other languages) we use the same phrase construction to make a question, simply adding a "?" at the end.

**Reproduce steps:**
{{ ''Beer"|_ }}
{{ ''Beer?"|_ }}

**Expected behavior:**
Beer
Beer?

**Actual behavior:**
Beer
Beer

I just tried to switch the return value to sha1($messageId) and it seems to be a good replacement that assure 1:1 string matching without any other change. This would prevent "collision" also in case of >250 char texts.

If this change is acceptable I think that should be easy ensure BC simply updating "code" column during migration.

**Comment by daftspunk** [comment]
Use codes instead
```
{{ ''beer"|_ }}
{{ ''beer_alt"|_ }}
```

**Comment by matteotrubini** [comment]
I got it, even if it could be a "problem" developing themes where we need to place keys instead of main languages' texts, which allows you to have themes more readable, like if you use something like gettext().
It could be an easier approach instead of use multiple content files. If you change a text in theme you MUST update according the translations, leaving blank the column of the source language.

Can hashes and "readable" codes coexist?
