### ISSUE TITLE
Change language problem Blog.RainLab post

### ISSUE THREAD

**Issue by RempadDesign** [rainlab/translate-plugin#259]
Hi,

I have a problem regarding the URL to a post page built with Blog Plugin. For the default language (Romanian) the link apear and works great: http://www.rempaddesign.com/clients/cnpcd/noutati

In the post detailed page http://www.rempaddesign.com/clients/cnpcd/ro/noutati/noutate/o-alta-noutate the language is not changed at all...

If I switch languages, the content is translated but the URL (of the post) is messed up and incomplete. I mention that I didn't translated the SLUG because is no need for that. You can change the languages from the bottom of the page - footer section.

If I change the default language to be English, the URL works but the title translation is inversed...
It's kind of confusing and have no ideea how to solve this :(

Best regards, Andrew.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
