### ISSUE TITLE
This plugin could be the next big thing of OctoberCMS!!

### ISSUE THREAD

**Issue by BMCouto** [rainlab/translate-plugin#26]
I'm having some troubles configuring october cms backend in order to be used by my client who doesn't understand a line of code, and while I'm translating my site's content, I had what *might* be a great idea:

- What if we could define translations by groups / pages? The plugin would have to identify which page that content belongs to, and then the client could just access translations to change it's content...

I'm having some troubles finding a way to give client the ability to change the content of a page without messing around with html and css, putting in risk the page interface, something like drupal where content is updated via input forms.
Maybe translation could accomplish this and be much more than a translations plugin, am I thinking correctly?

**Comment by aidanayala** [comment]
Anything on this? Sounds great to me personally.

**Comment by daftspunk** [comment]
Sounds like a reasonable feature. It needs discovery and someone to implement it. Tagged as a conceptual feature request for later review.
