### ISSUE TITLE
default language change in frontend - don`t work

### ISSUE THREAD

**Issue by Minius-dev** [rainlab/translate-plugin#260]
Hi,

Here is the error!  The situations:
1) install translations plugins;
2) say you have more than one language in website (in frontend);
3) firstly, say that your default language is EN. We fill in all information, static pages, plugins informations etc.. 
Another language is LT. We fill in all information to;
4) than, after some time (for example after 6 month) need to switch default lang from En to Lt (yes, this is done through backend settings of translations plugins);
5) go to frontend and pick up new default lang Lt;
6) And after that, some of the information (which translated throw translation plugin: static pages, translated attributes, etc..) became only in english, although it should be only in lithuanian. It happens in frontend & backend ().

This is very bad cases, if you need to switch language standard language after a while.
Need some updates for translation plugin on how to read translated attributes/strings from table `rainlab_translate_attributes`

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
