### ISSUE TITLE
Include a file with language prefix

### ISSUE THREAD

**Issue by filipblaauw** [rainlab/translate-plugin#261]
I have a php file I include in my template. Is there a way to include these files based on the current language?

So if language is set to French (fr) then load `fr-file.php` and `en-file.php` if language is English (en)?

```
function onStart() {
  include('includes/[lang]-file.php');
}
```
The reason is that I have a bunch of php and javascript inside this inluded file, and I haven't figured out how to translate these. So it might be easier to hard code the strings in separate files with prefixes.

**Comment by filipblaauw** [comment]
Figured it out. Posting sample here for reference:

```
$this['activeLocale'] = Lang::getLocale();
include('includes/'.$this['activeLocale'].'-file.php');
```

**Comment by LukeTowers** [comment]
Why aren't you using the built-in translation functionality within October?

**Comment by filipblaauw** [comment]
@LukeTowers 
Haven't figured out how to translate strings that are inside i.e a javascript. So for now, I'm just unsing the logic mentioned above to load the file with the language prefix.

Is there a way to translate the word `Latest` here?
```
title: {
  text: 'Latest:<b> <?php echo $siste; ?> </b>'
}
```

**Comment by LukeTowers** [comment]
The System module includes client JS translations that get compiled into JS files with the translations, but I'm not sure how it works exactly. I would suggest looking into that and see what you can find.
