### ISSUE TITLE
multilanguage control not showing up on pivot data

### ISSUE THREAD

**Issue by bombozama** [rainlab/translate-plugin#270]
My set up is as follows:
```php
<?php namespace Acme\Plugin\Models;

use October\Rain\Database\Pivot;
 
class PersonOrganizationPivot extends Pivot
{
    public $table = 'acme_plugin_organization_person';

    public $implement = ['RainLab.Translate.Behaviors.TranslatableModel'];

    public $translatable = ['details'];

    public $belongsTo = [
        'person' => ['Acme\Plugin\Models\Person'],
        'organization' => ['Acme\Plugin\Models\Organization'],
    ];
}
```
The relations are properly set up. I can go ahead and save/update/remove relation data, and mlcontrols show up in fields in the main `Person` model. It's just that the language selector on the field of the pivot relation doesn't show up. 

What am I doing wrong?

**Comment by LukeTowers** [comment]
I could be wrong, but I'm not sure that Pivot models support being translated.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
