### ISSUE TITLE
Using Translations and Cache Not Working

### ISSUE THREAD

**Issue by AugmentBLU** [rainlab/translate-plugin#271]
Hello,

I'm using the Translate plugin for one of my own plugins, I also have another plugin based on the Blog plugin and neither seem to work with Cache on translated pages.

I'm trying to reduce the 130+ queries that are appearing when using translated indexes on a page where on 30 blog posts are displayed. I can see a tonne of duplicated queries, I think it's related to the translation indexes changing the query after the initial get query (might be wrong here).

Anyway, I've tried to cache this, I realise the first page load with no cache will have the high level queries then I was hoping to store the results in Redis to reduce the DB queries. 

I'll use the Blog plugin example to illustrate my issue.

After the listPosts function I tried

```
Cache::remember('translation.'.$this->activeLocale.'/blog/'.$this->property('pageNumber'), 60, function() use($posts){
       return $posts->toJson();
});
```

This works fine on the default locale, I see the results in Redis and I can use that data fine using

```
json_decode(Cache::get('translation.'.$this->activeLocale.'/blog/'.$this->property('pageNumber'), true)
```

But when on a different locale I hit errors

> json_decode() expects parameter 1 to be string, array given

I also have this error - trying a different approach

> Serialization of 'Closure' is not allowed

2 things to ask, 

1. with the high level of queries - is this a massive issue on performance? I did read somewhere that in Laravel, query count is not necessarily something to worry about due to indexing. I am still learning Laravel so I'm not sure that this is something to believe - I mean 130 queries is a lot.

2. Is it even possible to cache translated pages, whether it's paginated results with translations or the details page of a single record?

Any help would be great.

**Comment by LukeTowers** [comment]
@AugmentBLU Did you ever fix the issue with the Translateable model not utilizing the deduplication functionality of the October DB engine?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
