### ISSUE TITLE
Override formController::update_onSave has a bug 

### ISSUE THREAD

**Issue by tim0991** [rainlab/translate-plugin#273]
When i override update_onSave, translate data has not been saved, and  i found `TranslatableModel::$translatableAttributes` is an empty array

This is the update method in Backend Controller of plugin
```php
 public function update_onSave($recordId = null, $context = null)
 {
        $input = post('Menu');
        $model = $this->formFindModelObject($recordId);

        $model = $model->update($input);
        Flash::success(Lang::get('backend::lang.form.update_success', ['name' => 'Menu'])); 
        
        if ($redirect = $this->makeRedirect('update', $model)) {
            return $redirect;
        }
 }
```

**Comment by LukeTowers** [comment]
As per [the contribution guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#reporting-a-bug-with-octobercms), please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

We'd need to see your model class that you are using at a bare minimum including any other code you have that would be affecting this process.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
