### ISSUE TITLE
Dropdown and data-request="onSwitchLocale" not working - common issue

### ISSUE THREAD

**Issue by omarkarray** [rainlab/translate-plugin#274]
I had this issue, 
After including [localePicker] in the layout and in the page itself i call this code in the homepage 
```
<p>
    Switch language to:
    <a href="#" data-request="onSwitchLocale" data-request-data="locale: 'en'">English</a>,
    <a href="#" data-request="onSwitchLocale" data-request-data="locale: 'ar'">Arabic</a>
</p>
```
But  the dropdown and the links are not working 
Can anyone help on that issue, i think it is a common issue

**Comment by jan-vince** [comment]
Hard to help with such little data.

I have tried your code in my page and it works.

So there is probably some problem in your code I guess.

Layout I use:

````html
[localePicker]
forceUrl = 1
==
<html>
	<head>
		{% styles %}
	</head>
<body>

    {% component 'localePicker' %}

	{% page %}

	{% scripts %}

</body>

</html>
````

Page I use:

````html
title = "Homepage"
url = "/"
layout = "default"
is_hidden = 0

[viewBag]
localeUrl[en] = "/"
localeUrl[de] = "/"
==
<p>
    Switch language to:
    <a href="#" data-request="onSwitchLocale" data-request-data="locale: 'en'">English</a>,
    <a href="#" data-request="onSwitchLocale" data-request-data="locale: 'de'">Deutsch</a>
</p>
````

It is important to set all laguages in administration in ````Settings > Manage languages````!

**Comment by LukeTowers** [comment]
Have you included framework.js in the frontend of your theme?

As per [the contribution guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#reporting-a-bug-with-octobercms), please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by omarkarray** [comment]
@LukeTowers What was missing is framework.js / thanks for your help

**Comment by LukeTowers** [comment]
No problem

**Comment by Antar74** [comment]
Hello I'm having a similar problem. I surely missed the "framework.js" mention in the translate plugin docs back on october plugins page. If this is the solution to the problem of the locale picker not working, where do I obtain the "framework.js" file and how do I include it?

Thanx!
