### ISSUE TITLE
Language match based on domain

### ISSUE THREAD

**Issue by alexraileanu** [rainlab/translate-plugin#275]
Hi, I have a bit of an issue.

I have the following situation: an app that runs on domain.com and it has 3 languages that can be accessed via domain.com/en, domain.com/de, domain.com/nl.

What I want to achieve is that when I land on domain.com/de I am redirected to domain.de and I keep the german language. 

The redirect bit I manage to do but it does not retain the language. 

I have this in my .htaccess file:

```
RewriteCond %{HTTP_HOST} ^domain\.com$
RewriteRule ^de$ http://domain.de [L,R=301]
```

Any help will be greatly appreciated

Kind regards,
Alex

**Comment by LukeTowers** [comment]
You'd have to set it up so that the frontend locale gets set based on the domain name the site is being accessed under. I'm not overly familiar with that process myself, but I'm sure there's online resources for how to do that.
