### ISSUE TITLE
get current or active language in component

### ISSUE THREAD

**Issue by yeomann** [rainlab/translate-plugin#276]
Hi i was able to find a way to get current local in partial, but failed to find any way to determine active local in one of my component. Is there any function which returns active language like {{activeLocale}} in components? Thank you for the attention. 

## Update:
Although for a fast work around, i solved using this way `Session::get('rainlab.translate.locale')`

**Comment by canthis** [comment]
@yeomann Take a look how it's done in [LocalePicker Component](https://github.com/rainlab/translate-plugin/blob/master/components/LocalePicker.php#L64)

So You can go something like:
```
use RainLab\Translate\Classes\Translator;

$translator = Translator::instance();
$activeLocale = $translator->getLocale();
```

**Comment by adsa95** [comment]
I think it would be great to have a facade with this and maybe a few other convenience features.

**Comment by LukeTowers** [comment]
@adsa95 there is:
```php
\RainLab\Translate\Classes\Translator::instance()->getLocale();
```
😄

**Comment by yeomann** [comment]
Hi thanks for providing facade, how about  you add in the documentation 😄 Although at the time of asking that question, i solved that situation in 2 different ways, one with session and one with digging in your LocalePicker Component. My approach for one of partial was this

```
==
use RainLab\Translate\Classes\Translator;
protected $translator;

function onStart()
{
	$this->translator = Translator::instance();
	$this['SelectedLanguage'] = $this->activeLocale = $this->translator->getLocale();
}
==
{% set CurrentLanguage = SelectedLanguage %}

```

**Comment by daftspunk** [comment]
Best approach is probably:

```
App::getLocale()
```

> how about you add in the documentation 

If you need help creating a Pull Request, there is [documentation for that](https://yangsu.github.io/pull-request-tutorial/).

**Comment by yeomann** [comment]
@daftspunk thank you for mentioning the Best approach. I will give a try.
and i know about Pull request so i will do that as well perhaps.
