### ISSUE TITLE
MLRepeater not compatible with new (grouped) repeater

### ISSUE THREAD

**Issue by jrnski** [rainlab/translate-plugin#278]
Seems that translate plugin ist not compatible with grouped repeater. When using translate plugin the format in which the data is stored differs vom current repeater method... no groups, just indizes..

With plugin:
{"3":{"text":"foo","name":"bar","position":"1"}}

Without plugin:
[{"text":"foo","name":"bar","position":"1","_group":"quotationgreen"}]

**Comment by jrnski** [comment]
Any updates on this?

**Comment by LukeTowers** [comment]
The support demand for October is increasing, while the available time the founders have to give remains the same. These issues will be handled in time, however there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

**Comment by LukeTowers** [comment]
Closing in favour of #290
