### ISSUE TITLE
Default language not working

### ISSUE THREAD

**Issue by gregoryloichot** [rainlab/translate-plugin#280]
Hello, 
I found you plugin very useful, but in fact, it does not work as expected.

I set up 2 languages: EN and FR (as main language). I create 2 home pages: home.htm and home.en.html

If I go to /: home.en.htm is displayed.
If I go to /fr: home.en.htm is displayed.
If I go to /en: home.en.htm is displayed.

If I delete home.en.htm and I go to /: home.htm is displayed.
If I delete home.en.htm and I go to /fr: home.htm is displayed.
If I delete home.en.htm and I go to /en: home.htm is displayed.

What's wrong ? I also try to delete all caches, set up FR as main language, but it is still not working.
Any idea (October 419) ?

**Comment by jan-vince** [comment]
Have you tried [Bonjour theme](https://octobercms.com/theme/rainlab-bonjour)? It can help to understand how this works.

**Comment by gregoryloichot** [comment]
Yes I did. In fact, the prefix ".en" works only on Contents and not on Pages (CMS pages).

**Comment by jan-vince** [comment]
I am asking just because of this - as far as I know only content files can be translated with language suffix.

Bonjour theme uses different approach with Static Pages plugin.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
