### ISSUE TITLE
Translate proxy fields

### ISSUE THREAD

**Issue by elboman** [rainlab/translate-plugin#281]
Hi,

I was wondering if there is any way to make a proxy field translatable, and in case how.

I have extended the Post model from the blog plugin with a `hasOne` relationship.

I'm extending the controller in order for the field to appear:
```php
PostController::extendFormFields(function($form, $model, $context){
    if(!$model instanceof PostModel || $form->isNested)
        return;

    $form->addSecondaryTabFields([
        'custom_post[featured_text]' => [
            'label' => 'Featured Text',
            'type' => 'text',
            'tab' => 'Additional Info'
        ]
    ]);
});
```

I'd like for the `custom_post[featured_text]` to be translatable. Any suggestion?

**Comment by elboman** [comment]
I would be happy to try and tackle this with a bit of help understanding where to start.

After some digging I think there should be a couple of things to change in order for this to work:
1. Render the ML version of the formwidget when the proxy field is translatable
2. Save/load the translated value

For the first point, I think the problem is here (`EventRegistry`):
```php
if (!empty($widget->config->fields)) {
    $widget->fields = $this->processFormMLFields($widget->fields, $model);
}

if (!empty($widget->config->tabs['fields'])) {
    $widget->tabs['fields'] = $this->processFormMLFields($widget->tabs['fields'], $model);
}

if (!empty($widget->config->secondaryTabs['fields'])) {
    $widget->secondaryTabs['fields'] = $this->processFormMLFields($widget->secondaryTabs['fields'], $model);
}
```

The config from the widget only includes fields statically declared in the config file and not the ones added dynamically when extending the model. If I add the field manually in the `fields.yaml` of the plugin the ML version of the widget renders properly.

For the second point I'm not sure where to begin, I think the `syncTranslatableAttributes` method should handle this.

I still wonder what the correct syntax would be in the end. I definitely think the translatable should be defined in the original model class and the controller shouldn't care about it. But when using the proxy syntax the attribute name is not the real field name (as it includes the model name). It should be stripped from the model name and handled as a normal field.

If you care to guide me a bit I'd happily start working on it and open a PR once I have something to work on that makes sense.

**Comment by LukeTowers** [comment]
I don't work enough with this plugin to be able to guide you, but perhaps @daftspunk can offer some advice

**Comment by kikobalco** [comment]
Any news in this topic? I'm trying to solve similiar issue these days. I'm adding extra fields to StaticPages plugin by extending it and need to make it translatable...

**Comment by elboman** [comment]
Unfortunately no news. Still waiting for some help to get started as I don't know the codebase well enough.

I went ahead and modified the plugin (even if not recommended) adding my fields and making them translatable instead of extending it.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.

**Comment by elboman** [comment]
@LukeTowers yeah, it's unfortunate. I was hoping for @daftspunk to give us some help to start working on it but I understand the quantity of support request is overwhelming.

I'd be happy to start working on it once/if the issue gets re-opened 👍

**Comment by LukeTowers** [comment]
@elboman if you want to work on this, go ahead! I only close issues as abandoned to motivate action on them :) Otherwise they would just languish on the queue and never get looked at. Let me know if you make a fix and then we can get it merged in via a pull request.

**Comment by iboved** [comment]
Any news in this topic? How to translate proxy fields?
I have proxy field in fields.yaml like this:
```
    profile[title]:
        label: Title
        type: text
```

**Comment by LukeTowers** [comment]
@elboman are you still interested in coming up with a solution?

**Comment by elboman** [comment]
Sure, would love to, but I don't know the code enough to start by my self, would still need any help from @daftspunk where to look at, at least.

If anyone wants to help, we can pair up and try and figure out together.
Let me know!
