### ISSUE TITLE
[L5.5.] Locale picker component does not change language

### ISSUE THREAD

**Issue by mplodowski** [rainlab/translate-plugin#282]
##### Expected behavior
When I change language with `localePicker` component it should change language to my selection.

##### Actual behavior
Language is not changed and it is always set to English (default). The ajax request has no errors and it redirects back successfully.

##### Reproduce steps
Add `localePicker` to layout file. Change language using the component dropdown.

##### October build
Build 419 with Laravel 5.5

**Comment by LukeTowers** [comment]
Did you include the `@framework` JS file?

**Comment by hocopor** [comment]
Same problem.
If you navigate manually to /en/, `Session::all()` returns only one array "rainlab".

Build 420 with Laravel 5.5

**Comment by mplodowski** [comment]
Yeah I included `@framework` JS file.

Problem here is that `activeLocale` is not persisted through session. If you go manually in browser to `/de`, than language is changed to German. Now if you go to home page without language code in url than locale is set to default `en` again.

**Comment by hocopor** [comment]
You can pick checkbox in the `activeLocale` settings.

![image](https://user-images.githubusercontent.com/8468291/28838308-aaf683b4-76f8-11e7-89b7-f1a47e9ac0e7.png)

This will solve the problem with the change of locale, but not with `Sesson`.

**Comment by hocopor** [comment]
So... 

I changed `RainLab/Translate/routes.php`

From: 

    ```
/*
     * Register routes
     */
    Route::group(['prefix' => $locale], function() {
        Route::any('{slug}', 'Cms\Classes\CmsController@run')->where('slug', '(.*)?');
    });

    Route::any($locale, 'Cms\Classes\CmsController@run');

    /*
     * Ensure Url::action() retains the localized URL
     * by re-registering the route after the CMS.
     */
    Event::listen('cms.route', function() use ($locale) {
        Route::group(['prefix' => $locale], function() {
            Route::any('{slug}', 'Cms\Classes\CmsController@run')->where('slug', '(.*)?');
        });
    });
```

To:

```
/*
     * Register routes
     */
    Route::group(['prefix' => $locale, 'middleware' => 'web'], function() {
        Route::any('{slug}', 'Cms\Classes\CmsController@run')->where('slug', '(.*)?');
    });

    Route::any($locale, 'Cms\Classes\CmsController@run');

    /*
     * Ensure Url::action() retains the localized URL
     * by re-registering the route after the CMS.
     */
    Event::listen('cms.route', function() use ($locale) {
        Route::group(['prefix' => $locale, 'middleware' => 'web'], function() {
            Route::any('{slug}', 'Cms\Classes\CmsController@run')->where('slug', '(.*)?');
        });
    });
```

And `Session` works fine.

**Comment by LukeTowers** [comment]
@hocopor Ah yes, Laravel changed how session middleware works, it's no longer loaded on every request. I had to make a similar change on one of my plugins as well. Thanks for spotting that!

**Comment by mplodowski** [comment]
Adding `web` middleware does not solve the problem here, because those routes only works with `prefix` set to `locale`, so only when `forceUrl` in component settings is enabled.

**Comment by LukeTowers** [comment]
@mplodowski could you test the solution in #283 and let me know if that resolves the issue for you?
