### ISSUE TITLE
Twig translation in Email Template

### ISSUE THREAD

**Issue by pvullioud** [rainlab/translate-plugin#285]
Any idea why twig translation is not working in email template. Other Twig function are working fine.
What could be the best way to fix it ?

`<h3>{{ 'FORMATION_CREATED'|_ }}</h3>`

**Comment by pvullioud** [comment]
Translation is not working in email because `self::$locale` is not declared

https://github.com/rainlab/translate-plugin/blob/e7ce25baf1006443d6309a13037d0a3edb79e912/models/Message.php#L100

**Comment by pvullioud** [comment]
I'm sending email notification with a cron/CLI. To solve translation issue in mail, I manually set the Locale of the Translator. It work fine now.

```
public function process()
    {
        $translator = Translator::instance();
        $translator->setLocale('fr');

        Mail::send('inetis.association::mail.user_notification', [], function ($message) {
            $message->to('xx@xxxxx.ch');
            $message->subject('user_notification_subject');
        });
}
```

**Comment by LukeTowers** [comment]
Is this on Build 420?

**Comment by pvullioud** [comment]
Yes, It's on Build 420. I'll test on 419 also and try to initialise `self::$locale`

**Comment by pvullioud** [comment]
It's work fine on frontend. For Cron and command line  `self::$locale` should be set by manually
like 

```php
use RainLab\Translate\Models\Message;
[...]
Message::$locale = 'fr';
Mail::send( [...]
```
and it's work fine now 👍

**Comment by LukeTowers** [comment]
So is there a bug or isn't there?

**Comment by pvullioud** [comment]
No bug here 😃 
Just something hard to find and not documented.
Could be great to add a `setLocale `method into the `RainLab\Translate\Models\Message` class with a description.

**Comment by hocopor** [comment]
@pvullioud as I see you can use it with static method `RainLab\Translate\Models\Message::forLocale('en');`

**Comment by pvullioud** [comment]
@hocopor Thanks

**Comment by wellyfrs** [comment]
How to list e-mail template messages to be translated into the backend? The search does not seem to scan e-mail templates. Do I need to add manually? How?

**Comment by LukeTowers** [comment]
Try sending an email with each template to force October to render them @wellyfrs

**Comment by wellyfrs** [comment]
With https://github.com/octobercms/october/pull/3152 and https://github.com/rainlab/translate-plugin/pull/304 and using the tip of @hocopor, I did it. Thanks!

**Comment by munxar** [comment]
I have the problem that regarding of what and where (Frontend, Task, Console) I set the locale with
Message::setContext(...)
The email template is always rendered in the default locale ('en'). I have setup *en* and *de* locale.
example for a test page:
```php
use RainLab\Translate\Models\Message;

function onStart() {
    Message::setContext('de', 'mail');
    Mail::send('backend::mail.invite', [], function($message) {
        $message->to('test@dev.com', 'Mr. Debug');
    });
}
```
Any ideas?

**Comment by munxar** [comment]
I have the problem that regarding of what and where (Frontend, Task, Console) I set the locale with
Message::setContext(...)
The email template is always rendered in the default locale ('en'). I have setup *en* and *de* locale.
example for a test page:
```php
use RainLab\Translate\Models\Message;

function onStart() {
    Message::setContext('de', 'mail');
    Mail::send('backend::mail.invite', [], function($message) {
        $message->to('test@dev.com', 'Mr. Debug');
    });
}
```
Any ideas?

**Comment by mjauvin** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Comment by Eoler** [comment]
So, where would one need to put locale changing call from https://github.com/rainlab/translate-plugin/issues/285#issuecomment-375560715 when using mail queues asynchronously?
