### ISSUE TITLE
Route breaks Sessions (and auth accordingly)

### ISSUE THREAD

**Issue by rounce** [rainlab/translate-plugin#288]
The issue occurred with the last update of october cms.

steps to reproduce
1. install translate and user plugins
2. auth
3. go to any /en location (/en/demo/plugins for example). Then
routes.php of translate call to "Route::any($locale, 'Cms\Classes\CmsController@run');"
and Session becomes empty (more precisely contains only one record)

This can be seen by add line public function onRun() {dd(Session::all());}
to /plugins/october/demo/components/Todo.php:
then on /en/demo/plugins:
array:1 [▼
  "rainlab" => array:1 [▶]
]

**Comment by hocopor** [comment]
@rounce Yep. Try #282 and #283

**Comment by rounce** [comment]
Your #284 fixes the issue. Thanks.

**Comment by daftspunk** [comment]
Please test 76b798e89d345957802888142a190e5643a5eafe to see if it fixes the issue.

If not create a brand new issue that references this one.
