### ISSUE TITLE
Updating Slug of translated menu item of static page not escalating to partial holding menu

### ISSUE THREAD

**Issue by vannut** [rainlab/translate-plugin#292]
I have several static menu's, each serving a specific locale and each holding several static pages. 
All these static pages have a translation via this Plugin. 

When updating the slug of one of the static pages, the corresponding url in the navigation item is _not_ updating and showing the former url/slug. The strange thing is the fact when updating the Title, this is propagating like normal, and will show the new title. 

Running a `php artisan cache:clear` or `php artisan view:clear` doesn't do the trick :(

**To make it even more awkward: after a while (10-15minutes) the changes to the url seem to propagate by them selves?** Is there somehow / somewhere somekind of cache present?? 
Shouldn't there be some kind of trigger to update this cache?

This is the code-stack i'm using to format and display the menu:

```twig
{# component loading #}
[staticMenu hoofdmenu_de]
code = "hoofdmenu_de"
====

{# Loading the items by pulling in the component suffixed with the locale #}
{% partial
    'hoofd-menu'
    items=attribute(_context, ('hoofdmenu_'~locale) ).menuItems
    class=''
%}
======
{# the partial itself #}
<ul class="{{ class }}">
    {% for item in items %}
        <li
            class="{{ item.isActive or item.isChildActive ? 'active' : '' }}
            {{ item.viewBag.cssClass }}"
        >
            <a href="{{ item.url }}"  class="mb1">
            
                {{ item.title }}
                {# ('menu_' ~ item.title )|_  #}
                {% if item.items %}<i class="material-icons v-btm">keyboard_arrow_down</i>{% endif %}
            </a>

            {% if item.items %}
                {% partial 'hoofd-menu' items=item.items class='sub-menu' %}
            {% endif %}
        </li>
    {% endfor %}
</ul>
```

**Comment by LukeTowers** [comment]
CMS objects have a separate cache time, check your https://github.com/octobercms/october/blob/master/config/cms.php#L152

**Comment by vannut** [comment]
So, somehow after updating the slugs the renew-event of the cache is not triggered...
Where does the cached-version live? Is there a way to manually trigger a cache renewal?

**Comment by LukeTowers** [comment]
@vannut there was some issues with the caches for the StaticPages plugin that have been solved recently, try updating and then let me know if this issue is still present.

**Comment by mjauvin** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
