### ISSUE TITLE
MLRepeater not working with richeditor

### ISSUE THREAD

**Issue by munxar** [rainlab/translate-plugin#294]
**Expected behavior**

A richeditor inside a MLRepeater should be translatable

**Actual behavior**

Only the default language is saved. Switching languages looses changes of richeditor.

**Reproduce steps**

- Make a translatable model with an attribute (e.g. content) that is translated and jsonable.
- Make a form and add a repeater for content.
- Place a richeditor inside of the repeater.
- Add text for different languages and switch between them

**October build**
419 
Rainlab.Translate 1.2.11

Note: replacing richeditor with text and everything works just fine.

**Comment by canthis** [comment]
This one was already fixed by https://github.com/octobercms/october/commit/edcd899a794caa78e2489a18987d59fd7acf83f2 and available on build 420+

**Comment by munxar** [comment]
my bad, close this.
