### ISSUE TITLE
Backward compatibility

### ISSUE THREAD

**Issue by tim0991** [rainlab/translate-plugin#295]
In my case, laravel/framework still 5.1
when i update package by `composer update rainlab/translate-plugin`  i get a error about web middleware
could you tag your commit on git follow your version.yaml 
so i can specify a tag in composer.json

**Comment by daftspunk** [comment]
You may now use branch `build419` for this.

**Comment by brunocascio** [comment]
Hi @daftspunk!

Since October installs the latest plugin versions, could you tell me how to install specific branch versions?

Thanks!

**Comment by LukeTowers** [comment]
@brunocascio why don't you just update October?

**Comment by brunocascio** [comment]
Thanks @LukeTowers! 

Now it's working :)
