### ISSUE TITLE
Unable to show site name on website

### ISSUE THREAD

**Issue by binglenozumi** [rainlab/translate-plugin#296]
Hi, I have a question here about the site name

So I had already include site.name inside the theme.yaml file, but when I try to put {{ site.name |_ }}, I cannot show any of the name, including English one (default setting)

What is the most likely situation that makes this happen? or if there is any particular files I need to check out on?

**Comment by jan-vince** [comment]
Try ````{{ this.theme.site_name |_ }}```` as [in docs](https://octobercms.com/docs/themes/development#customization).

*There is ````_```` not a ````.```` in ````site_name```` if you are following docs example.*
