### ISSUE TITLE
Pasting into translatable fields via mouse doesn't work

### ISSUE THREAD

**Issue by gtmeteor** [rainlab/translate-plugin#297]
As mentioned. Pasting with mouse into a translatable field and saving a Model will not update the model due to multilingual.js listening to `keyup` event. It should listen to `input` event.

assets\js\multilingual.js - #43 
```
this.$placeholder.on('keyup', function(){
   self.$activeField.val(this.value)
})
```
should be:
```
this.$placeholder.on('input', function(){
   self.$activeField.val(this.value)
})
```

**Comment by LukeTowers** [comment]
Thanks for the report!
