### ISSUE TITLE
Problem with translated URL 

### ISSUE THREAD

**Issue by quochuy** [rainlab/translate-plugin#298]
I have a newsletter archive page like this:
- title: Newsletter Archives
- file: newsletter-archives.htm
- url: /newsletter/archives which translates to http://mysite.com/en/newsletter/archives 
- the page loads a newsletter-archives.htm content file

My site also supports french language and I have a newsletter-archives.fr.htm content.
Now my problem is when I go to http://mysite.com/fr/newsletter/archives I get a 404 error but I get the page OK if I go to http://mysite.com/fr/newsletter-archives

So I went back in the CMS and edited the Newsletter Archives page, clicked on the URL and selected FR. The value was /newsletter-archives I tried to change it to /newsletter/archives and it saves successfully, but if I close and reload it, it is reverted back to /newsletter-archives

It used to work before. Probably a regression bug introduced recently.

**Comment by quochuy** [comment]
The work around is to edit the actual file and remove the line localeUrl[FR]=....

**Comment by LukeTowers** [comment]
@quochuy are you able to dig a bit deeper and make a PR to fix the issue?

**Comment by rounce** [comment]
https://youtu.be/ZeNkAiIXe5s

**Comment by LukeTowers** [comment]
Same to you @rounce

**Comment by mjauvin** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
