### ISSUE TITLE
How to find out if translation is not available?

### ISSUE THREAD

**Issue by layanto** [rainlab/translate-plugin#301]
In model, if the field is translated:
```php
$this->getTranslateAttribute('title', 'fr');
```
The translated text is returned.

But if the field is not translated, the default language ('en') is returned.

How can I find out that there is no translated text available? Is there a method that will return '' instead of the default language?

**Comment by datune** [comment]
```php
$this->noFallbackLocale()->lang('fr');
$this->getTranslateAttribute('title', 'fr');

```
https://github.com/rainlab/translate-plugin#fallback-attribute-values

**Comment by layanto** [comment]
What if I don't want to disable the fallback feature, I just want to find out if translation is available or not?

**Comment by datune** [comment]
https://github.com/rainlab/translate-plugin/blob/master/classes/TranslatableBehavior.php#L187

**Comment by layanto** [comment]
Thanks.
