### ISSUE TITLE
Undefined index TranslatableBehavior.php line 189 when calling hasTranslation

### ISSUE THREAD

**Issue by datune** [rainlab/translate-plugin#302]
Add the following code into any ListController index() method (for example, let's use Rainlab\Blog\Controller\Posts) and retreive a Model from the DB which is using the TranslatableBehaviour.

```php  
    $p = Post::find(1);
    $p->hasTranslation('slug', 'en');
```
This will throw an Error Exception: /plugins/rainlab/translate/classes/TranslatableBehavior.php line 189 undefined index 'en'.

BUT, when executing the following code, everything behaves as expected, and I can't figure out why. For some reason, the [$translatableAttributes array](https://github.com/rainlab/translate-plugin/blob/master/classes/TranslatableBehavior.php#L189) is empty, and only gets populated AFTER using an accessor. This makes absolutely no sense to me. Can you please enlighten me before I put my fist through my, quite expensive, monitor and pull out my hair?

```php  
    $p = Post::find(1);
    $p->title; // This suffices to make the following line of code work, but WHY?
    $p->hasTranslation('slug', 'en');
```

This problem has nothing to do with the Blog plugin, it happens with every single Model that implements the Translatable Behaviour. 

PS: Without trying to be disrespectful, some of the inline code documentation is so ambigious, and makes things only worse. For example, when just[ reading this code](https://github.com/rainlab/translate-plugin/blob/master/classes/TranslatableBehavior.php#L39), I don't know whether this property holds the translated attributes, or whether it represents the attributes that CAN be translated. Why call a property translatableAttributes if according to the documentation it is supposed to store translated attributes. IMHO the appropiate naming would have been translatedAttributes. Again, don't mean to be condescending, patronizing or <pick your flavor>...

**Comment by datune** [comment]
After dancing with a lot of gruesome xdebug sessions on the brink of insanity, I think I have solved the issue. 

It seems to me that there is simply a logic error in the current hasTranslation() method implementation. In all other methods there is a check made before relying upon values from the property $translatableAttributes, but in this method (hasTranslation) it is not. 

At the time of writing the code looks like this:
File: [TranslatableBehaviour.php::L187](https://github.com/rainlab/translate-plugin/blob/master/classes/TranslatableBehavior.php#L187)
```php
    /**
     * Returns whether the attribute is translatable (has a translation) for the given locale.
     * @param  string $key
     * @param  string $locale
     * @return bool
     */
    public function hasTranslation($key, $locale)
    {       
        return !!$this->getAttributeFromData($this->translatableAttributes[$locale], $key);
    }
```

The problem is that the property translatableAttributes has never been populated at this point of the request cycle. The following code seems to fix all my issues and after some testing does not seem to introduce any additional overhead nor did I notice any other problems. Obviously this needs to be reviewed... 

```php
    /**
     * Returns whether the attribute is translatable (has a translation) for the given locale.
     * @param  string $key
     * @param  string $locale
     * @return bool
     */
    public function hasTranslation($key, $locale)
    {       
        if (!isset($this->translatableAttributes[$locale])) $this->loadTranslatableData($locale);
        return !!$this->getAttributeFromData($this->translatableAttributes[$locale], $key);
    }
```
I would also like to suggest to revise the documentation for this method. There is already a method available named isTranslatable()...

Please let me know if you want me to create a PR and keep up the good work, it's much appreciated!

**Comment by datune** [comment]
Method had to be revised again, due to the nature of how default language attributes seem to be handled.

```php
    /**
     * Returns whether the attribute is translatable (has a translation) for the given locale.
     * @param  string $key
     * @param  string $locale
     * @return bool
     */
    public function hasTranslation($key, $locale)
    {
        /*
         * If the default locale is passed, the attributes are retreived from the model,
         * otherwise fetch the attributes from the $translatableAttributes property
         */
        if ($locale == $this->translatableDefault) {
            $translatableAttributes = $this->model->attributes;
        }
        else
        {
            // Ensure that the translatableData has been loaded
            if (!isset($this->translatableAttributes[$locale])) $this->loadTranslatableData($locale);

            $translatableAttributes = $this->translatableAttributes[$locale];
        }

        return !!$this->getAttributeFromData($translatableAttributes, $key);
    }
```

**Comment by LukeTowers** [comment]
Looking good @datune! Could you submit a PR with that? Also, could you make the isset if conditional the same format as the $locale == $this->translateableDefault if conditional? I.e. not single line.

**Comment by datune** [comment]
@LukeTowers [Here's the PR](https://github.com/rainlab/translate-plugin/pull/305) along with the requested changes.

**Comment by LukeTowers** [comment]
@datune awesome, thanks for your work on this!
