### ISSUE TITLE
Array & JSON Casting for translatable attributes empty fields

### ISSUE THREAD

**Issue by yarbala** [rainlab/translate-plugin#303]
Cast attributes are saved to db and to 'rainlab_translate_attributes' but have empty value for default language in editor

Model.php:
```
public $translatable = ['title', 'fields[test11]', 'fields[test12]', 'fields[test21]'];
protected $casts = [
        'fields' => 'array'
    ];
```

fields.yml:
```
        'fields[test11]':
            label: Test11
            type: text
            tab: 'Content'
        'fields[test12]':
            label: Test12
            type: text
            tab: 'Content'
```

After saving data I have proper values in DB. I open this form for editing and switch to not default language, then back to default - and field becomes empty.

I'm using latest october version. For other field types like Markdown it works same way.

**Comment by yarbala** [comment]
I made quick fix for it, may be you can add something similar to Plugin

file: plugins/rainlab/translate/classes/TranslatableBehavior.php
```
    protected function getAttributeFromData($data, $attribute)
    {
        $keyArray = HtmlHelper::nameToArray($attribute);

        $path = implode('.', $keyArray);
        $val =  array_get($data, $path);

        // For json attributes
        if (is_null($val) && count($keyArray) > 1) {
            $data[$keyArray[0]] =  json_decode($data[$keyArray[0]], true);
            if (!is_null($data[$keyArray[0]])) {
                $val = array_get($data, $path);
            }
        }

        return $val;
    }
```

**Comment by LukeTowers** [comment]
I have no idea what the issue is from your description. Please try to explain it in more detail and more step by step.

**Comment by yarbala** [comment]
@LukeTowers I'm trying to use dynamic forms(different field types for single model depending on model type) in OctoberCMS backend.  I uses attribute casting to store fields in json field https://laravel.com/docs/5.5/eloquent-mutators#attribute-casting. Everything works fine except translations for dynamic fields. getAttributeFromData function didn't works with json attribute casting. This function tries to get array, but field contains json. My fix solves problem - and my app works fine, but I'm not sure - this fix is best solution.

**Comment by LukeTowers** [comment]
This is a complex case. 

In order to aid in our understanding of the problem, please submit [a Pull Request to the test plugin](https://github.com/daftspunk/oc-test-plugin) for investigation that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it _using the test plugin_.

**Comment by yarbala** [comment]
@LukeTowers I crested pull request with steb by step instructions

**Comment by LukeTowers** [comment]
Thanks @yarbala, I don't have a lot of time to review it right now, but it'll eventually get taken care of. Perhaps @daftspunk could review it. Or, if someone else could confirm the bug and come up with a robust fix for it; I would probably merge it. I'll just need a detailed explanation that clearly and simply explains the issue, what's currently causing it, and how the proposed solution fixes it without introducing any adverse effects.

**Comment by yarbala** [comment]
If you try my code from merge request, it wiil take you 3 minutes to reproduce issue. https://prnt.sc/gtw8g9 - may be my engish is poor, watch to this screen

**Comment by yarbala** [comment]
@LukeTowers same issue if I replace $casts with jsonable. It works with fix and not works without it

```
//    protected $casts = [
//        'fields' => 'array'
//    ];

    protected $jsonable = ['fields'];
```

**Comment by LukeTowers** [comment]
The support demand for October is increasing, while the available time the founders have to give remains the same. These issues will be handled in time, however there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

**Comment by yarbala** [comment]
Some fix to previous fix - if you change existing field to translatable, this will prevent errors

```
protected function getAttributeFromData($data, $attribute)
    {
        $keyArray = HtmlHelper::nameToArray($attribute);

        $path = implode('.', $keyArray);
        $val =  array_get($data, $path);

        // For json attributes
        if (is_null($val) && count($keyArray) > 1 && isset($data[$keyArray[0]]) && is_string($data[$keyArray[0]])) {
            $data[$keyArray[0]] =  json_decode($data[$keyArray[0]], true);
            if (!is_null($data[$keyArray[0]])) {
                $val = array_get($data, $path);
            }
        }

        return $val;
    }
```

**Comment by LukeTowers** [comment]
@yarbala feel free to make your code changes in a PR so that we can easily merge them when they get reviewed.

**Comment by yarbala** [comment]
[](https://github.com/rainlab/translate-plugin/pull/322) - I made pull

**Comment by LukeTowers** [comment]
Thanks @yarbala, just need it to be reviewed now.
