### ISSUE TITLE
Translate messages doesnt show

### ISSUE THREAD

**Issue by danielsvens** [rainlab/translate-plugin#309]
I cant seem to solve this problem. When i go to the translate messages tab there is nothing there.

when i add text with {{ 'text'|_ }} i can see its properly saved in the DB. 

But since i cannot access the messages page i cannot translate anything. 

https://imgur.com/a/kKZKs
Picture of the error

Build is 419 and php 7.0.15

Anyone knows a fix for this?

**Comment by LukeTowers** [comment]
Try enabling edgeUpdates in config/cms.php and updating your installation.

**Comment by danielsvens** [comment]
i ran the update with edgeUpdates and some things was not updated i guess, i had to change cipher to AES and some other things. but after that it fixed all my issues. thank you for that.

**Comment by LukeTowers** [comment]
Awesome, glad to hear it!
