### ISSUE TITLE
need update version

### ISSUE THREAD

**Issue by plyusninva** [rainlab/translate-plugin#316]
Hello! 
Please update plugin
![image](https://user-images.githubusercontent.com/25381948/32326770-ddc95cc6-bff5-11e7-8beb-b3563310f546.png)

**Comment by vannut** [comment]
Those updates > 1.2.11 are pending updates, which means you can install them when having edgeUpdates on. They are built on the new version of OctoberCMS (build > 4.20).

Until OctoberCMS is 'stable' at the new version, the plugin also gets updated.

if you want the latest version without enabling `edgeUpdates` you can always clone this repo and drop it in your OctoberCMS install.

**Comment by LukeTowers** [comment]
As above @plyusninva

**Comment by plyusninva** [comment]
how soon will a new version of OctoberCMS?

**Comment by LukeTowers** [comment]
@plyusninva do you mean a stable release of the latest code changes?

**Comment by plyusninva** [comment]
Yes, I would like to try a new stable version :-) 
(edgeUpdates = false )

**Comment by LukeTowers** [comment]
If more people tested `edgeUpdates = true` then it would be faster ;). It should be here within the next couple of weeks, we need to push the next build and let it sit for a week.
