### ISSUE TITLE
creating files with the access right 777

### ISSUE THREAD

**Issue by plyusninva** [rainlab/translate-plugin#319]
when I create the "Test" page, a file with the access right 777 is created in the "/themes/[theme_name]/content/static-pages-en/test.htm" directory

![image](https://user-images.githubusercontent.com/25381948/32598536-d9709444-c55b-11e7-8ee3-fcf84441fb43.png)
and also when editing files, the access rights "644" are reset to "777"

this is normal? or bug?

--
october build 419 (translate 1.2.11)

**Comment by vannut** [comment]
Can't tell if its normal behaviour; but in the config-directory there is an entry for the permission mask:
`/config/cms.php`
```
/*
|--------------------------------------------------------------------------
| Default permission mask
|--------------------------------------------------------------------------
|
| Specifies a default file and folder permission for newly created objects.
|
*/
    'defaultMask' => ['file' => null, 'folder' => null],
```
If you specify the mask here, does the translate plugin use this?

**Comment by plyusninva** [comment]
everything works well, I just forgot about this setting. was set 777 ('file' => 777, 'folder' => 777)
I apologize for not attentiveness and thank you for your answers
