### ISSUE TITLE
Switching locale of ML repeater doesn't load values of the target locale

### ISSUE THREAD

**Issue by Fl0Cri** [rainlab/translate-plugin#323]
I have a page (from Rainlab Static Pages plugin) using a layout that defines a repeater.
I have set some values in the repeater for both languages I am using: EN (default) and FR.
The problem occurs when I try to switch the repeater from the default locale to any other locale.

#### Expected behaviour
When switching to an other locale (here from EN to FR), the fields inside the repeater should be filled with the values from the FR page:
![ml_repeater-working](https://user-images.githubusercontent.com/16371551/33882250-c74b7a86-df37-11e7-93a6-7bc3fd66eab7.png)

#### Actual behaviour
When switching to an other locale, the locale is switched, but the values inside the repeater are the one from the same as the previous locale:
![ml_repeater-not-working](https://user-images.githubusercontent.com/16371551/33882748-7871e7b8-df39-11e7-8150-34448f40a532.png)
But actually, if I look directly inside the static page file, the FR page has the correct values (`Repeater FR ...`, etc.).
If I hit save the save button in the backend when in this situation, all the values of the repeater in the FR page are overwritten by the EN values (what is displyed on the screen).

#### Reproduce steps
1. On a site, install:
    - static pages plugin
    - the translate plugin
1. In the languages settings, create a second language (for example FR)
1. Create a CMS layout that defines a repeater for static pages:
```HTML
description = "test layout"

[staticPage]
useContent = 1
default = 0
==
<!DOCTYPE html>
{repeater name="pageblocks"}
    {variable name="text" type="text" label="Content"}{/variable}
{/repeater}
<html>
    <head></head>
    <body>
            {% for item in pageblocks %}
            	<div>{{ item.text }}</div>
            {% endfor %}
        </div>
    </body>
</html>
```
4. Create a static page that uses this layout and fill some data inside the repeater for both languages.
4. Save the static page and refresh the browser page.
4. Open the static page again and try to switch the language of the repeater.
4. Now you can notice that:
    - The language indicator of the repeater is correctly displaying the wanted language
    - But the values displayed are the one from the default language
    - If you look at the values of the static page using a text editor, you can see that the values are still correct.
    - If you save the static page from the backend (after having tried to switch locale), and reopen the translated static page file with your text editor, you will see that the values have been replaced by the values of the default locale.

#### October build
430

#### A possible solution
The problem seems to be coming from the `onSwitchItemLocale()` method of the ML Repeater: https://github.com/rainlab/translate-plugin/blob/master/formwidgets/MLRepeater.php#L107

In this method, the translated data are correctly retrieved to the `$lockerData` variable by `$this->getLocaleSaveDataAsArray()`.

Then, from what I understand, `$this->reprocessExistingLocaleItems($lockerData);` will remove the fields in the repeater and recreate them, (it's ok but I will come back to this later).

Then, a loop is done to replace the values of the created fields (`$widget`s) with the transated values.
The problem here is that only the values of the fields (widgets) are replaced. But these values are stored at least at 3 places in the repeater object:
- Inside the widgets (`$this->formWidgets[]->data`), these are properly replaced
- In the repeater itself I suppose (`$this->formField->value`), these are not replaced
- In the source model (`$this->model->viewBag` and `$this->data->viewBag`), these are not replaced

Now going a bit further, we call `render()` of the Repeater object (we are in the cms now), which calls `prepareVars()`.

At the very beginning of this `prepareVars()` method, we call `processExistingItems()` which will recreate the repeater fields using the data inside `$this->formField->value` (assuming $this to be the repeater object. This is exaclty what we did with `reprocessExistingLocaleItems()` a moment ago.
This will overwrite the `formWidgets`, so we will lose the translated data we set.

I tried to comment this line https://github.com/octobercms/october/blob/master/modules/backend/formwidgets/Repeater.php#L126 (just to be sure). It solves the problem but of course it will break something else.

An other thing I tried is to replace the `formField->value` of the repeater like this (in the onSwitchItemLocale method where I started):
```PHP
/*
 * Update widget
 */
$lockerData = $this->getLocaleSaveDataAsArray($locale) ?: [];

$this->formField->value = $lockerData;  // Set the translated values in place of the original

$this->reprocessExistingLocaleItems($lockerData);
```
It works in my case, but I don't know if there is a situation where the translated data may not be compatible with `formField->value`.

**Comment by davidjmz** [comment]
Thanks a lot for the suggested solutions, the last one worked like a charm for us, but as you say, it may break anything else, but right now is working fine, thank you again <3

**Comment by slowpokefarm** [comment]
Thanks for submitting that issue, I was just going to do it myself as well, because it is really annoying and unusable.

**Comment by ranmichael** [comment]
@Fl0Cri your last solution works for us as well! 
(Hope it doesn't break anything)
There was a recent update to the Translate plug-in which I thought was going to solve this issue.
It partially solved it, because before the update - repeater values on different locales were stored sequentially i.e.
En would be
someRepeater[1][someValue]
someRepeater[2][someValue]
someRepeater[3][someValue]

and FR would be
someRepeater[4][someValue]
someRepeater[5][someValue]
someRepeater[6][someValue]

Text values for secondary locales in the Repeater would load in the BackEnd, but Richeditor and images wouldn't. (before the update that is)

Since the update, they are stored correctly in the content/static-pages in their respective folders.
so 
EN is 
someRepeater[0][someValue]
someRepeater[1][someValue]
...
and FR is also 
someRepeater[0][someValue]
someRepeater[1][someValue]

But nothing loads as you perfectly described, Fl0Cri.

Since everything is stored correctly - the problem seems to be only when switching languages in the Repeater in the Backend, which makes repeaters unusable. 

I tested your solution and it works also for Richeditor and Image (media) values.
Ping me if you need help testing this further.

Cheers.

**Comment by LukeTowers** [comment]
@Fl0Cri @ranmichael @slowpokefarm @davidjmz someone please submit a PR with the fix and get as many people to test it and comment on the PR verifying it as possible. Thanks!

**Comment by munxar** [comment]
@LukeTowers here you go: https://github.com/rainlab/translate-plugin/pull/324

**Comment by jan-vince** [comment]
Hi @LukeTowers, the PR: #324 works for me with basic repeaters in Static Pages and in plugin's forms fields.

Can you please merge it?
