### ISSUE TITLE
Slugs do not autocomplete

### ISSUE THREAD

**Issue by msimkunas** [rainlab/translate-plugin#327]
I've noticed that fields which autocomplete as you type according to another field (such as slugs) do not visibly autocomplete when using this plugin.

This issue can be reproduced using the `blog-plugin` but it applies to the general case as well (i.e. I notice the same behavior in one of my custom plugins). 

Steps to reproduce:
1. Open an existing blog post
2. Ctrl+click on the language chooser to switch ALL fields to a different language at once
3. Type the translated title
4. Observe that the slug does not _appear_ to be autogenerated (i.e. no value is being output in the slug field while typing the title)
5. Save the post and reopen it
6. Switch the language on the slug to see that it is properly translated (the translated slug is generated and saved but not shown while typing the translated title)

Translate plugin version: 1.3.5
October build: 431

**Comment by LukeTowers** [comment]
@msimkunas Could you provide a PR to fix this issue? It probably has to do wit the input preset JS handler not being appropriately reregistered onto the translated fields that are replacing the originals.

**Comment by msimkunas** [comment]
@LukeTowers Not at this time. I haven't investigated this issue on a technical level yet. I'll try my hand at this sometime after the holidays.

**Comment by LukeTowers** [comment]
Awesome, thanks @msimkunas

**Comment by iboved** [comment]
@msimkunas Have you solved this problem? I have the same problem.
Additionally, there is another problem. When you edit for example  the "Title" field in EN language, the "Slug" field is generated in ALL languages.
But it should be like this:
When you edit the "Title" field in EN language, the "Slug" field should be generated only in EN language.
When you edit the "Title" field in DE language, the "Slug" field should be generated only in DE language.
And so on...

**Comment by mjauvin** [comment]
Resolved by https://github.com/rainlab/translate-plugin/pull/458
