### ISSUE TITLE
Rainlab Blog: On switchLocale URL isn't translated

### ISSUE THREAD

**Issue by ranmichael** [rainlab/translate-plugin#328]
October Build: 431
Rainlab Blog: 1.2.19
Rainlab Translate: 1.3.3
----
Steps to reproduce:
1. Create a blog post in two languages. E.g. En, Fr.
2. Set up a different URL for each of the languages.
e.g. 
For English: /my-article
For French: /mon-article
You can choose to force or not the URL Schema in the LocalePicker.

3. Consult the blog article in the FrontEnd.
4. Switch Locales with a LocalePicker.

5. Notice the bug:
Language (Locale) is switched, but the url language isn't translated.
so we get:
/fr/blogue/my-article (BUG: Expected: /fr/blogue/mon-article)
and if we start our navigation from
/fr/blogue/mon-article
we get:
/en/blog/mon-article (BUG: Expected: /en/blog/my-article)

This is not acceptable for two reasons:
1. /en/blog/mon-article doesn't exist. 
(English content doesn't show, because it is the first language in the system)

2. For the second language (in this case Fr) SEO rank suffers - we have a duplicated page - with two different urls:
/fr/blogue/my-article (shouldn't exist)
/fr/blogue/mon-article
which are the same.

**Comment by LukeTowers** [comment]
Is this related to https://github.com/rainlab/translate-plugin/pull/326 @ranmichael?

**Comment by vannut** [comment]
On the one hand it seems related; but I don't read anything about changing the `prefixDefaultLocale` setting. With that setting being default it should not interfere with anything. 

That said, the behaviour does indeed look [like this](https://github.com/rainlab/translate-plugin/pull/318#issuecomment-354567683)

**Comment by ranmichael** [comment]
@vannut @LukeTowers , at first sight it seems related but isn't;
This happens Regardless of the settings/flags - I added the prefix /en and /fr only so that the explanation is clear.

Also, I don't encounter this problem on StaticPages; Though #326 is present on StaticPages.

For the record, the only two CMS pages (not static) I use have:
- One page: has the Post List Component. No problem with URL translation on Locale Switch.
/en/blog
/fr/blogue

- Second page: has the **Post Component** - where the problem occurs.

Again, the Locale is switched correctly, it is the URL that doesn't follow the switch.
What's interesting is that when switching to English we get half the url correctly:
> See correct in **bold**
**/en/blog/** mon-artcile 
**/fr/blogue/** my-article 
when schema isn't forced it's:
/blog/mon-article (wrong)
/blogue/my-article (wrong)

This said, I suspect fixing #326 and forcing schema might do the trick (but I do not think it will solve the bug when schema/prefix is not forced).

**Comment by LukeTowers** [comment]
@ranmichael are you able to do some digging and see if you can figure out what a fix would look like?

**Comment by ranmichael** [comment]
@LukeTowers I think it's better to wait for #326 fix first, then re-evaluate.
 If fixing #326 and forcing schema does the trick, this becomes low priority.

**PS - For any one looking for a workaround:**
At the mean time, for my project, the workaround is to redirect to the blog's PostList (category) page when the user switches languages while reading any specific Blog post.
So when the user is in English and clicks 'Fr', I redirect to /fr/blogue (should have been /fr/blogue/mon-article)
and when he/she is in French and clicks 'En', I redirect to  /en/blog (should have been /en/blog/my-article)

Not great, but acceptable from a user point of view.

**Comment by LukeTowers** [comment]
@ranmichael could you test #326 and let us know if it works for you? I'm waiting for someone else to test it before I merge it.

**Comment by anastasiauz** [comment]
I experience the same problem: Blog + Translate (2 languages RU/EN), URLs are not translated when I switch language on single post page (it is same as in the case above: force or not the URL Schema in the LocalePicker). I created test case, only these plugins, edge updates 'true', October 434, Translate 1.4.0. Will there be any fix? 

And another thing is strange - when I'm in default Russian I have all posts' as domain.tld/posty. If I manually type in URL English version domain.tld/posts and navigate to this it - I get 404. Is it a bug? User may go back in browser and get 404 instead of existing page in other language.

**Comment by LukeTowers** [comment]
@anastasiauz have you updated your plugin to use the fix in #326?

**Comment by anastasiauz** [comment]
@LukeTowers I'm using 1.4.0 Translate, the file classes/LocaleMiddleware.php already has changes offered in  #326

**Comment by LukeTowers** [comment]
Are you able to dig deeper and see if you can find the source of the issue? @munxar any input on this?

**Comment by munxar** [comment]
As far as I can tell, the described behavior is like it was implemented.
```php
        $post = $post->isClassExtendedWith('RainLab.Translate.Behaviors.TranslatableModel')
            ? $post->transWhere('slug', $slug)
            : $post->where('slug', $slug);
```
If the locale switches only the blog is found but the url is not rewritten.
imho this should be a feature request for the blog plugin.

**Comment by munxar** [comment]
a possible implementation could be like this:
```php
   // inside plugins/rainlab/blog/components/Blog.php
    public function init()
    {
        Event::listen('translate.localePicker.translateParams', function ($page, $params, $oldLocale, $newLocale) {
            $newParams = $params;
            $paramName = 'slug'; //?what if not named 'slug'?
            $paramValue = $params[$paramName];

            $records = BlogPost::transWhere($paramName, $paramValue, $oldLocale)->first();

            if ($records) {
                $records->translateContext($newLocale);
                $newParams[$paramName] = $records[$paramName];
            }

            return $newParams;
        });
    }
```
the only thing i could not figure out is how to get the name of the used 'slug' in the cms page, or what if someone decides to name it 'id'. 
any ideas?

**Comment by anastasiauz** [comment]
Thank you, I'll try that

**Comment by anastasiauz** [comment]
@munxar Thank you, the solution is working! Slugs are now translated. But I changed Post component so it'll work until new update or freeze the plugin. Will this be included in new updates?

**Comment by LukeTowers** [comment]
@munxar could you create a PR with that code in this plugin? @anastasiauz the updated code will be in this plugin, not in the blog plugin.

**Comment by bennothommo** [comment]
@munxar @anastasiauz @ranmichael Could you test [PR #436](https://github.com/rainlab/blog-plugin/pull/436) in the Blog plugin and confirm that it works with the locale switcher?
