### ISSUE TITLE
[Bug]With Model Translation records for all languages is not stored at time of creation 

### ISSUE THREAD

**Issue by anand-patel** [rainlab/translate-plugin#33]
With model translation at time of creating record it not saved with all languages it only save default language content, at time of updating record it save records with all languages.

i have extends translation model with my plugin and when i create record with all languages it`s not save other languages record, i have also check with forum plugin i got same result while creating(not updating) channel with all languages its only save data for default language not for other languages.

it should be like when you create record with all languages its save content for all languages.

**Comment by daftspunk** [comment]
Fixed in c9c1e7d73835e123b7cb64c53fe58992881a717c
