### ISSUE TITLE
Meta title/description for CMS page not translatable by default

### ISSUE THREAD

**Issue by vannut** [rainlab/translate-plugin#331]
I just found out that a CMS page's Meta title and Description is not translatable by default. 
![schermafbeelding 2018-01-11 om 10 30 23](https://user-images.githubusercontent.com/7419859/34818215-76e129a2-f6ba-11e7-9880-acdc870b0e59.png)

Only the slug is translatable. 
Am I missing something here?
Or might it be a good thing to make those fields also translatable by default?

**Comment by LukeTowers** [comment]
Make a PR to change this if you want :)

**Comment by vannut** [comment]
Haha. Will do, but was wondering if I was missing something here :)
But if the plugin lacks the feature I'll dive into it :)

**Comment by LukeTowers** [comment]
Sounds good 👍

**Comment by zakir1929** [comment]
@vannut @LukeTowers 
I also need this feature on my cms but as I can see it is not implemented until in 434 October Build. 
can you show me some workaround in that 
Thanks.

**Comment by munxar** [comment]
you can use this as a workaround:
```php
{{ this.page.meta_title|_ }}
```
but the messages must be translated on the translate messages page in the backend settings.

**Comment by zakir1929** [comment]
yes I seen that solution. I thought maybe there is a way now to give my client a ability to translate title in cms page title field.
![image](https://user-images.githubusercontent.com/16069667/36466187-cb1d2462-16fe-11e8-9185-25db61d128c5.png)

**Comment by hlev** [comment]
@munxar 
> you can use this as a workaround:
>
> `{{ this.page.meta_title|_ }}`
> but the messages must be translated on the translate messages page in the backend settings.

New 434 user here. The values of these properties do not seem to be collected by the scanner. How do you add them to the messages in the backend?

**Comment by LukeTowers** [comment]
@hlev they get populated on first generation of them, so visit the pages where they're defined and they'll populate into the DB

**Comment by hlev** [comment]
Thanks @LukeTowers
