### ISSUE TITLE
MLRichEditor input data lost after switch locale.

### ISSUE THREAD

**Issue by joelamltc** [rainlab/translate-plugin#333]
Input data lost after switch locale from top right corner.

For example, system has 3 languages (English, Traditional Chinese, Simplified Chinese).
I input data in English, then I switch to Traditional Chinese and copy and paste the data I input in English. Do the same for Simplified Chinese.
After that, I switch to English from Simplified Chinese, but no data present in RichEdotor.

### I found out that data is loaded if we input from typing but not loaded from copy and paste data. Reason is "[froalaEditor.contentChanged](https://www.froala.com/wysiwyg-editor/docs/events#contentChanged)" is not trigger to save the data locally when we copy and paste.

Any ideas that can let data save locally when we copy and paste.

**Comment by LukeTowers** [comment]
Looks like it was perhaps recently fixed in Froala: https://github.com/froala/wysiwyg-editor/issues/2055. There's been an issue open for @daftspunk to upgrade the version: https://github.com/octobercms/october/issues/3203

**Comment by joelamltc** [comment]
@LukeTowers Might I ask does it fixes yet?

**Comment by LukeTowers** [comment]
@joelamltc it hasn't been. Try pinging @daftspunk on the issue I linked you to in order to get him to upgrade the dependency

**Comment by joelamltc** [comment]
I saw daftspunk assigned you tho @LukeTowers

**Comment by LukeTowers** [comment]
@joelamltc nope, I assigned @daftspunk (https://github.com/octobercms/october/issues/3203#event-1312159941). And that doesn't really mean anything anyways. He's the only one with the access to Froala to update the DRM sources, so I'll ping him privately about the issues.

**Comment by joelamltc** [comment]
@LukeTowers okay thanks

**Comment by mjauvin** [comment]
Just tested this with latest develop (v1.0.454) and this is still happening.

**Comment by mjauvin** [comment]
Cannot reproduce anymore.
