### ISSUE TITLE
Cache timeout customization with env

### ISSUE THREAD

**Issue by viamage** [rainlab/translate-plugin#334]
Hello,

Currently cache timeout is hard coded to 1440. 

There are some occasions though - for example static websites where content or translations do not change, where it would make sense to increase that timeout. Otherwise every 24h some unlucky visitor, or a robot, will trigger a lot of queries, which can convert to several seconds of additional initial request time, because queries are not collected by run one after another. 

My suggestion would be to add possibility to use env and implement some simple solution like:

```
    public static function saveToCache()
    {
        if (!self::$hasNew || !self::$url || !self::$locale) {
            return;
        }

        Cache::put(self::makeCacheKey(), self::$cache, env('TRANSLATE_CACHE_TIMEOUT',1440));
    }
```

would you accept pull request with this, or maybe have some other idea to resolve it?

**Comment by LukeTowers** [comment]
@viamage I'd accept a PR that put it in the config file instead, that way people can use config overrides to use environment files if they want or just use the config override instead and commit that to their projects.

**Comment by viamage** [comment]
PR created @ https://github.com/rainlab/translate-plugin/issues/334 I guess it's in line with your comment.
