### ISSUE TITLE
[feature] With model translation can we have editor ? 

### ISSUE THREAD

**Issue by anand-patel** [rainlab/translate-plugin#34]
right now we have text field and textarea for model translation, but for content we don`t have editor which has ability to translate content.

if we has editor that has translate ability then it is very useful, it can be use for blog and static pages too.

**Comment by polikin** [comment]
+1 for translate static pages

**Comment by nsrosenqvist** [comment]
+1 for translatable static pages/partials/blog posts

**Comment by amircup2006** [comment]
+1

**Comment by DigitalMachinist** [comment]
This would be huge. It may be the deciding factor between whether I decide to use October for an upcoming project. +1

**Comment by daftspunk** [comment]
Richeditor has supported translations for quite some time now.

**Comment by ramachandranv** [comment]
The translate switcher is not visible in richeditor. Is there anything to be done?
