### ISSUE TITLE
Static Pages > Snippets > CMS Cache refresh problem when switching languages makes snippets unusable

### ISSUE THREAD

**Issue by ranmichael** [rainlab/translate-plugin#343]
Steps to Reproduce:
- Create a static page
- Add snippet 1 in first language (let's say Fr) - save.
- Still in the editor, switch to second language (let's say En) 
- Add snippet 2 in second language - save.
- Go to Frontend on first language.
Notice problem: Snippet 1 doesn't appear. Refresh. Still nothing.
Switch to second language (using locale picker or via url)
Snippet 2 DOES appear.
Switch back to first language. Still nothing.

- Go back to backend and clear CMS cache using Romanov Clear Cache widget.
- Go to front end - First language (fr) - Refresh - Snippet appears.

This is extremely frustrating; It means that snippets basically can't work on a bilingual site right now because of a minor cache problem. (Clients do not have access to refresh CMS cache)

**Comment by LukeTowers** [comment]
This was fixed a while ago, update your October instance and your plugins. https://github.com/rainlab/translate-plugin/commit/f5ddabbcf907af47a7129157c847472122c4ba7a

**Comment by ranmichael** [comment]
Oh !
Cool !
I was on Build 430 - updated to Build 431 and this problem was indeed fixed.

So the scenario above seems to work fine now - well... sort of.
It works if the snippets are inserted to the **'Content'** block (which is rendred by { %page% } ) - but not when using placeholders in Static pages. 
In other words, can't show snippet 1 for language EN and snippet 2 for language FR - using the scenario above, even when clearing cache.
My use case is simple:
I have
{% placeholder leftColumn title="Left Column" %}                             
{% placeholder rightColumn title="Right Column" %}            
And I am trying to use snippets to insert content in the left column.
It is impossible to use different snippets for each language.

Oh, and while at it, I ran some other tests and noticed two new snippet problems, one of which is also cache-related:

1) Snippets do not show when replaced by another snippet - unless cache is manually cleared  
(I think this is a **regression**)
**Steps to Reproduce:**
- Add snippet 1
- Save
-- Refresh Frontend - Snippet 1 is there.
- Delete snippet 1
- Save
- Add snippet 2
- Save
-- Refresh Frontend - Snippet 2 is NOT there.
- Clear CMS cache
-- Refresh Frontend - Snippet 2 IS there.


2) Some snippets (created from plug-ins?) will only show if inserted via 'Content' block.
But won't show if a placeholder is used.
Same example as above:
{% placeholder leftColumn title="Left Column" %}

I tested with @Renatio's snippet called: "Render Form Component".
So this snippet works in 'Content' but not in 'Left Column'.
The snippets I create from partials seem to work fine.

I know, @LukeTowers, these are three different issues, but somehow related and it took me a couple of hours to test and put my finger on what's wrong.
How do you want to tackle this?

Build 431
Translate | 1.3.8 | @alekseybobkov, @daftspunk
Pages |  1.2.18 | Alexey Bobkov, Samuel Georges
Form Builder | 1.4.2 | @Renatio

**Comment by LukeTowers** [comment]
@ranmichael could you do some testing to find the difference in how the snippets get rendered between the content field and placeholder sections and see if you can narrow down why it's not working for you a bit more?

**Comment by ranmichael** [comment]
Well, 
The reason I tagged the mighty creators of StaticPages, is because they should already know exactly what you're asking me to investigate, while I have to (kind of) reverse-engineer their work to get the answer...
Unfortunately, I can't see when I can make time in my schedule to do this in a timely manner.

**Comment by LukeTowers** [comment]
@ranmichael what makes you think the creators have time to take care of it? I could probably find the issue but I'm not personally encountering it right now and I have a significant amount of higher priority work to take care of right now so I probably won't get to it for a while. Hence why I recommended that you dig deeper into it so that you can have your issue solved.

**Comment by ranmichael** [comment]
I might not understand how October Community works then.
I contributed 3 hours today to test, pinpoint and document a few bugs (4 actually with another ticket), which is the first step to resolve them. I hope this save other people who run into this issues some testing time.

These are not my issues, these are the community's issues, and the community is led by people more tech savvy and October experts than I am.

I am not asking anyone to resolve this, but this should get prioritized somewhere (@LukeTowers I thought that you are in charge of prioritizing, apologies if I got the wrong impression), until someone has the time to pick it up and resolve this.
Since these  are overlapping issues, between StaticPages, Translate and the CMS cache, I am sure you are in a better position to dispatch these issues correctly.
Again, until someone has the time to resolve this.

Asking for the creators' opinion/guidance seemed natural to me... 

If I am not welcome to report bugs, just say so, as I have the feeling I am treated as someone who complains, although I am just trying to help.

Again, if the community works differently than what I described above it would be useful to know.

Thanks and happy coding !

**Comment by munxar** [comment]
@ranmichael ok, so first of all, I have snippets working in multilang.
I use this plugin https://octobercms.com/plugin/toughdeveloper-richeditorsnippets to make them work in content blocks. It's a little dusty and needs some manual changes to run with october 420+.
I can make you a fork with the fix in the meanwhile, if you like.

**Comment by LukeTowers** [comment]
@munxar are you able to dig into why exactly the Pages plugin doesn't parse snippets in placeholder richeditors?

**Comment by vannut** [comment]
Hmm this sounds very related to my issue: [Rainlab/Pages-plugin#326](https://github.com/rainlab/pages-plugin/issues/326)

**Comment by munxar** [comment]
afaik it was never implemented on content placeholders, only in the main {% page %} block.
So it's more like a request for an extension not a bug. And for the time being, the above mentioned plugin gives enough tools to make everything work.

**Comment by LukeTowers** [comment]
@vannut This is a feature request for supporting snippets in placeholders as well as the main content area; the issue you're having seems to be different.
