### ISSUE TITLE
Static Pages > Translated pages (files) not deleted when removing static page via the CMS

### ISSUE THREAD

**Issue by ranmichael** [rainlab/translate-plugin#346]
**Build 431
Translate | 1.3.8 | 
Pages | 1.2.18 |** 

Steps to reproduce
- Create a static page (en + fr)
- Add some content and translated content in a second language
- Delete the page
Notice bug:
- The file in the primary language was deleted
- The file in the secondary language still exists

Also, sometimes I see traces of deleted files still exist under the meta/static-pages.yaml
This is a separate issue and need further investigating.

**Comment by munxar** [comment]
I can reproduce this, non default language page is still present under content/static-pages-xy/abc.htm
I'll have a look into it.

**Comment by LukeTowers** [comment]
Thanks @munxar!
