### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by Akif-dev** [rainlab/translate-plugin#347]
Hello, everything working good via this plugin, i want to know if there is any code or way to use two headers to switch between two different languages

for instance: header1 for default language or language1 header2 for second language (RTL) right to left,

headers are ready,i am just looking for code to switch like if/else etc.

any switch for css, because i want to use different fonts for both the langs

Any switch for images between two languages in translate plugin, because i want to use different images for both languages, for instance, in english site different banner, in french site different banner.

thanks

**Comment by munxar** [comment]
I usually name my images like this:
logo_en.jpg, logo_de.jpg etc.
For each locale one. Then in my layout, I use the global variable activeLocale to concat the string like so:
'''php
<img src="{{ ('images/logo_' ~ activeLocale ~ '.jpg')|theme }}">
'''
with the same pattern you could include locale specific css or scripts.

Does that help?

**Comment by Akif-dev** [comment]
Thank you for your quick response, check below, can u modify it to be working for the both the languages having different banners

<img class="item-container" src="{{side_banner1|media}}" alt="1" />

i am using static pages plugin, so banner is uploaded via cms, this code is fine & working for single banner, if u modify this code, will it work for both the languages and we can upload two different banners for both lang ?

thanks

**Comment by munxar** [comment]
i see nothing ;-O

**Comment by Akif-dev** [comment]
pls refresh and check

**Comment by munxar** [comment]
If you do it like that, you'll have to use my (unfinished) multilingual mediafinder. 
https://github.com/munxar/translate-plugin/tree/feature/mlmediafinder
So the user can choose an image for each language. We're working on an integration in the translate plugin right now.
or you wait a few days :-)

**Comment by Akif-dev** [comment]
lets do it in your way, i have uploaded two banner on assets/images folder (named: chatBanner_en & chatBanner_fr

will the below code should work now ? pls advise 

`<img src="{{ ('assets/images/chatBanner_' ~ activeLocale ~ '.jpg')|theme }}">`

**Comment by munxar** [comment]
Upload into the assets/images folder inside your theme (CMS) not media
library and it should work.

Am 06.02.2018 1:37 nachm. schrieb "Akif-dev" <notifications@github.com>:

**Comment by Akif-dev** [comment]
i put images here:

\themes\demo\assets\images

is this fine ?

**Comment by munxar** [comment]
You tell me :-) yes looks good.

Am 06.02.2018 2:10 nachm. schrieb "Akif-dev" <notifications@github.com>:

**Comment by Akif-dev** [comment]
its not working..

/themes/demo/assets/images/chatBanner_.jpg

firebug is showing the above code.. and image is not showing

console is giving error:
Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by Akif-dev** [comment]
when i do the following, it works fine, but its for single language, actually its not recognizing or working with  ~ activeLocale ~ 

<img src="{{ ('assets/images/chatBanner_en.jpg')|theme }}">

**Comment by Akif-dev** [comment]
pls advise

**Comment by munxar** [comment]
You need a localePicker Component in your layout.


Am 06.02.2018 2:44 nachm. schrieb "Akif-dev" <notifications@github.com>:

**Comment by Akif-dev** [comment]
how can i add localePicker Component in my layout ???

**Comment by munxar** [comment]
rtfm: http://octobercms.com/plugin/rainlab-translate
first few lines.

**Comment by Akif-dev** [comment]
yeah i was already seeing this.. let me try

**Comment by Akif-dev** [comment]
awesome man.. its working perfectly.. can i do the same with CSS ? can u write code here for css ?

**Comment by munxar** [comment]
If you like more 'chatty' support, join our slack pls.
https://ocrtobercms.slack.com/
A github issue is not the right place for this questions.

**Comment by Akif-dev** [comment]
will this work?

'<img src="{{ ('assets/css/style_' ~ activeLocale ~ '.css')|theme }}" rel="stylesheet">'

**Comment by Akif-dev** [comment]
sure i will join

**Comment by LukeTowers** [comment]
Join the Slack group here: https://octobercms-slack.herokuapp.com/
