### ISSUE TITLE
date format does not respect locale

### ISSUE THREAD

**Issue by rounce** [rainlab/translate-plugin#350]
I have a multilingual site. All is well when the user is on the English version of the site. For formatting dates, I use format and it always produces the result in English. (because 'locale' => 'en' in config/app.php)
for example
```
$translator = Translator::instance();
$translator->setLocale("ru", false);
dd($user->created_at->format("F y"));
```
results in "May 16"
When i type  'locale' => 'ru' in config/app.php
result always "май 16".

**Comment by rounce** [comment]
For now it is necessary to set the locale by force:
```
$translator = Translator::instance();
$user->created_at->setLocale($translator->getLocale());
```

**Comment by LukeTowers** [comment]
Update your October instance, it already did although support was temporarily broken between Build 420 & Build 433. #338
