### ISSUE TITLE
CMS file translations

### ISSUE THREAD

**Issue by inalto** [rainlab/translate-plugin#352]
It would be nice to have the same filename mechanism for translating the contents for the cms pages.

- cms-page.htm
- cms-page.fr.htm
- cms-page.de.htm

the default language [viewBag] could be used to reference the slugs for all the different locales.
in this way:
- the twig tags would be available together with the translations in the cms page (in content pages aren't )
- seems more general and intuitive
- this fixes the cms page title translation because each translation has own title page on it's own page

Let me know if these are bad ideas :)

**Comment by munxar** [comment]
@inalto I like the idea, in fact a lot of file based cms do it like this, why not stick with this convention.

**Comment by mjauvin** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
