### ISSUE TITLE
Store language preference against RainLab User profile

### ISSUE THREAD

**Issue by joseph-d** [rainlab/translate-plugin#354]
This is meant as a question / enhancement idea.

I think that it would be useful to have the user's language preference persisted to the database as part of the Rainlab.User profile so that if they come back to the site after the session has expired or they log in from another device, they get their preferred language applied straight away.

An added advantage would be that it would be easy to see, at a glance, what percentage distribution of languages were being used by registered users by querying the database.

I would appreciate ideas about how to do this as a workaround right now, but I would also like it to be considered as a possible enhancement to this plugin.

**Comment by LukeTowers** [comment]
Not a bad idea. You would essentially need to add a way to store the preference to the user's record, whether that was modifying the table or creating a relationship that didn't require base table modification. Then, you would have an event listener on rainlab.user.login that would read that value and store it in the session with `setLocale`. As for setting it, you could either have a user preferences page that asks them for their desired locale or you could have something listening for the locale being changed and then save it to the currently logged in user

**Comment by joseph-d** [comment]
Thank you @LukeTowers for describing how it could be done.

Everything you mentioned seems to be straightforward enough for me to attempt myself in my app although I'm not sure how I would listen for the local being changed. I have looked at the code and I can't see anything that suggests an event is being fired that I could listen for.

Can you point me in the right direction of this, or were you in fact suggesting a way in which the Rainlab.Translate plugin itself could be enhanced?

**Comment by LukeTowers** [comment]
Storing it attached to the User specifically is something better handled in your own code or plugin for that express purpose; it's beyond the realm of what the Translate plugin should be doing. As for the event, it's just `locale.changed` fired by the application, so `Event::listen('locale.changed', $myFunction)` should be good: https://github.com/octobercms/library/commit/16f7a286d8c90fb114d3abc9f7a51218c414c1f7

**Comment by joseph-d** [comment]
Thank you @LukeTowers that's perfect!

**Comment by LukeTowers** [comment]
Not a problem @joseph-d! Feel free to make whatever you come up with open source / accessible to the community 😄
