### ISSUE TITLE
ForceRedirect, redirects as 302. 

### ISSUE THREAD

**Issue by CptMeatball** [rainlab/translate-plugin#355]
As the title implies; all redirects are redirected as 302. This is the default for Laravel's `Redirect::to` method. I'm no SEO expert but shouldn't it redirect as 301, so the link value is sent tot the redirect page?

**Comment by CptMeatball** [comment]
It seems to me that a force redirect acts a permanent action, so there at least should be an option to set the status of the redirect.

**Comment by vannut** [comment]
I see an additional config-parameter incoming for [config/config.php](https://github.com/rainlab/translate-plugin/blob/master/config/config.php) :)

**Comment by LukeTowers** [comment]
Could I have some more context on this issue please?

**Comment by vannut** [comment]
At the moment, when you enable forceRedirectUrl the plugin redirects with Laravels [Redirect::to()](https://github.com/rainlab/translate-plugin/blob/61e83fdd09fe4b51ddf0943b2e7ca5ced46e5b8a/components/LocalePicker.php#L115) Which in its turn defaults to using [a 302 as status code](https://laravel.com/api/5.5/Illuminate/Routing/Redirector.html#method_to). 

When you enable `prefixDefaultLocale` (which is the default for the plugin) you automatically discard the use of your root `example.com/` and choose to use `example.com/en`. SEO wise this is a permanent move (we will never use the `/` anymore) so we should return a `301 - permanent` redirect.

At least that is my small understanding of 301/2/7 redirects. Maybe somebody else with more SEO knowledge can weigh in.

Regardless of that, it might be wise to go ahead and substract the redirect status number in the `config.php`.

**Comment by CptMeatball** [comment]
Exactly that.

**Comment by LukeTowers** [comment]
So what are the proposed solutions to this? I'm not sure I see the value in providing a config parameter for this unless there's a reason for them to redirect with a 302 on a request path that will never be used.

**Comment by CptMeatball** [comment]
> unless there's a reason for them to redirect with a 302 on a request path that will never be used.
Not sure who you mean with "them", but the arguments stay the same:
- 302 is for temporary redirects 
- 302 redirects do not carry over the pagerank to the redirection 
- ForceRedirects **forces** the locale to be prefixed to the URL. So users will never hit a unprefixed URL. They'll always be redirected to the prefixed URL.

I think a proposed config parameter, or a component parameter which both default to 302 (to make sure that old installs don't suddenly redirect dfferently) which gives the option to redirect as 301.

**Comment by LukeTowers** [comment]
@CptMeatball I mean is there ever a reason someone would want forceRedirectUrl to 302 redirect?

**Comment by CptMeatball** [comment]
Can't think of any. @vannut ?

One other thing is that the redirects happen to the default, except when there's a locale stored in the session. Not sure if that might give issues for SEO purposes. 🤔

**Comment by mjauvin** [comment]
stale

**Comment by LukeTowers** [comment]
@mjauvin use https://github.com/octoberrain/meta/blob/master/github/saved-replies/abandoned.md and tag abandoned for stale issues please. I'm also looking into setting up StaleBot for OctoberCMS and RainLab.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Comment by get-web** [comment]
How did you solve the problem? It should be 301

**Comment by daftspunk** [comment]
This has been addressed in 2c11ea9029178cdeb69f1d3aa334cc13afbcd861
