### ISSUE TITLE
Localized URLs are purged in StaticPage plugin if they are equal to the URL in default language

### ISSUE THREAD

**Issue by iboved** [rainlab/translate-plugin#357]
Hi!
I have noticed, RainLab.Translate plugin removes localized page URL if it equal URL in default language.

How to reproduce:
First install RainLab.Translate plugin and add at least two active languages. Install RainLab.Pages (Static Pages) plugin. Create page in Static Pages plugin and set the same URL in all languages. After creating the page, URLs in all languages are present (as it should be). But when you save it again and refresh the page, all URLs (except the default URL) will be purged.

Expected behavior:
URLs in all languages should not be deleted even if they are equal.

I have found lines where URLs equal to the default URL are deleted. [Here is the condition](https://github.com/rainlab/translate-plugin/blob/master/behaviors/TranslatablePageUrl.php#L140-L142).

Can you tell me why this behavior is necessary? Is it possible to remove this condition and not violate another functionality?

Thank you in advance.

**Comment by LukeTowers** [comment]
@iboved why should it be retained if it's the same as the default locale?

**Comment by mjauvin** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
