### ISSUE TITLE
Twig pager filter prefix locale when prefixDefaultLocale = false

### ISSUE THREAD

**Issue by Verbat** [rainlab/translate-plugin#358]
I'm  not quite sure if this belongs here or if we need to open an issue at https://github.com/octobercms/october but when setting the prefixDefaultLocale to false the |page filter prefixes the URL with the locale.

I'm running on the latest Edge October build and all Plugins are up to date.
Switching languages works fine and the locale for the default language isn't included as it is intended.

However, when I'm including something like dfd `<a href="{{ 'about'|page }}">About Us</a>` at my partial it should generate (if we have a DE and EN locale)
1. Default language: http://domain.tld/about
2. Secondary language: http://domain.tld/en/about

Instead, it always generates 
1. Default language: http://domain.tld/de/about
2. Secondary language: http://domain.tld/en/about

I know it’s stated at the config file that only the alternate-hreflang component is using the setting but I wanted to make you aware of it and ask if there’s a way to circumvent this behavior.

**Comment by LukeTowers** [comment]
@vannut do you want to look into this?

**Comment by Verbat** [comment]
I think this can be closed. I started with another fresh october install and the behavour was gone. 
There was probably some old code/plugin in place which was the cause of this error. Sorry about this.
