### ISSUE TITLE
How to use setAttributeTranslated() in model's afterSave()?

### ISSUE THREAD

**Issue by hirisov** [rainlab/translate-plugin#359]
I have a model which has a geolocation info field, and a helper_location_city field to store the name of the city. This field is translatable (and indexable), and i want to get the translations during afterSave() of the model from google maps API and set them using setAttributeTranslated() like this eg for 'en' and 'hu' languages ( Modelname.php)

```php
afterSave() {
// fetch data for translations and store them in $city['en'] and $city['hu']

  $langs = ['hu', 'en'];
  foreach ($langs as $lang) {
    $this->setAttributeTranslated('helper_location_city', $city[$lang], $lang);

   // this doesn't work also
   $myModel = Modelname::find($this->id);
   $myModel->estAttributeTranslated('helper_location_city', $city[$lang], $lang);
  }
}
```
but helper_location_city doesnt appear in the model's corresponding row in rainlab_translate_attributes.attribute_data nor in the rainlab_translate_indexes table, and on the frontend i only can see the default language value too.

**Comment by hirisov** [comment]
My mistake, should't try to code at 1am after a couple of beers :) Forgot to add

$myModel->save()

as setAttributeTranslated() just populates the corresponding fields in the model, not saving it. Of course to avoid an infinite loop ( save() calls afterSave() which calls save() again etc) the above code has to be extended to check if it's needed to update the translated attributes at all and the only do it once.

**Comment by LukeTowers** [comment]
@hirisov so your question is resolved then?

**Comment by iboved** [comment]
@hirisov In order to avoid an infinite loop, you can use `$myModel->syncTranslatableAttributes()` instead of `$myModel->save()`.

**Comment by mjauvin** [comment]
closing this, please re-open if this has not been resolved.
