### ISSUE TITLE
BadMethodCallException: Method lang does not exist with get()

### ISSUE THREAD

**Issue by AdrienAdB** [rainlab/translate-plugin#360]
Hi all,
I am developing an API, with routes.php I wish to return all venues (/api/v1/{lang}/venues) or a single venue (/api/v1/{lang}/venues/{id})

Single venue is working fine and translate well.
However multiple venues are not working with ->lang('en') method.

Which method should I use to return multiple translated records?

Here is the error:
<pre>
BadMethodCallException: Method lang does not exist.
in /var/www/XXX/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:96
</pre>

Below is routes.php
<pre>
Route::group(['prefix' => 'api/v1/{lang}/'], function() {

  Route::get('venues', function($lang) {
    $venues = Venue::active()->get()->lang($lang);
    return $venues;
  });

  Route::get('venues/{id}', function($lang, $id) {
    $venues = Venue::with('images', 'img')->find($id)->lang($lang);;
    return $venues;
    }
  )->where('id', '[0-9]+');

}
</pre>

**Comment by munxar** [comment]
Grab an instance of the Translator Service and set it there instead before you do any model query:
```
\RainLab\Translate\Classes\Translator::instance()->setLocale($lang);
```

**Comment by AdrienAdB** [comment]
Thanks, you save my day. It works :-)
