### ISSUE TITLE
Dynamic Parser Syntax - How to use translations?

### ISSUE THREAD

**Issue by datune** [rainlab/translate-plugin#366]
How can we use translations within for example the following declaration:

default.htm layout:
```
....
<body>
{text name="foo" label="labels.translated|_"}Bar{/text}
...
```
How can we have the content of label translated?

**Comment by munxar** [comment]
because it's a backend translation, i'd use a corresponding plugin and use the normal translation strings.
```{text name="foo" label="vendor.plugin::lang.my.label"}Bar{/text}```

the twig filter you uses is for frontend translations.

**Comment by datune** [comment]
@munxar I see, thanks! I thought perhaps there was another way, without the need to add a plugin, since this is the workflow the dynamic parser syntax suggests, but adding a plugin is easy enough.
