### ISSUE TITLE
Translate page's title

### ISSUE THREAD

**Issue by BMCouto** [rainlab/translate-plugin#37]
It's very important to translate page title, makes no sense to change the language and keep page title in another language.

**Comment by mustafa-netlinks** [comment]
Worked!!! Thanks.

**Comment by bbrandtlv** [comment]
I agree with @BMCouto
this is not a solution, this is a fix.
I want to insert title and get option to translate it like any other place. 
Why there it's working, and in the title not?

I dont insert title, but the plugin does, so How can this fix help me?

Please add this to the core.
Tons of thanks.
