### ISSUE TITLE
Plugin wont translate text in bootstrap popover

### ISSUE THREAD

**Issue by Antar74** [rainlab/translate-plugin#377]
So far so good, your plugin works like a charm, but I have several bootstrap popovers associated to an unordered list, the text to be translate resides within the data-content attribute of the "a" html tag. 

The problem is that if I use the "content-block" somehow the popover starts behaving oddly and breaks. :(

Here is the code:

```html
<ul class="nav flex-column lfm-focus text-uppercase">
     <li class="nav-item">
         <a tabindex="0" class="nav-link d-inline-block" data-toggle="popover" data-html="true" data-placement="right"  data-content="
            <h3>Artes plásticas</h3>
            <hr>
            <strong>Lugar</strong>: Buceo<br/>
            <strong>Docentes</strong>: María Noel y María Ana Camino<br/>
            <strong>Actividad</strong>: El alumno toma aquí conciencia de sus posibilidades de expresión, desarrolla su capacidad creadora y va constituyendo una primera cultura artística. El arte es el vehículo del pensamiento; es así que el alumno aprende el dominio de las distintas técnicas, la representación del espacio, el juego con las formas, los colores y las materias.  Espacio privilegiado de socialización, el taller apuesta al desarrollo integral del niño.<br/>">
                Artes plásticas 
        </a>
   </li>
</ul>
```

And so on...

**Comment by munxar** [comment]
@Antar74 what exactly do you mean by odd? Can you post your twig markup?

**Comment by LukeTowers** [comment]
@Antar74 I strongly recommend that you base64 encode HTML if it is to be stored in element attributes and unencode it on use. You are likely to run into all sorts of weird issues if you don't.

**Comment by LukeTowers** [comment]
@Antar74 where does that HTML come from? How does the user modify it currently?

**Comment by Antar74** [comment]
@LukeTowers the html in question I entered it directly on the CMS page code, then extracted it and placed it on a content block file, then installed the Content editor plugin (that enables frontend editing tools) so the final user can edit without touching the content block file itself.

**Comment by LukeTowers** [comment]
That sounds slightly clunky, but whatever works for you I guess. Are you still having issues with this report @Antar74?

**Comment by mjauvin** [comment]
No response. Closing this.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
