### ISSUE TITLE
Firefox opening empty tabs when changing language using ctr+click

### ISSUE THREAD

**Issue by acasar** [rainlab/translate-plugin#378]
When I change the language of a field using ctrl+click, firefox keeps opening new tabs with url ``javascript:;``

![image](https://user-images.githubusercontent.com/6329543/40728041-8668e5fe-6429-11e8-9a44-53fd3c2d67b2.png)

Not sure how to fix this, so I'm opening this issue. If there are any good suggestions, I will prepare a PR.

**Comment by LukeTowers** [comment]
@acasar can we do something like `event.stopImmediatePropagation` or `event.preventDefault` in the handler for a ctrl+click on the language picker widget?
