### ISSUE TITLE
Translate plugin does not save data in RelationController

### ISSUE THREAD

**Issue by roojai** [rainlab/translate-plugin#380]
If I access a backend form for a model in the normal list then my multi-language data will save.

If I access that same form through a RelationController from another model's form, then only the data for the default language will save.

**Comment by LukeTowers** [comment]
Duplicate of #209

**Comment by LukeTowers** [comment]
Fixed by https://github.com/octobercms/october/commit/13d710b161bdf65a19f38f974c259bc4997a162c
