### ISSUE TITLE
Having a "Class web does not exist" Error after installed

### ISSUE THREAD

**Issue by chaskayu** [rainlab/translate-plugin#382]
Hi,

I'm trying to install Translate for my OctoberCMS website. However, after installing, the front-end shows an error if I put the language tag in the URL like: http://www.xxxxxxx.xom/en.

It shows:
Class web does not exist
/var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php line 741

OctoberCMS: CURRENT BUILD: 434
PHPL 7.2.7

Can anyone help on this?

Thank you very much!

**Comment by LukeTowers** [comment]
@chaskayu you are not running the latest version of October / it's dependencies. How did you install / update the project? This error is occurring because the translate plugin is attempting to use the `web` middleware which was only added with the switch to Laravel 5.5 in Build 420+

**Comment by chaskayu** [comment]
@LukeTowers I'm appreciated your prompt reply.
I've checked the current build of running october is 437 and it shows "No new updates were found." when I click "Check for updates". Do I need to dependencies by doing composer update?
Thank you so much.

**Comment by LukeTowers** [comment]
@chaskayu what did you use to install October? You may need to grab the latest version of composer.json from the github repo and then run composer update using that file instead.

**Comment by chaskayu** [comment]
@LukeTowers Thank you so much for your help! It works fine after doing composer update. :)

**Comment by LukeTowers** [comment]
Not a problem, feel free to support me on [Patreon](https://www.patreon.com/luketowers) :)
