### ISSUE TITLE
Changing custom button on translation

### ISSUE THREAD

**Issue by cloudwales** [rainlab/translate-plugin#385]
Hi. Im trying to add a custom switch button to switch the translations from one to the other, but i want it to remove the button that is the current language. 

I.e. I have 2 languages, english and welsh so when english or the default language is selected then only the welsh button is active. When welsh is selected, then only the english button is active. 

Heres what i have already. 
`/components/localepicker/default.htm`
```
{% for code, name in locales %}

{% if activeLocale == 'en' %}
	<a href="#" class="btn btn-sm header-button" data-request="onSwitchLocale" data-request-data="locale: 'cy'">Cymraeg</a>
{% endif %}

{% if activeLocale == 'cy'  %}
	<a href="#" class="btn btn-sm header-button" data-request="onSwitchLocale" data-request-data="locale: 'en'">English</a>
{% endif %}

{% endfor %}
```
With the code above it displays the button twice for some reason. 

Any help or info would be grateful.

**Comment by cloudwales** [comment]
Sorry figured it out...

```
{% for code, name in locales %}
	{% if code != activeLocale %}
		<a href="#" class="btn btn-sm header-button" data-request="onSwitchLocale" data-request-data="locale: '{{ code }}'">{{ name }}</a>
	{% endif %}
{% endfor %}
```

**Comment by LukeTowers** [comment]
Awesome, thanks for the follow up @cloudwales!
