### ISSUE TITLE
URL parameter translation of custom models does not seem to work

### ISSUE THREAD

**Issue by maartenmachiels** [rainlab/translate-plugin#386]
Hi,

I've built a small plugin to manage campaigns / cases, a kind of portfolio-system. 

My goal is to go to the translated version of a campaign upon clicking the language switcher, as per the guidelines outlined here: https://github.com/rainlab/translate-plugin#url-parameter-translation 

In my model, Campaign.php, I have defined:

```
    public $implement = ['RainLab.Translate.Behaviors.TranslatableModel'];
    public $translatable = ['title',[ 'slug', 'index' => true ],'intro','description','briefing','challenge'];

    public static function translateParams($params, $oldLocale, $newLocale) {
        $newParams = $params;
        foreach ($params as $paramName => $paramValue) {
            $records = self::transWhere($paramName, $paramValue, $oldLocale)->first();
            if ($records) {
                $records->translateContext($newLocale);
                $newParams[$paramName] = $records->$paramName;
            }
        }
        return $newParams;
    }
```
Further, in Plugin.php I have defined:

```
    public function boot() {
        Event::listen('translate.localePicker.translateParams', function($page, $params, $oldLocale, $newLocale) {
            if ($page->baseFileName == 'case') {
                return Campaign::translateParams($params, $oldLocale, $newLocale);
            }
        });
}
```
Whatever I do, the slug doesn't get translated. The slug remains in one language, while the language prefix switches over. Example, when I use the language switcher on a campaign / case detail page like below:

´http://localhost:8080/challenge/nl/cases/example-nl´
 
The result of clicking on FR in the language switcher gets ´http://localhost:8080/challenge/fr/cases/example-nl´, instead of ´http://localhost:8080/challenge/fr/cases/example-fr´

And it seems like the event ´translate.localePicker.translateParams´ is never fired. Whatever I enter in the code block below, seems to be ignored:

```
        Event::listen('translate.localePicker.translateParams', function($page, $params, $oldLocale, $newLocale) {
            // nothing here seems to work
        });
```
I'm using ´forceUrl = 1´, the detailpage of a case / campaign resides in a cms page named ´case.htm´, in which the top part looks like this:

```
title = "Case"
url = "/cases/:slug"
layout = "case"
is_hidden = 0

[detail-campaigns]
slug = "{{ :slug }}"

[viewBag]
forceUrl = 1
localeUrl[fr] = "/cases/:slug"
localeUrl[en] = "/cases/:slug"
==
{% component 'detail-campaigns' %}
```
My localeSwitcher looks like this:
```
            <ul class="c-nav__list c-nav__list--language">
                <li class="c-nav__list-item {% if activeLocale == 'nl' %}c-nav__list-item--current active{% endif %}"><a href="#" data-request="onSwitchLocale" data-request-data="locale: 'nl'">NL</a></li>
                <li class="c-nav__list-item {% if activeLocale == 'fr' %}c-nav__list-item--current active{% endif %}"><a href="#" data-request="onSwitchLocale" data-request-data="locale: 'fr'">FR</a></li>
                <li class="c-nav__list-item {% if activeLocale == 'en' %}c-nav__list-item--current active{% endif %}"><a href="#" data-request="onSwitchLocale" data-request-data="locale: 'en'">EN</a></li>
            </ul>
```
Also, I'd like to point out a possible SEO pitfall: the slugs of the default language still work, even if they have a different language prefix. This means that all three of the below urls return a 200 response code instead of a 404. This would imply that it's duplicate content and might be penalized by Google.

```
http://localhost:8080/challenge/nl/cases/example-nl
http://localhost:8080/challenge/fr/cases/example-nl
http://localhost:8080/challenge/en/cases/example-nl
```

Any idea what I might be doing wrong? Thanks in advance for having a look.

**Comment by mariavilaro** [comment]
I think forceUrl should be on the layout as a localePicker property.. I don't know if this is the problem, but I have it like this and it works:

(layout.htm)

[localePicker]
forceUrl = 1

(project.htm)
title = "Project"
url = "/projecte/:slug"
layout = "default"
is_hidden = 0

[viewBag]
localeUrl[es] = "/proyecto/:slug"
localeUrl[en] = "/project/:slug"

**Comment by maartenmachiels** [comment]
Hi Maria, thanks for your answer. I've double checked, but it doens't seem to work for me. The slug still stays in the default language, while the content is being translated...

**Comment by hkan** [comment]
I can confirm. The `localeUrl[lang]` variables work as intended, but `:slug` is always default locale's (English, in my case) slug.

**Comment by mjauvin** [comment]
Can you provide a test procedure with the octoberrain/test-plugin (https://github.com/octoberrain/test-plugin) so that we can try reproducing this?

**Comment by giorgionetg** [comment]
Same problem here... Slug is not translate... I get the same error!

**Comment by maartenmachiels** [comment]
I haven't had the time to create a test environment yet... Can anyone take over?

**Comment by mjauvin** [comment]
I have used this extensively and it is properly working. There must be a mistake in your event handler for `translate.localePicker.translateParams`.

If you can provide proper way to reproduce this with latest plugin and core versions, please re-open this issue.
