### ISSUE TITLE
ImportMessageTest failing.

### ISSUE THREAD

**Issue by HammenWS** [rainlab/translate-plugin#387]
@LukeTowers Your latest build is failing, because of commit 9d411c3.

I think you should move your new code a few lines up ;)
I have add a comment in the commit.

**Comment by acasar** [comment]
@HammenWS you're right - that's my mistake actually. I'm not using imports for new messages and I didn't detect this issue.

The fix is here: https://github.com/rainlab/translate-plugin/pull/388
