### ISSUE TITLE
Obtaining URLs for all available languages for using in "hreflang" meta-tag

### ISSUE THREAD

**Issue by NickolayCh** [rainlab/translate-plugin#389]
It's very useful to add "hreflang" in page head meta-tags (read more at https://support.google.com/webmasters/answer/189077), so adding something like this at the end of the _LocalePicker::onRun()_ component method will be a good feature:

```php
$alternateUrls = [];
foreach($this->locales as $locale => $label) {
	$alternateUrls[$locale] = $locale == $this->activeLocale ? $this->controller->currentPageUrl() : url('/').'/'.$locale.$this->makeLocaleUrlFromPage($locale);
}
$this->page['alternateUrls'] = $alternateUrls;
```

**Comment by munxar** [comment]
there is already a alternateHrefLangElements component in the plugin. just place it in the head element and your done.

**Comment by NickolayCh** [comment]
Sorry, missed it. Thanks!
