### ISSUE TITLE
String length cause duplication 

### ISSUE THREAD

**Issue by asystemg** [rainlab/translate-plugin#390]
Hello,
Can somebody please help me. Because i'm trying to fix that from couple of days. Without any success. 
I have theme field defined in fields.yaml.
`test_content:
            tab: Test
            label: Test
            type: richeditor
            default:
            span: right`
And in template looks like
`<div id="test">{{ this.theme.test_content |_ }}</div>`
The problem is that if field contains more than 250 symbols when i try to translate it. It just duplicate it in admin area and no translation appear on front.
Looks like 
![prob](https://user-images.githubusercontent.com/41574180/43072573-2d9f0cfc-8e7f-11e8-9616-293655485d36.jpg)
Any help will be appreciated.

**Comment by munxar** [comment]
you use content as the code for message translation.
this code usually is used like this:
{{ 'my.code.title' | _ }}
the translation messages code is set as a string in the db, an if you feed it some long content it just can't store it's full length and will truncate to it to 250 chars and that is why there is no translation happening.

If you have long string, I would use content placeholders. they are translatable out of the box.

**Comment by asystemg** [comment]
Firstly, thank you for the fast answer. 
If i understand you correctly there is no way to use theme settings and  and make things work correctly? I'm asking because theme settings management is must have in this project.
Best Regards.

**Comment by munxar** [comment]
try to explain what you want to do, and why. prob there is a better way than the theme settings.
there are about 4 ways other than system setting that could work ....

**Comment by asystemg** [comment]
Thank you.
So:
The idea behind theme settings is that a client can manage and create new text and content dynamically on pages from admin page. We are using theme settings forms because is easy for client to work with them. I'm open for new proposals on how things should be done. If you have any. That would be great. Because I'm new to ocotobercms. And still learning. The flow of the system.
Best regards.

**Comment by munxar** [comment]
1. check out the static pages plugin. it does what you want to do.
2. for more complex stuff make a custom plugin, so you have the full backend power (w. model 
 translations working)
3. good resource is the october cms docs: http://octobercms.com/docs
and the wonderful screencasts http://octobercms.com/support/topic/screencast
and this how to series http://octobercms.com/support/articles/tutorials.

I'd suggest you check out this first:
- http://octobercms.com/blog/post/static-pages-content-blocks-and-placeholders
- http://octobercms.com/blog/post/building-client-friendly-websites

join the friendly slack community: https://octobercms.slack.com

please close this 'issue' if you got what you need.

**Comment by asystemg** [comment]
Thank you so much for all of this. You are great 👍

**Comment by LukeTowers** [comment]
I agree, thanks for the help @munxar!
