### ISSUE TITLE
Is it possible to translate contents from canvas?

### ISSUE THREAD

**Issue by tijosfx** [rainlab/translate-plugin#392]
Hi, 
I want to translate some text inside a canvas/jquery file, can you help me to do this?
Please see the screenshot:
http://prntscr.com/keya9k
http://prntscr.com/key7uf

![screencapture](https://user-images.githubusercontent.com/9552889/43687764-c21fc8ca-98f8-11e8-95e4-b43414ed4c73.png)

Thanks

**Comment by LukeTowers** [comment]
The easiest way to do this would probably be to declare them as globaly accessible variables in your theme that the JS file then looks at or pass them to a constructor of sorts. The key thing is to have some JS that is rendered by your theme to be used by the JS that is in a separate file. 

Example:
```twig
<script>
    window[canvasLangKeys] = {
        reserve: '{{ 'canvas.reserve' | _ }}',
        presale: '{{ 'canvas.presale' | _ }}'
    };
</script>
```

**Comment by tijosfx** [comment]
Thank you,
I dont have much experince on this. What steps that I follow to display the
translate contents? Canyou please clarify?

**Comment by LukeTowers** [comment]
@tijosfx you're going to need a solid understanding of JS to accomplish what you are trying to do, unless you put your entire JS script in an inline `<script>` tag and then just do the translation there with the regular `{{ 'lang.key' | _ }}` syntax.
