### ISSUE TITLE
How to translate models in frontend?

### ISSUE THREAD

**Issue by KristlyDsena** [rainlab/translate-plugin#395]
default.htm
```

     {% for agentcom in agentcom %}
         {{agentcom.agent_title }}
        {% for image in agentcom.agentsteps %}
 
             <a href="{{ image.path}}">
             <img src="{{ image.thumb(auto,auto) }}" class="responsive">
             </a>
             <br>
 
         {% endfor %}
         <p>{{agentcom.agent_content|_ }}</p>
         <br>
     {% endfor %}
 
 {{ agentcom.render|raw }}
```
in backend 

![Uploading Screenshot 2018-08-08_11-59-46.png…](translate messages)

![Uploading Screenshot 2018-08-08_12-00-49.png…](CMS page where locale picker is used)

**Comment by munxar** [comment]
what is agentcom? A Model?
If yes, use model translation for it.

right now you are 'misusing' the themes message translation by passing a variables content (agentcom.agent_content) as the code. usually the code is something short like 'blog.title' and there is a db constrain to limit it to 255 chars.

**Comment by mjauvin** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
