### ISSUE TITLE
Repeating Translate Message issue

### ISSUE THREAD

**Issue by tijosfx** [rainlab/translate-plugin#397]
Some Translate Messages repeating multiple times, (once after delete row, still getting this issue) how to fix this.
Please check the screen: 

http://prntscr.com/kgbigx
http://prntscr.com/kgbkvz

code: http://prntscr.com/kgbla2

Thanks

**Comment by LukeTowers** [comment]
Don't translate messages like that. Just use a key instead and put your long messages in the translation table instead. I.e. instead of 
```twig
{{ 'Really long text that goes on and on here' | _ }}
```
do 
```twig
{{ 'some.key' | _ }}
```
and then you can put your really long text in the translation table instead.
