### ISSUE TITLE
How to get translatable date formats?

### ISSUE THREAD

**Issue by disvst** [rainlab/translate-plugin#400]
Hi,

I would like different date formats, to use in some components and Rainlab Blog plugin. 

A simple question: how is it possible to get translatable date formats (one per language)? In twig with default `|date` filter? Maybe another method?

I have seen some closed issues about dates translations it but I did't find a clue about formats... I also #checked the rainlab plugin, monthes are translated for some languages but does't seem to allow different formats.

My build number is 437.

Thanks

**Comment by vannut** [comment]
It depends a little bit on what ou exactly mean with  
> to get translatable date formats (one per language)

If this means you want the month names to be translated, but having the same structure (always eg date month year): I believe this is happening by default. 

If it means you want different structures for different locales; eg `dd/mm/yy` for Dutch and `mm-dd-yyy y` for English, as far as i know, You'll need to add some logic by means of a plugin. 
Firstly a simple plugin which registers a settings page in the backend in which you can register the different formats for the different locales. 
Secondly write [a custom twig filter](https://octobercms.com/docs/plugin/registration#extending-twig) which takes the date as a parameter, looks up the locale, converts the date to the desired format and returns it. 

As I type this, it might be a cool extension of the translate-plugin. But then we need to somehow overwrite the default `|date`.

**Comment by disvst** [comment]
Many thanks @vannut 

> If this means you want the month names to be translated, but having the same structure (always eg date month year): I believe this is happening by default

I get this behavior with `|date`in Rainlab Blog but not for custom components.

> If it means you want different structures for different locales

Yes, you got it right, its exactly what I would like. I will try a custom twig filter. 

> As I type this, it might be a cool extension of the translate-plugin

Yes, It would be great!

**Comment by LukeTowers** [comment]
@vannut no need to overwrite it, just add your own `| localizedDate` filter :)

**Comment by vannut** [comment]
That's off course always possible; but then the components which use the standard `| data` won't get a trans-formatting
