### ISSUE TITLE
Bug repeatable fields 

### ISSUE THREAD

**Issue by uitlaber** [rainlab/translate-plugin#404]
I have field "name" and field in repeatable "name".
Plugin added lang switcher to all fields.

**Comment by mskraban** [comment]
I have the same issue. Plugin keeps duplicating some entry's on "scan for new messages".

**Comment by mjauvin** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
