### ISSUE TITLE
Is it possible (or would it be easily fixable) to select concrete translations on demand in my frontend twig templates?

### ISSUE THREAD

**Issue by mrbohnke** [rainlab/translate-plugin#405]
An example is better if I'm not explaining myself well, is there some mechanism like the fictional one I use for the 'greeting' message for "on demand" translation?

{{ 'greeting'|_locale.code('en') }}, my name is {{ name }}.
Goodbye {{ yourname }}.

Sorry if it is widely known/explained, but I feel like I've been looking everywhere and could find an answer.

Thank you!

**Comment by joelamltc** [comment]
Same question here.

With more explanation, we want to have language specific translation on translate message.

e.g.  Let say we have two translation for message 'hello'.
```
# Chinese
zh:
    hello: '你好！'

# English
en:
    hello: 'Hello!'
```

We want to be like no matter what the current language is, we always want to output the english translation of 'hello'.

Conceptual idea:
`{{ 'hello'|_({ code: 'en' }) }}`

Cheers!

**Comment by LukeTowers** [comment]
@joelamltc could you explain more why that would be necessary?

**Comment by joelamltc** [comment]
@LukeTowers 
The idea comes from Laravel  [`trans()`](https://laravel.com/docs/5.6/helpers#method-trans) function, or the function comes with the [`rainlab\translate-plugin`](https://github.com/rainlab/translate-plugin).

In the above we are able to do language specific translation:
Laravel: 
```php
  /**
    * Get the translation for the given key.
    *
    * @param  string  $key
    * @param  array   $replace
    * @param  string|null  $locale
    * @param  bool  $fallback
    * @return string|array|null
    */
    public function get($key, array $replace = [], $locale = null, $fallback = true)
```

rainlab\translate-plugin:
```php
$user = User::first();

// Outputs the name in the default language
echo $user->name;

$user->translateContext('fr');

// Outputs the name in French
echo $user->name;

// Outputs the name in French
echo $user->lang('fr')->name;

// In Twig
{{ user.lang('fr').name }}
```

We hope that the message translation can be do this as well.

In my case, I was using the language specific translation in form `input[type="checkbox|radio|etc"] ` value for consisting the data to sending out.

Cheers!

**Comment by munxar** [comment]
I like the concept, but would extend it that way:
```php
{{ 'hello'|_({ my_param: 'test' }, 'en') }}
```
Why? If someone (and I'm someone) has written translations strings with a argument named 'code' in the past, we would break their translations.

extending the twig functions is easy:

```php
    public function translateString($string, $params = [], $locale = null)
    {
       // here comes the fun part, Message::trans has no locale switch
        return Message::trans($string, $params, $locale);
    }

    public function translatePlural($string, $count = 0, $params = [], $locale = null)
    {
       // same here
        return Lang::choice(Message::trans($string, $params, $locale), $count, $params);
    }
```

All we need to do think of is how we implement Message::trans to handle the locale argument.
```php
    public static function trans($messageId, $params = [], $locale = null)
    {
        // todo: handle locale switch

        $msg = static::get($messageId);

        $params = array_build($params, function($key, $value){
            return [':'.$key, $value];
        });

        $msg = strtr($msg, $params);

        return $msg;
    }
```
Any Ideas?

**Comment by joelamltc** [comment]
@munxar Sure!
Looking at this tho.
```php
   /**
     * Gets a message for a given locale, or the default.
     * @param  string $locale
     * @return string
     */
    public function forLocale($locale = null, $default = null)
    {
        if ($locale === null) {
            $locale = self::DEFAULT_LOCALE;
        }

        if (array_key_exists($locale, $this->message_data)) {
            return $this->message_data[$locale];
        }

        return $default;
    }
```

**Comment by munxar** [comment]
@joelamltc I had to extend the *get* method, but I . think it works.
can anyone test my PR please: https://github.com/rainlab/translate-plugin/pull/406

**Comment by mrbohnke** [comment]
> @joelamltc could you explain more why that would be necessary?

@LukeTowers Hi, for context, in *my* specific case, we are trying to achieve an XML feed that includes translations for every piece of information (instead of seven feeds, one for each of the language we work with).

**Comment by munxar** [comment]
@mrbohnke in your case I would use the Message model directly. It will give you all message translations.

**Comment by joelamltc** [comment]
@LukeTowers sorry, any follow up?

**Comment by LukeTowers** [comment]
@munxar anything that I need to action here?

**Comment by munxar** [comment]
@LukeTowers No, I gave @mrbohnke a possible solution for a message dump and made a PR (that works for me) to extend the message translation.
As long as @joelamltc can't give me more details in what doesn't work for him, I'm not willing to invest more time in this, sorry...

**Comment by LukeTowers** [comment]
Alright, well someone ping me if I'm needed.

**Comment by mjauvin** [comment]
@munxar will be closing this, it has been stale for too long.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
