### ISSUE TITLE
Translate markdown (.md) content files

### ISSUE THREAD

**Issue by nicolas-giuristante** [rainlab/translate-plugin#407]
Not sure if it's by design or a bug:

The plugin does not seem to load .md nor .txt the same way it does with .htm content files.

_Following tests: if the .htm exist, the other (.md|.txt) does not and vice/versa._

### Test 1
Using this in page `{% content 'home/intro' %}`
If `content/home/intro.XX.htm` exist, it loads, of course.
If `content/home/intro.XX.md` exist, it does not load. Saying the file could not be found.
If I'm not mistaken, this is by design as OctoberCMS loads htm files by default if no extension are declared.

### Test 2
Using this in page `{% content 'home/intro.md' %}`
If `content/home/intro.XX.htm` exist, it does not load, of course.
If `content/home/intro.XX.md` exist, it still does not load. Saying the file could not be found.
The file should be loaded and processed unless this feature is not implanted.

I wish this was working. A markdown block of text is way less intimidating for clients than a bunch of html tags opening and closing all around.

**Comment by LukeTowers** [comment]
@NicolasGiuristante this feature probably isn't implemented, feel free to do so yourself :)

**Comment by NicolasGiuristante** [comment]
I do not have the necessary skills to implement such a feature unfortunately.

Feel free to close this issue or let it open for anyone who would be able/willing to do it.

Sorry for the (very) late reply.

**Comment by LukeTowers** [comment]
Anyone can do anything so long as they have the time to learn :) I'll leave it open for another month for now.

**Comment by mjauvin** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Comment by NicolasGiuristante** [comment]
To be honest, I'd still like to see this implemented at some point. I am not a developer and cannot build it myself. I don't **expect** anyone to build it "just like that", so I ended up using `htm` files and never looked back. But remember that these are the kind of small limitations that make it less comfortable for the end-clients. Markdown is more pleasant on the eye for non-technical folks.

By all means, do not reopen it if you judge it to be useless. It is, like I said, a small issue. (:

**Comment by mjauvin** [comment]
I don't know if this was fixed at some point, but it works fine for me.
