### ISSUE TITLE
Please Help & Guide me "activeLocale" 

### ISSUE THREAD

**Issue by Akif-dev** [rainlab/translate-plugin#412]
Hi,

i have site having two languages, i am using this plugin, and i want to display two menus, one for first language and the other one for 2nd language, menus i am using custom developed.

i want to know the way to differentiate "div->ul->li->a" codes to use on both URLs via using activeLocale

i displayed the images on both site by the following code and it worked.

```
<img src="{{ ('assets/css/style_' ~ activeLocale ~ '.css')|theme }}" rel="stylesheet">
<img src="{{ ('assets/images/chatBanner_' ~ activeLocale ~ '.jpg')|theme }}">
```
how can i use "activeLocale" or any other trick to use div codings and that sits on both language site.

any if/else condition, switch condition, or via localization attribute etc.

for instance my code is:

```
code for 1st site OR 1st language localization attribute (en) :
<div>
 <ul>
  <li><a href="#">Link 1</a></li>
</ul>
</div>

code for 2nd site OR 2nd language localization attribute (fr):
<div>
 <ul>
  <li><a href="#">Link 1</a></li>
</ul>
</div>
```
and both of the codes will be used on same page, just let me know the way to set the code so that they work on their own languages sites

please let me know if i am not clear

**Comment by Akif-dev** [comment]
`Hi,

i have site having two languages, i am using this plugin, and i want to display two menus, one for first language and the other one for 2nd language, menus i am using custom developed.

i want to know the way to differentiate "div->ul->li->a" codes to use on both URLs via using activeLocale

i displayed the images on both site by the following code and it worked.

<img src="{{ ('assets/css/style_' ~ activeLocale ~ '.css')|theme }}" rel="stylesheet">
<img src="{{ ('assets/images/chatBanner_' ~ activeLocale ~ '.jpg')|theme }}">

how can i use "activeLocale" or any other trick to use div codings and that sits on both language site.

any if/else condition, switch condition etc.

please let me know if i am not clear`

**Comment by LukeTowers** [comment]
@Akif-dev don't cross post please. @munxar if you can answer his question in whatever repo makes more sense that would be awesome.

**Comment by vannut** [comment]
Don't know if I exactly understand your problem, but:

The variable `activeLocale` is only available if you have the `LocalePicker` component somewhere in your project. [It gets initiated here](https://github.com/rainlab/translate-plugin/blob/master/components/LocalePicker.php#L71)

So If you would want that var without dropping the localepicker somewhere, you'll have to insert the logic somewhere els. Eg in an own made plugin or the php section of the layout. 

```
use RainLab\Translate\Classes\Translator 

$translator = Translator::instance();
$this->page['activeLocale'] = $translator->getLocale();
```

To use the activeLocale to load something conditionally, just use it in an twig if-else statement. 

```
{% if activeLocale == 'en' %}
   Your englisch divs/nav
{% elseif activeLocale == 'fr' %}
   Your French nav.
{% endif %}
```

It might be better to introduce a partial per locale to keep the code clear:

```
{% partial 'my_nav_' ~ activeLocale ~ '.htm' %}
```

**Comment by LukeTowers** [comment]
@vannut thanks for responding! @munxar's solution is in the cross posted issue: https://github.com/rainlab/pages-plugin/issues/359#issuecomment-427472573
