### ISSUE TITLE
Translations are recreated all-the-time

### ISSUE THREAD

**Issue by moetheone** [rainlab/translate-plugin#415]
Hello,
i habe a strange problem.
After inserting the markup in my sites the to-translate-snippets are "found" by the plugin over and over again. After viewing the Frontend the snippet is recreated.
I doubble-checked the syntax of the markup, but i can´t find the problem causing this.
Strangeley just some of my snippets are affected.
Thx for any tips/help!
Moe

**Comment by mgollmer** [comment]
Hi There,

yeah i would be interested in this one too. I've the same error.
The same translatable Content repeatedly appears over and over again.

Regards
Michael

**Comment by munxar** [comment]
can you be more precise and give an example, I really don't get what you mean.
Where are the translations recreated? backend, frontend?

**Comment by mgollmer** [comment]
Hello, 

there are more then one entry for the same text, everytime I scan the content for new translatable phrases. Unfortunately I can't  take a screenshot right now. =(

**Comment by moetheone** [comment]
Hi there!
I solved it.
What i did was shorten the tags and save a translation also for default language. So maybe it was the length og the markup-snippet.
Thx for your assistance anyway!
Moe
