### ISSUE TITLE
TranslatableModel scopeTransWhere operator bug

### ISSUE THREAD

**Issue by aly-eldegwy** [rainlab/translate-plugin#418]
In the TranslatableModel, the scopeTransWhere now supports the $operator, but in line 42, the $operator missed to be sent to the where() function of the table model. So, the result of the search is not the same when changing the language. As a suggestion, the fix may be by sending the $operator to the where like that :
     $q->where($this->model->getTable().'.'.$index, $operator, $value); // line 42

**Comment by LukeTowers** [comment]
@aly-eldegwy please provide a PR with your proposed fix along with a detailed replication of the original issue along with how the original issue is fixed by your proposed fix.

**Comment by mjauvin** [comment]
resolved by #433
