### ISSUE TITLE
Assign languages to users

### ISSUE THREAD

**Issue by adamo** [rainlab/translate-plugin#424]
Hello.
Is there a way to assign a language to a user (editor) so he can only translate content into this language?

For example an admin adds site "contact" a user **editor 1** sees the page and can translate it into language (for example) '_polish_'
the user **editor 2** sees the same page but cannot edit in the language '_polish_' but only '_german_'

I guess this is a similar issue to this one https://github.com/rainlab/translate-plugin/issues/202 with more options.

Any suggestions to a possible solution or workaround would be helpful.

**Comment by munxar** [comment]
@adamo you can add a relation table for x_y_user_language into your plugin and add a 
User belongToMany Languages relation via Model::extend.

regarding the languages that a user can see depending on this setting: You must somehow replace the listAvailable() method in the Locale model to return only languages allowed by the current user.
no clue how to do that, but you could try Model::extend afterLoaded and tinker with the data?

**Comment by LukeTowers** [comment]
You could extend the available languages by hooking into the model's afterBoot event: https://octobercms.com/docs/api/model/afterBoot

```php
Locale::extend(function ($model) {
    $model->bindEvent('model.afterFetch', function () use ($model) {
        $model->local

**Comment by adamo** [comment]
Thank you @munxar for pointing me in the direction. When I have something viable I'll be posting it here or asking further questions ;)

**Comment by mjauvin** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
