### ISSUE TITLE
Translated attributes are not display correctly when switch default locale configuration.

### ISSUE THREAD

**Issue by joelamltc** [rainlab/translate-plugin#427]
I used this plugin to get my website to be i18n ready and I love this plugin. However, this is always holding me back. 

The situation is I have had created two languages in the backend Chinese and English (default). I saved the translated attributes in the form view. All are working fine but once I switch the default language in the backend config and come back into the form view. I noticed all things gone wrong. All chinese translated attributes became english and english translated attributes are gone.

It is related to #231, but it seems the discussion is ended. So I bring it up again.

OctoberCMS build 437
Translate Plugin 1.4.0

**Comment by LukeTowers** [comment]
@joelamltc please comment on that issue instead and I'll reopen it. Provide detailed step-by step instructions to replicate the bug, ideally with GIFs showing what's happening for each step of the process.
