### ISSUE TITLE
TranslatableModel returns default language if actual does not exists

### ISSUE THREAD

**Issue by Rike-cz** [rainlab/translate-plugin#430]
Little question - is fallback to default language in case when current language model does not exists intentional behavior? I mean this line: https://github.com/rainlab/translate-plugin/blob/319ab8e26022f440dc0fa4220025e9e3de67220c/behaviors/TranslatableModel.php#L42

**Comment by mjauvin** [comment]
@Rike-cz is there a link with what's being reported in #418 ? It's referencing the same line number (42).

**Comment by Rike-cz** [comment]
This one makes problem with #429 issue. That issue causes that each language receive the same slug (index), but only current language has model data. When you switch frontend to another language, you can see that same slug, but content is only in one language. So fixing #429 may make solution, BUT what happens with `where + orWhere` query (lines 42 and 43), when index for base table and index for translation tables is the same?
And is any reason to not do this scope like this:
```$query->select($this->model->getTable().'.*');
if($locale == $this->translatableDefault) { // I can make bypass for default lang when joining is not needed...
    $query->where($this->model->getTable().'.'.$index, $operator, $value);
} else {
    $query->where(function($q) use ($index, $value, $operator) {
        $q
            ->where('rainlab_translate_indexes.item', $index)
            ->where('rainlab_translate_indexes.value', $operator, $value);
    });
    $query->leftJoin('rainlab_translate_indexes', function($join) use ($locale) {
        $join
            ->on(Db::raw(DbDongle::cast($this->model->getQualifiedKeyName(), 'TEXT')), '=', 'rainlab_translate_indexes.model_id')
            ->where('rainlab_translate_indexes.model_type', '=', get_class($this->model))
            ->where('rainlab_translate_indexes.locale', '=', $locale)
        ;
    });
}
```

Yes, #418 is also bug, but not this problem.

**Comment by mjauvin** [comment]
@Rike-cz I suggest submitting a PR for this solution, we can then discuss it further and test your solution.

**Comment by Rike-cz** [comment]
@mjauvin If you think #418, it's easy. But in case #429, which is very important, it's more about JS and out of my current skills :-(

**Comment by mjauvin** [comment]
@rike-cz is this still a problem? #418 & #429 have both been resolved.

**Comment by Rike-cz** [comment]
@mjauvin Yes, that issues are resolved, great!
My first question was: _Is fallback to default language in case when current language model does not exists intentional behavior?_ And answer is: **Yes, it is.** Because Pages plugin do the same when current language version was not created. So we can close that.
