### ISSUE TITLE
how to translate a string in php in the frontend?

### ISSUE THREAD

**Issue by simon511000** [rainlab/translate-plugin#434]
```php
<?php
function onStart(){
  $hello = functionThatTranslates("bonjour");
}
```

**Comment by munxar** [comment]
@simon511000 
You can use the Message model like this:
```php
<?php
use \RainLab\Translate\Models\Message;

function onStart() {
    $hello = Message::get('bonjour');
}

```

note: in order that the translation code 'bonjour' is found when e.g. you run 'Scan for Messages' in the translate backend setting, the page must be called once to run the code.

**Comment by simon511000** [comment]
Thank you very very much :D
