### ISSUE TITLE
Duplicated Translate Messages

### ISSUE THREAD

**Issue by rejuvenatedigital** [rainlab/translate-plugin#446]
Hi,

Apologies if this has already been covered but I'm experiencing a bug with Translate messages where I'm getting duplicate entries of messages.

I believe this is because my database charset is utf8mb4 so my default string length is 191, but when the message code is created it's truncated to 250 characters before being saved and therefore doesn't match any existing entries.

Please let me know if you need any more info.

Many thanks.

**Comment by mjauvin** [comment]
Please, see #443
