### ISSUE TITLE
staticPage: Translated placeholders don't get saved without main content

### ISSUE THREAD

**Issue by patrick-durrer** [rainlab/translate-plugin#447]
### Expected behaviour
I create a new site in the static pages plugin and assign it to a layout with a placeholder. In the backend edit view I get two tabs: one for the main content and one for the placeholder.

![grafik](https://user-images.githubusercontent.com/15232963/53110807-1c436700-353c-11e9-9a4e-b2fe5274633d.png)

Now I translate the placeholder without entering something for the main-content and click the save button. I expect the content for the placeholder gets saved.

### Actual behavior
The content of the placeholder doesn't get saved.

### Information about the Issue
Because the main content is not translated, the plugin does not create an additional file for the locale specific content. So the content of the placeholder field can not be saved anywhere.

### Steps to reproduce the behavior

1. Install the Static Pages Plugin and the Translate Plugin
1. Add at minimum two languages to the Translate Plugin
1. Add `{% placeholder MyPlaceHolder %}` to a layout
1. Add StaticPage component to this layout
1. Create a new Static Page using the above layout
1. Change to the MyPlaceHolder tab, enter some content and click save

**Comment by w20k** [comment]
@munxar @mjauvin could you answer this one? Is it a bug?

**Comment by LukeTowers** [comment]
or @osmanzeki?

**Comment by osmanzeki** [comment]
I haven't used the Static Pages plugin as I always rely on a database so I am not familiar with this issue sadly.

**Comment by mjauvin** [comment]
Maybe the translate plugin should use default language content when placeholder is not null and content is null before saving?

**Comment by mjauvin** [comment]
Interesting find: if you hold CTRL when clicking on the locale for the placeholder (which will change locale for all translatable fields on the page), the content DOES get saved properly, even if the main content is empty...

I'll keep digging to find a fix for this.
