### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by sophie-vdv** [rainlab/translate-plugin#449]
Hi,
I made the plugin update few days ago since than I have an error on my staging environment.
Can anybody advice me how to fix this issue?

/plugins/rainlab/translate/behaviors/TranslatablePage.php line 55
Invalid argument supplied for foreach()

![screenshot 2019-02-26 at 09 11 46](https://user-images.githubusercontent.com/7673083/53410603-95234280-39c4-11e9-9381-45fede0c903d.png)

**Comment by munxar** [comment]
I think your october core and rainlab/translate-plugin are out of sync. 
how do you install the translate plugin? manually or with a dependency in the composer.json?

**Comment by mjauvin** [comment]
You need to update the core octobercms as well. What version of core and
the plugin do you have?

--
Marc

**Comment by sophie-vdv** [comment]
@munxar @mjauvin 
it was install by the cms interface 
translate-plugin 1.4.5
octobercms build 443

**Comment by mjauvin** [comment]
@LukeTowers this can be closed as invalid (core is not up2date)
