### ISSUE TITLE
Locale picker to redirect on custom link

### ISSUE THREAD

**Issue by zlobec** [rainlab/translate-plugin#451]
I need to have different CMS pages (layout, grid, etc) for each language variation. The default onSwitchLocale keeps the page on the same page. I need it to switch the locale and to a different url and CMS page.

I added the href second post value to the HTML:
```
<a href="#" rel="next" data-request="onSwitchLocale" data-request-data="locale: 'en', href: '{{ 'en/page1'|page }}'">{{ 'English'|_ }}</a>
<a href="#" rel="next" data-request="onSwitchLocale" data-request-data="locale: 'de', href: '{{ 'de/index'|page }}'">{{ 'German'|_ }}</a>
```
And changed the onSwitchLocale to include the $href parameter:
```
        // check if request has href parameter
        if ($href = post('href')) {
          // parameter is set, set redirect from href
          $pageUrl = $href;

        } else {
          // default url creation
          $pageUrl = $this->makeLocaleUrlFromPage($locale);

          // preserve the query string, if it exists
          $query = http_build_query(request()->query());
          $pageUrl = $query ? $pageUrl . '?' . $query : $pageUrl;
        }
```
Is this a correct way to do that? Or is there a simpler way to force the change of locale when CMS page is loaded?

**Comment by mjauvin** [comment]
@zlobec did you try this?

https://github.com/rainlab/translate-plugin#url-translation

**Comment by zlobec** [comment]
@mjauvin URL translation does not come in hand,  because the translated page in the second language is not the same CMS page, but different.... example the english page is located at en/page1 and german page located at de/index...

**Comment by mjauvin** [comment]
Ok, this is quite unusual as you usually want the same content but translate the relevant parts... otherwise you maintain many more files for what should essentially be the same page.

I guess the way you were doing it would be fine in this context.

**Comment by zlobec** [comment]
The idea is not to have identical content, some different components on each language page. Thanks Marc!
