### ISSUE TITLE
Translation memory support? (XLIFF, PO)

### ISSUE THREAD

**Issue by hirisov** [rainlab/translate-plugin#455]
Hello,

we have a project where the client want to use an external tranlation service to handle the translations. These services typically uses XLIFF or PO formats. Are there any plans to improve the Translate plugin to support import/export from/to these formats? Ideally they would want to handle all the translations (so model, template string,s and static pages content) with such systems. I think it would be a huge bonus if OctoberCMS and Translate would support such professional workflows and formats for i18n. 
We can build some custom solutions based on the rainlab_translate_messages and rainlab_translate_attributes tables and include content from static pages module meta and content directories, but if others would find this feature useful we would be also open to donate a unified, general solution instead.

thanks, Gabor

**Comment by mjauvin** [comment]
There is no current plan I am aware of. Please, do submit a PR if you have such a solution, it would be a welcome addition.

**Comment by mjauvin** [comment]
I wonder if this could be used along with Message Import/Export:

https://www.npmjs.com/package/po-csv

**Comment by w20k** [comment]
@mjauvin I think we'd have to add converter to importer/exporter routine ;)

**Comment by hirisov** [comment]
I created a bounty for this, please consider supporting this development:

https://www.bountysource.com/issues/71668207-translation-memory-support-xliff-po

**Comment by LukeTowers** [comment]
@hirisov there's no bounty posted on the issue. Feel free to post one or offer to pay directly for the feature yourself.

**Comment by daftspunk** [comment]
This has been addressed in the v3.1 release. A standard JSON format is now used and should be interoperable with most, if not all, systems. It can be observed when importing and exporting in JSON format, e.g.

```
{"default":"translated"}
```

- Link to the [upgrade guide](https://github.com/rainlab/translate-plugin/blob/master/UPGRADE.md)
- Link to [multisite documentation](https://docs.octobercms.com/3.x/cms/resources/multisite.html)

If you still need help, feel free to get in touch with the support desk for assistance: https://octobercms.com/contact

Thank you
