### ISSUE TITLE
How to translate 404 page?

### ISSUE THREAD

**Issue by hirisov** [rainlab/translate-plugin#456]
I created a pages/404.htm which appears when from a plugin component i return 404 like:

              $this->setStatusCode(404);
              return $this->controller->run('404');

this is the preferred method AFAIK. 

My site uses multiple languages, so i thought if i create a 

pages/404.hu.htm

then this should appear when i try a non existing URL with "hu" locale, like

/hu/my-component-page/non-existing-slug

which will produce the above 404 answer return. But i still see the content of 404.htm in this case, not the localized 404.hu.htm

Is there any way to return the appropriate version of this 404 file?

**Comment by mjauvin** [comment]
Maybe you could pass the current locale to your controller using the LocaleSwitcher component from Rainlab Translate?

**Comment by LukeTowers** [comment]
I would recommend just using the Message translation feature instead of completely separate files, that would be the simplest approach. https://github.com/rainlab/translate-plugin#message-translation
