### ISSUE TITLE
URL slug not getting translated 

### ISSUE THREAD

**Issue by andreacelery** [rainlab/translate-plugin#457]
Using my own custom model. My slug does not get translated on any of the pages.  The rest of the URL gets translated as normal, but the slug stays the default value.
My model (Post.php)  looks like this

    public $implement = ['RainLab.Translate.Behaviors.TranslatableModel'];

    public $translatable = ['title',
                            'content',
                            ['slug', 'index' => true]
                            ];

    public static function translateParams($params, $oldLocale, $newLocale) {
        $newParams = $params;
        foreach ($params as $paramName => $paramValue) {
            $records = self::transWhere($paramName, $paramValue, $oldLocale)->first();
            if ($records) {
                $records->translateContext($newLocale);
                $newParams[$paramName] = $records->$paramName;
            }
        }
        return $newParams;
    }

And in my Plugin.php I have

```
  public function boot() {
        Event::listen('translate.localePicker.translateParams', function($page, $params, $oldLocale, 
  $newLocale) {
            if ($page->baseFileName == 't-l-post') {
                return Post::translateParams($params, $oldLocale, $newLocale);
            }
        });
```

My locale selector 

```
 {{ form_open() }}
            <select class="btn btn-default mr-2 langSelect" id='languageSelector'>
                {% for code, name in locales %}
                {% if code == activeLocale %}
                <option value="none" selected disabled>{{name}}</option>
                {% endif %}
                    {% if code != activeLocale %}
                        <option value="{{code}}" name="locale">{{name}}</option>
                    {% endif %}
                {% endfor %}
            </select>
{{ form_close() }}
```

And finally my js is the same as in the documentation
```

$('#languageSelector, #smallScreenLanguageSelector').on('change', function () {
    const details = {
        _session_key: document.querySelector('input[name="_session_key"]').value,
        _token: document.querySelector('input[name="_token"]').value,
        locale: this.value
    }

    let formBody = []

    for (var property in details) {
        let encodedKey = encodeURIComponent(property)

        let encodedValue = encodeURIComponent(details[property])

        formBody.push(encodedKey + '=' + encodedValue)
    }

    formBody = formBody.join('&')

    fetch(location.href + '/', {
        method: 'POST',
        body: formBody,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
            'X-OCTOBER-REQUEST-HANDLER': 'onSwitchLocale',
            'X-OCTOBER-REQUEST-PARTIALS': '',
            'X-Requested-With': 'XMLHttpRequest'
        }
    })
    .then(res => res.json())
    .then(res => window.location.replace(res.X_OCTOBER_REDIRECT))
    .catch(err => console.log(err))
})
```

I tried every solution I could find on here as well as the october cms forums with no result.

**Comment by mjauvin** [comment]
Did you check this section of the documentation?

file:///android_asset/md/#indexed-attributes

**Comment by andreacelery** [comment]
> Did you check this section of the documentation?
> 
> https://github.com/rainlab/translate-plugin#indexed-attributes

Thank you for your reply. The translation works if I have one parameter in the url for example tnl/:countryslug. But if I have more than one, none of them would get translated (tnl/:country/:lawslug for example). Any ideas on how to fix that?

**Comment by mjauvin** [comment]
Ok, did you confirm your translateParams() method gets called?

**Comment by mjauvin** [comment]
I tested this using a very simple event handler (as shown below) and it works as expected:
```
        Event::listen('translate.localePicker.translateParams', function($page, $params, $oldLocale, $newLocale) {
            if ($page->baseFileName == 'tests/params-trans') {
                return [
                    'param1'=>'foo'.$newLocale,
                    'param2'=>'bar'.$newLocale,
                ];
            }
        });
```
So there must be something wrong in your translateParams() method.

**Comment by mjauvin** [comment]
@andreacelery can you run more checks on this, otherwise I will close the issue since I cannot reproduce.

**Comment by andreacelery** [comment]
> @andreacelery can you run more checks on this, otherwise I will close the issue since I cannot reproduce.

Thank you for your reply, it helped me fix it.

I found what caused my problem. The url field names didn't match the fields in my database. For instance I would have :country/:law where in the database these are both slugs in different tables.
