### ISSUE TITLE
How can I add translatable fields in theme.yaml

### ISSUE THREAD

**Issue by shakogele** [rainlab/translate-plugin#460]
Hi! II have fields in theme.yaml however I want to make these fields translatable, I'm using Rainlab.Translate plugin in my project. Thanks

**Comment by w20k** [comment]
Have you read docs? -> https://octobercms.com/plugin/rainlab-translate

**Comment by shakogele** [comment]
Sure, and whats your point?

**Comment by w20k** [comment]
https://github.com/rainlab/translate-plugin#message-translation
It's one option, second add as lang pack for your plugin (example: https://github.com/OFFLINE-GmbH/oc-mall-theme, https://github.com/OFFLINE-GmbH/oc-mall-plugin).

**Comment by w20k** [comment]
Github issues really aren't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: https://octobercms.com/forum
StackOverflow: https://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or https://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/

**Comment by shakogele** [comment]
I think you did not undestand my point. I have fields in theme.yaml like this:
my theme.yaml
`
name: Blank
description: ''
author: ''
homepage: ''
code: ''
form: config/fields.yaml
`
and my config.yaml
`
tabs:
    fields:
        sitename:
            label: Название сайта
            type: text
            span: left
            default: Urbanic AlkoShop
            tab: Основные настройки
        logo:
            label: Логотип
            type: mediafinder
            mode: image
            comment: Рекомендуемый размер 250*50px
            span: right
            tab: Основные настройки
        site_subtitle:
            label: Подзаголовок сайта
            type: text
            span: left
            default: Алкоголь в канистрах в СПб
            tab: Основные настройки
`
I want to make these fields translatable

**Comment by shakogele** [comment]
> Github issues really aren't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.
> 
> Forum: https://octobercms.com/forum
> StackOverflow: https://stackoverflow.com/questions/tagged/octobercms
> IRC: #october on Freenode or https://octobercms.com/chat
> Slack: https://octobercms-slack.herokuapp.com/

I already submitted my question there and did not got answer

**Comment by w20k** [comment]
Directly in theme, I've already posted a single solution. if you have a plugin for a theme - different story.

Add lang dir and use it as a key in your config.yaml example:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/lang/ru/frontend.php#L23
```
sitename:
            label: 'offline.mall::frontend.form.password_repeat' //author.name::translate.key
```
If you have only theme and want to translate within it:

```
name: My Theme
# [...]

translate:
    en:
        site.name: 'My Website'
        nav.home: 'Home'
        nav.video: 'Video'
        title.home: 'Welcome Home'
        title.video: 'Screencast Video'
```
Should be the keys to use:  `site.name`, if I'm not mistaken.

**Comment by w20k** [comment]
Like this: https://github.com/lovata/oc-bootstrap-shopaholic-theme/blob/master/config/fields.yaml

**Comment by roojai** [comment]
I am also stuck with this. I understand the question - how do we make configurable options in our config/fields.yaml

**Comment by mjauvin** [comment]
Please, see https://github.com/rainlab/translate-plugin/pull/559

**Comment by roojai** [comment]
Thanks!
