### ISSUE TITLE
No prefix for default language, but prefix for others

### ISSUE THREAD

**Issue by Zmove** [rainlab/translate-plugin#464]
Hello,

This may be a noob question, but I looked at the documentation and issue queue without finding the answer.

I'm trying to do that : 

- for default language, the website url should not be prefixed (www.website.com)
- for other languages, I want to add a prefix (www.website.com/fr, www.website.com/de, etc...)

The default component provide me 2 options, but none of them do what I want : 
- If I don't check "force URL schema", the language switch correctly, but the website url is always www.website.com
- If I check "force URL schema", the prefix is always added (and so, my website url, even for default language is www.website.com/en)

Is there a way do not have prefix for the default language ?

Thank you for your help, and for that very useful plugin !

**Comment by w20k** [comment]
@Zmove do you have default language set in config?

**Comment by Zmove** [comment]
@w20k  You mean in Settings > Manage language ? : Yes

**Comment by mjauvin** [comment]
no, plugins/rainlab/translate/config/

**Comment by mjauvin** [comment]
'prefixDefaultLocale' => true

**Comment by mjauvin** [comment]
if you set it to false, it'll do what you want

**Comment by mjauvin** [comment]
but don't set it under the plugin, set it under your app's config directory with the path "rainlab/translate/config/config.php" (copy the original file there)

**Comment by Zmove** [comment]
Hi, thank you for your answer.

I changed the option in /plugins/rainlab/translate/config/config.php and it does exactly what I need.

But I don't understand what do you mean with your latest comment. I tried to copy the /plugin/rainlab/translate/config/config.php to my config directory (so it gives /config/rainlab/translate/config/config.php), but it doesn't seems to be red.

**Comment by mjauvin** [comment]
My bad, the actual path should be:

`/plugin/rainlab/translate/config.php`

I had an extraneous "/config/" part

**Comment by LukeTowers** [comment]
@mjauvin I think that path is still wrong, shouldn't it be `~/config/rainlab/translate/config.php`?

**Comment by Zmove** [comment]
Yep, I firstly made the mistake, then I saw the [october CMS doc about overriding config](https://octobercms.com/docs/plugin/settings#file-configuration), and it was ok :)
