### ISSUE TITLE
"translate messages" don't work

### ISSUE THREAD

**Issue by kalichava** [rainlab/translate-plugin#47]
current build 205
in backend i have: http://grab.by/F4dE
in template i use:  <div class="menu-link-text">{{ 'menu.link.title'|_  }}</div>
on page i have: http://grab.by/F4ee

**Comment by IlanF** [comment]
Same thing. Apparently the 1.0.6 update broke it, 1.0.5 works fine.
I replaced the files with the 1.0.5 but now my clear cache button doesn't work:
```Class 'System\Console\CacheClear' not found" on line 46 of /path/to/october/plugins/rainlab/translate/controllers/Messages.php
```
