### ISSUE TITLE
Option to disable prefixed routes

### ISSUE THREAD

**Issue by Samuell1** [rainlab/translate-plugin#476]
Option to disable routing in routes.php (https://github.com/rainlab/translate-plugin/blob/master/routes.php#L9) to prevent duplicate URLs for SEO if is used custom plugin to set language or language is set depending on browser.

**Comment by LukeTowers** [comment]
_No response provided_

**Comment by Samuell1** [comment]
@LukeTowers edited my response to explain it more.

**Comment by LukeTowers** [comment]
I still don't understand the request. What is the option called? What is the effect of the option? Is this a feature request? Are you going to implement it or are you expecting other people to implement it for you?

**Comment by Samuell1** [comment]
Its mostly feature request but iam not sure where it should be implemented as option, when plugin is not using Settings model.

**Comment by LukeTowers** [comment]
The plugin uses config values

**Comment by mjauvin** [comment]
There is already prefixDefaultLocale config setting which would prevent the default locale to be inserted in front of the path.

**Comment by Samuell1** [comment]
@mjauvin yes but its about disabling links completely because they still works.

**Comment by mjauvin** [comment]
@Samuell1 What links are you talking about? Can you give more details otherwise we keep going in circles...

**Comment by Samuell1** [comment]
@mjauvin This links that are generated https://github.com/rainlab/translate-plugin/blob/master/routes.php#L9

**Comment by mjauvin** [comment]
Ok, I get what you mean now.

You want the locale based routes NOT to be created when you use Rainlab.Translate ALONG WITH a custom Plugin that handles switching the active Locale in a way other than using the locale prefix.

In my opinion, it would be the custom Plugin's task to disable those routes, no?

@LukeTowers can a plugin disable another plugin's routes somehow?

**Comment by LukeTowers** [comment]
@mjauvin well there's the cms.beforeRoute event (https://github.com/octobercms/october/blob/master/modules/cms/routes.php#L10) where you could in theory listen to that event, detect any routes that you don't want to exist and call `abort(404)` from there. We could also just add a `disableRoutes`  config option to our config file (defaulting to false of course) and then people can do whatever they want with that.

**Comment by mjauvin** [comment]
This code could be added to any plugin that wants to modify RT's basic routes:

```
Event::listen('backend.beforeRoute', function() {
    foreach (\Rainlab\Translate\Models\Locale::listEnabled() as $code => $name) {
        Route::any($code, function() {
            return Response::make(View::make('cms::404'), 404);
        });
    }
});
```

@LukeTowers For some reason, calling abort(404) does not work.

**Comment by LukeTowers** [comment]
@mjauvin are you on the latest? There were improvements made to the 404 handling recently, although that might have been only in the backend?

**Comment by mjauvin** [comment]
I get this error when using abort(404):

![Screenshot from 2019-05-22 10-09-39](https://user-images.githubusercontent.com/2013630/58181423-c46ee600-7c79-11e9-9279-53a7d86a5c76.png)

**Comment by mjauvin** [comment]
@LukeTowers 
$ composer show october*
october/backend v1.0.455 Backend module for October CMS
october/cms     v1.0.455 CMS module for October CMS
october/rain    v1.0.455 October Rain Library
october/system  v1.0.455 System module for October CMS

**Comment by Samuell1** [comment]
@mjauvin i dont think is good idea to overwrite something if we can disable it because routes still will be generated and replaced.

It will be cool if we can somehow be able to see what routes are in application but `php artisan route:list` doesnt work :(

**Comment by mjauvin** [comment]
@Samuell1 can you submit a PR for this?
