### ISSUE TITLE
Redirect after translate

### ISSUE THREAD

**Issue by tom-schmitz** [rainlab/translate-plugin#477]
Hi,

I was wondering if it's possible to redirect to a specific page after changing the local
in the dropdown menu?

**Example:**
From the contactpage redirect to the homepage after changing language.

Thanks for your time

**Comment by mjauvin** [comment]
You could add an ajax event handler on *ajaxDone *to do this (please see
https://octobercms.com/docs/ajax/javascript-api#global-events)

--
Marc

**Comment by mjauvin** [comment]
This is not something that is required as part of this plugin, but can easily be added seperately.
