### ISSUE TITLE
CMS file translations always uses langugage suffix

### ISSUE THREAD

**Issue by setianke** [rainlab/translate-plugin#480]
Using the content translation according to the documentaion for htm files like 

- cms-page.htm
- cms-page.en.htm

always results in OctoberCMS rendering the "cms-page.en.htm" instead of the deafult "cms-page.htm" and ignores the the URL /en paramater. 

I tried clearing cache and using the Local Picker with force URL structure without any success. 

OctoberCMS: 447
Translate Plugin: 1.4.5

**Comment by mjauvin** [comment]
What you refer to is for "content" pages... not CMS or Static pages. This is using the {% content "content-page-name" %} in twig.

**Comment by setianke** [comment]
@mjauvin yes you are correct - using the {% content "content-page-name" %} works as aspected - partials are not supported the same way right? Thank you for your time and response.

**Comment by mjauvin** [comment]
Right, partials are not supported for this.
