### ISSUE TITLE
Script tag in MLMarkdownEditor

### ISSUE THREAD

**Issue by patriknemecek** [rainlab/translate-plugin#484]
Hello,

I figured out, the editor allow script tag, which can be used for XSS in RainLab.Blog plugin, when you have more than one active language.

**Comment by bennothommo** [comment]
@patriknemecek Thanks for bringing this to our attention. While the scope of vulnerability is low, given that someone has to be signed in to the Backend in order to use the editor, we'll still need to disallow script tags in the widget.

**Comment by daftspunk** [comment]
Yes, please keep in mind that backend users are considered trusted, they do have the potential to include <script> tags and other things--for legitimate reasons. If you need to give access to untrusted users then you should build a front-end system that adequately controls the environment

**Comment by saitagency** [comment]
Of course they have rights to include <script> to frontend , but why original markdown editor don't exec script in backend and MLMarkdownEditor exec? This is in my opinion may be dangerous for create superuser with low-level permission admin.

**Comment by patriknemecek** [comment]
Of course they have rights to include <script> to frontend, but why original markdown editor don't exec script in backend and MLMarkdownEditor exec? In my opinion this may be dangerous for create superuser with low-level permission admin. If backend users are trusted, why all the community patch security holes? A lost cause?

**Comment by bennothommo** [comment]
@patriknemecek The original Markdown editor *does* execute script tags in the preview section, if a `<script>` tag is included. If people wish to use `<script>` or `<style>` in their Markdown content, they are free to do so at their own peril.
