### ISSUE TITLE
Backend label change suggestion

### ISSUE THREAD

**Issue by andreacelery** [rainlab/translate-plugin#488]
Wouldn't it make more sense to rename the "Clear Cache" label to "Save"? Since I feel like the end user doesn't need to know that the cache is getting cleared, all they care about is that this button saves the changes. It makes more sense to name it Save. I have changed it for my project but with any update I have to change it so its a bit frustrating.

**Comment by LukeTowers** [comment]
@andreacelery as I mentioned in the other issue you submitted, you can use language overrides to persist your changes between updates: https://octobercms.com/docs/plugin/localization#overriding. Feel free to make any changes you want in a PR and we can discuss them there as this would be a relatively minor change.
