### ISSUE TITLE
Problem when logged change language

### ISSUE THREAD

**Issue by onesoco** [rainlab/translate-plugin#494]
The problem is that when the language changes, if the user has logged in, an error foreach ()

![error_foreach](https://user-images.githubusercontent.com/22686689/60421592-75a65b80-9bea-11e9-83e5-c4ae9f365df5.PNG)

But, if you have not logged in if it works correctly.

**Comment by w20k** [comment]
@onesoco what's your translate plugin and core version?

**Comment by onesoco** [comment]
October: 455
Translate: 1.4.1

**Comment by onesoco** [comment]
already solved, it was a problem in a function that only compared if it was the default language and not another.
