### ISSUE TITLE
Error http 406 (The title field is required) when creating page

### ISSUE THREAD

**Issue by plyusninva** [rainlab/translate-plugin#495]
Hello!

When creating the page, the error "The title field is required.".

October Build 455
Enabled plugins:
- RainLab.Translate v. 1.6.0
- RainLab.Pages v. 1.2.21
- others are disabled

Steps:
1. create subpage "test01" -  result OK
2. next create another subpage "test02" -  result Error "The title field is required."

step 1
![2019-07-03_113716](https://user-images.githubusercontent.com/25381948/60569856-b5577980-9d89-11e9-9e8f-95b103aad0b8.png)
step 2
![2019-07-03_113952](https://user-images.githubusercontent.com/25381948/60569863-bb4d5a80-9d89-11e9-9b28-05e2959d7728.png)
![2019-07-03_114221](https://user-images.githubusercontent.com/25381948/60569868-bee0e180-9d89-11e9-9d06-c0b4e9b7ed11.png)
![2019-07-03_114548](https://user-images.githubusercontent.com/25381948/60569870-c0aaa500-9d89-11e9-94f9-70936d177822.png)

my guess is that "RLTranslate [en] [viewBag] [title]" parameter is not passed

**Comment by mjauvin** [comment]
I confirm this, was able to reproduce. What is interesting is that it only happens if you create TWO subpages under a parent WITHOUT CLOSING THE 1ST SUBPAGE tab before creating the second one...

Can you confirm this @plyusninva ?

**Comment by mjauvin** [comment]
Actually, it doesn't have to be subpages... create ANY TWO pages like below:

- click Pages -> Add
- type test01
- type CTRL-S (to save)
- click Pages -> Add
- type test02
- type CTRL-S

Error is shown...

But if you do the exact same thing but closing the "test01" tab after saving it, problem does not happen.

**Comment by plyusninva** [comment]
> Can you confirm this @plyusninva ?

Yes!
in addition, this only happens if there are two or more languages. It does not matter whether they are enabled or not.

**Comment by Balex70** [comment]
Yes, we have the same problems. I confirm that it happens when creating pages one by one without and only if you have more than one languages.

**Comment by mjauvin** [comment]
I tried reproducing this with latest core and Pages plugin and it's now working fine.
