### ISSUE TITLE
Can't translate repeater fields

### ISSUE THREAD

**Issue by Asinox** [rainlab/translate-plugin#497]
I know, this issue is here a few time, but after reading all of them, I can't find a solution.

The thing is, I have a repeater with a few fields, like "title", "subtitle", but I can't translate those fields.
```
public $implement = ['RainLab.Translate.Behaviors.TranslatableModel'];

public $translatable = ['property_name','property_title','property_subtitle','seo_description','seo_keywords','subtitle','title'];
```
`subtitle` and `title` are inside "sections" repeater.

Translate plugin: 1.6.0
October Build: 456

Thanks!

**Comment by mjauvin** [comment]
This is currently not supported. a PR to address this would be nice!

**Comment by GenaMS** [comment]
Hi! Wanted to know, is still not supported on Winter CMS? I haven’t found the answer. My question is at https://octoclub.ru/d/333-perevod-repeater-cerez-rainlabtranslate

**Comment by daftspunk** [comment]
This is possible in October CMS v2.2 which should be released soon. If you need support with this, feel free to contact us via official support channels: https://octobercms.com/contact
