### ISSUE TITLE
New release 1.6.1 for auto-update on octobercms

### ISSUE THREAD

**Issue by RodrigoGalter** [rainlab/translate-plugin#499]
Is there a version 1.6.1 ready, it is possible to release for automatic update by CMS?

**Comment by w20k** [comment]
@mjauvin what do you think? Can we push `1.6.1` to a stable?

**Comment by bennothommo** [comment]
@w20k It appears @mjauvin tagged 1.6.1 already: https://github.com/rainlab/translate-plugin/releases/tag/1.6.1, but no corresponding update to `version.yaml` was made. I think we'd have to tag the next one as 1.6.2.

**Comment by mjauvin** [comment]
Sure, I guess the latest changes were relatively safe. @bennothommo go ahead, I'm not able to at the moment.

**Comment by bennothommo** [comment]
@RodrigoGalter We have released version 1.6.2 of the Translate plugin, as version 1.6.1 was already previously tagged. It should appear as an update shortly if you have "edge updates" enabled.
