### ISSUE TITLE
Nestedform and Datatable field types cant be Translated

### ISSUE THREAD

**Issue by FirestarterUA** [rainlab/translate-plugin#500]
Any other type work as expected (can be transalted), but datatable and nestedform does not.

**Comment by LukeTowers** [comment]
@FirestarterUA feel free to submit a PR to add support or offer a bounty to get someone else to build support for it for you.

**Comment by iboved** [comment]
Any progress in this? How to use multilingual in NesterForms?

**Comment by daftspunk** [comment]
Moved to #584
