### ISSUE TITLE
404 when using multiple page arguments in URL

### ISSUE THREAD

**Issue by adamo** [rainlab/translate-plugin#505]
I've setup a home page with the url as follows

`/:id/:series_id?/:view?/:schema_id?`

All the parameters are used inside a component, the problem is that when using a seotool the response for the language home page for example `address.com/pl` is shown as a 404 status.

When I leave the `/id` status is back to 200.

I've tried many things to change the behavior, for instance adding another `:lang` parameter to the route `/:lang/:id/:series_id?/:view?/:schema_id?` with no luck.

The response using https://onlinecurl.com/ is

```
HTTP/1.1 404 Not Found
Date: Tue, 06 Aug 2019 14:24:32 GMT
Server: Apache
Cache-Control: no-cache, private
Set-Cookie: october_session=eyJpdiI6Iit3cnNZaWdcLzBPbFVlMzloWXg2RU5RPT0iLCJ2YWx1ZSI6Im84Rkh3SVwvUlNGd3pqK05uYVpFTkI0bnh3Sm5DZVdKZkt2YTcwMVNzaEpUOU8xYXJsc0tPaWFoWjlXRm9oaEh0UURBWlJTRERXbzZDbGwzVGtUaXRSQT09IiwibWFjIjoiYjRlNGMyYmM2MzE0OTI5MTZiZWU0YWRmZWI0Zjc3ZjY3YTY5Y2I4ZTI4MDFhZTE1ZjY3ZDI1NjE4OTQ1N2VkYyJ9; expires=Tue, 06-Aug-2019 16:24:32 GMT; Max-Age=7200; path=/; HttpOnly
Transfer-Encoding: chunked
Content-Type: text/html; charset=UTF-8
```
And below the html page content - which is correct.
I've tried to find the solution elsewhere (eg. slack) but could not solve this issue.

**Comment by mjauvin** [comment]
for the URL you refer to above, you NEED to provide an ID as the first parameter.

So the request to the page should be https://onlinecurl.com/123 or https://onlinecurl.com/pl/123

**Comment by adamo** [comment]
I changed this parameter to `/:id?/...` and so on but no luck. 
I've solved it by adding another page (the parameters where on the home page. 
So now i have a home page with the url `/` and a secondary page with the url `/id/...` little hacky but got the job done.

**Comment by mjauvin** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
