### ISSUE TITLE
Share language to relations

### ISSUE THREAD

**Issue by Samuell1** [rainlab/translate-plugin#506]
Hey, its there a way to share language to relations from main model?

**Example:**
`User::find(1)->lang('en')->product->name`

Calling lang on user returns user with en translations but it doesnt use lang value for _product_ relation

This can simplify sending a language emails depending on saved language in model depending on user etc.

**Comment by mjauvin** [comment]
@samuell1  can't you use `User::find(1)->lang('en')->product->lang('en')->name`?

**Comment by Samuell1** [comment]
Yes that works but it cant work with more relations and mostly "many" relations

**Comment by mjauvin** [comment]
@Samuell1 did you solve this?

**Comment by Samuell1** [comment]
@mjauvin No and yes :D I doing it this way

```
$localeCopy = Translator::instance()->getLocale();
$translator = Translator::instance();

// set locale depending on user detected
$translator->setLocale('en', false);

// get code from model
// ... $this->fresh();

// set locale back
$translator->setLocale($localeCopy, false);
```
