### ISSUE TITLE
Localization switcher doesn't seem to work

### ISSUE THREAD

**Issue by Lajmenko** [rainlab/translate-plugin#507]
Hello! 

I have been using the previous versions of plugin in the past with no issues, however this time, when building a new website it seems that I cannot get locale picker component to work. 

I can still access the translated content with manually writing the /en/ in url, however it seems whenever i try to do that via localepicker it looks unresponsive - nothing is happening. 

What I am possible missing? Should I provide additional information?

**Comment by mjauvin** [comment]
Try using the "Force URL schema" in the Locale Picker component settings.

**Comment by Lajmenko** [comment]
@mjauvin  I have tried it both ways, yet no dice.

**Comment by mjauvin** [comment]
Did you include the ajax framework in your layout/template?

ref. https://octobercms.com/docs/ajax/introduction#framework-script

**Comment by Lajmenko** [comment]
@mjauvin, That was it! I feel so dumb. Thank You so much for your help!

i included the framework BEFORE loading javascript, that the issue.
