### ISSUE TITLE
Field checkboxlist not translation

### ISSUE THREAD

**Issue by Darkrogua** [rainlab/translate-plugin#508]
I have a problem with translating checkboxlist fields . I'm trying to make a multilingual list that will have different meanings in each language. For example, a list of days: in English, it's Monday and Tuesday, and in Russian it's Friday and Saturday.

**Comment by mjauvin** [comment]
You can use a method in your model to populate the options. This method can
fill the options with different values depending on the currently selected
Locale.

ref. https://octobercms.com/docs/backend/forms#field-checkboxlist

ref. https://octobercms.com/docs/backend/forms#field-dropdown

note: checkbox lists and dropdown use the same method for defining options

--
Marc

**Comment by mjauvin** [comment]
You can use a method in your model to populate the options. This method can
fill the options with different values depending on the currently selected
Locale.

* ref. https://octobercms.com/docs/backend/forms#field-checkboxlist
* ref. https://octobercms.com/docs/backend/forms#field-dropdown

note: checkbox lists and dropdown use the same method for defining options

**Comment by Darkrogua** [comment]
Yes, I understand that, but how does that solve my problem with filling out a list with different values in different languages?

**Comment by mjauvin** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
