### ISSUE TITLE
Getting active locale prefixDefaultLocale false

### ISSUE THREAD

**Issue by Darkrogua** [rainlab/translate-plugin#512]
I'm trying to get an active locale on the backend, used to get Session:: get('rainlab.translate.locale'), but then decided to abandon the prefix in the standard language(    'prefixDefaultLocale' => false,) and now Session:: get('rainlab.translate.locale') always equals standard language...

**Comment by mjauvin** [comment]
@Darkrogua can you provide more information on how to reproduce this?

**Comment by mjauvin** [comment]
Do you have the "Force URL schema" enabled in your Locale Picker component?

**Comment by Darkrogua** [comment]
o sorry, i`ts work
