### ISSUE TITLE
Problems after different plugin removal

### ISSUE THREAD

**Issue by WebShapedBiz** [rainlab/translate-plugin#513]
Hi.

This probably has nothing to do with your plugin but the original developer of `mnshankar/oc-subscribe-plugin` doesn't seem to care :-(

Anyhow, after removing aforementioned `mnshankar/oc-subscribe-plugin plugin`, I'm getting an error message each time I scan for new messages in Rainlab Translate plugin:

> InvalidArgumentException: No hint path defined for [serenitynow.subscribe]. in /var/www/html/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:112

The scan, however, is successful. Any ideas on how to get rid of it? I've checked the DB and there are no leftovers of `mnshankar/oc-subscribe-plugin plugin` plugin. The plugin directory is also empty.

Cheers.

**Comment by LukeTowers** [comment]
@WebShapedBiz are you able to post a full stack trace of the error?

**Comment by WebShapedBiz** [comment]
Thank you @LukeTowers for your time and effort. I know that my post shoudn't be an issue for this plugin but that's the only place where I'm having this problem. This is from the log:

> InvalidArgumentException: No hint path defined for [serenitynow.subscribe]. in /var/www/html/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:112
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(90): Illuminate\View\FileViewFinder->parseNamespaceSegments('serenitynow.sub...')
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(76): Illuminate\View\FileViewFinder->findNamespacedView('serenitynow.sub...')
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\View\FileViewFinder->find('serenitynow.sub...')
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\View\Factory->make('serenitynow.sub...')
#4 /var/www/html/modules/system/models/MailTemplate.php(149): Illuminate\Support\Facades\Facade::__callStatic('make', Array)
#5 /var/www/html/modules/system/models/MailTemplate.php(134): System\Models\MailTemplate::getTemplateSections('serenitynow.sub...')
#6 /var/www/html/modules/system/models/MailTemplate.php(123): System\Models\MailTemplate->fillFromView('serenitynow.sub...')
#7 /var/www/html/vendor/october/rain/src/Database/Model.php(168): System\Models\MailTemplate->afterFetch()
#8 [internal function]: October\Rain\Database\Model->October\Rain\Database\{closure}(Object(System\Models\MailTemplate))
#9 /var/www/html/vendor/october/rain/src/Events/Dispatcher.php(233): call_user_func_array(Object(Closure), Array)
#10 /var/www/html/vendor/october/rain/src/Events/Dispatcher.php(197): October\Rain\Events\Dispatcher->dispatch('eloquent.fetche...', Array, false)
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php(148): October\Rain\Events\Dispatcher->fire('eloquent.fetche...', Object(System\Models\MailTemplate))
#12 /var/www/html/vendor/october/rain/src/Database/Model.php(433): Illuminate\Database\Eloquent\Model->fireModelEvent('fetched', false)
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(260): October\Rain\Database\Model->newFromBuilder(Object(stdClass))
#14 [internal function]: Illuminate\Database\Eloquent\Builder->Illuminate\Database\Eloquent\{closure}(Object(stdClass))
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(261): array_map(Object(Closure), Array)
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1477): Illuminate\Database\Eloquent\Builder->hydrate(Array)
#17 /var/www/html/vendor/october/rain/src/Extension/ExtendableTrait.php(423): Illuminate\Database\Eloquent\Model->__call('hydrate', Array)
#18 /var/www/html/vendor/october/rain/src/Database/Model.php(635): October\Rain\Database\Model->extendableCall('hydrate', Array)
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(481): October\Rain\Database\Model->__call('hydrate', Array)
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(465): Illuminate\Database\Eloquent\Builder->getModels(Array)
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(77): Illuminate\Database\Eloquent\Builder->get(Array)
#22 /var/www/html/modules/system/models/MailTemplate.php(154): Illuminate\Database\Eloquent\Builder->first()
#23 /var/www/html/modules/system/models/MailTemplate.php(71): System\Models\MailTemplate::findOrMakeTemplate('serenitynow.sub...')
#24 /var/www/html/plugins/rainlab/translate/classes/ThemeScanner.php(107): System\Models\MailTemplate::allTemplates()
#25 /var/www/html/plugins/rainlab/translate/classes/ThemeScanner.php(38): RainLab\Translate\Classes\ThemeScanner->scanMailTemplatesForMessages()
#26 /var/www/html/plugins/rainlab/translate/classes/ThemeScanner.php(27): RainLab\Translate\Classes\ThemeScanner->scanForMessages()
#27 /var/www/html/plugins/rainlab/translate/controllers/Messages.php(76): RainLab\Translate\Classes\ThemeScanner::scan()
#28 [internal function]: RainLab\Translate\Controllers\Messages->onScanMessages()
#29 /var/www/html/modules/backend/classes/Controller.php(620): call_user_func_array(Array, Array)
#30 /var/www/html/modules/backend/classes/Controller.php(470): Backend\Classes\Controller->runAjaxHandler('onScanMessages')
#31 /var/www/html/modules/backend/classes/Controller.php(267): Backend\Classes\Controller->execAjaxHandlers()
#32 /var/www/html/modules/backend/classes/BackendController.php(161): Backend\Classes\Controller->run('index', Array)
#33 [internal function]: Backend\Classes\BackendController->run('rainlab/transla...')
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('run', Array)
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Backend\Classes\BackendController), 'run')
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\Routing\Route->runController()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Route->run()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 /var/www/html/modules/backend/classes/BackendController.php(68): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(131): Backend\Classes\BackendController->Backend\Classes\{closure}(Object(Illuminate\Http\Request), Object(Closure))
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#53 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#56 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#59 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#60 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#61 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#62 /var/www/html/vendor/october/rain/src/Router/CoreRouter.php(20): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#63 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))
#64 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#65 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#66 /var/www/html/vendor/october/rain/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php(24): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#67 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#68 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#69 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#70 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#71 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#72 /var/www/html/index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#73 {main}

**Comment by mjauvin** [comment]
@WebShapedBiz are you sure there are no left-over call to that plugin from your theme/plugins ?

What is "serenitynow.subscribe" ?

**Comment by WebShapedBiz** [comment]
Thank you @mjauvin for your message. There are no leftovers from that plugin since I didn't even have a chance to configure it. There were some issues with mail configuration and I just removed it from my server. The only place I'm seeing it is when I scan for messages in Settings -> Translate messages.

The "serenitynow.subscribe" is this plugin [https://octobercms.com/plugin/serenitynow-subscribe](url). 

Cheers.

**Comment by mjauvin** [comment]
Can you try removing the serenitynow plugin to see what happens?

**Comment by WebShapedBiz** [comment]
The trouble with "serenitynow.subscribe" and Rainlab.Translate began when I removed the plugin.

**Comment by mjauvin** [comment]
Oh, I didn't realize "mnshankar/oc-subscribe-plugin" and "serenitynow" were the same plugin, sorry...

**Comment by mjauvin** [comment]
Did you try to empty your cache with "artisan cache:clear" ?

**Comment by WebShapedBiz** [comment]
Nope, I'll try that and update this thread if anything happens, thanx.

**Comment by mjauvin** [comment]
@WebShapedBiz I found what's causing this. It's not related to Rainlab Translate plugin but definitely a bug in October itself (I think).

Try searching the `system_mail_templates` db table for entries with code field matching the plugin name that has been deleted.

I don't know if October should delete those when a plugin is removed, maybe.

**Comment by WebShapedBiz** [comment]
Thank you @mjauvin for being on top of this. In the meantime, as I couldn't figure it out, I've migrated the site on a new installation, and everything is peachy now, as usually is with OctoberCMS :-)

Cheers.
