### ISSUE TITLE
Per-Locale Theme

### ISSUE THREAD

**Issue by MateThemes** [rainlab/translate-plugin#515]
Hello!

I have seen that the last update added a per-locale theme configuration feature. Now how is this working?

I can't any documentation on that. What I want is to translate the theme.yaml file in the backend language of the user. 

Thanks in advance!

**Comment by LukeTowers** [comment]
@MateThemes it was added to the README: https://github.com/rainlab/translate-plugin/commit/8aa2759b2f5ade6d01afcfdb34cba9884232d2b6#diff-04c6e90faac2675aa89e2176d2eec7d8R86-R102
