### ISSUE TITLE
Why full cache gets flushed on message update?

### ISSUE THREAD

**Issue by Samuell1** [rainlab/translate-plugin#518]
Hey, i was searching for issues why cache is getting flushed randomly then i findout that translate plugin flushes global cache on message update. Its this needed?

https://github.com/rainlab/translate-plugin/blob/60e88cb383e8a46c887459c63f87b2f6d50da635/controllers/Messages.php#L147

**Comment by w20k** [comment]
@Samuell1 yes, it is. See comment made by @alekseybobkov: `Clean cache automatically when a message translation is changed.`

**Comment by LukeTowers** [comment]
@Samuell1 since cached rendered templates could contain the changed message string they need to be regenerated. If you can suggest a more selective cache refresh then I'm happy to review that but otherwise we'll leave it as it is.

**Comment by Samuell1** [comment]
@LukeTowers maybe dont force it on update but manual user, thats why there is that clear cache button on top no?

**Comment by LukeTowers** [comment]
Existing behaviour is to clear the cache so I'm not sure we want to change that.

**Comment by LukeTowers** [comment]
Best we could do is maybe make it a config option for the plugin

**Comment by Samuell1** [comment]
@LukeTowers I mean mostly issue is that if you update 60 messages it flushes cache per every update thats what i dont like about this.

**Comment by LukeTowers** [comment]
@Samuell1 we're open to suggestions for improvements.

**Comment by Samuell1** [comment]
@LukeTowers Maybe it will be better if ocms tags cache items, then we can flush only what you want not full cache.

https://laravel.com/docs/5.5/cache#cache-tags

**Comment by LukeTowers** [comment]
@Samuell1 feel free to make a PR

**Comment by Samuell1** [comment]
@LukeTowers I was looking into it but there is limitation :(

> Cache tags are not supported when using the file or database cache drivers. Furthermore, when using multiple tags with caches that are stored "forever", performance will be best with a driver such as memcached, which automatically purges stale records.
