### ISSUE TITLE
Different menu for secondary language

### ISSUE THREAD

**Issue by MaTToX3** [rainlab/translate-plugin#519]
My site is using english for a secondary language. It is a different site (content wise) so it also needs it's own main menu. I want to create another main menu for english language and show it on the english version. What is the best way to do it? It will link to the static pages, that are translated from the original language content. 

Should I just create a custom component for Main Menu and do a locale check there or is there a better way?

**Comment by LukeTowers** [comment]
@MaTToX3 you could put two instances of the Menu component on your page, have one of them load the english menu and have the other load the other language, then in your template that renders the menu choose which component to use based on the currently selected locale.

**Comment by MaTToX3** [comment]
It's a good idea. I created a partial for main menu and did a check there. However since I have a custom style of my main menu, I have to actually have two more files now to style the second menu (which is basically the same). 

So I am still thinking of component where I do the check for locale.
