### ISSUE TITLE
Translating State Model in User plugin.

### ISSUE THREAD

**Issue by mplodowski** [rainlab/translate-plugin#52]
I installed User plugin and Translate Plugin.
I used Translate Plugin to translate Countries and States in User plugin. There is no problem with translating Country Model, but something is wrong with translating State Model.

I added these lines in Country and State Models:

```
public $implement = ['RainLab.Translate.Behaviors.TranslatableModel'];
public $translatable = ['name'];
```

Next I went to Settings -> Locations in admin panel area. Inputs were changed dynamically by Translate Plugin. I translated Country record and so far everything is working fine. Next I tried to translate State, but translated state is not persisted to database. I checked $_POST variable and translation is sended. I debuged TranslatableModel.php and found that $translatableAttributes variable is empty in function syncTranslatableAttributes().

I quick fixed that by going through $_POST variable setting $translatableAttributes for RainLab\User\Models\State model in syncTranslatableAttributes() function. 
That is very poor solution, but I have not found any other for this.

The problem persist everywhere where You use relationRender() function in backend view.

Sorry for my poor english. If you have questions I will try to help.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
