### ISSUE TITLE
Allow purging messages to keep existing translations

### ISSUE THREAD

**Issue by multiwebinc** [rainlab/translate-plugin#525]
When you do a scan for messages and check the "purge all messages first", this deletes everything, including existing translations, before re-adding the strings the scanner finds. And if you don't check the "purge all messages" box, any time you update a translation in the source files will create an extra message to be translated.

You are therefore left with two choices; check the box and have to re-translate everything again, or not check that box and end up with a bunch of ghost strings that are not found anywhere in the project. Neither of these cases is ideal and both will necessarily cause extra work for translators.

Here are my two suggestions:

- Add an option to purge only the strings that are not still in the project.
- Add a column to the list view to indicate that the string couldn't be found in the project anymore to give the translator an idea which strings can be safely deleted.

**Comment by mjauvin** [comment]
@multiwebinc any chance you could submit a PR for the proposed suggestion(s) ?
