### ISSUE TITLE
Fallback not translated Model properties to default locale

### ISSUE THREAD

**Issue by mplodowski** [rainlab/translate-plugin#53]
I have site with two languages, english (default) and german. I translated my Model class properties in backend from english to german and leave some of them blank. After I get record from database it has auto translated properties, but some of them are blank, because I did not fill them in backend.

It will be a good idea to fallback to default locale for those properties that are not translated. It is a better experience for user to see english value than an empty string.

**Comment by MilosStanic** [comment]
From what I see, now pulling attributes pulls default language where translation is not available.
However, I ineed (as a feature) some kind of switch to prevent fallback to default language for untranslated attributes.
Is that possible?

**Comment by MilosStanic** [comment]
Appears there is a switch to prevent fallback. 
The method is called `noFallbackLocale()`

**Comment by daftspunk** [comment]
As above. If this is still an issue, please provide the exact steps you are taking for the issue to occur. We can look at it again from there.
