### ISSUE TITLE
"Page not found" if "en" is not standard language/translation

### ISSUE THREAD

**Issue by RonMen** [rainlab/translate-plugin#530]
Hi there,

if I define "de" as a standard language for a site I get the site in german using "/" but I do not get english using "/en". If I define "en" as standard language for same site I get english using "/" and german using "/de", so in that case everything works well. Anything I can do making it working?

Regards
RonMen

**Comment by mjauvin** [comment]
I'd need more details but did you translate the site with English as default first? There's currently a limitation when changing the default language where it doesn't properly switch the translations

**Comment by RonMen** [comment]
Dear @mjauvin,

I reinstalled the plugin and first tried to change the default language to "de" and added "en" as a new language. Now it seems to work well on pages I tried.

Regards
RonMen
