### ISSUE TITLE
Ability to change StaticPages Layout per language

### ISSUE THREAD

**Issue by bob-tm** [rainlab/translate-plugin#531]
I have a multi-language site. Some pages on main language was upgraded to new layout. But localized pages are still on old-layout. 
I can manually add 
**layout = "old-layout"** to each **static-pages-de\*.htm**  and everything rendered as I want:
Main page works in new-layout, but localized in old-layout. But I have different {variable} fields, so I can not edit localized pages in control panel, even with manually added **layout = "old-layout"** to each localized htm file.

If plugin can read layout filed from localized pages - it will be excellent!

**Comment by mjauvin** [comment]
the above link will be disabled in 4 days.

**Comment by bob-tm** [comment]
I need direct file access, so I can't reproduce it in your CMS. But I create mine :)
Theme: https://en.babenko.info/cp/test.zip
![layout](https://user-images.githubusercontent.com/47008924/71091546-f7e10700-21ad-11ea-8707-a91ca217fe87.png)

EN version in new layout. 
UA version in old layout. 

https://en.babenko.info/test and https://ua.babenko.info/test
https://en.babenko.info/test-patched and https://ua.babenko.info/test-patched

The Problem 
I can not edit UA content in backend.

![layout2](https://user-images.githubusercontent.com/47008924/71092192-74281a00-21af-11ea-8c34-933c367c3d66.png)

**Comment by bob-tm** [comment]
https://en.babenko.info/backend
login and pass: mjauvin
please tell me when you don't need it.

**Comment by mjauvin** [comment]
@bob-tm what do you mean "file access" ? There is a console where you can access the filesystem for the october installation in that container.

**Comment by mjauvin** [comment]
The link to your environment (https://en.babenko.info/backend) leads to a 404 page

**Comment by bob-tm** [comment]
> @bob-tm what do you mean "file access" ? There is a console where you can access the filesystem for the october installation in that container.
oops :)



> The link to your environment (https://en.babenko.info/backend) leads to a 404 page

Fixed.

**Comment by mjauvin** [comment]
@bob-tm can ou check the provided test container, I would prefer if this oculd be done there for testability/reproducability

**Comment by bob-tm** [comment]
I will try to install theme https://en.babenko.info/cp/test.zip to your container.

**Comment by bob-tm** [comment]
Done!

https://72ba5d724105.octodock.com:8443/en/test
https://72ba5d724105.octodock.com:8443/ua/test


https://72ba5d724105.octodock.com:8443/en/test-patched
https://72ba5d724105.octodock.com:8443/ua/test-patched

**Comment by mjauvin** [comment]
Ok, I see what you mean, but it's not possible/supported to have different layouts for the same page for its different localizations. This just won't work.

And frankly, I don't see why anyone would need that.

**Comment by bob-tm** [comment]
When content changed, translated versions not always ready as fast, as main text. In my case layout also was changed. It's temporary solution while translation is synced (which can take weeks).

**Comment by mjauvin** [comment]
I don't see an easy way to fix this without a complete rewrite of the translate plugin.
