### ISSUE TITLE
Mail Templates translation

### ISSUE THREAD

**Issue by mjauvin** [rainlab/translate-plugin#533]
Content files can be translated by affixing the locale code to the file name. We need to apply the same technique to translate Mail template files. 

People are translating the mail templates themselves using the twig filters. This is a bad idea because when the mail is processed in a queue, it loses the locale setting.

**Comment by mjauvin** [comment]
I think this could be implemented by hooking into the "mailer.beforeSend" event and modifying the $view parameter in the event handler

**Comment by aurelien-roy** [comment]
Is this abandoned?

**Comment by mjauvin** [comment]
Yes, it is closed.
