### ISSUE TITLE
Add repeater widget support

### ISSUE THREAD

**Issue by MatissJanis** [rainlab/translate-plugin#54]
Currently the new repeater widget form fields cannot be translated. It would be nice to have this feature.

**Comment by mplodowski** [comment]
+1

**Comment by arikw** [comment]
+1

**Comment by Skadi2k3** [comment]
+1

**Comment by fresswolf** [comment]
+1

**Comment by vanillafudge** [comment]
+1

**Comment by Arekusei** [comment]
+1

**Comment by jhwh** [comment]
+1

**Comment by gotroch** [comment]
+1

**Comment by daftspunk** [comment]
Feel free to submit a bounty to have this prioritized.

**Comment by aurukas** [comment]
I've posted a 5$ bounty at https://www.bountysource.com/issues/10033097-add-repeater-widget-support. I encourage everyone to join by contributing at least a couple of bucks

**Comment by daftspunk** [comment]
This feature is available for testing. Requires v1.2.5 of Translate plugin and October Build 377+

**Comment by aurukas** [comment]
hey, good work. Unfortunately it doesn't work as one could expect. If I add the field from the repeater into the model $translatable, although giving an option to tranlate in the backend, it is not translated in the front. The string is shown in a language it was last saved.

I have also tried including the whole repeater into the $translatable. It works well, but It then has to go with the custom filter for decoding the json as it is presented as an object. 

Thanks!

**Comment by daftspunk** [comment]
@aurukas: Please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by pvullioud** [comment]
Hi 
Thanks for the code.

I have done a test with Page

my layout
````
{repeater tab="Le club" name="agruments" prompt="Ajouter un argument"}
		{variable type="text" name="title" label="Title"}Title{/variable}
		{variable type="textarea" name="argument" label="Content"}Content{/variable}
{/repeater}
````

If I create a page with this layout. The translation feature is missing
![Alt text](https://monosnap.com/file/LdQR7kKLRghwZfsxmseNgW8MlGnJIr.png)

**Comment by mberizzo** [comment]
I have the same problem

**Comment by daftspunk** [comment]
[Issue reported](https://github.com/rainlab/translate-plugin/issues/54#issuecomment-256067096) by @pvullioud has been fixed in 

- October Build 379+
- RainLab.Pages v1.2.11+
- RainLab.Translate v1.2.6+

**Comment by aurukas** [comment]
@daftspunk I'm trying to use the repeater translate feature in the Builder. If the repeater is not created (added) beforehand, it gives an error of "htmlentities() expects parameter 1 to be string, array given"
I guess the translate plugin simply doesn't find a field to be translated, but repeater doesn't have an option to be created by default, or does it?

**Comment by raskrial** [comment]
do you have an idea if translation for individual field in the Builder repeater will be supported soon ?

**Comment by daftspunk** [comment]
@aurukas, please log this as a new issue with full replication instructions.
