### ISSUE TITLE
LocalPicker and doesn't work

### ISSUE THREAD

**Issue by moto0000** [rainlab/translate-plugin#55]
LocalPicker doesn't change the URL path

**Comment by oliverpool** [comment]
Apparently it requires the AJAX Framework: is it embeded in you page?

**Comment by mabasic** [comment]
Should it change URL path?

**Comment by dgollub** [comment]
Yeah, it needs the October CMS JavaScript Framework enabled in the active theme or otherwise it won't work. 

I think this not mentioned in the documentation/readme, is it? If not, it should be mentioned there I'd think.

**Comment by daftspunk** [comment]
The localePicker does require {% framework %} tags to function, this is implied. Also the URL will change thanks to the `forceUrl` setting, which was introduced after this bug was logged.
