### ISSUE TITLE
How to translate jsonable fileds?

### ISSUE THREAD

**Issue by mvk843** [rainlab/translate-plugin#552]
Hello!
I have 
`protected $jsonable = ['base', 'works', 'time', 'result'];`
and
`public $translatable = ['name, base, works, time, result'];`
It looks like:
https://i111.fastpic.ru/big/2020/0210/16/39e788e61fdd2eebc9d2a8113554af16.png
So there is no option for entering translated values.
Is there any solution?

**Comment by mjauvin** [comment]
can you give more details like the fields definition file?

**Comment by mvk843** [comment]
`fields:
    name:
        label: Name
        span: full
        required: 1
        type: text
    price:
        label: Price
        span: full
        required: 1
        type: text
    slug:
        label: Slug
        span: full
        preset:
            field: name
            type: ''
        type: text
    base:
        label: Tools
        prompt: 'Add new item'
        span: full
        type: repeater
        form:
            fields:
                tool_name:
                    label: Tool
                    span: full
                    type: text
    works:
        label: Works
        prompt: 'Add new item'
        span: full
        type: repeater
        form:
            fields:
                work_name:
                    label: Work
                    span: full
                    type: text
    time:
        label: Time
        prompt: 'Add new item'
        span: full
        type: repeater
        form:
            fields:
                time_name:
                    label: Time
                    span: full
                    type: text
    result:
        label: Result
        prompt: 'Add new item'
        span: full
        type: repeater
        form:
            fields:
                result_name:
                    label: Result
                    span: full
                    type: text
    cases:
        label: 'Related cases'
        nameFrom: name
        descriptionFrom: description
        span: full
        type: relation
    products:
        label: 'Related products'
        nameFrom: name
        descriptionFrom: description
        span: auto
        type: relation
    services:
        label: 'Next steps'
        nameFrom: name
        descriptionFrom: description
        span: auto
        type: relation
`

**Comment by mvk843** [comment]
https://i111.fastpic.ru/big/2020/0210/c8/563615b14aae7c8ed472fc9e8cb861c8.png

**Comment by mjauvin** [comment]
Please, use the Discord channel to post questions and get help. Github Issues are for reporting bugs.

discord: https://discord.gg/gEKgwSZ
