### ISSUE TITLE
Plugin is not escaping the params value

### ISSUE THREAD

**Issue by chrisvidal** [rainlab/translate-plugin#553]
consider this twig:

`{{ 'Welcome back :user'|_({user: user.firstname}) }}`

the value `user.firstname` is not escaped.

if `user.firstname` is something like `<script>alert('hi there')</script>`, the script will run

**Comment by mjauvin** [comment]
Hi Chris, if you can test this that would be nice. I can setup an environment with the PR applied if you wish.

**Comment by bennothommo** [comment]
@chrisvidal You can escape it just by adding an `|e` filter to the Twig placeholder:

ie. `{{ 'Welcome back :user'|_({user: user.firstname})|e }}`

**Comment by chrisvidal** [comment]
@bennothommo thanks, good to know
@mjauvin I tested on the instance, with this:
```
        {% set firstname = "<script>alert('XSS')</script>" %}
        {{ 'Welcome back :user'|_({user: firstname}) }}```

and value is properly escaped. 

thanks
