### ISSUE TITLE
Indirect modification of overloaded property in TranslatableModel 

### ISSUE THREAD

**Issue by v-bubar** [rainlab/translate-plugin#558]
I used October CMS build 458  and RainLab.Translate version 1.6.2 and had no problems. 
Now i've started a new project with October CMS 464 and RainLab.Translate version 1.6.7.
Now I'm getting this:
```
"Indirect modification of overloaded property RainLab\Pages\Classes\MenuItem::$morphMany has no effect" on line 28 of /home/vagrant/code/andevent74/plugins/rainlab/translate/behaviors/TranslatableModel.php
```

It happens for example when I'm opening a backend table with models that implement `TranslatableModel` behavior.

**Comment by mjauvin** [comment]
I am using the same versions you are and I am not getting this error.

What plugins do you use? Did you extend any plugins?

**Comment by v-bubar** [comment]
@mjauvin Yes, in fact I use my own version of Pages Plugin, that, in turn utilises `TranslatableModel`.

**Comment by mjauvin** [comment]
Ok, in your plugin, did you add $morphMany relations by any chance?

**Comment by mjauvin** [comment]
Can you share the code in your model related to the morphMany relation?

I tried to reproduce this and couldn't.

**Comment by v-bubar** [comment]
@mjauvin It is the `RainLab\Pages\Classes\MenuItem` class from the said Pages plugin. I've double-checked it, and it has no other changes apart from implementing the `TranslatableModel` behavior  and no morphMany relations defined by me explicitly. 
However since `MenuItem` is not an Eloquent model there is some kind of conflict between its parent classes and `TranslatableModel`. I still can't say anything in specific, but at least I know now where to look.

**Comment by mjauvin** [comment]
But you can't implement TranslatableModel if it's not a Model...

**Comment by v-bubar** [comment]
@mjauvin It is not an **Eloquent** model. It is a Halcyon model, which is surely not the same thing but until some point was close enough to use with `TranslatableModel`.

Anyways, I think found what I was doing wrong,  it is really my fault and not a Plugin bug, so sorry for bothering...
