### ISSUE TITLE
Issue with longer then 191 chars code

### ISSUE THREAD

**Issue by flyingbaba** [rainlab/translate-plugin#571]
A bit strange behavior with translatable messages then they are longer then 191 chars. The code field in DB is 191 chars, but in Message model function makeMessageCode($messageId) returns a string limited to 250 symbols. I think here is a bug, but you should know better.

return Str::limit(trim($messageId, $separator), 250);

**Comment by mjauvin** [comment]
#566 will take care of this.

In the mean time, I suggest two alternatives:
* use a short *key* and add both a default language translation and the other translation(s) on the Translate Messages page
* use translatable content blocks (https://github.com/rainlab/translate-plugin/blob/master/README.md#content-translation)

**Comment by flyingbaba** [comment]
Sure, thanks for suggestions !
