### ISSUE TITLE
Indentation issue

### ISSUE THREAD

**Issue by adrenth** [rainlab/translate-plugin#574]
https://github.com/rainlab/translate-plugin/blob/bf83bfb5a569577506242527689043be4700ce2c/updates/version.yaml#L79

This breaks all build processes on our side :-(

**Comment by bennothommo** [comment]
Thanks for letting us know @adrenth - fixed as of https://github.com/rainlab/translate-plugin/commit/4aac31562191f79a9ed018ed7f81b6c9a95f2460.

**Comment by adrenth** [comment]
Not sure if your change has any effect for users who have already downloaded 1.7.0. Does this change appear in version 1.7.1 or do I have to stick with version 1.16.* for now.

**Comment by bennothommo** [comment]
@adrenth I believe the Symfony Yaml parser would've seen it as part of the array for 1.6.10 so it wouldn't have registered as a new version available to people if they use the Backend to update plugins.

As for Composer, it would've downloaded the changes regardless, it just wouldn't have registered that 1.7.0 is installed. If you run `php artisan october:up` after downloading the fix above, it should register 1.7.0 as being installed.

The version had only been out for about 24 hours at that point so hopefully it didn't go out to too many people.

**Comment by rubenvanerk** [comment]
@bennothommo release [1.7.0](https://github.com/rainlab/translate-plugin/releases/tag/1.7.0) does _not_ include the fix and breaks our builds..

**Comment by bennothommo** [comment]
@rubenvanerk Could you provide a little more info for us - when you mean it breaks your builds, are you saying that something in the most recent version isn't working? Did you update via Composer or via the Backend?

**Comment by rubenvanerk** [comment]
@bennothommo 
I'm using composer to require version `~1.6`. This resolves to version `1.7.0`. Version `1.7.0` points to commit https://github.com/rainlab/translate-plugin/commit/bf83bfb5a569577506242527689043be4700ce2c which means the fix you pushed (https://github.com/rainlab/translate-plugin/commit/4aac31562191f79a9ed018ed7f81b6c9a95f2460) for the indentation issue is not included in version `1.7.0`

**Comment by bennothommo** [comment]
Ah right, the tag is pointing to the old commit. I'll sort that out now.

**Comment by bennothommo** [comment]
I've tagged [version 1.7.1](https://github.com/rainlab/translate-plugin/releases/tag/1.7.1) with the fix in place. This should hopefully filter out to all installs properly now. Sorry for the confusion.

**Comment by rubenvanerk** [comment]
Thank you!
