### ISSUE TITLE
Different languages = different files

### ISSUE THREAD

**Issue by Zmove** [rainlab/translate-plugin#578]
Hello,

I red many threads about the translation of title and description of uploaded files for fileupload widget, but none about the possibility to upload a file for one language, and another file for another language, which can be a very common case when you use fileupload widget to upload PDF of text files and not images.

Is it possible actually, if yes, how ? (I tried to just add the fileupload relation to the list of translatable fields, it does not seems to do the job)

**Comment by mjauvin** [comment]
No, this is not currently possible.

The only way for now is to use a field of type `mediafinder` and make that field translatable.
