### ISSUE TITLE
Similar strings are getting treated as a single one

### ISSUE THREAD

**Issue by hugochinchilla** [rainlab/translate-plugin#585]
Hi

in my site I have a place where I have the string `contact` and another where I have the string `CONTACT:`.

In the translations panel only the later is found, in places where `contact` should be shown, `CONTACT:` is shown instead.

I have tried purging and rescanning, but the problem persists.

**Comment by igor-tv** [comment]
You can use twig filters in your templates to manage words cases.

**Comment by mjauvin** [comment]
Message translation currently does not differentiate between two strings with different casing.

**Comment by hugochinchilla** [comment]
Ok that makes sense. But one of the strings contains a colon and the other
does not.

**Comment by mjauvin** [comment]
Please see this method to understand the what's happening:

https://github.com/rainlab/translate-plugin/blob/master/models/Message.php#L286:L305

Note that you should use a unique key which can have a translation in all your locales.

**Comment by hugochinchilla** [comment]
Thanks for the clarification.
