### ISSUE TITLE
when switching languages via AJAX, the generated URLs are not valid 

### ISSUE THREAD

**Issue by perseon** [rainlab/translate-plugin#588]
Hi, 
Thanks for this great plugin, though I have a small issue that i'd like to know whether it's a known limitation or I'm messing up things. 
When I use the language switcher on a website I work (en is main language, es is secundary) everything switches just fine, but, the URL in the address bar is missing the "es" segment, which also works just fine _ONLY_ if yo're visiting that link on a "es" session, else you get a page not found error. 
Now, I could try to add a fix to  the  onSwitchLocale() to force the "es" segment but this is an inelegant solution since I hope it was already addressed. 
If needed I will provide the website's link. 

Thank you for your help!

**Comment by mjauvin** [comment]
Just set the LocaleSwitcher option to true when adding the component:

https://github.com/rainlab/translate-plugin/blob/master/components/LocalePicker.php#L50,L57

**Comment by perseon** [comment]
I'm sorry, I've missed that flag. It's not documented anywhere, though. 

Thank you!

**Comment by mjauvin** [comment]
Feel free to submit a PR to document it.

--
Marc
