### ISSUE TITLE
How to extend the plugin, add already translatable field to the index?

### ISSUE THREAD

**Issue by igor-tv** [rainlab/translate-plugin#593]
I am trying to add a model field to the index that is already translatable.
```
public function boot()
{
    Event::listen('backend.form.extendFieldsBefore', function($widget) {
    \Foo\Example\Models\Bar::extend(function($model) {
        $model->addDynamicProperty('translatable', [['name', 'index' => true]]);
        // I tried other code like this:
        // $model->translable = [['name', 'index' => true]];
        // $model->translable[] = [['name', 'index' => true]];
    });
}
```
But this had no effect.

Expandable model has:
```
public $implement = ['@RainLab.Translate.Behaviors.TranslatableModel'];
public $translatable = ['name']; 
```

**Comment by mjauvin** [comment]
Use this:
```
$model->translatable = array_replace($model->translatable, [['name', 'index' => true]]);
```

**Comment by igor-tv** [comment]
It doesn't work for me, no changes.

**Comment by mjauvin** [comment]
```
public function boot()
{  \Foo\Example\Models\Bar::extend(function($model) {
      $model->translatable = array_replace($model->translatable, [['name', 'index' => true]]);
    });
}

**Comment by igor-tv** [comment]
Sorry, maybe I'm doing something wrong or I don't notice something. But I checked several times and couldn't find the problem. It doesn't work for me.

Here is my real code and output from xDebug:
<img width="1039" alt="Снимок экрана 2020-08-15 в 13 39 34" src="https://user-images.githubusercontent.com/6777469/90310785-953b3900-defd-11ea-804f-3d5515c795f4.png">

If I change the PropertyValue model directly (`public $translatable = [['value', 'index' => true]];` instead `$translatable = ['value'];`), then the output in xDebug is:
<img width="1044" alt="Снимок экрана 2020-08-15 в 13 48 27" src="https://user-images.githubusercontent.com/6777469/90310862-3924e480-defe-11ea-932d-42512d262449.png">

**Comment by mjauvin** [comment]
in your screenshot above, you used "translable"... instead of translaTAble

**Comment by igor-tv** [comment]
> in your screenshot above, you used "translable"... instead of translaTAble

Many thanks! I'm sorry I wasted your time. I will check spelling errors carefully.
