### ISSUE TITLE
Redirect to 404 on untranslated static pages

### ISSUE THREAD

**Issue by satezmedia** [rainlab/translate-plugin#594]
Hello, please is possible to achvieve this behavior?

SK=Slovak language (default)
EN=English

When you **change your web language to EN** and you try to access **page Contact wich doesn't have any EN translations** it should **return 404 page.**

Thanks for your plugin and your time.

**Comment by mjauvin** [comment]
It's not really possible currently. Why exactly do you need this?

**Comment by satezmedia** [comment]
Hi,
we got it working!

`Event::listen('cms.page.init', function ($controller, $page) {
            if (!isset($page->apiBag['staticPage'])) {
                return;
            }

            $translator = Translator::instance();
            $lang = $translator->getLocale();
            $defaultLang = $translator->getDefaultLocale();

            if ($defaultLang == $lang) {
                return;
            }

            $path = sprintf(
                '%s/content/static-pages-%s/%s',
                themes_path(Theme::getActiveThemeCode()),
                $lang,
                $page->apiBag['staticPage']->fileName
            );

            if (file_exists($path)) {
                return;
            }

            return Redirect::to(Page::url('404')));
        });`

**Comment by LukeTowers** [comment]
@satezmedia instead of `Redirect::to(Page::url('404'));` you should probably try `Response::make($controller->run('404'), 404);`
