### ISSUE TITLE
Translating long texts without a short key

### ISSUE THREAD

**Issue by jomsky** [rainlab/translate-plugin#595]
I'm probably doing something wrong but when I do this:

`{{ content.section_text|_ }} `

The data is from a richeditor field in the backend:

![tr](https://user-images.githubusercontent.com/1947654/90720451-2426c780-e2e9-11ea-928d-bb304a1163ff.png)

 and if it holds a long paragraph I'm getting an error: 

`String data, right truncated: 1406 Data too long for column 'code' at row 1 (SQL: insert into 'rainlab_translate_messages' ('code', 'message_data')`

I understand that I should use a  short key for the code column but how do I handle it in this case when `content.section_text` can have different values on each page? 

I tried making the field translatable but I can't make it work, even on non repeater fields. The translatable property does not do anything to any forms on my plugins. Should I add something else for it to work? It's working fine on the CMS page though. 
Here's a screenshot from my yaml file on plugins/testauthor/forms/models/form/form-content-fields.yaml:

![rt2](https://user-images.githubusercontent.com/1947654/90720781-db234300-e2e9-11ea-8237-fbe328dd4e58.png)

Thanks!

**Comment by mjauvin** [comment]
You need to follow the instructions here:

https://github.com/rainlab/translate-plugin#model-translation

**Comment by mjauvin** [comment]
Note that you can't translate individual fields in a repeater... you need to make the repeater field itself translatable and create an instance of the repeater per language.
