### ISSUE TITLE
Why isn't the translation plugin updated at https://octobercms.com/plugin/rainlab-translate

### ISSUE THREAD

**Issue by uvolovik** [rainlab/translate-plugin#596]
This plugin has 1.7.2 version on GitHub, but octoberCMS has latest version - 1.6.7
Please, update plugin for octoberCMS https://octobercms.com/plugin/rainlab-translate

**Comment by mjauvin** [comment]
Did you enable edgeUpdates in your config/cms.php ?

**Comment by dynamiccontent** [comment]
> 
> 
> Did you enable edgeUpdates in your config/cms.php ?

By default edgeUpdates on config/cms.php is set to false. Once you set it to true the plugin updates fine. Maybe a note that on update page it says "Action required" but if you click on "View upgrade guide" it's empty. Other than that it's fine. Thanks!

Link for "Action required" -> https://example.com/backend/system/updates/details/rainlab-translate/upgrades?fetch=1
![Upgrade Guide](https://i.imgur.com/PSiRDRt.png)

![Upgrade](https://i.imgur.com/OMfRxUK.png)
