### ISSUE TITLE
Loss of menu item translations

### ISSUE THREAD

**Issue by igor-tv** [rainlab/translate-plugin#598]
CURRENT BUILD 468
RainLab.Translate 1.7.2
RainLab.Pages 1.3.5

When I edit translations of menu items, when I switch the language, already made translations are lost in the input. If I re-fill the empty translation fields, they remain, but after clicking the Apply button in the modal window, there is only one translation left, and the one that was active before applying.

I've tried removing the plugin and reinstalling it from the marketplace (using edgeUpdates). Problem still exists. Also I tried to recompile assets (`php artisan october: util compile js` `php artisan october: util compile less`), `composer dump autoload`, clear browser cache and cms cache, but that also didn't help.

I guess the problem here is in the js language context change handler.

![Sep-01-2020 05-47-31](https://user-images.githubusercontent.com/6777469/91789167-b9de2300-ec16-11ea-9b91-5236650dc4b8.gif)

On a clean system, there is no such problem, everything works as expected.

I haven't extended the Translate plugin myself. Additional plugins installed on my system:

- Mail Translatable
- Translate Extended
- Extend translate plugin

I tried disabling them, but that didn't seem to affect the problem in any way.

**Comment by mjauvin** [comment]
The the plugin "Extend translate plugin" you are using does not allow a single menu to be translated in multiple languages, it allows creation of multiple menus, one per language.

Please see the plugin documentation.

**Comment by mjauvin** [comment]
Are you sure you didn't install the RainLab.Translate plugin using git? Because such functionality has been merged, but the counterpart in RainLab.Pages also needs to be installed... this code has not been released yet.

**Comment by igor-tv** [comment]
Yes, first I installed the RainLab.Translate plugin using git. But then I removed it through the backend and installed it from the marketplace.

At the moment, removing the plugin "Extend translate plugin" has had no effect. Also I tried reinstalling Rainlab.Translate again. Hasn't helped yet.

**Comment by mjauvin** [comment]
You definitely have the git version still installed, or you wouldn't see the Static Menu title/url fields as translatable...

I suggest installing both RainLab.Translate/Pages from git, remove the extended translate plugin and you should be good to go.

**Comment by igor-tv** [comment]
This helped fix the problem. Many thanks!
