### ISSUE TITLE
Exception when doing Unit Test

### ISSUE THREAD

**Issue by RodrigoGalter** [rainlab/translate-plugin#599]
I'm creating unit tests but I'm experiencing problems running phpunit, I always get the message

`Exception: Class System\Models\File has already been extended with October\Rain\Database\Behaviors\Purgeable`

By commenting on the following lines in **Plugin.php** I can run without major problems.

`$model->extendClassWith('October\Rain\Database\Behaviors\Purgeable');`
`$model->extendClassWith('RainLab\Translate\Behaviors\TranslatableModel');`

Something similar to #546 , I tried to add the lines indicated by @LukeTowers but did not succeed.

This happens in the L6 branch of October.

**Comment by mjauvin** [comment]
@LukeTowers should we wrap the `extendClassWith()` calls with a conditional check to see if it has been extended already?

**Comment by LukeTowers** [comment]
@mjauvin I believe we had that discussion with @daftspunk a while ago and decided against it. This should have been fixed in https://github.com/octobercms/library/commit/1460bc00a0a7bc1a8db2a39354e0eb3499b750d2 though, @RodrigoGalter are you able to confirm that commit is present in your installation?

**Comment by RodrigoGalter** [comment]
Yes.

october/backend: [979d94b4220dd01441a7585bca31f7ab13e2b133](https://github.com/octoberrain/backend/commit/979d94b4220dd01441a7585bca31f7ab13e2b133)
october/cms: [e466884f83762af98305132f8d324c92e6e58680](https://github.com/octoberrain/cms/commit/e466884f83762af98305132f8d324c92e6e58680)
october/rain: [e33163d5b288f05ffec66ab9e55ee96c1457164b](https://github.com/octobercms/library/commit/e33163d5b288f05ffec66ab9e55ee96c1457164b)
october/system: [f7453c384cdbd1fe6e680682077c7bd42160ef4d](https://github.com/octoberrain/system/commit/f7453c384cdbd1fe6e680682077c7bd42160ef4d)

laravel/framework: 6.18.38

**Comment by LukeTowers** [comment]
@bennothommo can you look into this?

**Comment by bennothommo** [comment]
@LukeTowers I've tested this with the `wip/laravel-6` branch as part of https://github.com/rainlab/translate-plugin/pull/600 and the tests seem to be running fine for the plugin (although there is a test that is actually failing).

@RodrigoGalter before I can investigate further, I'll need some more information on the type of test you are running and where it is located.

**Comment by RodrigoGalter** [comment]
I run a simple assertTrue(true) test to test my configuration, right after I did a test to create a record on my mobile.
The tests are located in the test/ folder within the plugin folder in question.

**Comment by daftspunk** [comment]
Tests here are no longer used due to refactoring. We will revive them once the code matures. Documentation on unit testing plugins can be found here: https://docs.octobercms.com/3.x/extend/system/unit-testing.html

Thanks!
