### ISSUE TITLE
Setting 'prefixDefaultLocale' to false and 'forceUrl' to 1 removes the prefix on relative links.

### ISSUE THREAD

**Issue by jomsky** [rainlab/translate-plugin#601]
Relative links don't automatically include the selected language prefix when navigating if prefixDefaultLocale is set to false. I have to manually add the prefix on each link when the default language is not chosen. Not sure if this is a bug or I'm just doing something wrong. When **forceUrl** is true this is not a problem. I can click on links and still retain the current selected language.

**Comment by mjauvin** [comment]
just use the forceUrl=true property of the localePicker component

**Comment by mjauvin** [comment]
ref. https://github.com/rainlab/translate-plugin/blob/master/components/LocalePicker.php#L50,L55

**Comment by jomsky** [comment]
Yes that is one of the condition to reproduce the issue. I already have forceUrl set to 1 in the component. If it's set to false then there's no issue, navigating retains the current selected language.

**Comment by mjauvin** [comment]
In the problem description, you first say this happens when prefixDefaultLocale is set to true, then towards the end you say it's fine when prefixDefaultLocale is set to true... which is it? 

How exactly do you generate those "relative" links?

**Comment by jomsky** [comment]
Sorry updated the description. I meant forceURL.  Most of the links are via onclick js events that uses window.location.href after an ajax request.

**Comment by mjauvin** [comment]
this is not the proper way to do this, you should use the `page` twig filter that would properly create the URLs.

Can you explain a bit more what you're trying to do and show some code?

**Comment by jomsky** [comment]
Ohhh didn't know about the `page` filter. I was using `url()` on my html links as well. Just changed one and it worked. Thank you!
