### ISSUE TITLE
Angle brackets and double quotes (`<`, `>`, `"`) rendered incorrectly inside plugin's documentation on octobercms.com

### ISSUE THREAD

**Issue by spartanatreyu** [rainlab/translate-plugin#604]
The documentation on <https://octobercms.com/plugin/rainlab-translate> shows code examples like:

```php
Event::listen('translate.localePicker.translateParams', function($page, $params, $oldLocale, $newLocale) {
    if ($page-&gt;baseFileName == 'your-page-filename') {
        return YourModel::translateParams($params, $oldLocale, $newLocale);
    }
});
```

```twig
{{ form_open() }}
&lt;select id='I18N_SELECT'&gt;
    &lt;option value=&quot;none&quot; hidden&gt;&lt;/option&gt;
    {% for code, name in locales %}
        {% if code != activeLocale %}
            &lt;option value=&quot;{{code}}&quot; name=&quot;locale&quot;&gt;{{code | upper }}&lt;/option&gt;
        {% endif %}
    {% endfor %}
&lt;/select&gt;
{{ form_close() }}
```

where the `<`, `>` and `"` characters are displayed as `&lt;`, `&gt;` and `&quot;`.

**Comment by bennothommo** [comment]
@LukeTowers is this due to some double-encoding happening on the marketplace?

**Comment by mjauvin** [comment]
@bennothommo it would make sense since it's properly rendered on github...

**Comment by LukeTowers** [comment]
Yes @bennothommo, it's something that @daftspunk is going to have to fix.

**Comment by mjauvin** [comment]
@daftspunk anything you can do about this?

**Comment by spartanatreyu** [comment]
It's been a year next week and I can still see stuff like: `&lt;option value=&quot;none&quot; hidden&gt;&lt;/option&gt;`

**Comment by daftspunk** [comment]
Hi @spartanatreyu 

Thanks for following up. This was fixed a while ago but the product itself needed to be updated
