### ISSUE TITLE
Translated slug allows duplicates

### ISSUE THREAD

**Issue by buzmate** [rainlab/translate-plugin#610]
Hello,

Just need to confirm a "bug" of feature or the translate plugin. Although indexing works fine with the translated slug of a model it seems that the translated slug is not tested for duplication as it happens with the default, not translated, value of the field. Are there any solutions to this issue? Is there an event that we can bind too and test for duplication on translated fields? is there an easy way to retrieve all translated entries of a specific model's field and for specific locale and test for duplication?

Thanks.

**Comment by mjauvin** [comment]
Can you give a specific example for this?

**Comment by buzmate** [comment]
`<?php namespace Buzmate\Catalog\Models;

use Model;

/**
 * Model
 */
class Product extends Model
{
    use \October\Rain\Database\Traits\Validation;
    
    use \October\Rain\Database\Traits\SoftDelete;

    use \October\Rain\Database\Traits\Sluggable;

    protected $dates = ['deleted_at'];

    protected $slugs = ['slug' => 'title'];

    /**
     * @var string The database table used by the model.
     */
    public $table = 'buzmate_catalog_product';

    public $belongsTo = [
    'category' => 'Buzmate\Catalog\Models\Category'
    ];
    
    public $implement = ['RainLab.Translate.Behaviors.TranslatableModel'];
    
    public $translatable = ['title', ['slug', 'index' => true], 'summary', 'description']; 
    
    protected $jsonable = ['images','file'];
    
    /**
     * @var array Validation rules
     */
    public $rules = [
    ];
}
`
The above model uses title as slug. When creating a product with the same name as another the slug is appended with a number automatically in order to prevent duplication. For example I have two products called "Rust Cleaner" the first slug will be "rust-cleaner" and the second item's slug will be "rust-cleaner-2". Even if I manually change the slug the Sluggable trait with find the duplication and append the "-2" automatically to prevent aliasing. 

This works just fine if I have the name and slug translatable but only for the default language. When I assign a translation to the slug field the test doesn't happen and thus allowing multiple models of "Product" to have the same slug causing aliasing.

**Comment by mjauvin** [comment]
I believe this [abandoned PR](https://github.com/rainlab/translate-plugin/pull/535) is related to your problem.

**Comment by buzmate** [comment]
Yeap true. OK I will check it out.

**Comment by daftspunk** [comment]
This should be fixed in Translate v2 since the logic has been rewritten to adhere to attribute workflows, including validation and sluggable.
