### ISSUE TITLE
Home page not work when place component in the layout with static page

### ISSUE THREAD

**Issue by WebCreamGroup** [rainlab/translate-plugin#612]
There is bug when try to change language in home page `/` with static page and static menu placed to layout.
```
Missing required parameters for [Route: ] [URI: lv/{slug}].").
```

**Comment by mjauvin** [comment]
What version of October and RainLab.Translate do you use?

**Comment by mjauvin** [comment]
This error lets me think you are using v 1.1 (using Laravel 6) and the latest RainLab.Translate is needed.

You'll need to set edgeUpdates=true in `config/cms.php` since this has not been marked stable yet.

**Comment by mjauvin** [comment]
We marked the latest RainLab.Translate release (v1.7.3) as stable, so you should be able to update without setting cms.edgeUpdates to true.

**Comment by mjauvin** [comment]
Please let us know if that resolves your issue so we can close this.

**Comment by WebCreamGroup** [comment]
First i want to say **thank you for the fast answer and for the help**.

Yes, i just made update for the `Translate` plugin and now seems that all works perfect.

P.S. I have noticed 2 things (maybe bugs) related to the `RainLab.Translate` plugin, so i will open another 2 issues.
