### ISSUE TITLE
Markdown syntax field ( {variable type="markdown"} ) is not translatable

### ISSUE THREAD

**Issue by WebCreamGroup** [rainlab/translate-plugin#613]
I have noticed that markdown field type has no translation dropdown.

Field type placed via `{variable}` to the layout.

**Comment by mjauvin** [comment]
Please provide more details.

**Comment by WebCreamGroup** [comment]
I have use plugins:
- RainLab.Translation
- RainLab.Pages

When in the layout i place code like this:
```
{variable name="title" label="Title" type="text"}{/variable}
{variable name="content" label="Content" type="markdown"}{/variable}
```

Result in the editor mode *(In the static page editing area provided by plugin `RainLab.Pages`)*:
- `title` field successfully uses translations dropdown provided by plugin `RainLab.Translation`
- `content` field does not uses translations dropdown

I have noticed that `WYSIWYG` editor also works perfect like other fields types with multilanguage, but only `markdown` field type don't want to use `RainLab.Translation` language dropdown

**Comment by mjauvin** [comment]
You're right, I'll have to dig further into this to find what the reason is.

Thanks.
