### ISSUE TITLE
translatable="false" is not working if i use it in {variable}

### ISSUE THREAD

**Issue by WebCreamGroup** [rainlab/translate-plugin#614]
In some cases i think it will be good feature to use `translatable="false"` attribute to use in the `{variable}` in the layout.

**Comment by mjauvin** [comment]
Can you precise where you see this `translatable="false"` ?

**Comment by mjauvin** [comment]
why would you need this?

**Comment by WebCreamGroup** [comment]
For example when use field to describe link to static page, or wen use field type like code editor.

I think it could came in handy, that for some fields we can remove translatable feature.

I noticed that in the `form.yaml` this thing work perfectly, but in the `{variable}` not working at all.

**Comment by mjauvin** [comment]
What do you mean by "I noticed that in the form.yaml this thing work perfectly" ?

**Comment by mjauvin** [comment]
Field translation is OPTIONAL. Even though it's possible to translate a field does not REQUIRE it to be translated.

**Comment by LukeTowers** [comment]
@mjauvin is `translatable` a property that can be set on theme.yaml fields? And what is causing the syntax fields on CMS templates to be translated, could you point me at the code that handles that?

**Comment by mjauvin** [comment]
@LukeTowers yes, translatable is a property that has been added in this PR: https://github.com/rainlab/translate-plugin/pull/559

And for syntax fields, it is here: https://github.com/rainlab/pages-plugin/blob/master/controllers/Index.php#L610-L616

**Comment by LukeTowers** [comment]
@mjauvin can you update the RainLab.Pages code to detect if someone has set `translatable="false"` on the syntax field to exclude it from being automatically translated?

**Comment by mjauvin** [comment]
@LukeTowers I definitely can, but what's the point exactly?

**Comment by LukeTowers** [comment]
@mjauvin to give developers the freedom to say that a given field should not be translatable.

**Comment by mjauvin** [comment]
@LukeTowers Ok, but they can just leave it unstranslated, what's the real benefit?

**Comment by LukeTowers** [comment]
@mjauvin complete control over their end user's UX. Personally if I don't want a field translated as a developer then I don't even want to let my users see the option to translate it because they will, or they will possibly get confused by an extra unnecessary option.

**Comment by mjauvin** [comment]
fair enough @LukeTowers.

I've added this to PR https://github.com/rainlab/pages-plugin/pull/463
