### ISSUE TITLE
Model->fill() don't work if field is translatable

### ISSUE THREAD

**Issue by ref** [rainlab/translate-plugin#618]
I make my custom products import script with artisan command for OFFLINE/Mall plugin.

Simplify method for sample:

```php
...
$importItems = json_decode(file_get_contents($importFile), true);

foreach ($importItems as $item) {
    $product = Product::firstOrNew([
        'user_defined_id' => $item['article_no'],
    ]);

    $product->fill([
        'name' => $item['title_en'],
        'slug' => $slug,
        'additional_properties' => $someArray,
    ]);

    $product->save();
}
...
```

If table offline_mall_products empty, first import work great.

But if offline_mall_products has entries, then the field 'additional_properties' is not updated for an existing record.

$product->fill() work correctly if I delete 'additional_properties' from array $translatable in model OFFLINE\Mall\Models\Product.

Link to the Mall plugin issue — https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/614
@tobias-kuendig

**Comment by mjauvin** [comment]
@ref could you check if PR #606 solves your issue?

**Comment by mjauvin** [comment]
@ref did you have a chance to test if PR #606 solves your issue?

**Comment by ref** [comment]
> @ref did you have a chance to test if PR #606 solves your issue?

Yes, of cource. I need some days to test it. I reply after testing
