### ISSUE TITLE
Message translation don't work correctly if message in {% %} tags

### ISSUE THREAD

**Issue by ref** [rainlab/translate-plugin#620]
If i try translate message string in {% %} tags:

```twig
{% set arBreadcrumbs = [
    {'name': 'page.blog.breadcrumb_title'|_, 'url': '#'},
    {'name': blogPosts.category.name, 'url': '#'},
] %}
{% partial 'navigation/breadcrumbs' arBreadcrumbs=arBreadcrumbs %}
```

It's work, but i need clear cache and open CMS page on front end. And now i can see created variable in "Settings->Translate messages" page. But my variable have scan error status "Not found". 

And after, if i want change text, i need put new text, next click "Scan for messages", and refresh CMS page on front end. Without click "Scan for messages" new text  will be not show on front end page.

PS. Plz sorry for my english (:

**Comment by mjauvin** [comment]
The method that scan template files for translation messages is currently only searching for messages within `{{ }}` (see below):
```
    protected function processStandardTags($content)
    {   
        $messages = [];

        /*
         * Regex used:
         *
         * {{'AJAX framework'|_}}
         * {{\s*'([^'])+'\s*[|]\s*_\s*}}
         *
         * {{'AJAX framework'|_(variables)}}
         * {{\s*'([^'])+'\s*[|]\s*_\s*\([^\)]+\)\s*}}
         */

        $quoteChar = preg_quote("'");

        preg_match_all('#{{\s*'.$quoteChar.'([^'.$quoteChar.']+)'.$quoteChar.'\s*[|]\s*_\s*(?:[|].+)?}}#', $content, $match);
        if (isset($match[1])) {
            $messages = array_merge($messages, $match[1]);
        }

        preg_match_all('#{{\s*'.$quoteChar.'([^'.$quoteChar.']+)'.$quoteChar.'\s*[|]\s*_\s*\([^\)]+\)\s*}}#', $content, $match);
        if (isset($match[1])) {
            $messages = array_merge($messages, $match[1]);
        }

        $quoteChar = preg_quote('"');

        preg_match_all('#{{\s*'.$quoteChar.'([^'.$quoteChar.']+)'.$quoteChar.'\s*[|]\s*_\s*(?:[|].+)?}}#', $content, $match);
        if (isset($match[1])) {
            $messages = array_merge($messages, $match[1]);
        }

        preg_match_all('#{{\s*'.$quoteChar.'([^'.$quoteChar.']+)'.$quoteChar.'\s*[|]\s*_\s*\([^\)]+\)\s*}}#', $content, $match);
        if (isset($match[1])) {
            $messages = array_merge($messages, $match[1]);
        }

        return $messages;
    }
```

**Comment by mjauvin** [comment]
I suggest using localization strings as below:
```php
{% set arBreadcrumbs = [
    {'name': 'author.plugin::lang.page.blog.breadcrumb_title'|trans, 'url': '#'},
    {'name': blogPosts.category.name, 'url': '#'},
] %}
{% partial 'navigation/breadcrumbs' arBreadcrumbs=arBreadcrumbs %}
```

And add the localization string to your plugin's language file (e.g. `/plugins/author/plugin/lang/en/lang.php`)

**Comment by ref** [comment]
@mjauvin thanks for your answer! 

Look, I found a way to avoid the "not found" error.

I created a lang lang.yaml file and added some text messages:
```
en:
  page.blog.breadcrumb_title: 'Blog'
```

Then I added this variable to my page blog.htm:
```
{% set arBreadcrumbs = [
    {'name': 'page.blog.breadcrumb_title'|_, 'url': '#'}
] %}
{% partial 'navigation/breadcrumbs' arBreadcrumbs=arBreadcrumbs %}
```

And now, if I scan new messages, I don't see the "Not found" error and can change the message

![Screenshot 2020-11-04 at 15 54 34](https://user-images.githubusercontent.com/505388/98090028-1b8c6900-1eb6-11eb-9762-04b05eccbf58.png)

**Comment by LukeTowers** [comment]
@mjauvin I would recommend using the theme lang.yaml file over a backend translation provided by a plugin for any frontend stuff
