### ISSUE TITLE
Updating Model Attribute Issue with Translations

### ISSUE THREAD

**Issue by mahony0** [rainlab/translate-plugin#622]
I just want to update one of the attributes and it's translates of the model. Default selected language is turkish and trying this:

```php
$article = Article::find($this->article->id);

$article->short_desc = 'description in turkish';
$article->setAttributeTranslated('short_desc', 'description in english', 'en');
$article->setAttributeTranslated('short_desc', 'description in deutsch', 'de');

$article->save();
```

Like this way, EN and DE locales updating but original attribute of model (which is turkish) not updating. I tried using syncTranslatableAttributes() instead of save() but no luck.

**Comment by mjauvin** [comment]
Hello, what version of the plugin do you use?

**Comment by mjauvin** [comment]
Also, make sure the translation context is actually the default (TR in your case) before making an assignment without a language context, otherwise the current context will be used...
```php
$article->translateContext('tr');
$article->short_desc = 'description in turkish';
``` 
or
```php
$article->lang('tr')->short_desc = 'description in turkish';
```

**Comment by mahony0** [comment]
Thank you @mjauvin I also set App language and translate context to tr as well but was not work either.
I just solved this by using setAttributeTranslated for also tr language. So working final code is:

```php
$article->setAttributeTranslated('short_desc', 'description in turkish', 'tr');
```

It seems this is not a real issue but how to use the plugin.
