### ISSUE TITLE
transWhere more the one index

### ISSUE THREAD

**Issue by bmiskoski** [rainlab/translate-plugin#624]
Hello to all.

This is more of a question then an issue.

I want to use the index option for the translatable fields on more then one field. For example all the given examples are with the index being on the slug, i would also like to include the name field as index so that i can use the transWhere query on it.

Also related issue, can the transWhere usability be extended to include search queries such as: 
transWhere('slug', '!=', $this->param('slug')).

**Comment by mjauvin** [comment]
> I want to use the index option for the translatable fields on more then one field. For example all the given examples are with the index being on the slug, i would also like to include the name field as index so that i can use the transWhere query on it.

You can include as many fields with an index as you want, in your case:
```
public $translatable = [
   ['slug', 'index' => true],
   ['name', 'index' => true],
];
```
> Also related issue, can the transWhere usability be extended to include search queries such as:
> transWhere('slug', '!=', $this->param('slug')).
Yes, but you have to follow the method's signature:
```
scopeTransWhere($query, $index, $value, $locale = null, $operator = '=')
```
So you would need to use the following syntax:
```
transWhere('slug', $this->param('slug'), null, '!=')
```

**Comment by bmiskoski** [comment]
And I'm assuming for using the LIKE operator it would be like this?

transWhere('name', '%' . $comparedKeyword. '%', null, 'LIKE')

**Comment by mjauvin** [comment]
That's right.

**Comment by bmiskoski** [comment]
So I've indexed the name field in the model and run the following query: 

$products = Product::where('name', '%' . $comparedKeyword  . '%', null, 'LIKE')->orderBy('name', 'asc')->get();
** $comparedKeyword  is user input **

And got the following error:

![transWhere-exception](https://user-images.githubusercontent.com/58108005/99417743-8ef09a80-28fa-11eb-99ff-858dea3dde19.png)

Apparently the '=' operator remains although I've overridden it.

Am i missing something? Sorry for the constant bother :D

**Comment by mjauvin** [comment]
You're using the transWhere() scope signature... the where signature is different

**Comment by bmiskoski** [comment]
That was a stupid mistake ...

After correcting the mistake I still couldn't get the desired results.

So i converted the query to SQL and manually tested the database.

The results as follows:

In the en locale (the default) i get the desired results, i get all the related products except the ones that i am currently viewing (based on the slug of the product)

![en-slug](https://user-images.githubusercontent.com/58108005/99529982-f9f4ac80-29a0-11eb-8007-21a4f0f602a1.png)

In the mk locale i get all the related products including the one that i am currently viewing (also based on the slug).

![mk-slug](https://user-images.githubusercontent.com/58108005/99530087-214b7980-29a1-11eb-9ffc-8617f349c79e.png)

And here is the entry in the rainlab_translate_attributes table.

![data-translate-attributes](https://user-images.githubusercontent.com/58108005/99530169-3fb17500-29a1-11eb-9e51-173ab791bcb2.png)

I have tested the locale with 'en' and 'mk' and still got the same results (in the images above is left as empty string assuming that is the result from the null).

The end result should be as in the en locale test on the first image. Am i missing something?
