### ISSUE TITLE
Translatable file attachments

### ISSUE THREAD

**Issue by patrick-durrer** [rainlab/translate-plugin#630]
This is a follow up to #113. 

For the implementation of multilingual websites we often cannot use the actual fileuploader because the files only can be added  generally without any relation to a language. Especially if there is text on a picture or a document with text in it. We then have to switch to the mediafinder or create a separate attachment for each language: `image_de`,` image_en`, `image_fr` etc. We would like to solve this via the fileuploader that we like very much (apart from this).

Visualisation example: 

![Example for multilingual File-Upload](https://user-images.githubusercontent.com/15232963/103216989-c00bb400-4917-11eb-8f69-b8087ced9c9b.png)

How realistic do you see this feature being implemented? If there is a general need for this, we would like to post a bounty (200$) for this feature.

**Comment by mjauvin** [comment]
File uploads are implemented using the `system_files` db table and the fields `attachment_type` contains the Model class to which the file is attached and `attachment_id` contains that model record id ...

Not sure how easy it would be to work with this in order to add a different attachment per language using the current RainLab.Translate plugin.

Ideas?

**Comment by massimomegistus** [comment]
Hi guys,
two years ago I developed a plugin for this purpose
- it includes a custom File model that extends System\Models\File, where file_name, file_size, content_type and disk_name are translatable just like title and description. Something like
    public $translatable = [
        'title',
        'description',
        'file_name',
        'file_size',
        'content_type',
        'disk_name'
    ];
It overrides afterDelete() to remove the upload for each language whenever a file is removed

- the TRFileField formwidget displays a tab for each language and manage the file uploads
<img width="944" alt="TRFileField" src="https://user-images.githubusercontent.com/39944924/103228396-06b9d800-4931-11eb-9620-748ca3e6e5b1.png">
For non default languages, the Delete checkbox let you remove the upload translation, and the Upload button let you choose a new file

- the TRFileUpload Field, that uses TRFileField
<img width="660" alt="TRFileUpload" src="https://user-images.githubusercontent.com/39944924/103228521-513b5480-4931-11eb-9d32-54680ed91f8b.png">

I can't say if it's the best approach.
If you want, I could send the code as a starting point.

Massimo

**Comment by mjauvin** [comment]
@massimomegistus nice, thanks for sharing!

Please do send the code for this.

**Comment by tobias-kuendig** [comment]
This is looking great @massimomegistus!

A few thoughts on this implementation:

> it includes a custom File model that extends System\Models\File, where file_name, file_size, content_type and disk_name are translatable just like title and description.  It overrides afterDelete() to remove the upload for each language whenever a file is removed

This should be doable without using a separate model but by using `::extend` and the [model.afterDelete](https://octobercms.com/docs/api/model/afterdelete) Event.

> the TRFileField formwidget displays a tab for each language and manage the file uploads

This would be a great starting point to get the design in-line with October's usual translatable fields where you toggle it using the language selector instead of tabs.


Does `->thumb()` on translated image uploads still work as expected? What about eager loading the relations?

**Comment by massimomegistus** [comment]
Hi @tobias-kuendig, I agree with you, ::extend and model.afterDelete could replace the separate model
I did not test ->thumb() method yet, but I think it should work.
Adding {field_name}.translations to a scope, Eager loading works ad expected
$query->with([
   'translations',
   'images.translations'
]);

@mjauvin, unfortunately it isn't in marketplace.
In the attached bnkr.zip you can find the Media plugin and a Library plugin to test it
Install Rainlab.Translate, add the plugins/bnkr folder and then run
_php artisan october:up_

use the Bnkr\Media\Models\File in $attachMany
public $attachMany = [
        'attachments' => [
          **'Bnkr\Media\Models\File',**
          'order' => 'sort_order',
          'delete' => true
        ],
];

and in model fields.yaml use the trfileupload widget passing translateFile: true to display the tabs
  attachments:
            label: Attachments
            comment: If the post have at least one attachment the File icon will be shown in its preview
            mode: file
            **type: trfileupload**
            translateFile: true
            attachOnUpload: true
            span: auto
            tab: Uploads
[bnkr.zip](https://github.com/rainlab/translate-plugin/files/5750093/bnkr.zip)

The plugin adds also a Folder Model and two additional fields to system_file: please, ignore these features.

Massimo

**Comment by mjauvin** [comment]
@massimomegistus why is the line that implements the `TranslatableModel` commented out in your File model? Is it because we eventually added this in RainLab.Translate ?

**Comment by massimomegistus** [comment]
@mjauvin correct. This plugin was developed before title and description became translatable, so I commented the "public $implement" line

**Comment by shoguniphicus** [comment]
> Hi @tobias-kuendig, I agree with you, ::extend and model.afterDelete could replace the separate model I did not test ->thumb() method yet, but I think it should work. Adding {field_name}.translations to a scope, Eager loading works ad expected $query->with([ 'translations', 'images.translations' ]);
> 
> @mjauvin, unfortunately it isn't in marketplace. In the attached bnkr.zip you can find the Media plugin and a Library plugin to test it Install Rainlab.Translate, add the plugins/bnkr folder and then run _php artisan october:up_
> 
> use the Bnkr\Media\Models\File in $attachMany public $attachMany = [ 'attachments' => [ **'Bnkr\Media\Models\File',** 'order' => 'sort_order', 'delete' => true ], ];
> 
> and in model fields.yaml use the trfileupload widget passing translateFile: true to display the tabs attachments: label: Attachments comment: If the post have at least one attachment the File icon will be shown in its preview mode: file **type: trfileupload** translateFile: true attachOnUpload: true span: auto tab: Uploads [bnkr.zip](https://github.com/rainlab/translate-plugin/files/5750093/bnkr.zip)
> 
> The plugin adds also a Folder Model and two additional fields to system_file: please, ignore these features.
> 
> Massimo

Thanks! Brilliant solutions. This plugin should be included as core translatable.

**Comment by massimomegistus** [comment]
@shoguniphicus I'm glad you like it!
Here the new version that I'm working on, adapted to OctoberCms; For Seo reasons, the File model adds a slug prefix; maybe I'll add a console command to UNDO / REDO this task.
[bnkr_oc2.zip](https://github.com/rainlab/translate-plugin/files/8834360/bnkr_oc2.zip)
2

**Comment by daftspunk** [comment]
Support for translatable file attachments has been added in RainLab.Translate v2.1.0

Now you can add the relation name to the translatable attributes property. For example:

```
/**
 * @var array translatable attributes
 */
public $translatable = [
    'myimage'
];

/**
 * @var array attachOne relation
 */
public $attachOne = [
    'myimage' => \System\Models\File::class
];
```

Each attachment will be unique to the locale, however there is no fallback support, so each locale needs to be uploaded separately. A solution to this could be two define two attachments, one for fallback, one for translation.

I hope this helps.
