### ISSUE TITLE
Literal 1 in plural choice string causes wrong string to be selected

### ISSUE THREAD

**Issue by jjfmarket** [rainlab/translate-plugin#631]
I have a plural choice translate string in my twig template:
`{{ '{0} Coming soon |{1} 1 Open Position|[2,Inf[ :count Open positions'|__(hiring.job_count, {count: hiring.job_count}) }}`

When hiring.job_count is 1, the selected string will be "Coming Soon", instead of the expected "1 Open Position"
Replacing the literal 1 in the singular string causes the proper string to be selected, these two examples both work as expected:
```
{{ '{0} Coming soon |{1} :count Open Position|[2,Inf[ :count Open positions'|__(hiring.job_count, {count: hiring.job_count}) }}
{{ '{0} Coming soon |{1} One Open Position|[2,Inf[ :count Open positions'|__(hiring.job_count, {count: hiring.job_count}) }}
```

Note that when using laravels transchoice filter, this issue does not occur
`{{ '{0} Coming soon |{1} 1 Open Position|[2,Inf[ :count Open positions'|transchoice(hiring.job_count) }}`

**Comment by daftspunk** [comment]
It appears that there may be an error in the code you have written.

```
{0} Coming soon |{1} 1 Open Position|[2,Inf[ :count Open positions
```

The code should be.

```
{0} Coming soon |{1} 1 Open Position|[2,Inf] :count Open positions
```
