### ISSUE TITLE
does not work with several locales in theme config

### ISSUE THREAD

**Issue by Brovtsin** [rainlab/translate-plugin#632]
Hello!
I have theme config file as bellow -
code: ''
translate:
en: config/lang-en.yaml
ru: config/lang-ru.yaml
de: config/lang-de.yaml
fr: config/lang-fr.yaml
es: config/lang-es.yaml
it: config/lang-it.yaml

And it didn't scan all the yml files , so to make it work I had to add such code -
 // $config = $theme->getConfigArray('translate'); // instead of this line 
        $locales = collect(LocaleModel::listEnabled())->toArray();
        $config = [];
        
        foreach($locales as $loc => $name) {
            $config[$loc] = $theme->getConfigArray($loc);
            if(empty($config[$loc])) unset($config[$loc]);
        }

...

**Comment by mjauvin** [comment]
The entries under  the `translate:` key should be indented...

If they actually are, do all those languages exist and are active under the `Settings->Translate->Manage languages` ?

**Comment by shoguniphicus** [comment]
I ran into the same problem. If I had it indented. There will be an error complaining about "array_keys() expects parameter 1 to be array, string given"

![image](https://user-images.githubusercontent.com/5608586/106691185-0981aa00-660e-11eb-89e5-605a965983a4.png)
