### ISSUE TITLE
How to add an initial value to translatable backend form fields?

### ISSUE THREAD

**Issue by RoudyTarabay** [rainlab/translate-plugin#633]
Hello. 
First of all thank you for a great plugin. 
I have a particular case that I can't seem to find a way to achieve. I have a translatable field with a programmatically added initial value.
![image](https://user-images.githubusercontent.com/6538900/108396638-bb7cc100-721f-11eb-8988-8b5d60ee9f02.png)

I'm achieving this with the following code. 
```
 public function getCanonicalUrlAttribute()
    {
        if ($this->exists) {
            if (array_key_exists('canonical_url', $this->attributes) and $this->attributes['canonical_url']) {
                return $this->attributes['canonical_url'];
            }
            if ($this->subcategory) {
                $url=[$this->category->slug,$this->subcategory->slug,"post",$this->slug];
            } else {
                $url=[$this->category->slug,"post",$this->slug];
            }
            return env('APP_URL')."/".join("/", $url);
        }
    }
```

How would I go about it to add this initial value in multiple languages. My slug is translatable.

**Comment by mjauvin** [comment]
In your model, create this method:
```
public function getCanonicalUrlAttributeTranslated($locale)
{
    $this->translateContext($locale);
    if ($this->subcategory) {
        $url=[$this->category->slug,$this->subcategory->slug,"post",$this->slug];
    } else {
        $url=[$this->category->slug,"post",$this->slug];
    }
    return env('APP_URL')."/".join("/", $url);
}
```

I did not test this, but you can see this method will get called (if it exists) from `traits/MLControl.php`

**Comment by RoudyTarabay** [comment]
@mjauvin  $locale contains the value of canonical_url, it's not a locale

**Comment by RoudyTarabay** [comment]
Thanks a lot! It works.
