### ISSUE TITLE
Translate activeLocale dynamically?

### ISSUE THREAD

**Issue by sheriffmarley** [rainlab/translate-plugin#634]
How can i translate `activeLocale` ? 

I'm used to blade and there it's an easy task to do, but I really struggle to do it with twig.

I just want to translate the `activeLocale` to a full string.

For example I translate string like this: `{{ ':language-selector'|_({ name: 'Select language' }) }}`

How can I do this for the activeLocale?

Tried it with this
`{{  ":lang-#{activeLocale}"|_({ ":lang-#{activeLocale}": 'English' }) }}` 
but I got this error
`A hash key must be followed by a colon (:). Unexpected token "begin of string interpolation" ("punctuation" expected with value ":").`

**Comment by mjauvin** [comment]
use this:
```
{{ ("lang-" ~ activeLocale)|_ }}
```
And just translate the "lang-*" under `Setting/Translate Messages`
