### ISSUE TITLE
Is it possible to use this plugin without Force URL schema without getting 404?

### ISSUE THREAD

**Issue by dynamiccontent** [rainlab/translate-plugin#635]
Hello,
Just wondering if it's actually possible to use this plugin without forcing URL schema? I don't like the look of url schema I would rather have clean url addresses. Each page would have url named differently in each language.

Have two languages
Language 1 url /submit
Language 2 url /oddaja

If the language 1 is selected on website and I try to access language 2 url it will show error 404.

It looks like this plugin was not designed with this in mind and even if I enter two different urls each for different language on each page it won't work properly.

Also if I am doing redirections on the site like after submitted form I cannot select to what url should I redirect. If enter that it should redirect to url from language 1 and the user has selected language 2 it will show 404.

This makes this plugin quite unusable.

You can replicate this easily... Let me know if you have any suggestions how to deal with this. Thank you.

**Comment by daftspunk** [comment]
You can simply not translate the URLs and use the [language picker component](https://github.com/rainlab/translate-plugin#language-picker-component) which will store the language in the session instead. It has a `forceUrl` option that is default to FALSE

Is that what you are looking for?

**Comment by dynamiccontent** [comment]
> 
> 
> You can simply not translate the URLs and use the [language picker component](https://github.com/rainlab/translate-plugin#language-picker-component) which will store the language in the session instead. It has a `forceUrl` option that is default to FALSE
> 
> Is that what you are looking for?

I know this exist and even if I enable forceUrl to TRUE I will still have the same problem. I have translated the urls and I still have the same problem.

I don't know how to explain it better so let me show what I have and what I see. Here is quick demo where I implemented core components for menu and translation.

This is so it will display menu in the top right corner:
![demo1](https://user-images.githubusercontent.com/56940608/111764222-472b5100-88a3-11eb-850f-b1e92a36dabf.png)
![demo2](https://user-images.githubusercontent.com/56940608/111764269-55796d00-88a3-11eb-97bc-78d496266e65.png)
![demo3](https://user-images.githubusercontent.com/56940608/111764295-590cf400-88a3-11eb-805c-12c251abbd60.png)

Everything will work fine if I switch languages via language picker from english to slovenian it will switch the url from https://example.com/blogslovenian to https://example.com/blogenglish without problems.

I have added different url for each language on page:
![demo4](https://user-images.githubusercontent.com/56940608/111764776-dfc1d100-88a3-11eb-8e62-8247a53f269e.png)
![demo5](https://user-images.githubusercontent.com/56940608/111764782-e2242b00-88a3-11eb-8f8f-6c53251b3804.png)

This will work when I am switching languages via language picker:
![demo6](https://user-images.githubusercontent.com/56940608/111765270-77bfba80-88a4-11eb-8781-8a7602bec631.png)
![demo7](https://user-images.githubusercontent.com/56940608/111765280-7abaab00-88a4-11eb-86cd-6c76bd34daa7.png)

The problem is when I try to access different language url manually. For example the page is set to Slovenian (https://example.com/blogslovenian) via language picker and I access english url (https://example.com/blogenglish) manually it will 404.
![demo8](https://user-images.githubusercontent.com/56940608/111765430-9de55a80-88a4-11eb-954f-2d3f82ac155f.png)

Here is the error log:
![demo9](https://user-images.githubusercontent.com/56940608/111765668-f0267b80-88a4-11eb-85b2-2e6fa3b4ac65.png)

![demo10](https://user-images.githubusercontent.com/56940608/111765680-f3ba0280-88a4-11eb-8161-42c00be3fb55.png)

Thank you for taking the time to answer my question and I hope you understand now.

**Comment by daftspunk** [comment]
I understand now. Do you want the 404 will redirect to the correctly translated URL?

**Comment by dynamiccontent** [comment]
> 
> 
> I understand now. Do you want the 404 will redirect to the correctly translated URL?

Yes. Thank you!

**Comment by daftspunk** [comment]
Got it. Well, I can confirm this is indeed a limitation of the current design of this plugin. Pages are restricted to 1 URL only, so redirection is difficult to achieve. It is a complex issue

However, I have made a note to ensure this behaviour is included in the next iteration of October's translation features. Thank you for your feedback!

**Comment by dynamiccontent** [comment]
> 
> 
> Got it. Well, I can confirm this is indeed a limitation of the current design of this plugin. Pages are restricted to 1 URL only, so redirection is difficult to achieve. It is a complex issue
> 
> However, I have made a note to ensure this behaviour is included in the next iteration of October's translation features. Thank you for your feedback!

Thank you for letting me know. Now what should I do until the new version is released? Should I just use one url page or? I still need to translate the page and have two languages available. Should I look at something else. This is essential for my project and I need to have it working without errors.
Thanks!

**Comment by daftspunk** [comment]
In the meantime, you can create something called a proxy page. Do not use the translated URL feature at all. Instead, create a proxy page for each desired translation. 

- Define the URL - `/oddaja`
- In the Code section add the `onStart` method below, that runs the `/submit` page
- Leave the content blank

```
url = "/oddaja"
==
function onStart()
{
    return $this->run('/submit');
}
```

This will give you dual URLs for the same page. I hope this helps
