### ISSUE TITLE
Force viewBag URLs

### ISSUE THREAD

**Issue by daftspunk** [rainlab/translate-plugin#636]
@ivang76 As I understand it you have a single theme in a multisite environment that can have a different default locale per instance.

```
title = "NotizieTMP"
url = "/notizieTMP"
layout = "default"
is_hidden = 0
[viewBag]
localeTitle[it] = "Notizie"
localeTitle[en] = "News"
localeUrl[it] = "/notizie"
localeUrl[en] = "/news"
==
<?php ...
```

This makes the default URL somewhat redundant, however, it is always applied due to the logic of the default locale, which says "if locale is default, use the 'url' not the viewbag" but you want to force it to use the viewbag every time

As a workaround you've hacked the logic to always apply it

        if ($locale != $this->translatableDefault || true) {
            $localeUrl = $this->getSettingsUrlAttributeTranslated($locale) ?: $localeUrl;
        }

We could look at modifying the logic to simply check viewBag first always and use the URL as the fallback. This would solve the problem at minimal additional expense

**Comment by ivang76** [comment]
ok perfect, thank you... in this way I think that also the localeTitle will follow the same logic, and not only the localeUrl, isn't it?

**Comment by ivang76** [comment]
I write also here my actual solution to manage the title, just to keep note if maybe someone else need it...

```
function onEnd() {
    $this->page->title = $this->viewBag->localeTitle[App::getLocale()];
}

```
