### ISSUE TITLE
Implement searching for translated field.

### ISSUE THREAD

**Issue by LeoCantThinkOfAName** [rainlab/translate-plugin#637]
Hi,

I made a i18n website, at beginning everything works great, until I try to implement search function for my model with `searchWhere`, and found it doesn't work with translated field, I can only search for default language.

I'm not sure what's the best way to do this, I'm currently using some silly solution to query `rainlab_translate_attributes` with `like` expression, which doesn't seem like a optimal way to do it. And I just can't find any official solution or what so ever in the plugin documentation.

Any suggest?

**Comment by daftspunk** [comment]
This is not currently supported by the plugin. I have made a note to include this functionality in the next iteration. Seems like you have a good workaround in place. You're also welcome to submit a Pull Request to add this

Thanks!
