### ISSUE TITLE
Call to undefined method League\Csv\Reader::addFilter()

### ISSUE THREAD

**Issue by rubenmaas** [rainlab/translate-plugin#640]
My own research shows that League\Csv\Reader::addFilter method was removed from league/csv version > 9.0.0 [here](https://github.com/thephpleague/csv/blob/master/CHANGELOG.md#removed-17)

Steps to reproduce:

1. Export translated messages;
2. Import csv;
3. Select auto match columns.

Throws error:
`Call to undefined method League\Csv\Reader::addFilter()`

**Comment by daftspunk** [comment]
Hi @rubenmaas !

Thanks for the report. We've updated the importer methods to use the new league library. This will be fixed in v2.0.10
