### ISSUE TITLE
will it work with october 2 new editor ?

### ISSUE THREAD

**Issue by shiftaltd** [rainlab/translate-plugin#641]
After updating to october cms 2 the lang switcher is gone from the all fields on the editor tab.
slug, meta_title, meta_description...

Do you plan to put this precious feature back?

regards

**Comment by daftspunk** [comment]
Yes, we have it planned to be added in this release cycle

**Comment by shiftaltd** [comment]
Thanks. it's a must have in europe

**Comment by shiftaltd** [comment]
I'm sorry. but It's coming to be difficult to explain to a client why this feature has disappeared...

**Comment by daftspunk** [comment]
Sorry for the delay, it will be included as part of this roadmap item: https://portal.octobercms.com/c/14-api-for-customizing-complex-cms-template-properties

**Comment by daftspunk** [comment]
Related Pull Request #646

**Comment by daftspunk** [comment]
![image](https://user-images.githubusercontent.com/1392869/120135088-d5f90a00-c212-11eb-99f6-d315d3c85db7.png)

This feature has been restored in v1.9.0 of this plugin, combined with v2.0.17 of October CMS

Thanks!
