### ISSUE TITLE
Mediafinder field error (Translate + Pages)

### ISSUE THREAD

**Issue by massimomegistus** [rainlab/translate-plugin#643]
OctoberCMS Build: 2.0.10
RainLab Pages Plugin Version: 1.4.3
RainLab Translate Plugin Version: 1.8.2
PHP Version: 7.4.12

I have a mediafinder custom field in a static page layout (following Syntax Fields)
{variable tab="Heading" type="mediafinder" mode="image" name="heading_image" label="Heading Image (landscape)" span="left" comment="Wide heading image, min width 1200px" imageWidth="300" }{/variable}

I get these error when trying to open the static page editor form
- October\Rain\Exception\SystemException: The partial '_mediafinder.htm' is not found. in /Applications/MAMP/htdocs/ocdev2/modules/system/Traits/ViewMaker.php:89
- Class System\Classes\MediaLibrary has been deprecated, use Media\Classes\MediaLibrary instead.

**Comment by daftspunk** [comment]
Fixed in e135584fcd3099632257b3ef865f4ab8af63e846
