### ISSUE TITLE
Invisible checkboxes in popup: Scan for messages

### ISSUE THREAD

**Issue by Eoler** [rainlab/translate-plugin#644]
Version: 1.8.4
Core: 2.0.11

Can't see if options are selected or not:
![Popup-checkboxes](https://user-images.githubusercontent.com/680032/116540320-4b0eb200-a8ea-11eb-92b5-3c1a6268f1b2.png)

**Comment by daftspunk** [comment]
Thanks! Fixed in 1.8.6
