### ISSUE TITLE
Database error after first install

### ISSUE THREAD

**Issue by ZhuravlevAN** [rainlab/translate-plugin#645]
Hi, I found error...
When I click on "Scan for messages" after the first installation, аa have a error message:

> "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'found' in 'field list' (SQL: update `rainlab_translate_messages` set `found` = 0)" on line 669 of /home/user/PhpstormProjects/wintercms/vendor/laravel/framework/src/Illuminate/Database/Connection.php

Please, add column `found`  in table rainlab_translate_messages in migration.
Best regards, Andrey Zhuravlev

**Comment by daftspunk** [comment]
Hello @ZhuravlevAN !

Thanks for reporting this. It is fixed in fb1a612ce3cef1f24ed5713858389c1a5041140a (v1.8.5+)

To patch your installation please run the following

```
php artisan tinker
```

And paste in the following

```
if (!Schema::hasTable('rainlab_translate_messages')) { return; } if (!Schema::hasColumn('rainlab_translate_messages', 'found')) { Schema::table('rainlab_translate_messages', function($table) { $table->boolean('found')->default(1); }); } exit
```
