### ISSUE TITLE
October v2 richeditor problem

### ISSUE THREAD

**Issue by sizucen** [rainlab/translate-plugin#648]
How can I fix it? input field it's work but rich editor has old styles. (Try with multi language)

![ocv2](https://user-images.githubusercontent.com/73330095/124723403-b345c980-df13-11eb-8fbf-2cbf0f0d07df.PNG)

**Comment by daftspunk** [comment]
The v2 editor uses Vue and has not been integrated with the language picker. As a result, the `legacyMode` option is activated when translating richeditor fields. If it is purely a styling issue, feel free to submit this to the portal page as feedback: https://portal.octobercms.com/
