### ISSUE TITLE
Cannot translate relation fields

### ISSUE THREAD

**Issue by ariponce** [rainlab/translate-plugin#65]
- **Bug summary:** When using the plugin on a relation form, translations are not saved to the database
- **Reproduce steps:** 
  1 Create a relation between two models that are translatable
  2 Create a config_relation on a controller
  3 Render the relation view 
  4 Create a new relation record or update an existing one on the form, set the value in the different languages
- **Expected result:** The translations are saved on the database
- **Actual result:** No translations are saved

I think this is related to this issue #18

**Comment by fobus42** [comment]
The same error here!

**Comment by ariponce** [comment]
I've partially solved the problem on a fork, but the pull request was not accepted. You can check it on my fork
https://github.com/ariponce/translate-plugin

**Comment by fobus42** [comment]
@ariponce Thank you. It is working great. Did they accept pull request?

**Comment by fgomezserna** [comment]
@ariponce good job! Thank you :)

**Comment by CptMeatball** [comment]
@ariponce to what end did you fix this problem? As you say partially fixed the problem. What part didn't you fix?

**Comment by flo-sch** [comment]
Hey guys, has the PR been reviewed / accepted yet?

**Comment by tbergeron** [comment]
Any update on this?

**Comment by MilosStanic** [comment]
I just lost hours, because I forgot this doesn't work 🎱

**Comment by tbergeron** [comment]
@MilosStanic so this is still happening?! I guess you lost localized content because of this? I'll be careful I'm about to do the same thing 😨

**Comment by MilosStanic** [comment]
@tbergeron I didn't lose any content, I was just trying unsuccessfully to update translations in a relationship. And nothing happened. I think. I forgot :D . Many things happened in between.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
