### ISSUE TITLE
Taglist Multilang Not working

### ISSUE THREAD

**Issue by Anas-shamia** [rainlab/translate-plugin#651]
I am trying to add multiple languages for taglist with  String mode but it did not work, It's work perfectly in all fields except taglist,  I tried to do it but I don't know enough.

**Comment by daftspunk** [comment]
Hi @Anas-shamia ,

Tag List is not supported by this plugin, you can use a regular text field and separate each tag with a comma `,` as a workaround. Implementing the taglist control is complicated but we would accept a pull request if you can figure it out based on other controls.
