### ISSUE TITLE
Translate attributes / indexes not cleared when model is deleted

### ISSUE THREAD

**Issue by acasar** [rainlab/translate-plugin#652]
Translatable attributes/indexes are not removed from the database after a parent model is deleted, which can cause issues in some situations when using ``transWhere``. 

This was already reported (https://github.com/rainlab/translate-plugin/issues/211), but I am reopening the issue, since it has not been resolved and it's causing our production apps to fail in unexpected ways

**Comment by daftspunk** [comment]
This was most likely caused by 508c42c2c0a6240d71bf82994e204582adbc5d8e since it happens across two separate queries now. One idea is to use GC to clean up orphaned records.

**Comment by acasar** [comment]
That's true, when implementing https://github.com/rainlab/translate-plugin/commit/508c42c2c0a6240d71bf82994e204582adbc5d8e I was not aware that translation tables contain orphaned records by design. But I think that a cleanup of related translated records in beforeDelete event should solve this issue?

**Comment by daftspunk** [comment]
Yes, if you are happy with that, let's hook beforeDelete inside `\RainLab\Translate\Behaviors\TranslatableModel` to clean up orphaned indexes. 


    public function __construct($model)
    {
        parent::__construct($model);

        // ...

        $this->model->bindEvent('model.afterDelete', [$this, 'cleanupTranslatableData']);
    }

**Comment by acasar** [comment]
If anyone else is interested, I fixed this by extending the base model:

```php
$model->bindEvent('model.beforeDelete', function() use ($model) {
    if($model->isClassExtendedWith('RainLab.Translate.Behaviors.TranslatableModel')) {
        DB::table('rainlab_translate_attributes')
            ->where('model_id', $model->getKey())
            ->where('model_type', get_class($model))
            ->delete();
        DB::table('rainlab_translate_indexes')
            ->where('model_id', $model->getKey())
            ->where('model_type', get_class($model))
            ->delete();
    }
});
```
And I also added a console command to clean existing orphaned records.

**Comment by daftspunk** [comment]
Looks good, native integration added to the behavior here: d4eb4333eb0cd45048175f2bd648d378f830968c

Thanks @acasar!
