### ISSUE TITLE
Problem when switching languages

### ISSUE THREAD

**Issue by bmiskoski** [rainlab/translate-plugin#655]
Hello,

When switching languages from the default language to the secondary language all works as expected, the locale is changing also the URLs. (slugs)

The problem occurs when changing from the secondary language back to the default language. Then only the locale is changed (in my case en to de) but the URL stays the same which results with 404 page error.

I have used the transWhere method when accessing the pages via translatable slugs, the main problem occurs when changing the secondary language back to the default language and i can't seem to wrap my head around the problem.

All help is greatly appreciated.

October version: 2.0.25
Translate plugin version: 1.9.2

**Comment by daftspunk** [comment]
Hi @bmiskoski 

It's possible this is a known limitation with the translate plugin. However, we would need to see the issue demonstrated. There are many ways in which this plugin can be configured.

Please send us an email at hello@octobercms.com with instructions on how to configure the "demo" theme using the desired configuration and where the problem shows itself.

Thanks!
