### ISSUE TITLE
Form fields not replaced with ML controls when config is empty

### ISSUE THREAD

**Issue by mplodowski** [rainlab/translate-plugin#657]
October version: 2.1.10
RainLab.Translate version: 1.9.2

**Current behavior:**

I extended RainLab.Blog Category model with some fields that are added into tabs section. Those fields has also been added into translatable property on Category model. Added fields are not replaced with ML controls and are not translatable.

**Expected behavior:**

Added fields are replaced with ML controls and are translatable.

https://github.com/rainlab/translate-plugin/blob/master/classes/EventRegistry.php#L201

Above code checks the config and because fields.yaml does not have `tabs` property it returns `false`. I think this should check `fields` property instead.

**Comment by daftspunk** [comment]
Good catch, thanks!
