### ISSUE TITLE
Repeater data from other locales is not updated correctly

### ISSUE THREAD

**Issue by tobias-kuendig** [rainlab/translate-plugin#659]
You can reproduce this issue using the test plugin, go to `/backend/october/test/countries/update/1#primarytab-states` with RainLab.Translate installed.

If you fill out the repeater for another locale and then save the form, the data is not saved to the database:

Update, then save form, then refresh:

![no-switch](https://user-images.githubusercontent.com/8600029/136536431-8e2137e3-d1db-4a28-ab0e-bb45e7938ee0.gif)

If you switch the locale before saving the form, the data is saved as it shoud.

![switch](https://user-images.githubusercontent.com/8600029/136536631-94e70153-d286-47db-b932-1fdee074cd99.gif)

It looks like the hidden input fields are only updated with the new data once the locale gets switched.

October 2.1.14
RainLab.Translate 1.9.2

**Comment by daftspunk** [comment]
Hi @tobias-kuendig 

Oh no, I can't replicate this...

![repeater-locale-test](https://user-images.githubusercontent.com/1392869/136636859-b7040433-0451-455c-9635-88f9747b5df3.gif)

Using OCMS v2.1.14 and RL.Translate 1.9.2 in Chrome and Firefox

Steps taken:

1. Open URL /backend/october/test/countries/update/1
2. Navigate to States tab
3. Toggle to other language (RU -> EN)
4. Add "updated" text to State field
5. Press Ctrl + S to Save / Click the Save button
6. Refresh page
7. Navigate back to State field (as above)
8. Observe value has been updated as expected

Side note:

> It looks like the hidden input fields are only updated with the new data once the locale gets switched.

When saving, the hidden inputs don't need to be updated for the selected language. The code will notice what language is selected and use that for the current values. The hidden inputs are used primarily for the languages that are not currently selected.
