### ISSUE TITLE
Empty Translation are not delete

### ISSUE THREAD

**Issue by evwerkz** [rainlab/translate-plugin#662]
October Build: 470
PHP: 7.4
Translate Version: 1.9.2
Static Pages Version: 1.4.10

If I enter a translation and want to remove it afterwards by leaving the field empty, it will not be removed or changed.
Theme data is stored in the DB. The "Static Pages" plugin is used.

**How can I delete or remove translation data?**

![image](https://user-images.githubusercontent.com/49227960/152694897-bda6e89d-a825-4cb7-b8d3-f25344b5307d.png)
![image](https://user-images.githubusercontent.com/49227960/152694915-ddbd08db-4fbd-4264-9877-5dbe71e81cf4.png)

DB Table: cms_theme_templates: Fields "path" and "content"

**Comment by daftspunk** [comment]
Hi @evwerkz, sorry to hear you are having difficulty with this. Unfortunately, we could not reproduce this problem. 

Could you provide step by step instructions using a fresh installation of October CMS? It helps to be using the latest version of October CMS and the translate plugin.

Thanks
