### ISSUE TITLE
static-page-url-map clear on pages.object.save

### ISSUE THREAD

**Issue by massimomegistus** [rainlab/translate-plugin#664]
OctoberCMS: 2.1.30
Rainlab.Translate: 1.9.3

I've noticed that whether CMS_ROUTE_CACHE=true, when StaticPage slug is changed for a language different form the default one, the new url is not reachable (404). This occurs even for new StaticPages: default language url is reachable; other language urls raise a 404 error.
To fix that, I added $staticPageRouter->clearCache() to clear the 'static-page-url-map' in the 'cms.template.save' $handler function
This seems to work.

                if (!empty($dirtyLocales)) {

                    $theme = Theme::getEditTheme();
                    $currentLocale = Lang::getLocale();

                    foreach ($dirtyLocales as $locale) {
                        if (!$template->isTranslateDirty(null, $locale)) {
                            continue;
                        }

                        // Clear the RainLab.Pages caches for each dirty locale
                        App::setLocale($locale);
                        \RainLab\Pages\Classes\Page::clearMenuCache($theme);
                        \RainLab\Pages\Classes\SnippetManager::clearCache($theme);

                        **// clear static-page-url-map cache
                        $staticPageRouter = new \RainLab\Pages\Classes\Router($theme);
                        $staticPageRouter->clearCache();**
                    }

                    // Restore the original locale for this request
                    App::setLocale($currentLocale);
                }

What do you think about this solution?

M

**Comment by massimomegistus** [comment]
A cleaner approach:
\RainLab\Pages\Plugin::clearCache();

            if (!empty($dirtyLocales)) {

                $currentLocale = Lang::getLocale();

                foreach ($dirtyLocales as $locale) {
                    if (!$template->isTranslateDirty(null, $locale)) {
                        continue;
                    }

                    // Clear the RainLab.Pages caches for each dirty locale
                    App::setLocale($locale);
                    \RainLab\Pages\Plugin::clearCache();

                }
                
                // Restore the original locale for this request
                App::setLocale($currentLocale);
            }

**Comment by daftspunk** [comment]
This is a good improvement. Added in 6eae89e1ab11c86d5a4681234cde3e3cf66ef121

Thanks!
