### ISSUE TITLE
Prevent showing translated version of page by just changing the locale prefix and not the slug too.

### ISSUE THREAD

**Issue by bmiskoski** [rainlab/translate-plugin#667]
Hi,

I have this two language website, and I have implemented the translate plugin there with indexed slugs. The issue that I am facing is that I need to limit the user to not see the translated version of the page by simply changing the locale prefix from en to de and not its related indexed slugs

I implemented the event listener on translate.localePicker.translateParams as suggested in the documentation, and the locale switcher works as expected.

Actual behavior:
https://example.com/en/slug-en <-- Loads the en version 
https://example.com/de/slug-de <-- Loads the de version 

If user changes the URL manually to:
https://example.com/de/slug-en <-- he/she can see the translated de version

Expected behavior:
If user changes the URL manually:
https://site.com/de/slug-en should receive 404 page not found.

Any suggestions on how I can limit the user from accessing the translated page contents without having both locale and indexed slug correct?

P.S Only the primary locale allows for the page to be loaded with different locales and same slug, the secondary locale throws 404 error.

Thanks.

**Comment by daftspunk** [comment]
This is a known factor in the overall design. We could solve it by introducing a strict mode that shifts the priority to correctness over serving something. In most cases, the plugin wants to serve something where possible.

**Comment by bmiskoski** [comment]
@daftspunk understandable.

Can I somehow for the time being remove the locale prefix (en, de) on certain pages and load the content strictly by the slug?

Example:
https://example.com/some-page/slug-en <-- loads English version
https://example.com/some-page/slug-en <-- loads German version
without /en or /de

This to be only present on selected pages not on whole website (where can i unselect the force URL schema).

Thank you.

**Comment by daftspunk** [comment]
There is a site-wide config option to disable it (`rainlab.translate::disableLocalePrefixRoutes`). Disabling it on a per-page basis creates a chicken and egg problem. It will also force the default locale (en) slugs.

Your original request makes the most sense in this case. It could be as simple as something like this

```
{% if activeLocale != modelLocale %}
    {% do abort(404) %}
{% endif %}
```

Note: this is concept code. Finding the modelLocale is the missing link.

**Comment by daftspunk** [comment]
Hi @bmiskoski 

Try testing this using October CMS v3.1, there has been a lot of work to improve the underlying translation system and it is much easier for us to pinpoint issues. We can confirm it has been solved definitively by using Tailor. For the Translatable behavior, you/we may need to swap the lookup function for  `transWhereNoFallback`.

- Link to the [upgrade guide](https://github.com/rainlab/translate-plugin/blob/master/UPGRADE.md)
- Link to [multisite documentation](https://docs.octobercms.com/3.x/cms/resources/multisite.html)

If it is still a problem, let us know, and we can take another look, feel free to get in touch with the support desk for assistance: https://octobercms.com/contact

Thank you
