### ISSUE TITLE
Selecting language with URL prefix doesn't work on root route

### ISSUE THREAD

**Issue by justin-lau** [rainlab/translate-plugin#67]
With version 1.0.10, although the exception is no longer thrown as reported in #61, #62, and #64, the appropriate language is not being selected with URL prefix.

It seems to me as if no languages is being selected, not even the default language. It shows a 404 page, and when the locale picker is selected on this page an alert message pops up and display the value of `X_OCTOBER_REDIRECT`.

**Update**
The problem only occurs on the root route `/`

**Comment by schnubor** [comment]
+1 same issue.

**Comment by devillom** [comment]
+1 not working in home page
