### ISSUE TITLE
Entries are deleted on pressing return when adding them to the "Translate messages" list

### ISSUE THREAD

**Issue by chocolata** [rainlab/translate-plugin#672]
I'd just want to report a minor issue with the Translate messages list. When you enter some text in a translatable field and hit enter / return, the entry is being deleted instead of saving it and moving to the next row. Not a big deal, but I just wanted to let you guys know that this is present.

**Comment by uematsusoft** [comment]
Hi,
Any feedback about this issue? Because it is a big deal since when deleted, not even with clearing the translation cache the scan will not add the sttring again.

How can I reset the message so it gets added by the scan?

Best regards.

**Comment by daftspunk** [comment]
Hi all,

This can be fixed by updating to v2.2.22 of October CMS

> How can I reset the message so it gets added by the scan?

Some records are not picked up by the scan, but will be readded when they are first seen on the frontend.

Thanks
