### ISSUE TITLE
RainLab.Pages plugin's Static Menu's 'isActive' attribute not working when using language code prefix in URL

### ISSUE THREAD

**Issue by guus-frenken** [rainlab/translate-plugin#675]
Hi there!

I am not sure whether to submit this issue here, under rainlab/pages-plugin or octobercms/october.

When I use the language code prefix in the URL (website.com/en/page, website.com/fr/page etc..). The 'isActive' attribute in the StaticMenu component from the RainLab.Pages plugin does not work.

I have narrowed the issue down to the usage of `\Cms\Classes\Page::url()` in the `boot()` method of one of my custom plugins. For some reason, using this function in the boot() method breaks the functionality.

I am not really sure if anything can be done about this, but I figured I would document it since it took me quite some time to figure out what was going wrong.

**Comment by daftspunk** [comment]
Probably a race condition. Something to try is to defer the boot logic using `App::before`. See if it helps.

```php
function boot()
{
    App::before(function() { 
        // Use Page::url() here
    });
}
```

**Comment by guus-frenken** [comment]
You were correct, using `App::before()` fixed the issue. Thank you!
