### ISSUE TITLE
Import auto match issue (may be October v3 bug)

### ISSUE THREAD

**Issue by acasar** [rainlab/translate-plugin#678]
When importing Messages, the "Auto match columns" function is not working in October v3.0.38

![image](https://user-images.githubusercontent.com/6329543/170387816-3143b4d9-c57c-4ede-8513-4153019a47bf.png)

This may actually be an issue with October v3, but I'm posting it here since I am currently unable to test with any other plugin.

**Comment by daftspunk** [comment]
Hi @acasar 

Confirmed this is a bug with the CSV auto-match. Should be fixed in OC v3.0.40
 
Thanks
