### ISSUE TITLE
Purgeable trait

### ISSUE THREAD

**Issue by tomaszstrojny** [rainlab/translate-plugin#679]
Hi guys,

In [line 96 of `Plugin.php` file](https://github.com/rainlab/translate-plugin/blob/master/Plugin.php#L96) I see that `File` and `ThemeData` is extended with `Purgeable` behavior which from October 2 is deprecated. I would suggest adding the `Purgeable` trait to these two models and removing the extending part from here. Do you agree? I could prepare PRs for both changes, just wanted to ensure that you agree with me.

Thanks!

**Comment by daftspunk** [comment]
Hi @tomaszstrojny 

Thanks for taking the time to discuss this. In this case: the logic has already been removed. As in line 96, this logic does not run for October v2 and up. Take note of the method name `extendLegacyPlatform` and comment above the calling code:

```
// Extension logic for October CMS v1.0
if (!class_exists('System')) {
    $this->extendLegacyPlatform();
}
```

The translate plugin has been improved to not depend on these behaviours.

**Comment by tomaszstrojny** [comment]
Hi @daftspunk 

My bad, you're 100% right!
