### ISSUE TITLE
October v3 language picker UI issue

### ISSUE THREAD

**Issue by acasar** [rainlab/translate-plugin#680]
In October v3 the language picker appears too low on text inputs:

![image](https://user-images.githubusercontent.com/6329543/172924864-7145809a-22ca-4016-a5b7-aeb007f3a8f6.png)

But it seems to be OK on other input types like textarea:

![image](https://user-images.githubusercontent.com/6329543/172924908-fade63b2-1a54-4287-98ac-a0cb72dea404.png)

For comparison - the positioning on text inputs is much better in October 1.1:

![image](https://user-images.githubusercontent.com/6329543/172925338-1751061e-582d-4aa6-b75d-831cccb8feb9.png)

**Comment by samgeorges** [comment]
Hello @acasar, the alignment should be fixed in the next patch. Best regards
