### ISSUE TITLE
Theme data translation does not work with OctoberCMS v3

### ISSUE THREAD

**Issue by vimre** [rainlab/translate-plugin#682]
Hi RainLab,

According to the documentation of the plugin (at **Theme data translation** section) if I add `translatable: true` to theme config field then it should magically turn to a translatable field on the backend. I have expected a locale selector at the right side of the entry field as usually.

I have never used it before to be honest but it seems this function does not works with current version of `OctoberCMS` (`v3.0.44`) and latest version of `RainLab.Translate plugin` (`v1.11.1`).

Could you please check what could be the problem?

Thanks in advance,
vimre

**Comment by daftspunk** [comment]
Hi @vimre 

This has been tested with OCMS v3.0.50 and Translate v1.11.1 and appears to be working fine.

[Using our test theme](https://github.com/daftspunk/test-theme/blob/main/theme.yaml#L18-L20), the following shows the translation features:

```yaml
title:
    label: Title
    translatable: true
```

https://github.com/daftspunk/test-theme/blob/main/theme.yaml#L18-L20

![image](https://user-images.githubusercontent.com/1392869/174414138-50bfbb64-edc8-4d9e-977d-91c874161d10.png)

One thing to suggest, make sure you have more than one language set up. Also try to install or copy from the test theme to see if it helps.

**Comment by vimre** [comment]
Hi Sam,

Thanks for your answer.

It seems the problem is related only to repeater fields (actually fields inside a repeater widget).
If I add translatable attribute to the repeater widget itself (not to its fields) then repeater and all these fields become translatable.... but if I add translatable attribute to a field inside a repeater widget form, then nothing happens, that specific field won't be translatable. It happened in my case.

Maybe there is a solution to apply translatable attribute only on specific field(s) of repeater widget form but I was not able to find any workaround unfortunatelly.

**Comment by daftspunk** [comment]
No problem. This makes sense because repeater fields are not translatable. The whole repeater should be translatable instead, it's by design.
