### ISSUE TITLE
Multiple issues with MLMediaFinderv2

### ISSUE THREAD

**Issue by acasar** [rainlab/translate-plugin#686]
In the latest version of October v3 (v3.0.61) I tried to make a mediafinder field translatable. I noticed several issues:

1. When ``mode:image`` is set, thumbnail previews are not generated
2. When ``maxItems`` is set to a value of 2 or more, it's not possible to reorder records (they get duplicated)

The easiast way to replicate the issue is to install the https://github.com/octobercms/test-plugin and make all media fields in the ``October\Test\Models\User`` model translatable (also make sure that ``rainlab/translate`` is installed with at least 2 languages defined):

```php
public $translatable = ['media_file', 'media_image', 'media_files', 'media_images'];
```

Here is a short video demonstrating the issue:

https://user-images.githubusercontent.com/6329543/177830199-7aa01fd9-ddb2-4628-ae5f-461e0b04b39a.mp4

**Comment by samgeorges** [comment]
Thanks for finding this. The sorting issue (2) appears to be an issue in v2 also.

1. This is fixed in commit 74871aa2a0737734f4fc6314b9ed03e9317b6274
2. This is to be fixed in >= v3.0.62 and v2.2.33
