### ISSUE TITLE
ML Markdown Editor issues in October v3

### ISSUE THREAD

**Issue by acasar** [rainlab/translate-plugin#687]
There are some issues with the translatable Markdown editor in October v3. I am using the latest versions (October 3.0.62 and RainLab.Translate 1.11.1).

1. Language picker is shown too low on the page
2. The formatting option in the toolbar is not working (javascript error)

To replicate the issue, you can add the following two lines to the ``Post`` model of the [test plugin](https://github.com/octobercms/test-plugin):
```php
public $implement = ['@RainLab.Translate.Behaviors.TranslatableModel'];
public $translatable = ['content_md'];
```

Video demonstration:

https://user-images.githubusercontent.com/6329543/180031305-7bc7830c-cc4f-4339-9c73-d1f94898e5a6.mp4

**Comment by samgeorges** [comment]
Alignment issue fixed in bb979598677d59fd9c6d0c395380c428d60c6e15
JS error fixed in https://github.com/octobercms/october-private/commit/6eace916d6a52f8f2bc31c2f5c143c1e1fdcbb3e
