### ISSUE TITLE
Translate datepicker fields

### ISSUE THREAD

**Issue by bob-tm** [rainlab/translate-plugin#689]
Hi,

I have datepicker field on my main page. But I want different value on translated page. 
Can you add MLdatepicker widget? 

I saw sources "translate\formwidgets\MLText.php". Seems just copy paste and MLdatepicker should work.

**Comment by daftspunk** [comment]
Hey @bob-tm,

You're welcome to submit this as a Pull Request to add this. However, we are working towards a more generic solution to this requirement in a future release.

**Comment by daftspunk** [comment]
This has been implemented in October CMS v3.1

- Link to the [upgrade guide](https://github.com/rainlab/translate-plugin/blob/master/UPGRADE.md)
- Link to [multisite documentation](https://docs.octobercms.com/3.x/cms/resources/multisite.html)

If you still need help, feel free to get in touch with the support desk for assistance: https://octobercms.com/contact
