### ISSUE TITLE
[Proposal] Add twig filters that generate links with locale

### ISSUE THREAD

**Issue by justin-lau** [rainlab/translate-plugin#69]
Create filters that generate links equivalent to the [existing ones](https://octobercms.com/docs/cms/markup#linking-to-pages-assets) but with locale prefixes.

For example, when browsing, the urls should go from `/es/about-us` to `/es/contact-us` instead of just `/contact-us`.

These filters may be named `_app`, `_page` and `_themes`.

**Comment by daftspunk** [comment]
This was the original behavior and was enabled by default, it should be fixed in the latest build and the latest version of this plugin.

**Comment by justin-lau** [comment]
@daftspunk Tested with the latest build (257) of October and the master branch of this plugin. The locale isn't injected to the URL generated with twig filters.

**Comment by justin-lau** [comment]
Two of my local october installations had the same issue of the `page` filter not generating twig filters, both of them have the latest october builds and the translate plugin installed.

Strangely, force updates done just now actually fixed the problem on both installations. Not really sure what happened, except for it isn't a cache problem since I have cleared my cache during the development process hundreds of times before the force update.
