### ISSUE TITLE
Components views are not scanned for messages

### ISSUE THREAD

**Issue by mplodowski** [rainlab/translate-plugin#702]
It seems like plugin components views are not scanned for translated messages. 

```
public function scanForMessages()
{
    $this->scanThemeConfigForMessages();
    $this->scanThemeTemplatesForMessages();
    $this->scanMailTemplatesForMessages();
    // todo scan components for messages
}
```

**Comment by daftspunk** [comment]
We can include this in addition to the other checks. However, it won't cover partials inside the components directory other than the default one. Most components should strive to be encapsulated in a single template, this makes them easy to override, so this proposal is helpful to include.

**Comment by samgeorges** [comment]
Added this in 8c66aeba6e50dab37ba88fa2c94f767c4810207c
