### ISSUE TITLE
"Undefined class constant 'INDEX_PREFIX'"

### ISSUE THREAD

**Issue by alexTitakoff** [rainlab/translate-plugin#704]
"Undefined class constant 'INDEX_PREFIX'" on line 166 of /web/htdocs/www.maoarchitects.com/home/plugins/rainlab/translate/formwidgets/MLRepeater.php

Good afternoon. Error when changing the language in the Repeater field.  Can you tell me in which direction to think?
All other fields are working fine.

**Comment by daftspunk** [comment]
This looks like it might be related to a version mismatch. The `INDEX_PREFIX` constant was removed a long time ago. Consider using the latest version for the best compatibility and support. 

As a patch, you are most likely missing this commit: edcd899a794caa78e2489a18987d59fd7acf83f2

You are welcome to contact the helpdesk for help with upgrading: https://octobercms.com/contact

**Comment by alexTitakoff** [comment]
Thanks Sam! I'll try

**Comment by alexTitakoff** [comment]
Yes, it worked. Faced with an incorrect update. I returned the old system files, everything worked. October 1st version.
