### ISSUE TITLE
OCMS 2.x translate plugin create duplicate content due to the language url prefix

### ISSUE THREAD

**Issue by PubliAlex** [rainlab/translate-plugin#707]
Hello,

When translate plugin is enabled, a page can be accessed using 2 different urls (exemple when website defined to french) : 

- https://www.mywebsite.com/mypage
- https://www.mywebsite.com/fr/mypage 

This happens even if you have only one language defined in backoffice, and even if you don't have the multilingual component present on the page or layout. Just the fact to install translate plugin in enought to create that behavior.

It shouldn't do that because it create duplicate content.

Best regards,

**Comment by PubliAlex** [comment]
@daftspunk Sorry, I forgot to precise that the problem occurs on October CMS 2.x

The page concerned is an standard editor page, didn't test with static page plugin.

Best regards,

**Comment by daftspunk** [comment]
Thanks for the clarification. This is one of the known issues of v2 and one of the reasons we redesigned it. The approach we would use to fix v2 is how we have fixed it in v3.
