### ISSUE TITLE
404 when going to / with locale

### ISSUE THREAD

**Issue by tommazer** [rainlab/translate-plugin#71]
The root page is not found when accessing it with the locale appended in the url.
http://www.example.com/ - Works
http://www.example.com/en - 404

**Comment by justin-lau** [comment]
There was [an issue related to the root route](https://github.com/rainlab/translate-plugin/issues/67) just being fixed recently. I didn't encounter similar problems after updating the plugin to the latest version.

**Comment by tommazer** [comment]
I downloaded all the latest versions with the installer but it didn't work. Changed the code manually and now it does! Thank you.

**Comment by justin-lau** [comment]
I think it is a caching problem. I usually clear the cache via artisan after every update.
