### ISSUE TITLE
Error when trying to translate a custom model

### ISSUE THREAD

**Issue by PubliAlex** [rainlab/translate-plugin#712]
Hello,

When I try to translate a model, I get the following error popup : 

![image](https://user-images.githubusercontent.com/55833027/214314987-b70d9201-d953-408d-9ea3-e7edf214e3a6.png)

If I go the event log to see what happens, I get the following error : 

![image](https://user-images.githubusercontent.com/55833027/214315214-92706520-1cb8-43bc-bc96-b6491320c9e3.png)

The translation is made with rainlab.translate, not the multisite method, because the website is in production and it was developped before the multisite feature.

**Comment by daftspunk** [comment]
Fixed by 008637da4359ee38e12b0b1e03b96ebf215949ba

Please update to v2.2.2
