### ISSUE TITLE
Translation not work in snippets

### ISSUE THREAD

**Issue by snipiba** [rainlab/translate-plugin#713]
In previous versions translations work fine, currently on version 2.2.2 all translations were lost, removed from database and not added into backend translation list. Multiple scans created, tested, etc.

for example, when snippet contains `{{ 'key_for_translate' | _ }}` this was not found in messages in backend.
previous version was fond this and it was translated. currently not found and missing in database as well

**Comment by daftspunk** [comment]
Hi @snipiba 

We are looking at snippets currently. For this issue, can you confirm are your snippets based on components or partials?

**Comment by snipiba** [comment]
> Hi @snipiba
> 
> We are looking at snippets currently. For this issue, can you confirm are your snippets based on components or partials?

on that time it was a partial based snippet in cms/partials

**Comment by daftspunk** [comment]
This should be fixed in v3.4
