### ISSUE TITLE
Translation fallbacks not working anymore

### ISSUE THREAD

**Issue by tschortsch** [rainlab/translate-plugin#714]
Since updating to the latest version of the plugin our translation fallbacks don't work anymore for me. I tracked the issue down to this change: https://github.com/rainlab/translate-plugin/commit/4ec93022beb2a11cb73bc1e9c76ec7041ca42f79.

The `hasTranslation()` function now returns `true` if there is an empty string in the `rainlab_translate_attributes` table which seems to be the case for nearly all our items. Even worse those empty strings can't be removed via the backend since saving an empty field adds the empty string record to the database.

When I revert this change the fallbacks work again but when I now save a translated item it always get saved to the database even if I didn't touch the value (it saves the string from the fallback language as translation). Is this intended to happen?

**Comment by daftspunk** [comment]
Hey @tschortsch 

Can you try this commit, it seems to satisfy both use cases: ca559b84ac885601de22263cc7a0ab8eac465033

**Comment by daftspunk** [comment]
Try this one: 997e05e72e8e18da19f68cead7927113e79096a0

**Comment by tschortsch** [comment]
Wow you're crazy, thanks a lot! Only thing which might be strange is that now an empty array is saved to the database if there are no translated attributes. I fixed this in this PR: https://github.com/rainlab/translate-plugin/pull/715. With that the whole translation entry gets removed from the database if there are no translated attributes.

**Comment by daftspunk** [comment]
Discussion on this moved to #720
