### ISSUE TITLE
Issue with upgrading 1.10.5 to  latest 2.2.2

### ISSUE THREAD

**Issue by chrisvidal** [rainlab/translate-plugin#716]
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/2263496/227512644-3fb13ee8-f29f-4f79-a144-902760ef3091.png">

Performinig an OC v1 upgrade to OC v3

from Rainlab.translate: v1.10.5, I do a `php artisan october:update` and have this error in the terminal.

it's like it is installing from scratch because there is no v1.10.5 for this plugin?

```
RainLab.Translate
- v1.0.1:  Migration "create_indexes_table.php" failed

In Connection.php line 760:
                                                                                                                         
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'rainlab_translate_indexes' already exists (SQL: creat  
  e table `rainlab_translate_indexes` (`id` int unsigned not null auto_increment primary key, `locale` varchar(255) not  
   null, `model_id` varchar(255) null, `model_type` varchar(255) null, `item` varchar(255) null, `value` mediumtext nul  
  l) default character set utf8mb4 collate 'utf8mb4_unicode_ci' engine = InnoDB) 
```

**Comment by daftspunk** [comment]
Yes, for some reason it is trying to migrate from the beginning of time. You can skip failing migrations by opening the file and adding `return;` to the beginning of the `up()` method.
