### ISSUE TITLE
Theme translation not working after Translate plugin install

### ISSUE THREAD

**Issue by webBook-cz** [rainlab/translate-plugin#719]
Hi! I use translation strings in my theme (https://docs.octobercms.com/3.x/cms/themes/localization.html#localization-file-structure)
When the plugin is installed the twig filter |trans does not work anymore.

**Comment by daftspunk** [comment]
Hi @webBook-cz 

Could you provide some more information, please describe the following clearly -

What is the expected behavior?

What is the current behavior?

**Comment by webBook-cz** [comment]
I made a clear install just translate plugin and empty template. - and it works as expected.
I will do further inspection, it could cause any other plugin (offline.mall, probably) I'll let you know.

**Comment by webBook-cz** [comment]
Yep, when I turn off the Mall plugin, everything is OK. I'll contact offline than, thank you!
