### ISSUE TITLE
Recursion happening in afterSave method, trying to save translated slug

### ISSUE THREAD

**Issue by jjezik82** [rainlab/translate-plugin#723]
Hello, my situation is that I'm trying to regenerate slug automatically for a customer, if customer decides to change a product title. 
createSlug function is there to check for duplicates. Problem is that, setAttributeTranslated method is getting into recursion or for some reason is taking a long time to execute until crash. I have no idea where problem in this function occures. 

```
    public function afterSave()
    {
        $locale = \Site::getEditSite()->locale;

        if($this->title != $this->getOriginal('title')){
            $newSlug = $this->createSlug($this->title , $this->id);
            $this->setAttributeTranslated('slug', $newSlug, $locale);
            $this->save();
            return;
        }
    }
```

**Comment by daftspunk** [comment]
It's a recursive function because `save` will trigger `afterSave`.

```
protected $isSavingParent = false;

public function afterSave()
{
    if ($this->isSavingParent) {
        return;
    }

    $this->isSavingParent = true;
    $locale = \Site::getEditSite()->locale;

    if($this->title != $this->getOriginal('title')){
        $newSlug = $this->createSlug($this->title , $this->id);
        $this->setAttributeTranslated('slug', $newSlug, $locale);
        $this->save();
        return;
    }

    $this->isSavingParent = false;
}
```

This is how you can prevent the recursion.

**Comment by jjezik82** [comment]
Thank you! I had to make a few changes, because getOriginal() didn't work with translated title, but now it seems to be working.

`
    protected $isSavingParent = false;

    public function afterSave()
    {

        if ($this->isSavingParent) {
            return;
        }

        $this->isSavingParent = true;
        $locale = \Site::getEditSite()->locale;

        if($locale == 'en'){
            if ($this->title != $this->getOriginal('title')) {
                $newSlug = $this->createSlug($this->title, $this->id);
                $this->slug = $newSlug;
                $this->save();
                return;
            }
        }else{
            if ($this->title != $this->getTranslatableOriginals($locale)['title']) {
                $newSlug = $this->createSlug($this->title, $this->id);
                $this->setAttributeTranslated('slug', $newSlug, $locale);
                $this->save();
                return;
            }
        }

        $this->isSavingParent = false;
    }
`
