### ISSUE TITLE
New translation strings are not added after scanning

### ISSUE THREAD

**Issue by igor-tv** [rainlab/translate-plugin#724]
When I add new translation keys that have not previously been seen in the templates, and add translation messages for those keys to the theme's translation file, I expect the translation to appear after the messages are scanned. But I only see translation keys on the frontend. Only scanning with purge all messages first helps.

`theme.yaml` file has setting `translate: config/lang.yaml`.
`lang.yaml` has this structure:
```
en:
    example.string: 'Example string'
```
RainLab.Translate version 2.2.6

**Comment by daftspunk** [comment]
Hey @igor-tv 

This has been tested and is working normally. Remember that the scan does not overwrite existing translations unless you purge/delete the messages first. If the translation key is never seen, it will be included without purging first.

![image](https://github.com/rainlab/translate-plugin/assets/1392869/abb03f51-033b-4f8e-b917-4366a185e469)

It sounds like the scanner is not scanning the correct theme. You can check for the active theme by opening the editor, and whatever theme is active, here is the theme that will be scanned.

We've added some code to make this more obvious in: 168e4fb56e0ef495ba08e6d5ee807d500ee0c335

If you still think this could be a bug, mention my username, and we can take another look.

Thanks!
