### ISSUE TITLE
Trait "RainLab\Translate\Traits\MLControl" not found

### ISSUE THREAD

**Issue by Hsimonse** [rainlab/translate-plugin#728]
I have upgraded OctoberCMS from 1x to 3x and when i try to edit a blogpost i get this error message, connected to Rainlab translate:

Trait "RainLab\Translate\Traits\MLControl" not found
~/plugins/rainlab/blog/formwidgets/MLBlogMarkdown.php line 13

using v3.4.15, both translate and blog is up to date

**Comment by daftspunk** [comment]
Hi @Hsimonse 

You may need to update the RainLab.Blog plugin as well. Looking for this line specifically:

https://github.com/rainlab/blog-plugin/blob/195fc043115bef6042b20a8aab38e9203d876b14/controllers/Posts.php#L121

**Comment by Hsimonse** [comment]
The blog plugin was updated to latests version, however a remove and reinstall worked. Thanks for the swift reply!
