### ISSUE TITLE
Can't install 2.2.8

### ISSUE THREAD

**Issue by apinard** [rainlab/translate-plugin#736]
Hi,

I can't get 2.2.8 installed. So I went into my composer.json file and specified it explicitly: 

`"require": {
        "rainlab/translate-plugin": "2.2.8", ..... the rest
    },`
    
 I receive:
 
_-Root composer.json requires rainlab/translate-plugin 2.2.8 (exact version match: 2.2.8 or 2.2.8.0), it is satisfiable by rainlab/translate-plugin[v2.2.8] from composer repo (https://repo.packagist.org) but rainlab/translate-plugin[v1.11.0, v1.11.1, v1.12.0, v2.0.0, ..., v2.2.7] from composer repo (https://gateway.octobercms.com) has higher repository priority. The packages from the higher priority repository do not match your constraint and are therefore not installable. That repository is canonical so the lower priority repo's packages are not installable. See https://getcomposer.org/repoprio for details and assistance._

**Comment by daftspunk** [comment]
It looks like the tag was missed. Try now and it should work.

Thanks for reporting this!
