### ISSUE TITLE
Broken translation editing in CMS

### ISSUE THREAD

**Issue by acasar** [rainlab/translate-plugin#738]
This commit broke translations in the CMS: https://github.com/rainlab/translate-plugin/commit/f0bb2b7ce38cbb2b1bd5fe3d3f3e4554d6b78009

It seems that everything is saved in EN regardless of the selected site.

October version 3.5.15

**Comment by acasar** [comment]
I investigated a bit. It seems that CMS calls ``App::setLocale`` in ``Backend\Models\Preference`` model:

![image](https://github.com/rainlab/translate-plugin/assets/6329543/f89c9eb3-3de9-4a66-8a8c-3b8620048272)

This then triggers the ``'locale.changed'`` event and injects CMS's locale into the Translate plugin, which is not correct. Translate plugin should use the locale from the Site context.

**Comment by daftspunk** [comment]
Thanks, this makes sense.

Rolled back in 8b68d3a76a1961ce144b4a34125d4c3649d827d3
