### ISSUE TITLE
Cannot save translation with "quotes"

### ISSUE THREAD

**Issue by acasar** [rainlab/translate-plugin#739]
There is a javascript error when I try to translate a message containing quotes. I am using October 3.5.* and the latest translate plugin

![image](https://github.com/rainlab/translate-plugin/assets/6329543/95f02cfd-137d-40de-8ace-a24fce217f83)

**Comment by daftspunk** [comment]
Hey @acasar 

This looks like a longstanding issue with the table widget not escaping its selector. The fix would be included in v3.6 which I'm guessing will be a problem here.

Quickest/easiest solution is to swap `"` for `'` as a workaround.

**Comment by acasar** [comment]
@daftspunk Thanks, as a workoround I used » and « which work as well. We plan to upgrade to 3.6 soon anyway.

**Comment by daftspunk** [comment]
Fixed in v3.6 with core hash 877dfa5bbe207d3ff3d68a7434d4928cc05ce4cd
