### ISSUE TITLE
How can I access specific "locales" based on back-end administrator users permissions?

### ISSUE THREAD

**Issue by agholeal** [rainlab/translate-plugin#741]
Dear,

I hope everything is alright. 👋

Please, see this situation:  I need a specific back-end administrator users permissions acces only one language (locales).

Today I have 3 languages: 

![image](https://github.com/rainlab/translate-plugin/assets/99978792/6cc39dd7-6994-406b-93b7-54be30748ef0)

And created a specific role and permissions:

![image](https://github.com/rainlab/translate-plugin/assets/99978792/f33bd8ce-c444-4d6b-9ef7-89716cc64361)

![image](https://github.com/rainlab/translate-plugin/assets/99978792/9d9eca28-c553-41e1-b10e-21790759abe5)

👆This works fine! 👆

But now I need this back-end administrator users permissions acces only one language (green) and the others languages (yellow) must be disabled. 👇

![image](https://github.com/rainlab/translate-plugin/assets/99978792/4278824c-e82a-49d6-a37e-fa1ef87882aa)

How can I do this? Is this possible? Can you help me?

I'm using a Model Translation like this:

![image](https://github.com/rainlab/translate-plugin/assets/99978792/2cffa0bf-811c-413b-8e87-ee30febf665d)

My versions:
October CMS V2.1.32
RainLab.Translate  1.12.0

Many thanks. 🙏

**Comment by daftspunk** [comment]
Hello @agholeal 

This is solved in the next version upgrade (v3), which allows you to restrict site definitions (languages) via the administration page.

![image](https://github.com/rainlab/translate-plugin/assets/1392869/be4b2987-e179-4416-83dc-3082a9f9af93)

Best regards

**Comment by beatriznbarroso** [comment]
Hi @daftspunk,
Just to clarify  - this would allow for someone to access the CMS, having only access, for example, spanish (ES) and when accessing an model/fields  and wanting to edit something only being able to access ES and not other languages? 

Thanks

**Comment by daftspunk** [comment]
That's correct, @beatriznbarroso
