### ISSUE TITLE
Unable to install v2.2.8

### ISSUE THREAD

**Issue by mariavilaro** [rainlab/translate-plugin#742]
Lately I get this error when running composer update --lock in my projects:

Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires rainlab/translate-plugin == 2.2.8.0 (exact version match), it is satisfiable by rainlab/translate-plugin[v2.2.8] from composer repo (https://repo.packagist.org) but rainlab/translate-plugin[dev-master, v2.2.9] from composer repo (https://gateway.octobercms.com) has higher repository priority. The packages from the higher priority repository do not match your constraint and are therefore not installable. That repository is canonical so the lower priority repo's packages are not installable. See https://getcomposer.org/repoprio for details and assistance.

It's the first time that I see this error, it never happened before this 2.2.9 update I think.

We don't run composer update every time that we do any minor change in a website (we only run composer update when executing scheduled maintenances), we need to be able to run composer update --lock in our servers and install any previous version that is locked.

Is it possible that you revert this change, so we are able to install version 2.2.8 or any other previous version if we need it?

**Comment by daftspunk** [comment]
Hi @mariavilaro 

We rebuilt this plugin today, try again and see if it helps.
