### ISSUE TITLE
Primary Site / Locale cannot be changed

### ISSUE THREAD

**Issue by damnason** [rainlab/translate-plugin#749]
No matter what, /en is the default locale.
Translate Messages works which is the primary language, but url redirect not.
Config (locale, fallback_locale), .env, db all changed to /de still /en is the primary.

**Comment by damnason** [comment]
Sorry for openin/closing ticket.

So the problem is:
First one is solved, I couldn't see that it auto choose lang in default, but:
If my language is FR (located by IP or browser language), but it's disabled, then primary lang will be /en, not the actual primary language, in my case it's /de.

Or am I missing something?

**Comment by daftspunk** [comment]
The logic here is pretty straightforward

```php
$policy = Config::get('cms.redirect_policy', 'detect');

// Detect site from browser locale (same site)
if ($policy === 'detect') {
    return Site::getSiteFromBrowser(
        (string) Request::server('HTTP_ACCEPT_LANGUAGE'),
        $originalSite->group_id
    )?->attachRoutePrefix($originalUrl);
}

// Use primary site
if ($policy === 'primary') {
    return Site::getPrimarySite()?->base_url;
}

// Use a specified site ID
return Site::getSiteFromId($policy)?->base_url;
```

Unless you have the "en" site ID set in the configuration, it should default to your primary site, which should be "de" in your case.

**Comment by daftspunk** [comment]
On second pass, it looks like it does indeed take the **first site** from the group when it doesn't find a matching site from the locale. This means you may need to sort the sites so that the "de" site appears above the "en" site.

```php
$locales = $this->getLocalesFromBrowser($acceptLanguage);

$sites = $this->listEnabled()->inGroup($groupId);

foreach ($locales as $locale => $priority) {
    if ($foundSite = $sites->inLocale($locale)->first()) {
        return $foundSite;
    }
}

return $sites->first();
```

I hope this helps.
