### ISSUE TITLE
AJAX error

### ISSUE THREAD

**Issue by FelixINX** [rainlab/translate-plugin#75]
Hi,

I have an error with the localePicker. When I choose a language, I get the following error;
`AJAX handler 'onSwitchLocale' was not found.`
![ajax error](https://cloud.githubusercontent.com/assets/8009156/7689406/fc8a3c52-fd79-11e4-8994-153da21fe5f0.png)

According to [this thread](https://octobercms.com/forum/post/plugins-not-working-with-custom-markup-ajax-handler-was-not-found), is a October related issue. But I just want to be sure, how can I resolve it?

Please note that `mysite.com/{langcode}/` works.

Thanks

**Comment by Flo-Schield-Bobby** [comment]
Include the `[localePicker]` in your layout/page.

```
<!-- /themes/your-theme/layouts/name-of-your-layout.htm -->
description = [...]
[localePicker]
==
```

If you include links having a `data-request="onSwitchLocale"` attribute on a partial, you still need to include this component in the layout of the page where the partial is rendered.

**Comment by FelixINX** [comment]
Thanks, but a bit late :smile:

**Comment by leonachman** [comment]
Thanks. Not late for me :-)

**Comment by sopmac** [comment]
Nice one

**Comment by simon511000** [comment]
Thank you :D
