### ISSUE TITLE
Non-primary language translations override the primary translations of a custom model

### ISSUE THREAD

**Issue by antonpequeno** [rainlab/translate-plugin#750]
Hello,

I have two different languages for my CMS: English and Spanish.
Spanish is set as my primary and default language.
The issue is that when I edit the English translation, it overrides the Spanish translation stored in the model table, even though it is correctly stored in the translate_attributes table.
However, if I update the Spanish translation, the English version remains correct without any changes.

public $implement = ['@RainLab.Translate.Behaviors.TranslatableModel'];
public $translatable = ['name', 'abstract', 'description', 'address'];

![Captura de pantalla 2024-09-26 a las 12 02 12](https://github.com/user-attachments/assets/4a1117d5-ba12-4c92-875e-21a575a96a41)

![Captura de pantalla 2024-09-26 a las 12 00 07](https://github.com/user-attachments/assets/62b71f6d-3946-40f0-acd9-a1764eb3bfda)

Thanks for any help.

**Comment by daftspunk** [comment]
Hi @antonpequeno 

I can't seem to reproduce this, could you provide more detail, specifically how to reproduce it from a fresh installation. Sometimes, the value will replicate if it is the same value but this usually won't appear in the database...

**Comment by antonpequeno** [comment]
Hello,

We only added a custom plugin and extended an October Model to use our custom models. Then, we added a controller with CRUD views and created a model in the primary language, Spanish.

After that, we switched the Language Picker to English, our secondary language. When we saved the changes in English, it also overwrote the primary language (in the model table).

However, if we update the primary language (Spanish), it works fine. The English version remains correct without being changed.

The only thing we extended from the original model is:
```    
protected function afterSave()
{
        $this->name = Utils::sanitizeTitle($this->name);
        $this->address = Utils::sanitizeTitle($this->address);
        $coords = explode(",", $this->map);
        $this->lat = trim($coords[0]);
        $this->lng = trim($coords[1]);
        $this->updateSearchable();
        $this->flushTypeCache();
}
```

If you need more information, let me know and I'll try to provide additional details.

Thanks.

**Comment by antonpequeno** [comment]
Hello, 

We're using this picker to switch between languages.
![Captura de pantalla 2024-09-30 a las 16 50 47](https://github.com/user-attachments/assets/f2aed420-75d9-490c-9ac7-ce59cb5b6c8a)

And this is the basic configuration of the sites.
![Captura de pantalla 2024-09-30 a las 16 51 29](https://github.com/user-attachments/assets/7aa6a752-b2e4-4a4b-87ca-adf4ec04c5f4)

Best regards,
Thanks

**Comment by Benjade** [comment]
@daftspunk But now I have the same problem as @antonpequeno, if I translate the French page, it also translates the English page and vice versa.

**Comment by daftspunk** [comment]
I'm sorry, but I still cannot reproduce this problem. Here are the replication instructions.

1. Install the Test plugin → https://github.com/octobercms/test-plugin/
2. Navigate to Locations → Manage Countries
3. Open a Country
4. Switch to the non-default language (French)
5. Update the Country Name to "Test Name"
6. Navigate back to the default language (English)
7. The Country Name does not equal "Test Name"
8. The translation is functioning normally

Let me know if you can reproduce the issue using this plugin and we can take another look.
