### ISSUE TITLE
Add support for translating menu items

### ISSUE THREAD

**Issue by fobus42** [rainlab/translate-plugin#76]
Hello,

We are using Menu List Plugin https://octobercms.com/plugin/flynsarmy-menu

There is two models in the plugin Menu and Menuitems. All models implements the Rainlab Translation plugin correctly. Menu model works great but Menuitem model doesn't save the fields in to rainlab_translate_attributes

I have created a thread here : https://octobercms.com/plugin/flynsarmy-menu/menu-items-translation-doesnt-work-2?page=1#post-6567

**Comment by fobus42** [comment]
I think here you don't supply support.

**Comment by fobus42** [comment]
Did this plugins development stop?

**Comment by daftspunk** [comment]
Sorry for the late reply. This actually needs assistance from the plugin author of Flynsarmy.Menu.
