### ISSUE TITLE
Add theme translations to version control

### ISSUE THREAD

**Issue by lowerends** [rainlab/translate-plugin#77]
Is there a way to add translations for a front-end theme to version control, without having to add them to the database? This would allow for a theme to be translated while developing and having the translations available at the moment that the site is put live.

**Comment by shrpne** [comment]
+1
I think File based CMS should be really file based

**Comment by keiosweb** [comment]
+1. aside the development usability, I really don't like the fact that every time cache gets forgotten, someone visiting our websites makes hundreds of queries to read all translation keys. i've set cache to forever on crucial websites, but it's still ugly and quite bad on hosted websites where we can't pull out redis. J.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
