### ISSUE TITLE
Plugin doesn't work compatible with relation tables

### ISSUE THREAD

**Issue by fobus42** [rainlab/translate-plugin#78]
We are developing a custom plugin and we have problems on relation tables.

We have Countries table and offices table. Countries has many offices related to country_id on offices table. We have defined all relations in models and in yaml files.

Every thing works fine on CRUD.

We are implemented translation plugin in to our pluing, Countires tables works great with translation table, but offices table saves blank fields for second language.

When I check the "rainlab_translate_attributes" table I can see recods for "Countries" model but there is no record for Offices Model.

The same thing occurs on "Menu Lists Plugin" here is the thread : https://octobercms.com/forum/post/menu-items-translation-doesnt-work-2

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
