### ISSUE TITLE
Plugin installed, without class?

### ISSUE THREAD

**Issue by FelixINX** [rainlab/translate-plugin#80]
Hi,

I have installed the plugin, and working on an improvement for pages plugins (see issue [#32](https://github.com/rainlab/pages-plugin/issues/32)). I have tried the `RainLab.Translate.Behaviors.TranslatableModel` behavior, but the class dosen't seem to exsist.

I have created a sample page, with this as code;

```
function onStart(){
    if (!class_exists('RainLab\Translate\Behaviors\TranslatableModel'))
         return;
    else{
        die('Class dosen\'t exsist!!');
    }    
}
```

And the result : `Class dosen't exsist!!`.

Seem weird.

Thanks

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.

**Comment by LukeTowers** [comment]
Also you're missing the starting backslash, should be `class_exists('\RainLab\Translate\Behaviors\TranslatableModel')`
