### ISSUE TITLE
Cache Clearing Bug

### ISSUE THREAD

**Issue by drtzack** [rainlab/translate-plugin#85]
It's really weird. I use benfreke/menumanager.

In home page( http://nonashield.com/ ) translate doesnt work but it works well in other pages ( http://nonashield.com/account )

**Comment by drtzack** [comment]
I think the reason is about caching system but I made clear cache but still same.

**Comment by shrpne** [comment]
Sometimes Translate's "Clear cache" dont' work for me.
In this cases i use http://octobercms.com/plugin/romanov-clearcachewidget this plugin.

**Comment by artras** [comment]
I also have thise problem ! Clear cache button do not work in backend!

**Comment by amdad** [comment]
Ok, for me this is also problem. Seems like system cache have some problems. It refresh new strings with some delays.

**Comment by daftspunk** [comment]
This should be fixed by https://github.com/octobercms/october/commit/cb6cf4515650f40e770985650e59acf6897a4bd4

Available in build 330+
