### ISSUE TITLE
translatePlural messages

### ISSUE THREAD

**Issue by zek** [rainlab/translate-plugin#86]
I couldn't see translatePlural messages in backend TRANSLATE MESSAGES.

```
public function translatePlural($string, $count = 0, $params = [])
{
    return Lang::choice($string, $count, $params);
}
```

As I see it is linked to Laravel Lang::choice. Is that mean we can't translate texts from backend?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
