### ISSUE TITLE
Can't translate Mail Templates

### ISSUE THREAD

**Issue by zek** [rainlab/translate-plugin#87]
I've tried to translate mail templates but I couldn't.

Is this plugin supports translating mail templates?

**Comment by gergo85** [comment]
I can't translate the mail templates too so I use different template for every language. See the following plugin for details: https://github.com/gergo85/oc-news

**Comment by wellyfrs** [comment]
Same problem.

**Comment by LukeTowers** [comment]
If anyone wants to work on implementing a fix for this, please do so and make a PR. Otherwise, just adding +1 or "same problem" is not helpful.

**Comment by wellyfrs** [comment]
All right, @LukeTowers. I made one request (#304), but it depends on another one in October (https://github.com/octobercms/october/pull/3152). With this, the search also scans e-mail templates.

**Comment by LukeTowers** [comment]
@wellyfrs awesome thanks, will wait to merge #304 until after merging octobercms/october#3152
