### ISSUE TITLE
Call to undefined method QueryBuilder::getAttributeValue()

### ISSUE THREAD

**Issue by alvaro-canepa** [rainlab/translate-plugin#91]
After update to build 293 I can't create/edit any model using the `TranslatableModel` behavior.

This is the LOG:

	exception 'BadMethodCallException' with message 'Call to undefined method October\Rain\Database\QueryBuilder::getAttributeValue()' in /home/inmobiliaria/public_html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:1999
	Stack trace:
	#0 [internal function]: Illuminate\Database\Query\Builder->__call('getAttributeVal...', Array)
	#1 [internal function]: October\Rain\Database\QueryBuilder->getAttributeValue('title')
	#2 /home/inmobiliaria/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(933): call_user_func_array(Array, Array)
	#3 /home/inmobiliaria/public_html/vendor/october/rain/src/Database/Builder.php(131): Illuminate\Database\Eloquent\Builder->__call('getAttributeVal...', Array)
	#4 [internal function]: October\Rain\Database\Builder->__call('getAttributeVal...', Array)
	#5 [internal function]: October\Rain\Database\Builder->getAttributeValue('title')
	#6 /home/inmobiliaria/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(3362): call_user_func_array(Array, Array)
	#7 /home/inmobiliaria/public_html/vendor/october/rain/src/Extension/ExtendableTrait.php(325): Illuminate\Database\Eloquent\Model->__call('getAttributeVal...', Array)
	#8 /home/inmobiliaria/public_html/vendor/october/rain/src/Database/Model.php(418): October\Rain\Database\Model->extendableCall('getAttributeVal...', Array)
	#9 /home/inmobiliaria/public_html/plugins/rainlab/translate/behaviors/TranslatableModel.php(126): October\Rain\Database\Model->__call('getAttributeVal...', Array)
	#10 /home/inmobiliaria/public_html/plugins/rainlab/translate/behaviors/TranslatableModel.php(126): Pronet\RealEstate\Models\Property->getAttributeValue('title')
	#11 [internal function]: RainLab\Translate\Behaviors\TranslatableModel->getTranslateAttribute('title', 'es')
	#12 /home/inmobiliaria/public_html/vendor/october/rain/src/Extension/ExtendableTrait.php(311): call_user_func_array(Array, Array)
	#13 /home/inmobiliaria/public_html/vendor/october/rain/src/Database/Model.php(418): October\Rain\Database\Model->extendableCall('getTranslateAtt...', Array)
	#14 /home/inmobiliaria/public_html/plugins/rainlab/translate/traits/MLControl.php(93): October\Rain\Database\Model->__call('getTranslateAtt...', Array)
	#15 /home/inmobiliaria/public_html/plugins/rainlab/translate/traits/MLControl.php(93): Pronet\RealEstate\Models\Property->getTranslateAttribute('title', 'es')
	#16 /home/inmobiliaria/public_html/plugins/rainlab/translate/traits/mlcontrol/partials/_locale_values.htm(6): RainLab\Translate\FormWidgets\MLText->getLocaleValue('es')
	#17 /home/inmobiliaria/public_html/modules/system/traits/ViewMaker.php(207): include('/home/inmobilia...')
	#18 /home/inmobiliaria/public_html/modules/system/traits/ViewMaker.php(69): Backend\Classes\WidgetBase->makeFileContents('/home/inmobilia...', Array)
	#19 /home/inmobiliaria/public_html/plugins/rainlab/translate/traits/MLControl.php(61): Backend\Classes\WidgetBase->makePartial('locale_values', Array)
	#20 /home/inmobiliaria/public_html/plugins/rainlab/translate/formwidgets/mltext/partials/_mltext.htm(31): RainLab\Translate\FormWidgets\MLText->makeParentPartial('locale_values')
	#21 /home/inmobiliaria/public_html/modules/system/traits/ViewMaker.php(207): include('/home/inmobilia...')
	#22 /home/inmobiliaria/public_html/modules/system/traits/ViewMaker.php(69): Backend\Classes\WidgetBase->makeFileContents('/home/inmobilia...', Array)
	#23 /home/inmobiliaria/public_html/plugins/rainlab/translate/formwidgets/MLText.php(41): Backend\Classes\WidgetBase->makePartial('mltext')
	#24 /home/inmobiliaria/public_html/modules/backend/widgets/form/partials/_field_widget.htm(5): RainLab\Translate\FormWidgets\MLText->render()
	#25 /home/inmobiliaria/public_html/modules/system/traits/ViewMaker.php(207): include('/home/inmobilia...')
	#26 /home/inmobiliaria/public_html/modules/system/traits/ViewMaker.php(69): Backend\Classes\WidgetBase->makeFileContents('/home/inmobilia...', Array)
	#27 /home/inmobiliaria/public_html/modules/backend/widgets/Form.php(247): Backend\Classes\WidgetBase->makePartial('field_widget', Array)
	#28 /home/inmobiliaria/public_html/modules/backend/widgets/form/partials/_field.htm(19): Backend\Widgets\Form->renderFieldElement(Object(Backend\Classes\FormField))
	#29 /home/inmobiliaria/public_html/modules/system/traits/ViewMaker.php(207): include('/home/inmobilia...')
	#30 /home/inmobiliaria/public_html/modules/system/traits/ViewMaker.php(69): Backend\Classes\WidgetBase->makeFileContents('/home/inmobilia...', Array)
	#31 /home/inmobiliaria/public_html/modules/backend/widgets/form/partials/_field-container.htm(8): Backend\Classes\WidgetBase->makePartial('field', Array)
	#32 /home/inmobiliaria/public_html/modules/system/traits/ViewMaker.php(207): include('/home/inmobilia...')
	#33 /home/inmobiliaria/public_html/modules/system/traits/ViewMaker.php(69): Backend\Classes\WidgetBase->makeFileContents('/home/inmobilia...', Array)
	#34 /home/inmobiliaria/public_html/modules/backend/widgets/form/partials/_form_fields.htm(2): Backend\Classes\WidgetBase->makePartial('field-container', Array)
	#35 /home/inmobiliaria/public_html/modules/system/traits/ViewMaker.php(207): include('/home/inmobilia...')
	#36 /home/inmobiliaria/public_html/modules/system/traits/ViewMaker.php(69): Backend\Classes\WidgetBase->makeFileContents('/home/inmobilia...', Array)
	#37 /home/inmobiliaria/public_html/modules/backend/widgets/form/partials/_section.htm(17): Backend\Classes\WidgetBase->makePartial('form_fields', Array)
	#38 /home/inmobiliaria/public_html/modules/system/traits/ViewMaker.php(207): include('/home/inmobilia...')
	#39 /home/inmobiliaria/public_html/modules/system/traits/ViewMaker.php(69): Backend\Classes\WidgetBase->makeFileContents('/home/inmobilia...', Array)
	#40 /home/inmobiliaria/public_html/modules/backend/widgets/form/partials/_form.htm(3): Backend\Classes\WidgetBase->makePartial('section', Array)
	#41 /home/inmobiliaria/public_html/modules/system/traits/ViewMaker.php(207): include('/home/inmobilia...')
	#42 /home/inmobiliaria/public_html/modules/system/traits/ViewMaker.php(69): Backend\Classes\WidgetBase->makeFileContents('/home/inmobilia...', Array)
	#43 /home/inmobiliaria/public_html/modules/backend/widgets/form/partials/_form-container.htm(8): Backend\Classes\WidgetBase->makePartial('form')
	#44 /home/inmobiliaria/public_html/modules/system/traits/ViewMaker.php(207): include('/home/inmobilia...')
	#45 /home/inmobiliaria/public_html/modules/system/traits/ViewMaker.php(69): Backend\Classes\WidgetBase->makeFileContents('/home/inmobilia...', Array)
	#46 /home/inmobiliaria/public_html/modules/backend/widgets/Form.php(214): Backend\Classes\WidgetBase->makePartial('form-container', Array)
	#47 /home/inmobiliaria/public_html/modules/backend/behaviors/FormController.php(338): Backend\Widgets\Form->render(Array)
	#48 [internal function]: Backend\Behaviors\FormController->formRender()
	#49 /home/inmobiliaria/public_html/vendor/october/rain/src/Extension/ExtendableTrait.php(311): call_user_func_array(Array, Array)
	#50 /home/inmobiliaria/public_html/vendor/october/rain/src/Extension/Extendable.php(44): October\Rain\Extension\Extendable->extendableCall('formRender', Array)
	#51 /home/inmobiliaria/public_html/plugins/pronet/realestate/controllers/properties/update.htm(10): October\Rain\Extension\Extendable->__call('formRender', Array)
	#52 /home/inmobiliaria/public_html/plugins/pronet/realestate/controllers/properties/update.htm(10): Pronet\RealEstate\Controllers\Properties->formRender()
	#53 /home/inmobiliaria/public_html/modules/system/traits/ViewMaker.php(207): include('/home/inmobilia...')
	#54 /home/inmobiliaria/public_html/modules/system/traits/ViewMaker.php(80): Backend\Classes\Controller->makeFileContents('/home/inmobilia...')
	#55 /home/inmobiliaria/public_html/modules/backend/classes/Controller.php(369): Backend\Classes\Controller->makeView('update')
	#56 /home/inmobiliaria/public_html/modules/backend/classes/Controller.php(251): Backend\Classes\Controller->execPageAction('update', Array)
	#57 /home/inmobiliaria/public_html/modules/backend/classes/BackendController.php(95): Backend\Classes\Controller->run('update', Array)
	#58 [internal function]: Backend\Classes\BackendController->run('pronet/realesta...')
	#59 /home/inmobiliaria/public_html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(246): call_user_func_array(Array, Array)
	#60 /home/inmobiliaria/public_html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(162): Illuminate\Routing\Controller->callAction('run', Array)
	#61 /home/inmobiliaria/public_html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(107): Illuminate\Routing\ControllerDispatcher->call(Object(Backend\Classes\BackendController), Object(Illuminate\Routing\Route), 'run')
	#62 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
	#63 /home/inmobiliaria/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
	#64 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
	#65 /home/inmobiliaria/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
	#66 /home/inmobiliaria/public_html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(108): Illuminate\Pipeline\Pipeline->then(Object(Closure))
	#67 /home/inmobiliaria/public_html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Backend\Classes\BackendController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'run')
	#68 /home/inmobiliaria/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Backend\\Classes...', 'run')
	#69 /home/inmobiliaria/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
	#70 /home/inmobiliaria/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(701): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
	#71 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
	#72 /home/inmobiliaria/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
	#73 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
	#74 /home/inmobiliaria/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
	#75 /home/inmobiliaria/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Pipeline\Pipeline->then(Object(Closure))
	#76 /home/inmobiliaria/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(670): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
	#77 /home/inmobiliaria/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
	#78 /home/inmobiliaria/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(214): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
	#79 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
	#80 /home/inmobiliaria/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
	#81 /home/inmobiliaria/public_html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
	#82 /home/inmobiliaria/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
	#83 /home/inmobiliaria/public_html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(61): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
	#84 /home/inmobiliaria/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
	#85 /home/inmobiliaria/public_html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(36): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
	#86 /home/inmobiliaria/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
	#87 /home/inmobiliaria/public_html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(40): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
	#88 /home/inmobiliaria/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
	#89 /home/inmobiliaria/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
	#90 /home/inmobiliaria/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
	#91 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
	#92 /home/inmobiliaria/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
	#93 /home/inmobiliaria/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(115): Illuminate\Pipeline\Pipeline->then(Object(Closure))
	#94 /home/inmobiliaria/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(84): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
	#95 /home/inmobiliaria/public_html/index.php(44): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
	#96 {main}

Thanks

**Comment by daftspunk** [comment]
Should be fixed in Build 294+

**Comment by alvaro-canepa** [comment]
Thanks ;)
