### ISSUE TITLE
Problems with keys

### ISSUE THREAD

**Issue by keiosweb** [rainlab/translate-plugin#93]
Hello,

I would like to go back to discussion about *keys* in this plugin, as I am continuously running into problems with them.

Let's take an example of 'detected location'. I have following strings on my website:

    {{'Detected Location'|_}} <br> <some stuff>

and 

    {{'List of available languages for'|_}} <a title="{{ looong component variable as a hint }}" class="some css classes">{{'detected location'|_}}</a>.

Taking polish as an example, first translates as *Wykryta Lokacja*, second as *wykrytej lokacji*, but with your plugin they have the same key and grammar will always be incorrect in one of the cases. 

Do you think it is reasonable to extend twig filter to support some kind of context parameters that will add some string to key for such cases? Like

    {{'List of available languages for'|_}} <a title="{{ looong title }}" class="some classes">{{'detected location'|_(a)| }}

    {{'Detected Location'|_(b)}}

would append *-a* and *-b* accordingly to the keys so they could be stored separately in db. maybe not exactly like that, that's just first idea i got that would resolve this. Still, as it's quite common that I have incorrect grammar in my translation, because the same key is generated for contextually different strings, the possibility to manipulate keys when creating translatable strings would be really nice.

I sometimes try to do hacky things like {{'your detected location'|_}} to keep different keys for different contexts, but it is not always possible, especially when small/big letters are involved or there is huge amount of strings to translate.

I would really like to resolve this and that's why I'm here to ask what do you think is the best way.

Regards,
James

**Comment by daftspunk** [comment]
I suppose you could always do something like this

```
{% set a = { v1:'', v2:'' } %}

{{'Detected Location:v1'|_(a)}}

{{'detected location:v2'|_(a)}}
```

**Comment by keiosweb** [comment]
That works fine, should be in docs as 'adding context to keys' or something. Thanks.
