### ISSUE TITLE
With .htaccess redirect, Translate component does not work 

### ISSUE THREAD

**Issue by WebShapedBiz** [rainlab/translate-plugin#97]
Hi.

I'm using .htaccess to automatically switch the language using this
>    RewriteCond %{HTTP:Accept-Language} ^hr [NC]
>    RewriteRule ^$ /hr/ [L,R=301]
>    #For every other language use English
>    RewriteRule ^$ /en/ [L,R=301]

and it works as it should with all my content blocks and pages. Unfortunately, Locale Picker does not like this and it stopped working. No errors, just what ever you select you will end up with the original language.

Is this a bug or am I using this plugin the wrong way?

Cheers.

**Comment by Eoler** [comment]
I don't think its nice to (permanently!) force visitors to language root if they happen to have "hr" as a first locale configured in a browser. There could be a better way:

1. force URL language prefixing (forceUrl=1 in [localePicker] component): #72
2. redirect site root URL by detecting visitors accepted locales (temporary, they can change their preferences later)
```
    ## Localization rewrites for root URL
    RewriteCond %{REQUEST_URI} ^/$ [NC]
    RewriteCond %{HTTP:Accept-Language} (hr) [NC]
    RewriteRule .* /hr/ [R=302,L]
    RewriteCond %{REQUEST_URI} ^/$ [NC]
    RewriteCond %{HTTP:Accept-Language} (it) [NC]
    RewriteRule .* /it/ [R=302,L]
    ## Default language
    RedirectMatch 302 ^/$ /en/

**Comment by daftspunk** [comment]
Good suggestion, I think the OP may have submitted this before forceUrl existed.
