### ISSUE TITLE
Can't save the translation to database

### ISSUE THREAD

**Issue by surahmans** [rainlab/translate-plugin#98]
Hi, 

I have tried the the translate plugin in rainlab.blog. I added new field (content_id) to the table and set the column field. But, when I trying to save with this code. (In the post model of rainlab.blog)

```
public function beforeSave()
    {
        $this->content_html = self::formatHtml($this->content);

        $this->setTranslateAttribute('content_html', $this->content_id, 'id');
    }
```

the model can't save it. What should I do to fix it?

thanks

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
