### ISSUE TITLE
How to set Localization Routes

### ISSUE THREAD

**Issue by paper9oll** [rainlab/translate-plugin#99]
Hi Developer / Everyone,

I would like to know how to set localization routes.
Reason - Because clicking any of the links will return the users back to the default locale which is en, i have a couple of countries localization which i just declared as cn for china, uk for united kingdom ...

**Comment by CptMeatball** [comment]
Consider using: 

    <a href="{{ 'filename'| page}}">Pagename</a>

If you set the localisation correctly, this should point to the route of the active language.

**Comment by paper9oll** [comment]
@CptMeatball 
hi thanks for the reply, just a quick question.
my filename is about do i put it like this {{'/about'| about}} for the href

**Comment by CptMeatball** [comment]
If your file name is ````about````:

    <a href="{{ 'about'|page}}">About</a>

The ````page```` part in the twig statement is a ````filter````, so you can't change that.

See the documentation for more information about the ````|page```` filter and other markup related things. 
https://octobercms.com/docs/markup/filter-page

**Comment by paper9oll** [comment]
oh okay understood

thanks you for the reply
